### ISSUE TITLE
search_write_format returns `None` when given a PNG request

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#1001]
_Originally posted by @djhoese in https://github.com/imageio/imageio/issues/824#issuecomment-1572163572_

Sorry for commenting on an old PR, but I just wanted to point out that this is not backwards compatible but it sounds like the aim was for it to be. When doing:

```python
>>> import imageio
>>> request = imageio.core.Request("test.png", "w?")
>>> imageio.formats.search_write_format(request)
<stdin>:1: DeprecationWarning: ImageIO now uses a v3 plugin when writing this format. Please migrate to the v3 API (preferred) or use imageio.v2.
```

The result is `None`, but I would have expected it to still return the v2 equivalent. Right?

Edit: Ah looks like if I comment that except block out it shows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/SIFT_2.0.0b0/lib/python3.11/site-packages/imageio/core/format.py", line 853, in search_write_format
    return imopen(request, request.mode.io_mode, legacy_mode=True)._format
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PillowPlugin' object has no attribute '_format'. Did you mean: '__format__'?
```

What is the proper way to access this functionality from a v3 API?

**Comment by FirefoxMetzger** [comment]
@djhoese Could you add some more context on how you are writing the image? 

`imageio.core.Request` is an internal, intermediate object that we use to help with plugin selection and to create instructions for the selected backend. In 99% of cases, you don't want to use it directly and instead use a function from one of our functional APIs. 

Without knowing more, my guess is that a simple `imwrite("test.png", img_data)` would be the way to go in your case, but that depends on your use case so I'd need more context to say for sure.

>> `>>> imageio.formats.search_write_format(request)`
>
> The result is None, but I would have expected it to still return the v2 equivalent. Right?

Neither the v2 API nor the v3 API rely on `FormatManager` anymore. Both APIs use the selection logic of `imopen` (simpler yet more powerful), which is why we are deprecating the entire `FormatManager` class.

If you **must** use an old `Writer` object (the object returned by `imageio.format.search_write_format`), you can get it from the v2 API:

```python
import imageio.v2 as imageio

with imageio.get_writer("test.png") as writer:
    ...  # consume the old writer object
```

The result is a `LegacyWriter` object, which implements the old `imageio.core.format.Writer` API and translates calls to it into instructions for the new v3 plugins in cases where a v3 plugin exists, or an old `Writer` object in cases where we haven't migrated the plugin yet. 

The reason I say _must_ is because I often see `get_reader` and `get_writer` miss-used in the wild. E.g., they are used without a context manager (and end up potentially leaking a file handle), or they are used in places where an `imread` or `imwrite` would have made the code less complex. 

We also now have the v3 API, which makes `get_reader` and `get_writer` redundant and has a whole list of other benefits like improved performance, a more intuitive API, etc. If migrating is an opinion, then that would should be the preferred choice :)

> What is the proper way to access this functionality from a v3 API?

Which functionality are you looking for? (a) finding a plugin that can write PNG, (b) write some image data as PNG, (c) check if ImageIO can generally write PNG, (d) find all plugins that are capable of writing PNG?

**Comment by djhoese** [comment]
I'm away from my computer but think I can give a decent context on my phone so...

We have an interface (Qt GUI dialog) that can either save a single image or a series of images (frames) to either a single file (ex. PNG) or to a series of images (ex. PNGs), or to a video (ex. MP4 with imageio-ffmpeg).

The code splits the saving into two steps (at least for this discussion): check if the filename the user entered is valid (imageio can support it) and then write the output. The output writing is constructed as a for loop over a `zip` with frames to write and output files, then using get_writer and a for loop over each frame with append_data regardless of singe image or video/multi-frame format. It all ends with a .close on the writer object so yeah not a context manager.

So the misuse of `search_write_format` was likely a desperate attempt at getting something to work to know if a filename was valid before we tried writing output. Not sure it has to be that way in hindsight.

**Comment by FirefoxMetzger** [comment]
> The output writing is constructed as a for loop over a `zip`

I initially thought you were writing multiple PNGs into a ZIP file, but I guess you are talking about Python's `zip(*iterable)` 😅 

Anyway...

> The output writing is constructed as a for loop over a `zip` with frames to write and output files, then using get_writer and a for loop over each frame with append_data regardless of singe image or video/multi-frame format.

In v3 all of this can be done directly via `imwrite`. That is assuming that your videos are short and that all frames are available in-memory as numpy arrays.

```python
import imageio.v3 as iio
import numpy as np

paths = ["some.png", "some.jpeg", "output.mp4", "funny.gif"]

rng = np.random.default_rng()
frames = [
    rng.integers(0, 255, (255, 255, 3), dtype=np.uint8)
    if frames == 1
    else rng.integers(0, 255, (frames, 255, 255, 3), dtype=np.uint8)
    for frames in (1, 1, 200, 25)
]

for path, data in zip(paths, frames):
    # note: customization is limited because we use
    # different backends depending on the input
    iio.imwrite(path, data)
```

> [...] check if the filename the user entered is valid (imageio can support it)

I think the easiest way to check this is to open the file for writing:

```python
file = None
try:
    file = iio.imopen("image.png", "w")
except IOError:
    ... # can not write to the given resource
finally:
    if file is not None:
        file.close()
```

This will jump through all the hoops involved in writing and stop just before writing any data. If raising an exception here is fine, you can also let the `IOError` bubble; it contains useful information about what has failed, e.g., if it is because a plugin is missing (which could be installed by the user).

**Comment by djhoese** [comment]
RE: zip, yeah I shouldn't have worded it that way.

Regarding `imwrite``, I think the original goal when the code was written was to allow frames to be generated in a generator. As the code evolved it looks like it is limited to a list so all frames do exist as numpy arrays. I think `imwrite` should work fine.

Regarding the format support, I think I'll just remove the check. This check likely stems from something historical, but right now I don't know why it exists like this. Just curious, is there any guarantee that `imopen` won't truncate/overwrite an existing file?

I think I'm satisfied with this answer and I'll make sure to update my code. Thanks. Since you technically created the issue I can't close it.

**Comment by FirefoxMetzger** [comment]
Incremental writing is quite similar:

```python
with iio.imopen(resource, "w") as file:
    for frame in frame_list:
        file.write(frame, is_batch=False)
```

The `is_batch=False` kwarg is optional and used to differentiate batches of images (e.g. `(6, 100, 150, 3)`)) from volumetric images. If omitted, ImageIO will attempt to auto-detect if the input is a batch or not, but this process is imperfect because the inputs (batch/volume/other) can at times look identical. `is_batch` helps differentiate in those cases.

It may also happen that a backend doesn't implement incremental writing - in this case please raise an issue and I will check if we can add that feature :)

>  Just curious, is there any guarantee that imopen won't truncate/overwrite an existing file?

Unfortunately no. If you don't specify which plugin to use `imopen` needs to find a capable backend/plugin. This means that we have to give the plugin control so that it can run its checks and report back if it can handle your request. I try to make sure that this doesn't involve creating/overwriting the file (and will patch it where it occurs, if possible), but there is no hard guarantee that the file won't be overwritten. Especially if you use external, third-party plugins.

**Comment by FirefoxMetzger** [comment]
> I think I'm satisfied with this answer and I'll make sure to update my code. Thanks. Since you technically created the issue I can't close it.

Closing!
