### ISSUE TITLE
heif format / .heic image file support

### ISSUE THREAD

**Issue by smidm** [imageio/imageio#1021]
Are there any plans to support .heic image files? For pillow there is https://pypi.org/project/heif-image-plugin/ based on https://github.com/carsales/pyheif.

**Comment by FirefoxMetzger** [comment]
There is no explicit roadmap for HEIC, but if you (or someone else) is interested in writing a plugin, I'm happy to review :)

**Comment by bigcat88** [comment]
> Are there any plans to support .heic image files? For pillow there is https://pypi.org/project/heif-image-plugin/ based on https://github.com/carsales/pyheif.

Also can take a look at [pillow-heif](https://github.com/bigcat88/pillow_heif), if you wish to.
