### ISSUE TITLE
ImageResource type should support bytes

### ISSUE THREAD

**Issue by ivan94fi** [imageio/imageio#1024]
Hi, I think `bytes` should be added to the `ImageResource` union, as it is supported by `imread`.

I suggest the following change in this file https://github.com/imageio/imageio/blob/2cdf5632622e00adc8edfadb27dda0b4880e50ba/imageio/typing.py#L11C16-L11C16:

```patch
- ImageResource = Union[str, BytesIO, Path, BinaryIO]
+ ImageResource = Union[str, bytes, BytesIO, Path, BinaryIO]
```

**Comment by FirefoxMetzger** [comment]
Good Catch @ivan94fi ! I've created #1026 to include this :)
