### ISSUE TITLE
It does not seem to support avif image format 

### ISSUE THREAD

**Issue by anilsathyan7** [imageio/imageio#1043]
```
import imageio.v3 as iio
im=iio.imread('51.avif')
```

_OSError                                   Traceback (most recent call last)
[<ipython-input-4-2fb2e37d23e4>](https://localhost:8080/#) in <cell line: 2>()
      1 import imageio.v3 as iio
----> 2 im=iio.imread('51.avif')

1 frames
[/usr/local/lib/python3.10/dist-packages/imageio/v3.py](https://localhost:8080/#) in imread(uri, index, plugin, extension, format_hint, **kwargs)
     51         call_kwargs["index"] = index
     52 
---> 53     with imopen(uri, "r", **plugin_kwargs) as img_file:
     54         return np.asarray(img_file.read(**call_kwargs))
     55 

[/usr/local/lib/python3.10/dist-packages/imageio/core/imopen.py](https://localhost:8080/#) in imopen(uri, io_mode, plugin, extension, format_hint, legacy_mode, **kwargs)
    279 
    280     request.finish()
--> 281     raise err_type(err_msg)

OSError: Could not find a backend to open `51.avif`` with iomode `r`._

It's available in PIL via https://pypi.org/project/pillow-avif-plugin/ plugin

**Comment by Pandede** [comment]
This issue could be resolved after the pull request #1042 is merged, as `pillow-heif` also support `avif` image file.
