### ISSUE TITLE
Support for Pillow v10.1 (re: setting `image.mode`)

### ISSUE THREAD

**Issue by tcompa** [imageio/imageio#1044]
Hi there, and thanks for your support.

In https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py#L312, the `mode` attribute of a `PIL.Image` object is set directly, as in
```python
image.mode = desired_mode
```

I think this is not working any more as of the recent Pillow v10.1:
> If you attempt to set the mode of an image directly, e.g. im.mode = "RGBA", you will now receive an AttributeError. This is not about removing existing functionality, but instead about raising an explicit error to prevent later consequences. The convert method is the correct way to change an image’s mode.
> (https://pillow.readthedocs.io/en/stable/releasenotes/10.1.0.html#setting-image-mode)

---

The minimal failing example would be something like
```python
from imageio.plugins.pillow import Image

img = Image.Image()
img.mode = "RGBA"
```
This example goes through with Pillow v10.0, but with Pillow v10.1 if fails as in:
```python traceback
Traceback (most recent call last):
  File "/tmp/x.py", line 4, in <module>
    img.mode = "RGBA"
AttributeError: can't set attribute 'mode'
```

EDIT: the test above is with imageio 2.31.5

---

(original issue in our repo, for the record: https://github.com/fractal-analytics-platform/fractal-tasks-core/issues/570)

**Comment by FirefoxMetzger** [comment]
👍 good find. This does break our pillow plugin in a few places, because we have reasons to _want_ those later consequences. 

In a nutshell, the `convert` function from pillow doesn't allow raw modes as input; however, using them allows us to do certain performance optimizations. For example:

https://github.com/imageio/imageio/blob/0bbf1962c7c36ebee28639aee8441e01d4168215/imageio/plugins/pillow.py#L289-L312

I need to see if/how we can keep this functionality given the recent changes.

**Comment by FirefoxMetzger** [comment]
I tried to "sidestep" the `Image.mode` problem by setting `Image._mode` instead until there is a better solution available. 

Unfortunately, I found some additional problems related to GIF writing (among other things, one of our test images is now detected as a "compression bomb" by Pillow) and noticed that the JPEG writer is flakey on my local Mac (produces non-deterministic results that cause sporadic test failures).

Long story short, I will pin Pillow to v10.0.0 until I can take a better look at all the changes introduced by pillow v10.1 (PR lives here https://github.com/imageio/imageio/pull/1046).

**Comment by mgorny** [comment]
Ping. Have you been able to make any progress? Given the history of security vulnerabilities in pillow, we're a bit nervous about the pin. FWICS the newest vulnerability is in `<10`  but this can change at any moment.

**Comment by FirefoxMetzger** [comment]
A little, but it is still not done. I found a solution for the problems that Pillow v10.1.0 causes in our old Pillow plugin. Now all tests pass locally on my Windows workstation but still break on CI on Linux, so I'm currently looking into those.

**Comment by FirefoxMetzger** [comment]
@mgorny Done. ImageIO once again works with all recent pillow versions and I've removed the pin. Will be part of Monday's release :)

**Comment by mgorny** [comment]
Thank you!

**Comment by GaetanLepage** [comment]
> @mgorny Done. ImageIO once again works with all recent pillow versions and I've removed the pin. Will be part of Monday's release :)

Thanks so much @FirefoxMetzger ! Do you know if the next release will happen soon ?

**Comment by FirefoxMetzger** [comment]
Thanks for the ping @GaetanLepage . It should have been released on Monday, but was blocked by failing tests on CD (the same tests passed in CI so this is an interesting failure).

I will have a look and trigger a release after I fixed the problem :)
