### ISSUE TITLE
imageio.imread changes the values of graycale pixels, try to read 12-bit png grayscale image.

### ISSUE THREAD

**Issue by keale** [imageio/imageio#1049]
Dear imageio community,

I would like to process a 12-bit grayscale image saved in png format. A monochromatic 12-bit camera was used as the signal source. The image file was created with NI Vision` IMAQ Write File2.vi`. The maximum pixel value is 419 counts. When I load the image with Python3 `imageio-2.32.0` `imageio.imread("testimagefile"`), it seems that the image is scaled automatically, the maximum value is now 55019 counts.  I tested `imageio.imread("testimagefile", mode="L")` and got 255 as maximum and `mode="I"` and got 55019 again.

How can I keep the original grayscale value?

Thanks for hints.

**Comment by keale** [comment]
`imageio.imread("testimagefile", mode="I;12")`  or `pilmode="I;12" ` returns `ValueError: conversion from L to I;12 not supported`. You can see the problem image here: [cloud.uni-jena.de/s/iqxJrDY28DJ2qjN](https://cloud.uni-jena.de/s/iqxJrDY28DJ2qjN)

**Comment by Pandede** [comment]
PNG only has the format PNG8, PNG16, PNG24 and PNG32.
I guess PNG would round up the 12-bits image to 16-bits with zero padding.

**Comment by keale** [comment]
Well, as far as I stay in LabVIEW-buble, I get the original values ( CCD signal ) when reading the file. Is it possible to reverse the applied operation?

**Comment by Pandede** [comment]
I think you may save the image in RAW format and read it with numpy is a simple feasible way.

**Comment by keale** [comment]
I found we answer and solution at [NI-Forum](https://forums.ni.com/t5/Machine-Vision/How-do-you-load-signed-16-bit-png-file-outside-of-labVIEW/m-p/4253919/highlight/true#M54066).
They propose a [solution ](https://forums.ni.com/t5/Machine-Vision/How-do-you-load-signed-16-bit-png-file-outside-of-labVIEW/m-p/4254068/highlight/true#M54069) using openCV.

**Comment by keale** [comment]
Thanks to @AndrDm.

**Comment by AndrDm** [comment]
You're welcome! Glad to see that it was helpful for you!
