### ISSUE TITLE
[Question] What tonemapping method does the imageio library use when reading HDR images?

### ISSUE THREAD

**Issue by Wanglongzhi2001** [imageio/imageio#1057]
Hello, really great job! I learned from https://stackoverflow.com/questions/31412662/imageio-to-open-hdr-file that the imageio library uses a simple global tone-mapping method by default when reading HDR images. What is the tonemapping method that the imageio library uses?

**Comment by Pandede** [comment]
The package you mentioned is the `ImageIO` in Java but not this repository in Python.
BTW, `imageio` (this repository) reads `.hdf` image file via the marvelous open-source library `freeimage`.
You may find more information in this [PDF](https://graphics.stanford.edu/courses/cs148-10-summer/docs/FreeImage3131.pdf).

**Comment by Wanglongzhi2001** [comment]
> The package you mentioned is the `ImageIO` in Java but not this repository in Python. BTW, `imageio` (this repository) reads `.hdf` image file via the marvelous open-source library `freeimage`. You may find more information in this [PDF](https://graphics.stanford.edu/courses/cs148-10-summer/docs/FreeImage3131.pdf).

Really thank you for your comprehensive answer!
