### ISSUE TITLE
Coverage drop

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#106]
We have a pretty deep coverage drop since we introduced the tiff plugin; the _tifffily.py is 5k lines, but the tests do not cover nearly all of it.

@blink1073 are there extensive tests for this that can perhaps be moved/copied here? Or should we have coverage ignore that file?

**Comment by blink1073** [comment]
Christoph has a private test suite for this file with some test TIFFs that I can't replicate.  I'd say ignore coverage (that's what we do in scikit-image).
