### ISSUE TITLE
How to add a pause between loops of a GIF?

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [imageio/imageio#1073]
I use `imageio.mimsave("fname.gif", frames, loop=4)` to save a GIF from python plots. I would like to add a pause between each loop. Is this possible?

**Comment by Pandede** [comment]
Use optional argument `duration`, it accepts `float` for all frames or `list` for one value of each frame.
Pausing the GIF between loops can be done via this tricky method:
```python
import imageio.v2 as iio

frames = iio.mimread("imageio:newtonscradle.gif")
# The default duration of each frame
default_duration = 50
# The lagging
lag = 1000
# Pause the GIF by extending the duration of the last frame
duration = [default_duration] * (len(frames)-1) + [lag]
iio.mimwrite('paused.gif', frames, loop=4, duration=duration)
```
![paused](https://github.com/imageio/imageio/assets/38829000/2d86a6e5-833b-41f4-8918-2e7c27f4692f)

Note that, you may find out the frame duration with `imageio.v3.immeta`:
```python
import imageio.v3 as iio
meta = iio.immeta("imageio:newtonscradle.gif")
print(meta['duration'])  # 50
```

**Comment by FirefoxMetzger** [comment]
I am closing this as answered - thank you again @Pandede 🚀
