### ISSUE TITLE
support read gzip data in .nrrd file

### ISSUE THREAD

**Issue by zhaolun7** [imageio/imageio#1075]
Hi, I am trying to read a .nrrd file with imageio. from the comments I guess it is generated by imageio a few years ago.

it seems like that imageio/itk doesn't support to read gzip data anymore?
The file source is: https://github.com/mrdoob/three.js/blob/dev/examples/models/nrrd/stent.nrrd
![image](https://github.com/imageio/imageio/assets/16096787/cc280818-aff1-4dca-93da-fa95943a8447)

![image](https://github.com/imageio/imageio/assets/16096787/297d3a73-f5ae-4295-8be4-947952aa9410)

**Comment by Pandede** [comment]
It seems that's the issue of `itk`, you may reprodure this error by directly invoking `itk`:
```python
import itk
image = itk.imread('stent.nrrd')
```

**Comment by zhaolun7** [comment]
@Pandede Yes, use `pynrrd` package instead.
