### ISSUE TITLE
Please make it possible to run tests against `test_images` without Internet access

### ISSUE THREAD

**Issue by mgorny** [imageio/imageio#1078]
A fair number of tests currently require data from the `test_images` repository. It is currently technically possible to download the contents of the repository as a git snapshot and unpack it into `.test_images` directory but `conftest.py` unconditionally invokes `git pull`, which breaks that.

Furthermore, the `test_images` fixture currently implies `needs_internet` marker, which makes it impossible to distinguish between the tests that actually access Internet at testing time, and these that just need the `.test_images`.

Could you, please, make it possible to use a prefetched test image cache without using `git` at all, and to deselect just the tests that need Internet? I can make a pull request if you tell me which approach you'd like to employ for this.

**Comment by Pandede** [comment]
Use the marker `needs_internet` to handle the internet interactions of `test_images` is a perfect approach.
@FirefoxMetzger How do you think about it?

**Comment by FirefoxMetzger** [comment]
> Could you, please, make it possible to use a prefetched test image cache without using git at all, and to deselect just the tests that need Internet? I can make a pull request if you tell me which approach you'd like to employ for this.

I agree that we should respect pytest inputs when we `git pull` the test images and that we shouldn't fetch if we have a marker that asks us to not use the internet. I would appreciate a PR that fixes this 🚀 

The part I am not sure about is the usage of cached images in the scenario where internet is unavailable. The intention of the cache is currently purely for performance (it is _much_ faster to cache images locally than to fetch them each time the test suite runs). This doesn't mean we can't (or shouldn't) use it to run tests offline that otherwise need the internet. However, we should have a short discussion around the implications of doing so.

My concern: How do we handle missing images? I.e., a new test image was added to the suite but hasn't been synced locally. A test may depend on the image and will now fail; however, the failure is a false positive because it's not a bug in ImageIO but a missing test image.

Also a point of curiosity: What would be the use-case for testing without internet? The "no-internet" test option today exists largely for legacy reasons. There was a use-case for it years before I joined the project, but since then nobody has expressed need for it and I was always curious why someone would want to unit-test a library on a box without internet access. (Totally not a reason to say "we shouldn't support it" - I'm honestly curious where this comes in handy.)

**Comment by mgorny** [comment]
This is how we test stuff in Gentoo — at least whenever possible. We actually have a detailed writeup on this. If you don't mind me copy-pasting:

> - the build may be running in an environment with no or restricted Internet access, and this must not cause the tests (build) to fail;
> - the Internet connection may be unstable (e.g. poor reception) in which case an interrupted connection or packet loss must not cause the tests to fail or hang, and it should not cause unnecessary delays;
> - the Internet connection may be running on a limited data plan in which case the additional network use may cause additional charges or other inconveniences to the user;
> - the remote network services used by the tests may become unavailable temporarily or permanently, causing unexpected test failures;
> - accessing remote sites always poses a privacy issue, and possibly a threat to security (e.g. through inadvertently exposing information about the system).
>
> (from https://devmanual.gentoo.org/ebuild-writing/functions/src_test/#tests-that-require-network-or-service-access)

**Comment by FirefoxMetzger** [comment]
I see. So its users building a package from source while effectively being offline. How would you distribute the pre-fetched images in this case? (How would we ensure that the image suite is up to date enough to support the tested version's test suite?)

**Comment by mgorny** [comment]
We're fetching (and mirroring) the GitHub snapshot by commit ID, making sure that the correct commit is matched to every release, e.g. for 2.34.1 we're fetching imageio/test_images@1121036015c70cdbb3015e5c5ba0aaaf7d3d6021, `https://github.com/imageio/test_images/archive/1121036015c70cdbb3015e5c5ba0aaaf7d3d6021.tar.gz`.

**Comment by FirefoxMetzger** [comment]
Ah, so a user would be served the test images alongside the source if they choose to download the source code with portage. It sounds a bit excessive to distribute almost 550MB of test images alongside 300kB of code by default but I also get the other side of the argument that "one should be able to test offline".

Either way, I see how the risk of generating false-positives from a stale cache is small if you distribute matching snapshots of the test image repo. Those that do occur, we can likely filter out when people report the issue - and if that gets too frequent we can look into adding logic to set a more descriptive error message than just "file not found".

@mgorny Would you like to submit a PR that changes the logic here?
- Modify the logic in `conftest.py` to skip updating the cache if `-m "not needs_internet"` is set
- Modify the logic of `test_images` to (1) no longer need internet, (2) check if the cache folder exists, and (3) conditionally  skip the test if no cached images are available.

**Comment by mgorny** [comment]
> Ah, so a user would be served the test images alongside the source if they choose to download the source code with portage. It sounds a bit excessive to distribute almost 550MB of test images alongside 300kB of code by default but I also get the other side of the argument that "one should be able to test offline".

They get them only if they explicitly enable testing, so it's not a major concern.

> @mgorny Would you like to submit a PR that changes the logic here?
> 
>     * Modify the logic in `conftest.py` to skip updating the cache if `-m "not needs_internet"` is set
> 
>     * Modify the logic of `test_images` to (1) no longer need internet, (2) check if the cache folder exists, and (3) conditionally  skip the test if no cached images are available.

Sure. I'm not sure if 1) is technically possible though, but I'll check through pytest docs.

**Comment by mgorny** [comment]
Ok, I don't think it's possible to check `-m` like that using the public API, and I don't think it'd be easy even with the private API.

Perhaps I could add a custom option like `--skip-needs-internet` instead?

**Comment by FirefoxMetzger** [comment]
Hm, you are right there is something finicky about the way markers and fixtures interact here. 

Normally we could use a snippet like the following inside the `test_images` fixture

```python
use_internet = False
    for marker in request.node.iter_markers(name="needs_internet"):
        use_internet = True
        break
```

This doesn't seem to work for a session-scoped one; however, it works perfectly fine when I remove the session scope. Let me brainstorm on this for a bit to see if there is a nice way around it. I would prefer to not have 2 arguments (`-m "not needs_internet"` and `--skip-needs-internet`) that do the same thing.

**Comment by mgorny** [comment]
Please correct me if I'm wrong, but doesn't that iterate over markers that the specific test is decorated with, rather than these requested by user?

**Comment by FirefoxMetzger** [comment]
How about the following solution:

1. we add the `pytestconfig` fixture to `test_images`
2. We use the below snippet to check if `needs_internet` was deselected

```python
use_internet = "not needs_internet" not in pytestconfig.getoption("-m")
```


>Please correct me if I'm wrong, but doesn't that iterate over markers that the specific test is decorated with, rather than these requested by user?

You're right. Tests with deselected markers won't be run in the first place and thus their fixture never executes, meaning the above won't actually work for us - well spotted!

**Comment by mgorny** [comment]
I suppose that could work. It feels kinda icky but should be good enough.
