### ISSUE TITLE
Release (with NumPy 2 compatibility)?

### ISSUE THREAD

**Issue by jakirkham** [imageio/imageio#1090]
Recently some fixes were made for NumPy 2.0 ( https://github.com/imageio/imageio/issues/1077 ) ( https://github.com/imageio/imageio/pull/1089 ). Am curious if it would be possible to make a release so users get these fixes when using NumPy 2.0

**Comment by FirefoxMetzger** [comment]
Yep that's possible, normally releases roll out every Monday ... but today they didn't. I will check the CD pipeline once I finish my actual work.

**Comment by FirefoxMetzger** [comment]
Turns out it tripped on a flakey GH actions runner for the pypy tests. Re-ran the failed test and now the updated version is released :)

**Comment by jakirkham** [comment]
Great thanks Sebastian! 🙏

This takes automating releases to the next level 😄
