### ISSUE TITLE
Regression in imageio release 2.35.0 ; install_requires numpy less than 2.0.0

### ISSUE THREAD

**Issue by maxwell-k** [imageio/imageio#1097]
First thank you for this library, I've been a user and a fan of imageio for a long time.  For my use case; I notice a problem with the latest release; it pulls in an older version of NumPy than the previous release:

- `imageio==2.34.2` didn't have an upper bound on the version of NumPy
- `imageio==2.35.0` forces `numpy<2.0.0`
- relevant [line in setup.py](https://github.com/imageio/imageio/blob/v2.35.0/setup.py#L86)

Context:

- merged [pull request](https://github.com/imageio/imageio/pull/1089) adding NumPy 2.0 support
- [issue](https://github.com/imageio/imageio/issues/1090) asking for a release with NumPy 2.0 compatibility that lead to 2.34.2
- [commit](https://github.com/imageio/imageio/commit/6bc8c6cf9b5015eb4a514f8debcf92eca7162f1c) that introduced the `numpy<2.0` constraint

<details>

<summary>Demonstration of pip installing numpy==2.0.1 with imageio==2.34.2</summary>

Command to demonstrate with 2.34.2:

    python3.12 -m venv --clear --upgrade-deps .venv \
    && .venv/bin/python -m pip install imageio==2.34.2 \
    && .venv/bin/python -m pip list

Output:

    Collecting imageio==2.34.2
      Downloading imageio-2.34.2-py3-none-any.whl.metadata (4.9 kB)
    Collecting numpy (from imageio==2.34.2)
      Downloading numpy-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
    Collecting pillow>=8.3.2 (from imageio==2.34.2)
      Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
    Downloading imageio-2.34.2-py3-none-any.whl (313 kB)
    Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
    Downloading numpy-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 12.8 MB/s eta 0:00:00
    Installing collected packages: pillow, numpy, imageio
    Successfully installed imageio-2.34.2 numpy-2.0.1 pillow-10.4.0
    Package Version
    ------- -------
    imageio 2.34.2
    numpy   2.0.1
    pillow  10.4.0
    pip     24.2

</details>

<details>

<summary>Demonstration of pip installing numpy==1.26.4 with imageio==2.35.0</summary>

Command to demonstrate with 2.35.0:

    python3.12 -m venv --clear --upgrade-deps .venv \
    && .venv/bin/python -m pip install imageio==2.35.0 \
    && .venv/bin/python -m pip list

Output:

    Collecting imageio==2.35.0
      Downloading imageio-2.35.0-py3-none-any.whl.metadata (5.0 kB)
    Collecting numpy<2.0.0 (from imageio==2.35.0)
      Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
    Collecting pillow>=8.3.2 (from imageio==2.35.0)
      Downloading pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
    Downloading imageio-2.35.0-py3-none-any.whl (315 kB)
    Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 13.2 MB/s eta 0:00:00
    Downloading pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 12.9 MB/s eta 0:00:00
    Installing collected packages: pillow, numpy, imageio
    Successfully installed imageio-2.35.0 numpy-1.26.4 pillow-10.4.0
    Package Version
    ------- -------
    imageio 2.35.0
    numpy   1.26.4
    pillow  10.4.0
    pip     24.2

</details>

Is this desired behaviour?

**Comment by zlevine-spin** [comment]
Same issue here. thanks @maxwell-k

**Comment by FirefoxMetzger** [comment]
Interesting find. There shouldn't be anything requiring us to be on `numpy<2.0` - quite the opposite in fact I went and patched all the places where we didn't support it when it was released.

I'll have a look during my afternoon.

**Comment by maxwell-k** [comment]
@FirefoxMetzger Thank you for looking into this so quickly. Do you have plans to release a new version including the fix? Does imageio have a release schedule? Thanks again, I appreciate your help.

**Comment by FirefoxMetzger** [comment]
We have automatic releases every Monday morning. I was thinking of triggering it manually for this, but then I realized that it's smart to not release changes a few hours before the weekend.
