### ISSUE TITLE
All images are stacked and the previous frame image will not disappear

### ISSUE THREAD

**Issue by ZhuGeCold** [imageio/imageio#1106]
`iio.imwrite(directory+"gresult.gif",img_array,fps=1,duration=1,loop=0)`

I set the parameters I already know and generated the gif successfully, but all the already played frames stay on the screen without disappearing, so that about 20 pictures are stacked on top of each other.
I checked the documentation but didn't get a solution, please help me thanks.

**Comment by Pandede** [comment]
I'm trying to reproduce the scenario but it works fine:
```python
import imageio.v3 as iio

iio.imwrite(
    'output.gif',
    iio.imread(".test_images/newtonscradle.gif"),
    fps=1,
    duration=1,
    loop=0
)
```
![output](https://github.com/user-attachments/assets/ae3b237b-f99c-48cc-b527-2446d3f9b5b9)

May you provide the images for building the GIF?

**Comment by ZhuGeCold** [comment]
Of course. Their background is transparent instead of the usual white background, I'm not sure if this is the cause of the problem.

![E061_01](https://github.com/user-attachments/assets/3b3a2866-0906-45e5-8526-50e45a1178ed)
![E061_02](https://github.com/user-attachments/assets/5b081a7e-681b-4baf-96d9-de48ea57d55c)
![E061_03](https://github.com/user-attachments/assets/6351e516-8857-4bfc-8cea-0c16fac7f853)
![E061_04](https://github.com/user-attachments/assets/50e13ad8-b484-4398-9aa8-2fb672e14260)
![E061_05](https://github.com/user-attachments/assets/056ca17f-a6a8-40a7-a3be-b1ae4fe13563)
![E061_06](https://github.com/user-attachments/assets/724e17c1-84bf-4c7c-981e-58de47850809)
![E061_07](https://github.com/user-attachments/assets/c5c788b2-aa89-4e07-9896-cfcc381dfc46)
![E061_08](https://github.com/user-attachments/assets/f2d6e6ed-e5c9-4205-9abd-0d03f38e47a9)
![E061_09](https://github.com/user-attachments/assets/0760b8b1-69ce-4bc1-801d-79d9223c6fb3)
![E061_10](https://github.com/user-attachments/assets/4b827532-0919-468b-a61b-7dfae14a56d6)
![gresult](https://github.com/user-attachments/assets/2f30c014-e665-4ca2-8cc5-98a90476c5fd)

**Comment by ZhuGeCold** [comment]
> I'm trying to reproduce the scenario but it works fine:我正在尝试重现该场景，但效果很好：
> 
> ```python
> import imageio.v3 as iio
> 
> iio.imwrite(
>     'output.gif',
>     iio.imread(".test_images/newtonscradle.gif"),
>     fps=1,
>     duration=1,
>     loop=0
> )
> ```
> 
> ![output](https://private-user-images.githubusercontent.com/38829000/382562029-ae3b237b-f99c-48cc-b527-2446d3f9b5b9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mjg0MjIsIm5iZiI6MTczMDYyODEyMiwicGF0aCI6Ii8zODgyOTAwMC8zODI1NjIwMjktYWUzYjIzN2ItZjk5Yy00OGNjLWI1MjctMjQ0NmQzZjliNWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NzRhNzkyYTUxMzA1Y2EyNTcwOGIzMjBmZWZlMzE4NDc1Y2FjNGU0NzBjYTA5YmJjNDEwZGM1NWNlNjVhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SctU_5838i4ATKZs-K2KwSLBzvD-u4J4Z1EDIGffxlQ) [ ![output](https://private-user-images.githubusercontent.com/38829000/382562029-ae3b237b-f99c-48cc-b527-2446d3f9b5b9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mjg0MjIsIm5iZiI6MTczMDYyODEyMiwicGF0aCI6Ii8zODgyOTAwMC8zODI1NjIwMjktYWUzYjIzN2ItZjk5Yy00OGNjLWI1MjctMjQ0NmQzZjliNWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NzRhNzkyYTUxMzA1Y2EyNTcwOGIzMjBmZWZlMzE4NDc1Y2FjNGU0NzBjYTA5YmJjNDEwZGM1NWNlNjVhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SctU_5838i4ATKZs-K2KwSLBzvD-u4J4Z1EDIGffxlQ) ](https://private-user-images.githubusercontent.com/38829000/382562029-ae3b237b-f99c-48cc-b527-2446d3f9b5b9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mjg0MjIsIm5iZiI6MTczMDYyODEyMiwicGF0aCI6Ii8zODgyOTAwMC8zODI1NjIwMjktYWUzYjIzN2ItZjk5Yy00OGNjLWI1MjctMjQ0NmQzZjliNWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NzRhNzkyYTUxMzA1Y2EyNTcwOGIzMjBmZWZlMzE4NDc1Y2FjNGU0NzBjYTA5YmJjNDEwZGM1NWNlNjVhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SctU_5838i4ATKZs-K2KwSLBzvD-u4J4Z1EDIGffxlQ) [ ](https://private-user-images.githubusercontent.com/38829000/382562029-ae3b237b-f99c-48cc-b527-2446d3f9b5b9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mjg0MjIsIm5iZiI6MTczMDYyODEyMiwicGF0aCI6Ii8zODgyOTAwMC8zODI1NjIwMjktYWUzYjIzN2ItZjk5Yy00OGNjLWI1MjctMjQ0NmQzZjliNWI5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEwMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NzRhNzkyYTUxMzA1Y2EyNTcwOGIzMjBmZWZlMzE4NDc1Y2FjNGU0NzBjYTA5YmJjNDEwZGM1NWNlNjVhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SctU_5838i4ATKZs-K2KwSLBzvD-u4J4Z1EDIGffxlQ)
> 
> May you provide the images for building the GIF?您可以提供构建 GIF 的图像吗？

Of course. Their background is transparent instead of the usual white background, I'm not sure if this is the cause of the problem.

![E061_01](https://github.com/user-attachments/assets/3b3a2866-0906-45e5-8526-50e45a1178ed)
![E061_02](https://github.com/user-attachments/assets/5b081a7e-681b-4baf-96d9-de48ea57d55c)
![E061_03](https://github.com/user-attachments/assets/6351e516-8857-4bfc-8cea-0c16fac7f853)
![E061_04](https://github.com/user-attachments/assets/50e13ad8-b484-4398-9aa8-2fb672e14260)
![E061_05](https://github.com/user-attachments/assets/056ca17f-a6a8-40a7-a3be-b1ae4fe13563)
![E061_06](https://github.com/user-attachments/assets/724e17c1-84bf-4c7c-981e-58de47850809)
![E061_07](https://github.com/user-attachments/assets/c5c788b2-aa89-4e07-9896-cfcc381dfc46)
![E061_08](https://github.com/user-attachments/assets/f2d6e6ed-e5c9-4205-9abd-0d03f38e47a9)
![E061_09](https://github.com/user-attachments/assets/0760b8b1-69ce-4bc1-801d-79d9223c6fb3)
![E061_10](https://github.com/user-attachments/assets/4b827532-0919-468b-a61b-7dfae14a56d6)
![gresult](https://github.com/user-attachments/assets/2f30c014-e665-4ca2-8cc5-98a90476c5fd)

**Comment by Pandede** [comment]
@ZhuGeCold You're right, that's because the transparent background of PNG, replace the transparent into the white background can fix this problem:
```python
from glob import glob

import numpy as np

import imageio.v3 as iio


def transparent_to_white(image):
    if image.shape[-1] == 4:
        alpha_channel = image[..., 3]
        white_background = np.ones_like(image) * 255
        white_background[..., :3] = image[..., :3]
        white_background[alpha_channel == 0] = [255, 255, 255, 255]
        return white_background
    return image


ims = [transparent_to_white(iio.imread(frame)) for frame in glob("*.png")]

iio.imwrite(
    'output.gif',
    ims,
    fps=1,
    duration=1,
    loop=0
)
```

**Comment by FirefoxMetzger** [comment]
The reason this happens is the "disposal method" set for the GIF. I can't find a good way to xref the spec, so here is the the quote of the relevant section:

     iv) Disposal Method - Indicates the way in which the graphic is to be treated after being displayed.
            Values :    0 -   No disposal specified. The decoder is
                              not required to take any action.
                        1 -   Do not dispose. The graphic is to be left
                              in place.
                        2 -   Restore to background color. The area used by the
                              graphic must be restored to the background color.
                        3 -   Restore to previous. The decoder is required to
                              restore the area overwritten by the graphic with
                              what was there prior to rendering the graphic.
                     4-7 -    To be defined.

The default of pillow is `1` (do not dispose). In theory this can be adjusted, but I never quite got it to work, so - unfortunately - I can't say which parameter to pass in order to wipe the canvas/screen between two frames.
