### ISSUE TITLE
Cannot Write 16-Bit Monochrome Lossless Videos

### ISSUE THREAD

**Issue by AlexanderGroeger** [imageio/imageio#1107]
Hi,

I'm trying to run a simple ChatGPT code example that will save 16-bit monochrome videos with lossless encoding, but every time I try to do so, I get a warning message `Lossy conversion from uint16 to uint8. Losing 8 bits of resolution. Convert image to uint8 prior to saving to suppress this warning.`

I don't know how to get around this issue, but I'm pretty sure FFV1 supports 16-bit encoding/decoding when I ran imageio's ffmpeg executable using the `-codecs` flag. I'm using python 3.12.0 with imageio 2.34.0. I installed it with `pip install imageio[ffmpeg]`.

I just want to write 16-bit monochrome lossless videos for data storage purposes. I'm intentionally moving away from splitting the 16-bit frames into an 8-bit RGB frames.

```python
import numpy as np
import imageio

# Define video parameters
width, height, fps = 640, 480, 30
num_frames = fps*2

# Create a video writer object with the desired parameters
output_file = "output_video.avi"

with imageio.get_writer(
    output_file,
    format='FFmpeg',
    fps=fps,
    codec='ffv1',  # Use FFV1 for lossless compression
    ffmpeg_params=['-pix_fmt', 'gray16le']  # Set pixel format to 16-bit grayscale
) as writer:
    for _ in range(num_frames):
        # Generate a random 16-bit frame
        frame = np.random.randint(0, 65536, (height, width), dtype=np.uint16)
        
        # Append the frame to the video writer
        writer.append_data(frame)

print(f"Video saved as {output_file}")
```

**Comment by Pandede** [comment]
You may use plugin `pyav` instead:
```python
import numpy as np

import imageio.v3 as iio

# Define video parameters
width, height, fps = 640, 480, 30
num_frames = fps*2

# Create a video writer object with the desired parameters
output_file = "output_video.avi"

# Generate random 16-bit frames
frames = np.random.randint(0, 65536, (num_frames, height, width), dtype=np.uint16)

iio.imwrite(
    output_file,
    frames,
    plugin='pyav',
    codec='ffv1',
    in_pixel_format='gray16le',
    out_pixel_format='gray16le'
)

print(f"Video saved as {output_file}")
```

**Comment by AlexanderGroeger** [comment]
Got it. Thank you for looking into this!
