### ISSUE TITLE
What if we create a PNG/JPEG plugin based on libpng and libjpeg

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#111]
libpng and libjpeg are probably small enough that we can just ship the dst package with a version for each platform (maybe all linuxes come even with these libs by default?), or even include it in the git repo. With good png and jpeg support provided this way, I think we can make freeimage an optional dependency, making distribution much easier.

**Comment by almarklein** [comment]
@blink1073 thoughs? This is something for the longer term, I suppose; I don't expect these plugins to be written overnight.

**Comment by blink1073** [comment]
Seems reasonable, though I have no interest myself in writing low-level drivers.

**Comment by almarklein** [comment]
I remember freaking out a bit when touching the very beginnings of the libjpeg API. More importantly, this issue is no longer relevant now that we have Pillow providing good PNG and JPEG support.
