### ISSUE TITLE
Alternatives for FreeImage

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#114]
FreeImage is maintained by a small group of devs, which is not necessarily a bad thing, but they are on sourceforge with CVS for version control. On [people asking](http://sourceforge.net/p/freeimage/discussion/36111/thread/f2fae857/) them to move to Github, so they can have CI, more contributors, etc. they seem to fail to see the advantage.

This is slightly worrisome, and we should keep an eye out for alternatives, thus this issue.
- Nathanael Jones keeps a clone of freeimage. They have not changed code, but added CI: https://github.com/imazen/freeimage
- There's several other Freeimage clones on GH, but most seem to have changed the code.
- There is https://github.com/OpenImageIO/oiio
- We could ctypes into libjpeg and libpng (#111)
- Maybe  Luis' [imread](http://luispedro.org/software/imread/), which is C++, but maybe he can provide a C-api that we can talk to using ctypes.
- Pillow

**Comment by stefanv** [comment]
@njsmith  just pointed out to me that FreeImage's license is essentially MPL 1.0, which is not GPL compatble.  This package (which "links" to freeimage using ctypes), is governed under the more restrictive of the BSD and the MPL license, not the BSD license as indicated.

/cc @blink1073

**Comment by blink1073** [comment]
I'd be in favor of adding a Pillow plugin based on the one we have in scikit-image, and adding a dependency here on Pillow.

**Comment by almarklein** [comment]
> This package (which "links" to freeimage using ctypes), is governed under the more restrictive of the BSD and the MPL license, not the BSD license as indicated.

I'm not sure I follow ...

**Comment by blink1073** [comment]
By bundling freeimage *and* depending on it, this library becomes subject to the licensing terms of that library, if I understand correctly.

**Comment by stefanv** [comment]
Yes, and not even bundling--the moment you use ctypes to load freeimage, you've effectively linked to it and the binary should be distributed under the terms of the GPL, not the BSD license.

**Comment by njsmith** [comment]
Specifically IIUC if you use/distribute FreeImage then you're bound by either the GPL (v2 or v3), or the "FreeImage Public License" which is a rebranding of the Mozilla Public License v1.0. The situation is complicated, and it's *definitely* misleading to summarize it as being "BSD". (The GPL is, well, the GPL, and MPL 1.0 is a funky weak-copyleft license that's GPL-incompatible and deprecated -- Mozilla these days uses the substantially rewritten MPL 2.0.)

**Comment by almarklein** [comment]
I remember having looked into the FreeImage license with a few other ppl when this all started. We concluded that it looked ok-ish. GPL is a problem, obviously, but the FPL seemed liberal enough for us to bind to the binaries. So I'm guessing we drew the wrong conclusion then?

**Comment by stefanv** [comment]
As Nathaniel mentioned, the FPL is, at a quick glance at least, the MPL 1.0, which is more constraining than BSD.

**Comment by almarklein** [comment]
Well, the LPGL is also more constraining than BSD, but it would allow us using the libs :)  Before we make any decisions, I'd like to be sure that MPL restricts us from ctyping into the libs (from BSD-licensed code).

**Comment by njsmith** [comment]
It depends on what you mean by "restricts". Legally you can certainly call into the MPL1.0-licensed libs. However, there are people who can use BSD-licensed code who would no longer be able to use your code, i.e. your code would not actually be BSD-licensed anymore as far as downstream users are concerned. The most obvious example is that the MPL1.0 and GPL are incompatible licenses, so a GPL licensed project is allowed to use your library if it's BSD-licensed, but not if you use MPL1.0 code. Well, and there are complicated details that depend on whether they actually get distributed together or not, and possibly in this particular case they could instead choose the GPL-licensing option for FreeImage. 

I think the bottom line is, your users might or might not be okay with whatever license you end up using -- it's just that the whole (imageio + freeimage) conglomeration is not actually BSD-licensed, so instead of telling users that it it BSD you should somehow communicate what the license actually is so that they can decide whether or not it works for their particular circumstances.

**Comment by almarklein** [comment]
Ok, I read through the FI license again. This is what I make of it.

> 2.1. The Initial Developer Grant.
> The Initial Developer hereby grants You a world-wide, royalty-free, non-exclusive license, subject to third party intellectual property claims:
>
> (a) to use, reproduce, modify, display, perform, sublicense and distribute the Original Code (or portions thereof) with or without Modifications, or as part of a Larger Work; and
>
> (b) under patents now or hereafter owned or controlled by Initial Developer, to make, have made, use and sell ("Utilize") the Original Code (or portions thereof), but solely to the extent that
any such patent is reasonably necessary to enable You to Utilize the Original Code (or portions thereof) and not to any greater extent that may be necessary to Utilize further Modifications or
combinations.

Sounds good ...

> 3.6. Distribution of Executable Versions.
> You may distribute Covered Code in Executable form only if the requirements of Section 3.1-3.5 have been met for that Covered Code, ...

Meaning that any changes that we make to the freeimage source code must be made available under the same license. But we make no changes to freeimage itself.

> ... and if You include a notice stating that the Source Code version of the Covered Code is available under the terms of this License, including a description of how and where You have fulfilled the obligations of Section 3.2. The notice must be conspicuously included in any notice in an Executable version, related documentation or collateral in which You
describe recipients' rights relating to the Covered Code. 

So, we should mention/provide the FreeImage license in our docs and let our users know that any derived work should also mention the FI license.

> You may distribute the Executable version of Covered Code under a license of Your choice, which may contain terms different from this License,
provided that You are in compliance with the terms of this License and that the license for the Executable version does not attempt to limit or alter the recipient's rights in the Source Code version from the rights set forth in this License. If You distribute the Executable version under a different license You must make it absolutely clear that any terms which differ from this License are offered by You alone, not by the Initial Developer or any Contributor. You hereby agree to indemnify the Initial Developer and every Contributor for any liability incurred by the Initial Developer or such Contributor as a result of any such terms You offer.

IIUC this means we can ship and use the library, and as long as we honor the FI license for the FI code, we can use whatever license we want for *our* code.

> 3.7. Larger Works.
> You may create a Larger Work by combining Covered Code with other code not governed by the terms of this License and distribute the Larger Work as a single product. In such a case, You must make sure the requirements of this License are fulfilled for the Covered Code.

**Comment by njsmith** [comment]
I'm sorry, but I just don't really have time to play armchair lawyer here :-/.  Sorry that FOSS licensing means that you have to somehow pick up a bunch of expertise in this irrelevant nonsense... I stand by my summary in my previous comment. (BTW your summary skills over crucial bits, including the parts that make MPL1.0 incompatible with the GPL.)

**Comment by almarklein** [comment]
Thanks for your comments @njsmith. I am just trying to make sense of the situation, and I want to be absolutely certain that the problem is indeed so big that we may need a decision like ditching freeimage.

Maybe I am naive, but wouldn't each software that uses imageio (and thus freeimage) have the option to use either the GPL or FIPL to cover the freeimage libs? If that's the case, I don't see the problem.

**Comment by njsmith** [comment]
This is why I said:
> I think the bottom line is, your users might or might not be okay with whatever license you end up using -- it's just that the whole (imageio + freeimage) conglomeration is not actually BSD-licensed, so instead of telling users that it it BSD you should somehow communicate what the license actually is so that they can decide whether or not it works for their particular circumstances.

:-)

(Though of I were a downstream package of you I'd be tempted to conclude that it's a problem just because I can't be bothered to try and explain the resulting licensing complexities to all of *my* users -- that's a legitimate reason not to take on a dependency.)

**Comment by almarklein** [comment]
Ok, so what does this mean concretely, according to @njsmith and @stefanv, in terms of imageio becoming skimage's image io module? What possible actions do we have?

**Comment by almarklein** [comment]
I thought about this some more. Sorry if I sound repetitive here, but I am not convinced by your arguments :)

1) I keep thinking, what if FI were covered by the LGPL license, like PySide is. I am pretty sure there would be no problem, because any code that wraps it can be covered by any license, only the library being wrapped is covered by the LGPL. With that in mind, and the fact that the FIPL seems more liberal than the LPGL ... what's the problem? 

2) PyQt4 is a an example library covered by a dual license, and AFAIK, any library that uses it can select either the GPL or the commercial license. And any software that uses a library that uses PyQt4 can make that choice *again*. Why would it be different in this case? 

3) I am pretty sure that the FreeImage devs would be happy to see us use their work. If there really is a problem, maybe we should seek out a solution instead of running away. My guess is that they won't just jump at using BSD. But maybe we can convince them to use MPL 2.0 if that helps?

Do we need help with establishing what the problem is / could be? Maybe Continuum has ppl who can offer advice in this matter.

**Comment by njsmith** [comment]
FIPL is not really more liberal than LGPL in any useful sense -- it is more liberal in some ways, less so in others, the details are what matter. For example, GPL code can use LGPL code, but GPL code cannot use FIPL code, because FIPL imposes extra restrictions that the LGPL does not. (There are also extra restrictions imposed by the LGPL that are not imposed by the FIPL, but this isn't relevant to the current issue.)

Contacting the FreeImage devs would indeed make sense. Perhaps they'd be willing to add LGPL or BSD or MPL 2.0 to their license list to make things clearer. Of course, this is only possible if everyone who has ever contributed code to FreeImage can be found and agrees, which is often a challenge. But I don't know how diverse the FreeImage contributor base is -- maybe this is just a few people. And only if skimage is willing to link to LGPL or MPL 2.0 code.

In theory NumFOCUS can provide legal advice to its sponsored projects -- is skimage signed up yet? Or the SFLC might be able to help -- they have actual experts on these kinds of licenses :-). But, when talking to a lawyer you have to be clear on what exactly the question is. Obviously no lawyer is going to say "oh yes, dual-licensed GPL/FIPL is totally identical and interchangeable with BSD, so it's totally legit to distribute FreeImage as part of wheels while telling people that the BSD license is the only license relevant to those wheels". So what are you hoping to get instead?

**Comment by almarklein** [comment]
@njsmith and @stefanv are you guys in Scipy coming July? If so, it would be great if we could discuss this in person and come up with a plan.

**Comment by njsmith** [comment]
I'll be there yes.

On Fri, May 13, 2016 at 1:57 PM, Almar Klein <notifications@github.com>
wrote:

> @njsmith <https://github.com/njsmith> and @stefanv
> <https://github.com/stefanv> are you guys in Scipy coming July? If so, it
> would be great if we could discuss this in person and come up with a plan.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/imageio/imageio/issues/114#issuecomment-219157281>
>



-- 
Nathaniel J. Smith -- https://vorpus.org <http://vorpus.org>

**Comment by stefanv** [comment]
Yes, I'll be there as well.

>
>

**Comment by almarklein** [comment]
Yay, we managed to meet up! Summarizing:

The problem with the freeimage license is that it is based on version 1 of the MPL (Mozilla Public License), which is incompatible with the GPL. As written on [this page](https://www.gnu.org/licenses/license-list.en.html): *"[The CDDL license] is a free software license. It has a weak per-file copyleft (like version 1 of the Mozilla Public License) which makes it incompatible with the GNU GPL. This means a module covered by the GPL and a module covered by the CDDL cannot legally be linked together. "*

The MPL 2.0 does *not* have this problem, as is written in the [MPL v2.0 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/): *"Q14: May I combine MPL-licensed code and (L)GPL-licensed code in the same executable program? --- Yes, by creating a "Larger Work" under the terms of Section 3.3. In particular, three requirements must be met: [...]"*

The plan is to contact the FreeImage authors to hopefully convince them to upgrade to the MPL 2.0 license.

Regardless of  what the outcome of that will be, we'll add a plugin based on Pillow, which seems to come really close nowadays in terms of supported formats (and is on GitHub, has CI, etc.). The outcome will likely affect what we'll do about what the default plugin will be for certain formats, and whether we include/depend on FreeImage and Pillow by default.

**Comment by ghisvail** [comment]
> The plan is to contact the FreeImage authors to hopefully convince them to upgrade to the MPL 2.0 license.

I believe it is in the pipeline (some thread I read on the upstream sourceforge forum), but the project does not look very active. I forwarded a few patches to them and never got any reply back for instance.

> we'll add a plugin based on Pillow, which seems to come really close nowadays in terms of supported formats

Using Pillow as a dependency sounds more sensible indeed, with the added benefit that it will be easily pip installable.

**Comment by almarklein** [comment]
I have not yet had a reply from the email that I sent in July. I just send a reminder. In the meantime I plan to work on a Pillow plugin in the coming weeks.

**Comment by almarklein** [comment]
Took me a while, but its done!

**Comment by njsmith** [comment]
Hooray! I know this kind of thing can be long and thankless, so: thanks :-)

**Comment by stefanv** [comment]
This is amazing; thank you so much!  Now the path is open to using imageio as the IO backend to skimage.

**Comment by timofonic** [comment]
How and where? Where's the updated version? Sourceforge repository is outdated. Please inform more about this if you can ;)

**Comment by ghisvail** [comment]
> Sourceforge repository is outdated.

Who in the world is still using SourceForge to get software? PyPI is you friend.

**Comment by timofonic** [comment]
Sorry, but PyPI is for Python. There's a world of other programming
languages, y'know ;)

2016-12-28 14:31 GMT+01:00 Ghislain Antony Vaillant <
notifications@github.com>:

**Comment by ghisvail** [comment]
> Sorry, but PyPI is for Python.

And `imageio` is written in?

**Comment by p-pap** [comment]
> FreeImage is maintained by a small group of devs, which is not necessarily a bad thing, but they are on sourceforge with CVS for version control. On [people asking](http://sourceforge.net/p/freeimage/discussion/36111/thread/f2fae857/) them to move to Github, so they can have CI, more contributors, etc. they seem to fail to see the advantage.

I'm sorry but I fail to see the "advantage" as well. I m not related to FreeImage developers nor I am a big fan of SourceForge, but I applaud their decision to stay away of GitHub.As for their CVS for version control - which you seem to hate - well guess what, they seem to like it. It's their project, not yours.

GitHub created more problems than the ones it is supposed to solve. To name the tip of the iceberg: every random unskilled "coder" just forks an existing project, adds literally nothing to it (or replaces building system with another one nobody asked for) and there, he/she is a developer now. I can perfectly understand why some developers stay away of GitHub, and I am one of them. The only reason I have an account here is because of other projects require it for bug reports.

**Comment by almarklein** [comment]
> It's their project, not yours.

Sure. But there is no way for us to contribute back this way. This is a liability. Similarly they have been unwilling to update their license to make it more easier to use legal-wise. The FreeImage devs are free to do what and where they want. Good for them. But it has implications on how useful FreeImage is to us. That's all what this issue is about 🤷

**Comment by stefanv** [comment]
Everyone's entitled to their opinion on all these issues, but I don't see the point of this discussion; this issue has been closed since 2016. Please make concrete suggestions for changes, if any, and otherwise let's keep the conversation civil.

**Comment by ghisvail** [comment]
I did not expect this thread be revived and fail to understand the rationales as to why.
