### ISSUE TITLE
New Plugin for video based on PyAV (bindings to ffmpeg lib)

### ISSUE THREAD

**Issue by jakirkham** [imageio/imageio#115]
It looks like it hasn't seen a release in almost 3 years and no new commits in 1.25 years. This is a little concerning. Is it worth considering alternatives or is this unnecessary?

**Comment by almarklein** [comment]
ffmpeg is an alternative. avbin was added as a lighter weight and possibly faster alternative (because ffmpeg transfers image data over a pipe, while avbin can be communicated with via ctypes). But if you know an alternative, I'm happy to learn about it.

**Comment by patricksnape** [comment]
I agree with @jakirkham - this [Debian mailing list conversation](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741935) seems to suggest that Debian are going to mark AVbin as orphaned. The one guy working on it seems to be struggling for time.

**Comment by patricksnape** [comment]
[PyAV](https://github.com/mikeboers/PyAV) seems to be working quite actively on creating a native FFMPEG binding library for Python - it doesn't seem they are using pipes to me.

**Comment by almarklein** [comment]
Interesting. PyAV is not pure Python, but we could make a plugin that hooks into it (so PyAV becomes an optional dependency).

**Comment by ghisvail** [comment]
The `avbin` library is gone from Debian, which makes the avbin plugin of imageio useless on Debian-based distributions.

**Comment by almarklein** [comment]
I would still love this, but its pretty much for conda-users only. I've been working on making improvements to the current ffmpeg plugin in the past days. I'm probably not going to work on this myself anytime soon, but am very open to other contributing a pyAV plugin (I suspect it's a relatively easy plugin to make).

**Comment by jakirkham** [comment]
It looks like [PyAV]( https://github.com/mikeboers/PyAV#installation ) can be `conda` or `pip` installed. So don't think this is limited to `conda` users.

That said, I suspect (and am somewhat biased by personal experience) that the overlap of people working with image data in Python and `conda` users is near to complete.

**Comment by ghisvail** [comment]
I'd welcome that change too.

**Comment by almarklein** [comment]
That's great. This will probably one of the things I'll work on in my next "image sprint".

**Comment by almarklein** [comment]
Oh crap. It looks like something has changed, or I did not look close enough earlier, but pyav is only available via conda now :'(

**Comment by almarklein** [comment]
Let's take this discussion here: #406

**Comment by jakirkham** [comment]
> Oh crap. It looks like something has changed, or I did not look close enough earlier, but pyav is only available via conda now :'(

Looks like they call it [av]( https://pypi.org/project/av/ ) on PyPI and conda-forge.
