### ISSUE TITLE
How to get and distribute freeimage libraries

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#121]
- [x] Let setup.py make wheels containing the libs for Windows and OSX (#108)
- [ ] Get a good freeimage conda recipe accepted at anaconda-recipes
- [ ] Do a release. Get things out in the wild
- [ ] Create/update imageio conda recipe
- [ ] Add a script to imageio-binaries that downloads the freeimage libs from anaconda.org, so that we have one source for the freeimage lib (imageio-binaries is then basically a mirror). Or ... Maybe we should make imageio download from anaconda.org directly.

When we have this sorted:
- [ ] If all this works well for a release or two, make imageio a skimage dependency
- [ ] Maybe we can eventually deprecate the auto-downloading?

cc @blink1073

**Comment by ghisvail** [comment]
> make imageio a skimage dependency

Is this a plan for skimage or is it just a proposal?

> deprecate the auto-downloading?

In favour of an Anaconda-only solution? (based on the first bullet points)

**Comment by almarklein** [comment]
This plan is currently stuck on a license issue for freeimage. See the discussion in  #114

**Comment by almarklein** [comment]
#167 makes this a non-issue.
