### ISSUE TITLE
Support for FLIF (free lossless image format)

### ISSUE THREAD

**Issue by bitwave** [imageio/imageio#122]
Are there plans integrating FLIF? (See: http://flif.info/)

bitwave

**Comment by almarklein** [comment]
I did not know about FLIF until just now. It seems interesting; I'd be open to contributions. Is there a lib we can wrap with ctypes, or (even better), would it be possible to implement this in pure Python?

**Comment by bitwave** [comment]
I think implementing in python will be too slow...

**Comment by bitwave** [comment]
... and the current problem is, that flif is relativly new, so we have this: https://github.com/FLIF-hub/FLIF/issues/4 (no C interface, only C++, only file2mem based for decode, encode vice versa)...

**Comment by bitwave** [comment]
ctypes is (currently) not an option. I got only C++ gibberish, nothing useful :(

**Comment by almarklein** [comment]
> I think implementing in python will be too slow...

It does not have to be, it would depend on the compression and complexity of the format in general. E.g. a pure Python PNG encoder/decoder is pretty darn fast. I think the biggest limitation is whether the kind of compression used is natively supported in Python (e.g. zlib, bz2, or lzma).

We could also create a C lib that statically links to their C++ lib and in that way expose a C api that we can hook into with ctypes. But maybe its better to wait for them to implement a C API.

**Comment by bitwave** [comment]
the C api is there...

**Comment by bitwave** [comment]
I have started implementing it...

**Comment by bitwave** [comment]
https://github.com/bitwave/imageio/tree/flif

**Comment by almarklein** [comment]
Awesome!

**Comment by almarklein** [comment]
Any luck with this? :)

**Comment by bitwave** [comment]
I stopped on it more or less. :(

**Comment by almarklein** [comment]
No problem. Out of curiosity, were you stuck on something, or was it mostly a lack of time?

**Comment by bitwave** [comment]
Lack of time...

**Comment by FirefoxMetzger** [comment]
I just checked the website of FLIF mentioned in the first post. It now has a paragraph saying

> FLIF development has stopped since FLIF is superseded by FUIF and then again by JPEG XL, which is based on a combination of Pik and FUIF. For more information, see Jon's JXL info page or visit the JPEG XL Discord server. 

@almarklein Should we close this issue? FLIF appears to be discontinued and superseded. I think that a sensible approach would be to just let it rest in peace. If anybody needs FLIF support in the future (to read legacy files) we can discuss this in a dedicated/new issue.
