### ISSUE TITLE
incorrect image read

### ISSUE THREAD

**Issue by greghumphreysFD** [imageio/imageio#125]
imageio (and, I think, the underlying freeimage library) loads the attached image as all zeroes.

![buggy_imageio](https://cloud.githubusercontent.com/assets/13434433/10920060/17915d52-8266-11e5-8c9d-984c28c0cc24.png)

    import imageio
    im = imageio.imread('buggy_imageio.png')
    print im

produces:

    [[[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]
    
     [[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]
    
     [[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]
    
     ..., 
     [[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]
    
     [[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]
    
     [[0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]
      ..., 
      [0 0 0 0]
      [0 0 0 0]
      [0 0 0 0]]]

**Comment by almarklein** [comment]
I just tried, and the image loads just fine. What you see in this repr is only a tiny portion of the image. Of the beginning and end to be precise, which are transparent due to the curved corners.

Can you try visualizing the image in e.g. Matplotlib, or run `im.max()`? If that turns up black/zero, then we should definitely look into it.

**Comment by greghumphreysFD** [comment]
I'm sorry, you're right -- I jumped the gun on this one.  There's
definitely a bug in the library that's using imageio, and I tracked it down
wrong.  Thanks for your time.

On Wed, Nov 4, 2015 at 9:33 AM, Almar Klein <notifications@github.com>
wrote:

> I just tried, and the image loads just fine. What you see in this repr is
> only a tiny portion of the image. Of the beginning and end to be precise,
> which are transparent due to the curved corners.
>
> Can you try visualizing the image in e.g. Matplotlib, or run im.max()? If
> that turns up black/zero, then we should definitely look into it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/imageio/imageio/issues/125#issuecomment-153656797>.
>



-- 
Greg Humphreys
Director of Engineering
__________________________
www.FanDuel.com <http://www.fanduel.com/>
