### ISSUE TITLE
Try this to build our wheels easier

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#130]
https://github.com/bebraw/pypandoc/issues/84

cc @blink1073

**Comment by blink1073** [comment]
Yep, seems reasonable to me.  I'm swamped through the end of this month.

**Comment by almarklein** [comment]
me too, that's why I made in issue rather than trying it right away ;)

**Comment by almarklein** [comment]
Since FreeImage is no longer a strict dependency, we don't need wheels anymore.
