### ISSUE TITLE
Format for 3D data (because npz is not so good)

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#14]
NPZ is not supported on pypy and has issues with certain combinations of Python 2.x and numpy. We better had a good alternative ...

**Comment by almarklein** [comment]
Reopening. I'm thinking of something pure Python (not relying on simpleITK), or more generic (preferably both).

**Comment by ghisvail** [comment]
Have you looked into the formats that OpenImageIO supports for inspiration?

**Comment by almarklein** [comment]
I did now. But their plugins that support volumetric images are either based on hdf5 or aimed very much on animation.

**Comment by dimatura** [comment]
There's the nrrd format, which is quite simple (basically flat binary, optionally compressed): http://teem.sourceforge.net/nrrd/
I've used the pure python implementation here: https://github.com/mhe/pynrrd/blob/master/nrrd.py

**Comment by almarklein** [comment]
Thanks @dimatura that sounds interesting, especially since its pure Python

**Comment by jni** [comment]
@almarklein why has TIFF not been discussed here? iirc TiffFile has a pure python implementation...?

**Comment by almarklein** [comment]
Would TIFF be suited for storing a 512x512x512 volume? I've never seen people do that with GIF, perhaps because the compression is not that good?

In some cases it would also be necessary to store meta data like spacing between voxels, the origin, or a transformation matrix.

**Comment by jni** [comment]
Haha I use TIFFs for such data all the time. They have some compression support, but I don't know anything about its performance in comparison to other options. TIFF also has vast metadata capabilities, although see my upcoming comment in #263 for caveats.

**Comment by almarklein** [comment]
Fair enough :)  The Tiff format recently became 3D capable by supporting `volread()`. My impression was that this was mostly to read all channels at once, but it can indeed also be used to store actual volumetric data.

**Comment by almarklein** [comment]
Maybe this is why Tiff, although 3D capable, is a bit hard to sell as *the* format for 3D data: https://github.com/imageio/imageio/issues/263#issuecomment-306909272 :)

**Comment by jni** [comment]
🏳️
