### ISSUE TITLE
get_reader() takes a long time to complete for format='ffmpeg'

### ISSUE THREAD

**Issue by ohadassi** [imageio/imageio#152]
The reason for that is imageio waits for the header to be fully read (_load_infos) before get_reader() returns. 
This is done by pollin _stderr_catcher.
The StreamCatcher class, in turn utilizes a  wait loop that reads 20 characters at a time, and then sleeps for 0.001 seconds before reading again. 
(For systems with low system-clock resolution, this may take quite a while. For example: if the header size is ~1000 bytes, the thread will wait ~50 times, which takes ~0.015*50=0.75 seconds for a system-clock  resolution of 67 Hz).
A solution would be to implement the read loop with no sleep at all until the header was fully read. I implemented this solution and it seems to be working fine for me - reducing the overhead to 0.03 seconds.

Below is the suggested fix

(in ffmpeg.py)
```
class StreamCatcher(threading.Thread):
   ...
   ...
    def run(self):
        while True:
            if self._header:   # --------- My Code
                time.sleep(0.001)
            # Read one line. Detect when closed, and exit
            try:
                line = self._file.read(20)
            except ValueError:  # pragma: no cover
                break
            if not line:
                break
            # Process to divide in lines
            line = line.replace(b'\r', b'\n').replace(b'\n\n', b'\n')
            lines = line.split(b'\n')
            lines[0] = self._remainder + lines[0]
            self._remainder = lines.pop(-1)
            # Process each line
            for line in lines:
                self._lines.append(line)
                if line.startswith(b'Stream mapping'):
                    header = b'\n'.join(self._lines)
                    self._header += header.decode('utf-8', 'ignore')
                    self._lines = []
            if self._header:
                self._lines = limit_lines(self._lines)
```

**Comment by almarklein** [comment]
Great find! Would you mind doing a pull request?
