### ISSUE TITLE
AttributeError: attribute '__doc__' of 'type' objects is not writable

### ISSUE THREAD

**Issue by nilswagner** [imageio/imageio#153]
```
imageio/docs/ext/imageio_ext.py", line 68, in prepare_reader_and_witer
    Reader.__doc__ = imageio.core.format.Format.Reader.__doc__
AttributeError: attribute '__doc__' of 'type' objects is not writable
```

**Comment by almarklein** [comment]
Is this on pypy?

**Comment by nilswagner** [comment]
git clone https://github.com/imageio/imageio
cd imageio
python setup.py install --prefix=$HOME/local

**Comment by almarklein** [comment]
I am aware of this type of error (but was not when I wrote that code). Just curious, what OS and what Python interpreter?

**Comment by nilswagner** [comment]
Debian GNU/Linux 7
Python 2.7.11

**Comment by almarklein** [comment]
Wait, this does not make any sense. The error occurs in the Sphynx doc building process. How could this possibly happen when just *installing* imageio?

**Comment by nilswagner** [comment]
Yes, you are right. The previous information is related to the installation procedure.
The error occurs if I use 

make html 
make latex

within the docs subfolder.

**Comment by almarklein** [comment]
Right, that explains it :)  there is some mangling of `__doc__` attributes in the doc building. We should try to get rid of that.

**Comment by almarklein** [comment]
I am going to mark this as wont-fix; imageio's docs need to be build on CPython 3.x. Feel free to reopen if this is a real problem.
