### ISSUE TITLE
tiff read/write problem

### ISSUE THREAD

**Issue by gazzar** [imageio/imageio#155]
Some code of mine which is writing and reading tiffs via imageio occasionally crashes as it fails to read tiff files that have been written by imageio's tiff writer. I suspect this is due to this bug fix in tifffile which has been fixed: "2016.02.22 Write 8 bytes double tag values using offset if necessary (bug fix)." If I use a recent or current version of tifffile I don't see this problem anymore, so for the moment my workaround is to use tifffile directly.
As the version of tifffile used by imageio (2014.08.24) is getting quite out of date (Chistoph Gohlke's latest version is 12 releases newer), would it be possible to simply update the version used by imageio to the current version?

**Comment by almarklein** [comment]
I think we can just replace `plugins/_tiffile.py`, yes.
cc @blink1073

**Comment by blink1073** [comment]
Yep, see #156.

**Comment by gazzar** [comment]
Nice! Thanks Almar and Steven!

**Comment by almarklein** [comment]
@gazzar care to make a PR for this?

**Comment by almarklein** [comment]
Oh, sorry, I missed that @blink1073 already did that :D
