### ISSUE TITLE
Core dumped with AVBIN format

### ISSUE THREAD

**Issue by cachitas** [imageio/imageio#175]
I was trying out the AVBIN format

```
r = imageio.get_reader(path_to_video, format='AVBIN')
```

It started by downloading `avbin`

```
Imageio: 'libavbin-10-linux64.so' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/avbin/libavbin-10-linux64.so (6.9 MB)
Downloading: 7259947/7259947 bytes (100.0%)
  Done
File saved as /home/hugo/.imageio/avbin/libavbin-10-linux64.so.
Floating point exception (core dumped)
```

and exited with that last exception. I am using Ubuntu 14.04.5 LTS.

All following attempts running it (getting the reader as above) result in 

```
Floating point exception (core dumped)
```

even if I close the reader at the end of the script. So now this is related to getting the reader.

Am I missing something? Could it be a problem with the `libavbin` provided?

Edit: this does not happen with the test video `'cockatoo.mp4'`. The video I used is an avi for which ffprobe reports:

```
  Metadata:
    encoder         : Lavf53.32.100
  Duration: 00:02:11.35, start: 0.000000, bitrate: 15973 kb/s
    Stream #0:0: Video: mpeg4 (Simple Profile) (FMP4 / 0x34504D46), yuv420p, 1024x1024 [SAR 1:1 DAR 1:1], 15962 kb/s, 60 fps, 60 tbr, 60 tbn, 60 tbc
```

**Comment by almarklein** [comment]
Closing this as an upstream bug in avbin. Avbin is not actively developed anymore (latest release was 2012).
