### ISSUE TITLE
Support for Variable Frame Rate

### ISSUE THREAD

**Issue by cancan101** [imageio/imageio#176]
For example mp4 (and many other formats) support variable frame rates: https://en.wikipedia.org/wiki/Comparison_of_video_container_formats#Information.

**Comment by almarklein** [comment]
Can you not do this via the `ffmpeg_params`? http://imageio.readthedocs.io/en/latest/format_ffmpeg.html

**Comment by cancan101** [comment]
Does that work for reading a file as well?

**Comment by almarklein** [comment]
If a file was written with a variable frame rate, I don't there's anything else you have to do to read it. Or am I misunderstanding your question?

**Comment by cancan101** [comment]
When reading the frames to know the amount of time between each frame.

**Comment by almarklein** [comment]
Aha! I don't think that ffmpeg provides any way to get the timestamp of individual frames. At least not in the way that we're using it now. So I fear that the answer is no. Maybe with the avbin plugin (though I consider it half-deprecated)?
