### ISSUE TITLE
is imageio supposed to work on windows 32 bit ?

### ISSUE THREAD

**Issue by stonebig** [imageio/imageio#177]
I see the binary compiled in 32 bit on pypi, but not the 32 bit, hence my worried question.

**Comment by stonebig** [comment]
having wheel versions that do include the dll could be interesting for windows users also, for python-3.5+

**Comment by almarklein** [comment]
IIRC on 32bit windows pip will download the zip without binaries, and the Freeimage binary will be automatically downloaded at runtime. 

We're close to getting rid of the Freeimage dependency, replacing it wil Pillow, which means that we do not need the distributions with binaries in them (and we also get rid of automated downloads).

**Comment by stonebig** [comment]
you only download freeimage stuff ?

**Comment by almarklein** [comment]
The only platform-dependent stuff in the packages on Pypi is the FreeImage lib, yes.

The auto-downloads also apply to ffmpeg, but I now think its better to raise an error and provide an easy path to download it, e.g. via `imageio.download_ffmpeg()`.
