### ISSUE TITLE
No more automatic downloads

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#178]
Currently, imageio will automatically download certain files when needed:

* a set of standard images, like `chelsea.png`  and `astronaut.png`.
* the freeimage library
* the avbin library
* the ffmpeg executable

Downloading of standard images should stay, in my opinion, but automatic downloading of executables or libraries is a bit curious. We sort of needed it to make the freeimage plugin Just Work, which provides the majority of formats, but now that we rely on Pillow (#167) this is much less of a problem.

In #167, the automatic downloading of libraries and executable is therefore removed. Instead an exception will be raised that displays a message of a function to call to explicitly download the exe/lib, e.g. `imageio.plugins.ffmpeg.download()`.

I think this is ok for FreeImage, and avbin is sort of redundant with ffmpeg anyway, but it makes the ffmpeg plugin not just work. 

@Zulko will probably want to be aware of this. The exceptions mentioned above are `imageio.core.NeedDownloadError` instances, so you can catch them specifically. 

For people using conda to install Moviepy we can make it easy. Since ffmpeg is available as a conda package (on conda-forge), maybe imageio should be made to be able to make use of it (if it not already does), and Moviepy's conda package can add it as a dependency.

**Comment by ghisvail** [comment]
> Downloading of standard images should stay

Are they really so big to be worth the hassle of keeping them separate from the source tree and requiring an additional download step?

Reason I am asking is that they are required for running the tests, but Linux distributions usually prevent fetching of remote content at build time to avoid potential tempering with the source tree. Making them available under say `data` would make things way easier.

**Comment by almarklein** [comment]
I am reluctant to put binaries into the source repo. So if we can find another solution, I'd much prefer that.
They are going to be packaged in the source dist on Pypi, does that help?

**Comment by ghisvail** [comment]
Le 9 déc. 2016 8:58 PM, "Almar Klein" <notifications@github.com> a écrit :

I am reluctant to put binaries into the source repo.

Depends what you include in "binaries". Images can be considered both
binaries and source files, tbh.

So if we can find another solution, I'd much prefer that.

Static data such as images are often part of the source repository unless
they really outsize the rest of the source files. I understand your
position, I just wanted to point out that it may be overkill in the latter
case.

They are going to be packaged in the source dist on Pypi, does that help?

I can use either GitHub or PyPI releases. So indeed it would help and fix
this issue. Right now I am using a snapshot of master to sort as much of
the packaging as possible ahead of the next release.

**Comment by jni** [comment]
I've used GitHub LFS (large file storage) in another project and am quite happy with it. I just don't know whether it will ever migrate to base git, so that might make you reluctant to use it also.

**Comment by almarklein** [comment]
Closing, this was mainly an issue to notify @Zulko
