### ISSUE TITLE
Residual .pyc files in the release tarball

### ISSUE THREAD

**Issue by ghisvail** [imageio/imageio#187]
The following residual `.pyc` files were not filtered in the `2.0.0` release tarball on PyPI:
```
docs/ext/docscrape.pyc
docs/ext/docscrape_sphinx.pyc
docs/ext/imageio_ext.pyc
docs/ext/numpydoc.pyc
```
You should consider updating `MANIFEST.in` to exclude all `.pyc` from the tarball creation in the future.

**Comment by almarklein** [comment]
Thanks. Fixed by https://github.com/imageio/imageio/commit/73651f33440cd312ab1fb56cd283114c4825cf5c
