### ISSUE TITLE
`imread`, `imwrite` support for 16bit .png images

### ISSUE THREAD

**Issue by soupault** [imageio/imageio#204]
If I understood correctly, `imageio` implements 16bit .png support via `freeimage` plugin.
The question is: is it possible to force read/write in 16bit? Looking at the code I haven't found an easy way to do so.

See https://github.com/scikit-image/scikit-image/issues/2436.

**Comment by almarklein** [comment]
No, we recently dropped freeimage in favor of Pillow. This was actually a requirement for skimage to really adopt imageio, due to license issues. A great part of imageio's Pillow plugin came from skimage, and 16bit png just works:

```py
import imageio

import numpy as np

im1 = np.zeros((3,3), np.uint16)
im1[0,0] = 1000

imageio.imsave('c:/data/im16.png', im1)
im2 = imageio.imread('c:/data/im16.png')

print(im1.dtype, im1[0, 0])  # -> uint16 1000
print(im2.dtype, im2[0, 0])  # -> uint16 1000
```

**Comment by soupault** [comment]
@almarklein I see, thanks!

And what about multichannel images?
```
In [19]: im1 = np.zeros((3,3,3), np.uint16)
    ...: im1[0,0] = 1000
    ...: 
    ...: imageio.imsave('im16.png', im1)
    ...: im2 = imageio.imread('im16.png')
    ...: 
/usr/lib/python3.6/site-packages/imageio/core/util.py:81: UserWarning: Lossy conversion from uint16 to uint8, loosing 8 bits of resolution
  warn('Lossy conversion from uint16 to uint8, '

**Comment by soupault** [comment]
Sorry, one more question (I believe it has already been discussed somewhere, but I'm not aware):
What do you actually mean by "dropped"? I see the wrapper in https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimage.py .

**Comment by almarklein** [comment]
> And what about multichannel images?

Apparently these are mapped to uint8. Does the PNG standard, and Pillow support it? If so, we need to fix that.

> What do you actually mean by "dropped"? 

The Freeimage plugin can still be used, but it has moved "further down the detection chain", making Pillow the default plugin for all the common formats. It will still be selected for formats that only FreeImage supports though, or when the user selects it explicitly. Further, imageio does not come (or auto-download) the Freeimage binaries anymore. You can still install them with one function call though.

**Comment by soupault** [comment]
PNG standard (https://tools.ietf.org/html/rfc2083) seems to allow 16bit/channel RGBa images:
```
         Bit depth restrictions for each color type are imposed to
         simplify implementations and to prohibit combinations that do
         not compress well.  Decoders must support all legal
         combinations of bit depth and color type.  The allowed
         combinations are:

            Color    Allowed    Interpretation
            Type    Bit Depths

            0       1,2,4,8,16  Each pixel is a grayscale sample.

            2       8,16        Each pixel is an R,G,B triple.

            3       1,2,4,8     Each pixel is a palette index;
                                a PLTE chunk must appear.

            4       8,16        Each pixel is a grayscale sample,
                                followed by an alpha sample.

            6       8,16        Each pixel is an R,G,B triple,
                                followed by an alpha sample.
```

`Pillow` docs don't state anything explicitly (see http://pillow.readthedocs.io/en/3.4.x/handbook/image-file-formats.html#png), however, accoding to `scipy.ndimage` (which uses PIL under the hood), everything is expected to be 8-bit.

Here is a comment from `Pillow` devs - https://github.com/python-pillow/Pillow/issues/2107#issuecomment-246007526 (in short, no support for multichannel 16-bit .png images yet).

Thanks for a quick response @almarklein ! Closing for now.

**Comment by OrganicIrradiation** [comment]
@soupault: the short term fix for 48-bit PNGs is to force usage of freeimage by specifying the format attribute (however, this may break if freeimage is completely eliminated). See comment here: https://github.com/imageio/imageio/issues/146#issuecomment-281509008

@almarklein: Unfortunately this "deprioritization" does break previously working pipelines that may have relied upon freeimage's capabilities (e.g., for 48-pit PNGs). It would have been helpful to receive a depreciation warning. I only realized there was an issue when I saw the 16-bit -> 8-bit recasting warnings and delved into the code to find that the default PNG handler changed.

**Comment by stuaxo** [comment]
I'm not sure how your detection chain works, but if there is some kind of weighting, would it be worth making lossy conversions have less weight than lossless ones ?

**Comment by OrganicIrradiation** [comment]
@stuaxo, PNGs are inherently lossless. They become lossy in the imageio pipeline is when a higher bit-depth version (greater than 8/16 bits per channel) is passed to the imwrite command. If you preprocess your data into a uint8/16 type then you should be writing/reading the same data (lossless).

How would you suggest weighting?

**Comment by almarklein** [comment]
For reference:

There are three elements that play a role:
* Each format specifies a "mode" that it can handle (single images, multiple images, volumes, or multiple volume). 
* Each format specifies extensions that it supports.
* Each format can report on a per-file basis whether it can read/write a format, and can inspect the first few bytes to make this decision.
* Formats are ordered to give preference (e.g. Pillow > PIL).

Imageio first selects all formats that conform to the mode and extension and then asks these formats whether they can handle the current request. The first format to return `True` will be used. If none of the selected formats handles the request (e.g. because the extension is not known), then all formats are again given a chance to handle the request.

This procedure is already complex enough as it is; thought its relatively predictable. The ordering (basically the order of imports in `plugins/__init__.py`) seems sufficient to assign priorities. A weighting will make things more flexible, but also less predictable.

**Comment by stuaxo** [comment]
That sounds better than a weighting, I should have a look at that code before making any suggestions.

**Comment by almarklein** [comment]
https://github.com/imageio/imageio/blob/master/imageio/core/format.py#L642-L697

**Comment by stuaxo** [comment]
I grabbed some sample pngs
```$ wget -r -R1 http://fnordware.com/superpng/samples.html```

Is there a really minimal way I can load a png, using just these specfic plugins ?

**Comment by almarklein** [comment]
```py
# read with Pillow
imageio.imread('imageio:chelsea.png', 'PNG-PIL')
# read with FreeImage
imageio.imread('imageio:chelsea.png', 'PNG-FI')
```
