### ISSUE TITLE
Multiple icons in ICO file fails on win32

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#21]
I get:

    lib.FreeImage_AppendPage(self._bitmap, bitmap._bitmap)
     -> OSError: exception: priviledged instruction

Depending on the size of the images, I also get just segfaults.

**Comment by patricksnape** [comment]
Can you give an example ICO to see if I can replicate this?

**Comment by almarklein** [comment]
I am afraid I can't remember what icon file this was for. Maybe it was any multi-page icon file? Anyway, I just tried to replicate, but it works fine. Maybe it fixed in freeimage since I posted this.

I think I'll just close this, and re-open if someone encounters it again.
