### ISSUE TITLE
IndexError when opening any GIF

### ISSUE THREAD

**Issue by Rawing** [imageio/imageio#210]
Opening GIF images raises a weird IndexError. Other formats can be opened with no problem.

Minimal example:

```
f= '/home/rawing/Desktop/temp {e}/merlin.gif'

i= imageio.imread(f)

# OR

reader= imageio.get_reader(f)
for frame in reader:
    pass
```

Full traceback:

> Traceback (most recent call last):
>   File "untitled.py", line 7, in <module>
>     i= imageio.imread(f)
>   File "/usr/lib/python3.5/site-packages/imageio/core/functions.py", line 187, in imread
>     return reader.get_data(0)
>   File "/usr/lib/python3.5/site-packages/imageio/core/format.py", line 332, in get_data
>     im, meta = self._get_data(index, **kwargs)
>   File "/usr/lib/python3.5/site-packages/imageio/plugins/pillow.py", line 116, in _get_data
>     im = pil_get_frame(self._im, self._grayscale)
>   File "/usr/lib/python3.5/site-packages/imageio/plugins/pillow.py", line 424, in pil_get_frame
>     frame = p[frame_paletted]
> IndexError: index 250 is out of bounds for axis 0 with size 192

The index changes depending on the image that I open, but axis is always 0 and size is always 192.

**Comment by almarklein** [comment]
Is it this particular image or are there more images for which you see this problem? Would it be possible to send me the image in question, so that I can reproduce (and hopefully fix) it?

**Comment by almarklein** [comment]
@Rawing I cannot reproduce this, an example image would help me narrow things down. You can send me a personal email with the image if you cannot share it publicly.

**Comment by almarklein** [comment]
I can reproduce this with e.g. https://dl.dropboxusercontent.com/u/1463853/images/dog.gif
