### ISSUE TITLE
save_all=True produces static GIF

### ISSUE THREAD

**Issue by Rawing** [imageio/imageio#211]
I'm not sure how to actually create an animated GIF with PIL, so I've resorted to using Image.save like so:

```
from PIL import Image, ImageSequence

f1= Image.new("RGB", (100, 100), "white")
f2= Image.new("RGB", (100, 100), "black")

p= 'test.gif'
f1.save('test.gif', 'GIF', save_all=True, append_images=[f2])

i= Image.open(p)
print('number of saved frames:', len(list(ImageSequence.Iterator(i))))
```

I've confirmed that this does actually call the _save_all function in from GifImagePlugin, and the append_images parameter is also passed there correctly. Even so, the saved GIF only has 1 frame. The code snippet also counts only 1 frame.

**Comment by Rawing** [comment]
My bad, this is a PIL issue, I opened it in the wrong place.

**Comment by almarklein** [comment]
For the record, in imageio this would be something like: `imageio.mimsave('test.gif', [f1, f2])`, with `f1` and `f2` numpy arrays in this case.
