### ISSUE TITLE
OSError: [Errno 24] Too many open files When calling get_data in reverse order

### ISSUE THREAD

**Issue by ekcheng** [imageio/imageio#212]
When calling `get_data` in reverse order on a video file, ffmpeg processes fail to close properly, causing an `OSError: [Errno 24] Too many open files` error.

Here is some simple code that causes the error in v 2.1.1:

```
import imageio
mov = imageio.get_reader('movie.mp4')
N = mov.get_length()
for i in range(N):
    im = mov.get_data(N-1-i)
```

If the movie is long enough, this will cause the error. But there are no problems reading forwards, from frame 0 to the end.

Appears to be related to #145.

**Comment by ekcheng** [comment]
I see now that this is maybe because `get_data` reinitializes itself when you are decreasing the position per these lines in ffmpeg.py. It looks like maybe `reinitialize` is not closing out existing ffmpeg processes properly:

```
if index == self._pos:
                return self._lastread, {}
            elif index < 0:
                raise IndexError('Frame index must be > 0')
            elif index >= self._meta['nframes']:
                raise IndexError('Reached end of video')
            else:
                if (index < self._pos) or (index > self._pos+100):
                    self._reinitialize(index)
                else:
                    self._skip_frames(index-self._pos-1)
                result = self._read_frame()
                self._pos = index
                return result, {}
```

**Comment by ekcheng** [comment]
Note I have observed this problem both on Ubuntu 16.04 and macOS Sierra (10.12.2).

**Comment by almarklein** [comment]
Thanks for reporting. This is a bit odd, since `_reinitialize()` calls `_close()`, which calls `_terminate()`. The latter ought to be *the* way to safely close the ffmpeg process. It's been though a number of iterations though ...

Can you make sure that you're using the latest version of imageio (2.1.1)? Perhaps you can try fiddling with `_terminate()` to make it work, like uncommenting that `kill` call. Otherwise, @kuchi or me will look into it when we have some time to spare.

**Comment by almarklein** [comment]
Closed by #213

**Comment by ekcheng** [comment]
Thanks! When is the next release planned?

**Comment by almarklein** [comment]
I think we should do one pretty soon, since we fixed a few important bugs. There's one or two open issues, which I hope we can include, so perhaps next week.
