### ISSUE TITLE
imageio creates corrupted GIF from PNG files

### ISSUE THREAD

**Issue by SteveDoyle2** [imageio/imageio#217]
Hi there,

I recently switched from using the images2gif.py script to imageio and am running into problems.

I'm trying to make an animated gif and have only succeeded in making corrupted gifs.  The first image of the gif is correct, but all subsequent images look like a poorly read VHS tape.  I've updated all my packages, which seems to have no effect.  I've also made sure that all my images have the same dimensions.  Any suggestions?

    png_filenames = [
        'DisplacementXYZ_00.png', 
        'DisplacementXYZ_57.png',
    ]

    gif_filename = 'DisplacementXYZ.gif'

    import imageio
    images = []
    for png_filename in png_filenames:
        image = imageio.imread(png_filename)
        images.append(image)
    imageio.mimsave(gif_filename, images)

I'm using:

     Python 2.7.12
     imageio 2.1.1
     libpng 1.6.27
     pillow 4.0.0
     anaconda 2.5.0
     conda 4.3.8-py27_0
     Windows 10

Image 0
---------
![displacementxyz_00](https://cloud.githubusercontent.com/assets/1059417/22399434/6155924c-e551-11e6-884f-5eab02574a8a.png)

Image 57
---------
![displacementxyz_57](https://cloud.githubusercontent.com/assets/1059417/22399435/6158473a-e551-11e6-95da-9de613d6d360.png)

The final gif.  Github doesn't seem to be able to display this
----------------------------------------------------------------------
![displacementxyz](https://cloud.githubusercontent.com/assets/1059417/22399436/61585f0e-e551-11e6-80d6-8f0962e32370.gif)

The gif alternates between Image 0 and the image below
--------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/1059417/22399553/7821f856-e553-11e6-9cd8-aff934ef1016.png)

So a small bar as seem above and a large white region

**Comment by almarklein** [comment]
This has been fixed a few days ago in #215. To make use of the fixed version, you can make use of the latest version from master, or wait (about a week?) for the next release.

**Comment by SteveDoyle2** [comment]
Thanks so much!
