### ISSUE TITLE
Provide newer version of ffmpeg

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#219]
The version of ffmpeg that we distribute has grown rather old. Let's update it to the latest release version, and also provides a means for users to update it.

cc @Zulko

**Comment by Zulko** [comment]
That's great ! If you do so, you may consider using ffmpeg all the way for GIF creation, as the GIF capabilities of ffmpeg 2.6+ are above everything else I've tried (quality, speed, size). See here for more:

http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html

**Comment by almarklein** [comment]
Thanks for the tip @Zulko, I made a new issue for it.

**Comment by Nytrox** [comment]
If possible, can you also look into faster SEEKs? Specifically for seeks greater than 100 frames such that it no longer calls a reinitialization?

**Comment by almarklein** [comment]
> If possible, can you also look into faster SEEKs? Specifically for seeks greater than 100 frames such that it no longer calls a reinitialization?

cc @kuchi :)

**Comment by kuchi** [comment]
@nytrox do you know of a faster way to do seeks?  The last commits I made were the fastest way that the ffmpeg documentation suggested. I would be interested in more efficient ways so let me know if there is a better way. It seems like OS X QuickTime has much more efficient seeking than ffmpeg. But with ffmpeg I'm not sure of a better way.

**Comment by Nytrox** [comment]
@kuchi Haha I was hoping one of you guys would know

**Comment by almarklein** [comment]
> do you know of a faster way to do seeks? 

I wonder whether pyav can do it faster (#115).
