### ISSUE TITLE
Animated gif writer via ffmpeg

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#220]
As mentioned in #219, ffmpeg can also export animated gif (ffmpeg 2.6+). Would be a nice addition. http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html

Advantages are speed and maybe quality, we'd have to do some testing to see how the paletting related to PIL's paletting. Disadvantage is that it needs the ffmpeg exe, which is not available by default (though easy enough to install using one function call).

**Comment by almarklein** [comment]
Also see #115

**Comment by FirefoxMetzger** [comment]
I submitted a PR to pyAV a few days back that allows sending EOF to a filter, so we will be able to use `palettegen` with the next pyAV release. From this point on it should be possible to generate GIF via ffmpeg, too.

**Comment by FirefoxMetzger** [comment]
pyAV released v9 recently which includes my changes to send EOF to filters (among other goodies). I've updated our pyAV plugin, and now we can indeed create GIF using ffmpeg:

![test](https://user-images.githubusercontent.com/4402489/157633664-ccf0351f-6745-4901-bba7-f4ead280060e.gif)

(at the moment it's grayscale only until I work out how to handle frames with palette in pyav)

**Comment by FirefoxMetzger** [comment]
And now we can do colored GIFs, too:

![test](https://user-images.githubusercontent.com/4402489/161819196-5354b320-949d-47df-b58f-528c7298b80b.gif)
