### ISSUE TITLE
imageio debian package

### ISSUE THREAD

**Issue by kerimlcr** [imageio/imageio#221]
Hi,
I'll make imageio's debian package but I need e-mail. Is there any contact mail for imageio organization.

**Comment by almarklein** [comment]
Hi,

Thanks for your offer. Please coordinate with @ghisvail about this. If I understand correctly, he's got it covered already, though perhaps he can use some help.

**Comment by ghisvail** [comment]
@kerimlcr There is already an [imageio Debian package](https://packages.debian.org/source/sid/python-imageio)

Feel free to join the Debian Science Team if you want to help with its maintenance. We always welcome extra pair of eyes and hands.

**Comment by kerimlcr** [comment]
My pleasure
I want to help
How can I join Debian Science team ?
Regards

2017-02-08 16:36 GMT+03:00 Almar Klein <notifications@github.com>:

**Comment by ghisvail** [comment]
@kerimlcr => https://wiki.debian.org/DebianScience
