### ISSUE TITLE
write_gif() tries to use an invalid quantization algorithm 'wu'

### ISSUE THREAD

**Issue by Joedang** [imageio/imageio#223]
When calling `moviepy.video.VideoClip.write_gif()`, the function `converToPIL()` in [`imageio/plugins/pillowmulti.py`](../../imageio/blob/master/imageio/plugins/pillowmulti.py) is given a value of `'wu'` for the quantizer. This results in the following error:

```python
/usr/local/lib/python3.4/dist-packages/imageio/plugins/pillowmulti.py in converToPIL(self, im, quantizer, palette_size)
    348             im_pil = im_pil.quantize(colors=palette_size, method=quantizer)
    349         else:
--> 350             raise ValueError('Invalid value for quantizer: %r' % quantizer)
    351         return im_pil

ValueError: Invalid value for quantizer: 'wu'

```

This happens even when, for example, `clip.write_gif('myclip.gif', opt=0)` is given. (giving `opt='nq'` actaully sticks, but fails earlier in the same if-statement.) 

I couldn't find where `quantizer` was being set to `'wu'`, but was able to work around this by placing 
```python
if quantizer == 'wu':
    quantizer = 0
```
immediately before the offending if-statement. 

I'm not a software developer, but it seems like this method should default to using `0` for the quantizer until `'wu'` is implemented.

**Comment by almarklein** [comment]
cc @Zulko related to these functions in moviepy: 
https://github.com/Zulko/moviepy/blob/d4c9c37bc88261d8ed8b5d9b7c317d13b2cdf62e/moviepy/video/VideoClip.py#L409
https://github.com/Zulko/moviepy/blob/d4c9c37bc88261d8ed8b5d9b7c317d13b2cdf62e/moviepy/video/io/gif_writers.py#L259

The cause of this is that imageio switched its default gif reader/writer from FreeImage to Pillow, which has different possible quantizers.

Perhaps it makes sense to:
* let moviepy pass `None` for the quantizer by default, and let users give a value for `opt` that is passed unchanged. Perhaps update the docs too. 
* make sure that imageio accepts `None` for the quantizer for all gif plugins.

Notes:
* there is an idea to also add a Gif writer plugin to imageio based on ffmpeg, just so you know.
* for the (current default) Pillow plugin, by far the best quantizer seems to be '0'. Apparently, I did not even bother documenting the quantizer argument.

**Comment by almarklein** [comment]
This is an issue between imageio and moviepy and it appears to have been fixed.
