### ISSUE TITLE
Improve docs related to reading from bytes

### ISSUE THREAD

**Issue by mef51** [imageio/imageio#229]
I'm trying to save bytes as frames of an animation of a plot but 

```python
import matplotlib.pyplot as plt
import imageio

plt.plot(1, 1)
fig = plt.gcf()
fig.canvas.draw()
data = fig.canvas.tostring_rgb() # These are bytes
imageio.imread(data)

File "<string>", line unknown
SyntaxError: cannot handle 76-bit layers
```

I also tried converting it to a numpy array of uint8s but `imread` just spits the data back into my terminal and doesn't do anything. Is this the way to read in raw bytes? Is something missing from the docs?

Thanks

**Comment by almarklein** [comment]
What are you trying to achieve by letting imageio "read" the bytes? The feature of imageio to read from bytes is to read  e.g. a png or jpeg file that is already read in memory, but not yet decoded. If you already have bytes in rgb values, the hard work is already done :)

Leaving this open, because I think the docs related to this can be improved.

**Comment by almarklein** [comment]
Maybe also add tests, it seems you tried a few things, but imageio never warned you that you were doing something wrong.

**Comment by mef51** [comment]
Ah yes, I was reading bytes from matplotlib because I wanted to save them into an animated gif or an .mp4 using imageio.

the way im currently doing it is making an image, saving it to disk with imageio, and then immediately reading it back into memory so that I can save it as a frame of my animation :P 
I wanted to skip the 'write to disk and read it back' part

**Comment by almarklein** [comment]
You could do:
```py
im1 = ... # numpy array
bb = imageio.imsave(imageio.RETURN_BYTES, im1, format='png')
im2 = imageio.imread(bb, format='png')
```

Though I don't understand why you're doing it this way. Imageio wants a numpy array when saving, and produces a numpy array when reading. What do you win by writing and then reading back?

**Comment by mef51** [comment]
Sorry, I wasn't clear. 
What I *want* to do is make an animation of an orbiting planet this way:

```python
with imageio.get_writer('animation.mp4', mode='I', fps=24) as writer:
	for t in time:
		x, y = changeXandYSomehow(t)
		plt.plot(x, y)
		fig = plt.gcf()
		fig.canvas.draw()
		data = fig.canvas.tostring_rgb() # These are bytes
		image = imageio.imread(data)
		writer.append_data(image)
		plt.close()
```
But that gives me the error I mentioned in my first post, even if I convert to a numpy array, and what I'm *stuck* doing is having to write to disk and read it back because that's the only way I can make it work:

```python
for t in time:
	x, y = changeXandYSomehow(t)
	plt.plot(x, y)
	plt.savefig('frames/frame' + t + '.png')

with imageio.get_writer('animation.mp4', mode='I', fps=24) as writer:
	for filename in os.listdir('frames'):
		image = imageio.imread(os.path.join('frames', filename))
		writer.append_data(image)
```

This is less than ideal because writing to disk and reading it back is expensive and I have something like 10000 frames. This takes forever to run and I'm trying to make it quicker by feeding rgb bytes straight into a video file being written by `imageio`

**Comment by mef51** [comment]
Ah okay, well I've figured it out! Just had to reshape the data a little bit before giving it to `imageio`. Here's a little snippet that saves an animation:

```python
import matplotlib.pyplot as plt
import numpy as np
import imageio
from numpy import sin, pi

time = np.linspace(0, 10, 100)
with imageio.get_writer('test.gif', mode='I', fps=24) as writer:
	print('Working...')
	for t in time:

		x = np.linspace(-2*pi,2*pi, 100)
		plt.plot(x, (x/(2*pi))*sin(t+x))
		plt.grid()
		plt.xlim(-2*pi, 2*pi), plt.ylim(-1.2, 1.2)
		fig = plt.gcf()
		fig.canvas.draw()
		data = fig.canvas.tostring_rgb()
		rows, cols = fig.canvas.get_width_height()

		imarray = np.fromstring(data, dtype=np.uint8).reshape(cols, rows, 3)
		writer.append_data(imarray)
		plt.close()
print('Done.')
```
![test](https://cloud.githubusercontent.com/assets/1703141/23527040/4fce09ac-ff62-11e6-989d-63281e63a51f.gif)

**Comment by almarklein** [comment]
Ah I see. I was confused by the `imageio.imread(data)`. Glad you got it working. Nice animation!
