### ISSUE TITLE
FreeImage-3.15.1-win64.dll can't be downloaded

### ISSUE THREAD

**Issue by warkid** [imageio/imageio#239]
Trying to dowload freeimage plugin with imageio.plugins.freeimage.download() fails with timeout.
Using github we-interface gives "Error 503 first byte timeout" when clicking Download button on this page -
https://github.com/imageio/imageio-binaries/blob/master/freeimage/FreeImage-3.15.1-win64.dll
Note: FreeImage-3.15.1-**win32**.dll is ok - downloads fine.

**Comment by almarklein** [comment]
I cannot reproduce this. Perhaps this was a temporary glitch? Still strange that the win32 version worked fine though. Can you please verify whether this is still an issue?

**Comment by warkid** [comment]
works now
