### ISSUE TITLE
No file found Error

### ISSUE THREAD

**Issue by insatmc** [imageio/imageio#241]
Hello

        img = imageio.imread(fl.decode('base64'))
        images.append(img)

fl is a base64 string

This code, in 95% of times works, but in 5% throws an error  "No such file: '/var/task/u�Z'"

I am wroking with python 2.7 inside of an AWS Lambda function

**Comment by almarklein** [comment]
Base64 is used to encode bytes. So I think you  might need: `imageio.imread(fl.decode('base64').decode('utf-8'))`.

**Comment by almarklein** [comment]
Closing this, as I don't think this is a problem with imageio, but a base64-related problem. Feel free to reply if my above comment did not fix it though.
