### ISSUE TITLE
Saving empty animated image

### ISSUE THREAD

**Issue by PeterQLee** [imageio/imageio#242]
Saving an animated image with mimwrite or mimsave with an empty list will write a file with a single byte.

For example:

```
import imageio
imageio.mimwrite('a.gif',[])
```

If you check the contents of a.gif after running, it contains a single 0x3b byte.
This doesn't seem like the intended behaviour. Maybe it should throw an error, or at least give a warning to the user?

**Comment by almarklein** [comment]
There could be formats where its "legal" to have a sequence of 0 images. Though I don't a single-byte gif can be a valid GIF file :)
