### ISSUE TITLE
avbin plugin yields black images the first 5 frames

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#25]
On my machine its 5 frames. on Travis it seems more than that ...

Any idea @rreilink ?

**Comment by dave-epstein** [comment]
I still have this problem with avbin, is there any known fix? Reading the same videos using the ffmpeg and the avbin plugins, the ffmpeg plugin works fine.

**Comment by almarklein** [comment]
@dave-epstein since avbin is not maintained anymore (last release is from 2012), so I would not wait for a fix :)  Actually, imageio should probably deprecate its plugin for it ...

**Comment by almarklein** [comment]
Yes, ffmpeg is not perfect, but is the best-supported way (at least in imageio) to read video.
