### ISSUE TITLE
Iphone video read output changes with FFMPEG 3.3

### ISSUE THREAD

**Issue by chenliu0831** [imageio/imageio#252]
Recently we upgrade from FFMPEG 3.2 to 3.3. It seems `imageio` is giving out frames (mov and mp4s) from row-major to column-major. Not sure if this is an `imageio` or `ffmpeg` problem.. Anyone else seeing this?

**Comment by chenliu0831** [comment]
update: `ffmpeg 3.3` dumps to pngs just fine. Seems to be imageio's problem

**Comment by almarklein** [comment]
Does it do this with this too:
```
import imageio
with imageio.get_reader('imageio:cockatoo.mp4') as reader:
    for im in reader:
        print(im.shape)
```

I get the correct shape `(720, 1280, 3)` on Linux with the new binaries that I just uploaded (3.3.1).

**Comment by almarklein** [comment]
Reading this again, I wonder whether you meant that the images were rotated, or whether the arrays where in F mode instead of C mode.

**Comment by chenliu0831** [comment]
@almarklein sorry I was on vacation. yeah I mean the shape appears to be correct, but the array seems to be filled in F mode.

**Comment by almarklein** [comment]
No need to apologize for a vacation :)

Interesting case. I am not sure whether imageio should take a stance on whether image data should be produced in C mode or F mode. Most libs that need either mode will convert if necessary. So if your code depends on the data being in C-mode, you should probably use something like:
```py
im = np.array(im, copy=False, order='C')
```
which will convert if needed, or let the image pass through otherwise.

@blink1073 what do you think? Also cc @kuchi

**Comment by blink1073** [comment]
Sounds fair to me.

**Comment by chenliu0831** [comment]
@almarklein Cool that's a great workaround. If you guys think the root cause might be in ffmpeg feel free to close this one. Thanks.

**Comment by chenliu0831** [comment]
Ah looks like it's not the byte order problem. For context, I got `WARNING:root:Warning: the frame size for reading (1080, 1920) is different from the source frame size (1920, 1080).` from an iphone mp4 (or `.mov` ). And with `ffmpeg 3.2.4` I got correct image with dimension `1080 * 1920` but with `ffmpeg 3.3.1` I got `1920 × 1080`.

**Comment by almarklein** [comment]
Ok, so this issue should be reopened?

**Comment by chenliu0831** [comment]
@almarklein I think so. Thanks

**Comment by almarklein** [comment]
Can I get a (sample of) a video to reproduce this issue?

**Comment by chenliu0831** [comment]
@almarklein could you try this [link](https://drive.google.com/file/d/0B94o8aKhIY1FelZkbm5lTC0zX3M/view?usp=sharing)?

**Comment by almarklein** [comment]
I get this:
```py
import imageio
ims = imageio.mimread('c:/data/imageio_issue252.mp4')
print(ims[0].shape)
print(ims[0].flags)
```
```
(1920, 1080, 3)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by chenliu0831** [comment]
@almarklein right and in mac finder it shows `1080*1920` and if I use raw ffempg (either 3.3 or 3.2) to dump individual frames as jpgs it looks correct.

**Comment by chenliu0831** [comment]
@almarklein any update on this? it seems you were testing it under windows? On mac/linux I'm still getting the incorrect shape with 3.3+

**Comment by almarklein** [comment]
Are you sure that the shape is incorrect? In imageio, its typical for images stored in numpy arrays to have a shape that is `(height, width)`. I suspect that Finder reports `width*height`. Maybe try this:

```
import imageio
ims = imageio.mimread('c:/data/imageio_issue252.mp4')
print(ims[0].shape)
print(ims[0].flags)

import matplotlib.pyplot as plt
plt.imshow(ims[0])
plt.show()

```

**Comment by chenliu0831** [comment]
Yeah.... see below.
![figure_1](https://user-images.githubusercontent.com/1504463/27483495-a7f3aac6-57f3-11e7-886b-6f30b4dbda92.png)

**Comment by chenliu0831** [comment]
@almarklein Just check in if you got any chance to look into this issue?

**Comment by almarklein** [comment]
I'm not exactly sure what we can do. I guess we can start with posting a possible workaround here (i.e. how to correct the image). But I don't think that we can reliably detect the case (consider this a challenge to proof me wrong).

Have you found a way to swizzle your image to make it correct again? If not, can you send me the image in npz format so I can have a go?

**Comment by chenliu0831** [comment]
@almarklein I'm closing this issue and for context I would recommend people either swizzle manually or use the default installation [built-in](https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py#L52).
