### ISSUE TITLE
Numpydoc vendoring

### ISSUE THREAD

**Issue by ghisvail** [imageio/imageio#256]
Why is this required? Can't you just make `numpydoc` a requirement for the docs and let pip handle the rest?

**Comment by almarklein** [comment]
Dunno, it could be that it was not available as a package back in the days when I wrote those lines? I think those parts are copied from another project even, so they go way back. I'll have a try at removing the vendoring.

**Comment by ghisvail** [comment]
I can have a look, I believe I managed to unvendor numpydoc and use the system package on Debian.

**Comment by almarklein** [comment]
np, it seems to work without, so it should be a matter of making CI and RTD install numpydoc.
