### ISSUE TITLE
Allow userDir to be configurable to account for more restrictive environments like AWS Lambda

### ISSUE THREAD

**Issue by kappataumu** [imageio/imageio#265]
Its seems that AWS Lambda only allows writes to `/tmp`. When imageio tries to download ffmpeg, it first tries `~`, then `/var/tmp` and finally fails because neither are writeable ([relevant code](https://github.com/imageio/imageio/blob/master/imageio/core/util.py#L441) -- also see https://github.com/imageio/imageio/issues/54).

Instead of trying yet another directory (`/tmp`), it would be handy if we were able to configure this using an environment variable, say `IMAGEIO_USERDIR`.

**Comment by almarklein** [comment]
Sounds like a good idea. Would you care for a PR? You already found the place where a change would be needed. Additionally, it should be briefly explained in the docs [here](https://github.com/imageio/imageio/blob/master/docs/envvariables.rst).

**Comment by kappataumu** [comment]
Sure thing, I'll send a PR your way tomorrow.
