### ISSUE TITLE
Add `shell=True` to `subprocess.Popen` calls (Pyinstaller)

### ISSUE THREAD

**Issue by paulmueller** [imageio/imageio#266]
I can confirm that imageio+ffmpeg works with Pyinstaller on Windows and Anaconda Python 2.7 (#32).
However, when using the [ffmpeg](https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py) plugin in a frozen application on Windows, and when seeking through an avi video (`imageio.get_reader`) using `get_data`, an empty command Window pops up with the title ("path/to/ffmpeg-win32-v3.2.4.exe"). These command windows are not shown when the keyword argument `shell=True` is set in `sp.Popen`: https://github.com/paulmueller/imageio/commit/b5aeb617fb6b1a74ff30c40ae998bac31b526f39

If this does not break compatibility, I would recommend adding that extra keyword argument everywhere. I can create a pull request if you are too busy yourself.

**Comment by almarklein** [comment]
A pull request would be great. But perhaps only do it on Windows, since it only seems to be a problem there (`shell=ISWIN`).
