### ISSUE TITLE
freeimage JXR format seems not to work

### ISSUE THREAD

**Issue by decarlof** [imageio/imageio#269]
im = imageio.imread("lena.tif")
imageio.imwrite("test.jxr", im)

... imageio/core/functions.py", line 169, in get_writer  'in mode %r' % mode)
ValueError: Could not find a format to write the specified file in mode 'i'

I am on RedHat 7, anaconda python 2.7 and
rpm -q freeimage
freeimage-3.10.0-19.el7.x86_64

I tried both conda install and python setup.py install of image io
____
Update: I run:
imageio.plugins.freeimage.download()

and now executing:
im = imageio.imread("lena.tif")
imageio.imwrite("test.jxr", im)

I get:
RuntimeError: Could not save file "test.jxr": Invalid instruction - please contact the FreeImage team

Also the reader on these [jxr images](http://www.shikino.co.jp/eng/products/product-ip_core_products.html) fails:
im = imageio.imread("SMALLTOMATO.wdp")
... site-packages/imageio-2.2.0.dev0-py2.7.egg/imageio/plugins/_freeimage.py", line 828, in load_from_filename
    self._fi._get_error_message()))
ValueError: Could not load bitmap "SMALLTOMATO.wdp": Unsupported format

renaming SMALLTOMATO.wdp to SMALLTOMATO.jxr does not help:
ValueError: Could not load bitmap "SMALLTOMATO.jxr": Unsupported format

**Comment by almarklein** [comment]
First off: you indeed need to ensure you have the freeimage library before you can use it.

You can also tell imageio to use a specific format. That can result in more precise error messages:

```py
im= imageio.imread('c:/stack/data/FLOWER.wdp', format='JXR')
imageio.imread('test.jxr', im, format='JXR')
```

----

That said, I am also not able to read the wdp images from the site that you linked, and can also not safe an image in this format. I dove a bit into saving, and FreeImage reports that it cannot safe the file for any possible format. You could try using the latest FreeImage library. Maybe the support has improved.

**Comment by almarklein** [comment]
Upstream issue.
