### ISSUE TITLE
replacing (or providing alternative) to visvis examples

### ISSUE THREAD

**Issue by stonebig** [imageio/imageio#274]
Hello,

As visvis is no more recommanded, how could we rewrite the example provided in http://imageio.readthedocs.io/en/latest/examples.html ?

initial workaround fail:
![visvis](https://user-images.githubusercontent.com/4312421/28996923-c323e29c-7a09-11e7-86ec-8caec2f98280.PNG)

**Comment by stonebig** [comment]
same for the video example

**Comment by almarklein** [comment]
This should do the trick with Matplotlib.
```py
from matplotlib import pyplot as plt
plt.imshow(...)
```

But using visvis is usually fine. It's not really developed further, but still maintained. Doing the webcam example with MPL would probably be slow, and the volume rendering would need a 3D visualization library, of course.
