### ISSUE TITLE
could opencv package ("import opencv2") be used as an alternative to ffmpeg ?

### ISSUE THREAD

**Issue by stonebig** [imageio/imageio#275]

**Comment by almarklein** [comment]
I don't know. Last time I checked py-opencv (or whatever the bindings are called) were a pain to install. But that was years ago.

Is it easy to install by now and does it provide the feature that we'd need? My feeling is that PyAV would be an easier route (#115).

**Comment by paulmueller** [comment]
I would not recommend going through the trouble of implementing a wrapper for OpenCV:
- Installation is still painful. There is a [package on PyPI](https://pypi.python.org/pypi/opencv-python), but ``MacOS and Linux packages do not support video related functionality (not compiled with FFmpeg).``
- This makes testing (e.g. with travis) almost impossible. I stopped trying. 
- OpenCV causes strange errors (e.g. on Windows: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/issues/129)

I would suggest waiting until all wheels on PyPI support video functionality (https://github.com/skvark/opencv-python/issues/14).

**Comment by almarklein** [comment]
Ok, answering this question with no then, at least for the time being :)
