### ISSUE TITLE
from FreeImage to a common wheel with moviepy

### ISSUE THREAD

**Issue by stonebig** [imageio/imageio#276]
Hi,

I'm trying to get moviepy working at minimal Kilobyte cost. I discover that FreeImage somewhat Includes ImageMagick, and that FreeImage is no more kept up-to-date.

Would it be possible to shift to another wrapper of ImageMagick:
-  preferably common with moviepy ?
-  wrapped in a cgohlke wheel ?

(pgMagick comes to mind at first, but there is also PythonMagick)

I'm not expert in the domain, maybe there are better alternatives, just hope to have only one wheel that can be shared by both projects.

**Comment by stonebig** [comment]
well, reading https://github.com/scikit-image/scikit-image/pull/2744 , maybe I'm going the wrong direction from your 2015 initial plan. closing.

**Comment by almarklein** [comment]
We've settled in Pillow to do most of the common formats. The FreeImage plugin is still usable, but you'd need to bring your own libraries :)
