### ISSUE TITLE
Have animated GIF play once and only once when loop=0

### ISSUE THREAD

**Issue by tjdawson** [imageio/imageio#277]
Leaving the loop parameter at the default, 0, results in infinite looping. Setting the parameter to 1 will result in the image playing *twice* -- an initial time, and then once more. 'inf' as a string is already an alias for infinite looping, why not have 0 result in the expected behavior?

**Comment by almarklein** [comment]
> Setting the parameter to 1 will result in the image playing twice

Have you tried with the latest release of imagio? We recently made some changes to this. It appeared that some players interpret loop not as "number of iterations", but as "number of times to repeat". See also #237 and #253.

**Comment by almarklein** [comment]
Closing. Please reopen if the latest version is still wrong in any way.
