### ISSUE TITLE
`if imageio.get_reader(...): pass` fails for FfmpegFormat.Reader objects

### ISSUE THREAD

**Issue by dennisvang** [imageio/imageio#280]
The following statement:

`if imageio.get_reader('<video0>'): pass`

raises 'OverflowError: cannot convert float infinity to integer' (at least in Python 2.7)

It seems that `FfmpegFormat.Reader` has no `__nonzero__()` method (nor `__bool__()` for Python 3?), so the `__len__()` method is evaluated, which, in this case, returns `float('inf')`.

A quick hack for anyone running into this issue could be to use `if ... is not None`.
(see [stackoverflow](https://stackoverflow.com/a/7816439/4720018))

**Comment by almarklein** [comment]
mmm, yes resolving to a bool uses `Reader.__len__`, and also `len(reader)` fails. Best is indeed to compare with `None` or to check `reader.get_length() > 0`, dependening on the situation.

I'm leaving this open for now. Perhaps `__len__` should return the highest possible int or something.

**Comment by almarklein** [comment]
I'm closing this. It's a bit of an ugly bit, but it's a given fact that some readers don't know how much images there are. The value `inf` makes the most sense IMO --- `-1` will have its own complications, and so does the largest possible int. I'm sure this won't be the last time someone bumps into this the hard way though ...

**Comment by FlorianFranzen** [comment]
@almarklein Why can you not just bring back ```__nonzero__```. That is all @dennisvang is asking for. Else this is a very confusing change of API and then should at least be documented in the change log.

This used to work just fine in 2.4.9.

**Comment by almarklein** [comment]
I guess I overlooked the option of bringing back `__nonzero__` or `__bool__`. Sounds reasonable. Reopening.
