### ISSUE TITLE
Setting pointer to a frame

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [imageio/imageio#285]
I am taking frames from a `get_reader()` with the `get_next_data()`, and I am wondering is there a way to change the position of the pointer to say, 10th frame such that the first call of the `get_next_data()` returns the 11th frame?

This does not seem possible, even thought multiple iterations though the `get_reader()` object is not an issue with the `__iter__()` and `__next__()` approach - calling something like `for frame in reader: ...` multiple times.

**Comment by almarklein** [comment]
One can use `get_data(index)`, and then the next call to `get_next_data()` will get the data at `index+1`.

**Comment by MarcinKonowalczyk** [comment]
Cheers @almarklein. It's still a workaround though. It'd be nice it it were a feature. Also; like that I don't think I can set the data pointer to `index = 0` - I can read the first frame alright, but I cannot reset the `get_reader()` to the state I'd get it in after it's initialization.

**Comment by almarklein** [comment]
Good point. You want to submit a PR? It should be easy to add; the code is in `imageio/core/_format.py`.

**Comment by MarcinKonowalczyk** [comment]
@almarklein I'll give it a go...
