### ISSUE TITLE
Support fetching remote file that does not contain file extension in url

### ISSUE THREAD

**Issue by toshitanian** [imageio/imageio#293]
As image io detects file format by file extension, we cannot use remote file without extension in url.

```python
import imageio

reader = imageio.get_reader('http://example.com/jpeg-file')
```

Enabling specifying format explicitly might be good.

**Comment by almarklein** [comment]
This should work:
```py
imageio.get_reader('http://example.com/jpeg-file', 'jpg')
```

Second argument can be a format object, a format name or an extension.
