### ISSUE TITLE
mimwrite breaks if input is a generator

### ISSUE THREAD

**Issue by gmgunter** [imageio/imageio#295]
mimwrite breaks if `ims` is a generator because of this section:
```python
    #Ensure non empty sequence
    if len(ims) == 0:
        raise ValueError('Numpy sequence must not be empty.')
```
since generators don't have a `__len__` attribute. 

If it's necessary to check for empty sequence, [this workaround](https://stackoverflow.com/a/664239/6038094) could be used for generator types.

**Comment by almarklein** [comment]
I think it makes sense to check at the end of the iteration whether at least one image has been written.
Since `Writer` does not necessarily have a `__len__` either, we should track the number of written images. Care for a PR? :)

**Comment by gauvinalexandre** [comment]
I just hit the same problem. Is anyone going to do something about it? I could work on it and make a PR, but perhaps it concerns other parts of the code, and if someone else is more aware of the code specifications...

**Comment by almarklein** [comment]
I would eventually fix this (when I find the time t,o do some imageio work), but this should be a good issue for someone to start contributing. It should be contained within `functions.py`, and does not require a whole lot of changes. Don't hesitate to ask for help when you need it.

**Comment by almarklein** [comment]
done
