### ISSUE TITLE
Fair rounding when converting floats to ints

### ISSUE THREAD

**Issue by untom** [imageio/imageio#296]
When converting from floats to ints during saving an image, imageio always rounds down to the next-smallest integer value, instead of rounding to the closest one. e.g. a value of 245.99 will get rounded down to 245. Arguably, rounding up would lead to a better uint8 representation, and I'd suggest changing imageio's rounding behavior in [this function](https://github.com/imageio/imageio/blob/master/imageio/core/util.py#L57) accordingly.

Note that this is likely related to #289 , as `scipy.misc.imsave` (which is now deprecated and suggests using `imageio.imwrite`) rounds to the closest pixel value, so that `imsave` and `imwrite` will often produce different images: many pixels in the output differ by 1 intensity value. While not visually noticeable, this produced weird artefacts in my image analysis pipeline (which is how I found out about this in the first place).

**Comment by almarklein** [comment]
I agree. I'm actually surprised that this has not come up earlier ...
