### ISSUE TITLE
update tifffile

### ISSUE THREAD

**Issue by ischg** [imageio/imageio#299]
[Version 2017.09.29](https://www.lfd.uci.edu/%7Egohlke/code/tifffile.py.html) brought significant updates for `tifffile.py`, e.g. consolidated access to metadata. At the moment, imageio holds at version 2017.01.12; it would be great if this could be updated.

**Comment by almarklein** [comment]
@blink1073 do you have time to look into this sometime?

**Comment by almarklein** [comment]
@blink1073  do you have time to look into this?

**Comment by blink1073** [comment]
I'm limiting myself Jupyter-related projects, lest I burn out again.

**Comment by almarklein** [comment]
@blink1073 No problem, good to set boundaries. Sorry to hear you burned out ...

**Comment by almarklein** [comment]
@ischg @scivision It would be awesome if one (or the two) of you could keep an eye out for Tifffile, since I don't use it myself. A ping when an update is needed is already great. PR's even better ;)

**Comment by scivision** [comment]
Probably the adoption rate of imageio will jump, as SciPy is emitting DeprecationWarning. It should be an infrequent occurance in any case.
