### ISSUE TITLE
Plugin: scientific TIFF files

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#30]
In some fields a variant of the TIFF format is heavily used, e.g. for multiplanar microscopic images. Like OME-TIFF (https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/).
The freeimage TIFF reader only deals with basic TIFF.

This is not really my field, so could use some input on what is needed.

One implementation that we could potentially use is: http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html
I believe there was another, but I cannot remember.

**Comment by jgostick** [comment]
I just posted on the Google groups mailing list but should have checked here first I guess.  I actually use the tifffile package, not Pilllow.

**Comment by jgostick** [comment]
I should add that this file format is also widely used with x-ray tomography.

**Comment by almarklein** [comment]
cc @blink1073

**Comment by blink1073** [comment]
On its way!
