### ISSUE TITLE
imageio.imread with jpg image with Spyder 3.2.5 and Python 3.6 debug message Error closing: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by dlwalter** [imageio/imageio#300]
when running imageio.imread to import a jpg image with DEBUG logging enabled I get the following on Spyder 3.2.5 and Python 3.6

```
import imageio
import logging

logging.basicConfig(level=logging.DEBUG)
a = imageio.imread('picture.jpg')
```
`DEBUG:PIL.Image:Error closing: 'NoneType' object has no attribute 'close'`

the picture imports fine.

**Comment by almarklein** [comment]
The logging occurs in the PIL package, so I suspect that this issue relates to Pillow. It's also a debug message; if we assume that Pillow does its job well, it should be harmless ...

If you want to look closer into this, you could check whether the same message is logged when using Pillow directly.

**Comment by almarklein** [comment]
Closing as a upstream issue.

**Comment by almarklein** [comment]
Nope. This is on us, at least partly.
