### ISSUE TITLE
TIFF I/O broken?

### ISSUE THREAD

**Issue by scivision** [imageio/imageio#307]
Normally I use  `tifffile` (directly, not via imageio) extensively for multipage TIFF. I also use simple metadata in TIFF.  I began to want to use imageio.
However, I am unable to read or write TIFF, even single image TIFF with imageio v.2.2.0 or current git master.
With a very simple multi-page tiff, I get:

```python
imageio.mimread(filename)
```

  File "imageio/core/functions.py", line 278, in mimread
    for im in reader:
  File "imageio/core/format.py", line 394, in iter_data
    n = self.get_length()
  File "imageio/core/format.py", line 328, in get_length
    return self._get_length()
  File "imageio/plugins/tifffile.py", line 188, in _get_length
    return len(self._tf)
TypeError: object of type 'TiffFile' has no len()

I am only able to use imageio.imwrite() or mimwrite() if I don't use any metadata like "description"
```python
imageio.imwrite(filename,img,description='my image')
```
(or mimwrite, as shown below, same results)

  File "imageio/core/functions.py", line 316, in mimwrite
    writer = get_writer(uri, format, 'I', **kwargs)
  File "imageio/core/functions.py", line 172, in get_writer
    return format.get_writer(request)
  File "imageio/core/format.py", line 182, in get_writer
    return self.Writer(self, request)
  File "imageio/core/format.py", line 218, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'description'

**Comment by almarklein** [comment]
I can reproduce that this happens when you install the latest version of tiffile. Apparently, it changed its api somewhat ...

**Comment by almarklein** [comment]
Related to #299

**Comment by scivision** [comment]
Thanks a lot for the quick (pending) update for Tifffile API. It's so nice to have the unified cross-format imageio API.

**Comment by scivision** [comment]
great, what would the PyPi release schedule be?

**Comment by almarklein** [comment]
I'm trying to get some imageio work done right now. Depending on how things go, maybe this week, or next ... or the week thereafter if things take longer than expected :)

**Comment by almarklein** [comment]
Update: probably next week. I was planning on doing work on ffmpeg, but it would be good to release early with the scipy-compat changes and do a next release soonish with mainly ffmpeg improvements.

**Comment by kmilos** [comment]
I was still having trouble using the TIFF API for e.g. writing compressed files w/ imageio 2.5.0 and tifffile 0.15.1, and took me a while to find a solution.

I don't feel low level workarounds like this should be necessary: https://groups.google.com/d/topic/imageio/YZHMvPVHdCU/discussion

**Comment by almarklein** [comment]
If you are you talking specifically  about the compression parameter of the the tiff plugin, we could consider adding an argument to the plugin, so it can be used in `imwrite`.

**Comment by kmilos** [comment]
I was thinking more about passing all possible parameters in the keyword list, which seems to be case for the Reader class? If that's not an option (I guess a limitation of the tifffile lib?), than at least clarify the documentation on https://imageio.readthedocs.io/en/stable/format_tiff.html that the low level method is required for the metadata writing

**Comment by almarklein** [comment]
> I was thinking more about passing all possible parameters in the keyword list,

I'm reluctant to support and document *all* parameters, but we might make it possible to pass a dict that represent kwargs for tifffile and refer to the tifffile docs.
