### ISSUE TITLE
Getting wheter paletted image is grayscale fails for 1-color palettes

### ISSUE THREAD

**Issue by rec** [imageio/imageio#312]
PIL gets it right, however!

I have a short test script to demonstrate it [here](https://github.com/rec/animated_gif/blob/master/single_color.py).

It creates six 64x64 GIF files that are entirely black, red, green, blue and white, and then puts those files into an animated GIF.

I then write it using PIL, and the two imageio strategies from https://stackoverflow.com/a/35943809/43839.  PIL works, but the imageio strategies generate monochromatic GIFs!

NOTE:  I have not been able to find more complex images that exhibit the same issue.  I suspect it's something to do with the "monochromatic GIF file".

Python 3.4.4, MacOS.

**Comment by almarklein** [comment]
Reproduced. Thanks for that script!

**Comment by almarklein** [comment]
The cause was that upon reading, Imageio incorrectly considers the image as grayscale. Updated the title accordingly.
