### ISSUE TITLE
Reading dicomdir may fail if dcm files are in a subfolder

### ISSUE THREAD

**Issue by dm0** [imageio/imageio#315]
If provided with a directory,  `_can_read` function of `dicom` plugin tries to open all files in the directory in sequence until it finds first dicom file.

This fails if the directory contains a subdirectory and that subdirectory has name that after sorting comes before first dicom file. 

Code tries to open directory with `open` and raises `IOError: [Errno 21] Is a directory: ...`

Related code:
```python
    def _can_read(self, request):
        # If user URI was a directory, we check whether it has a DICOM file
        if os.path.isdir(request.filename):
            files = os.listdir(request.filename)
            files.sort()  # Make it consistent
            if files:
                with open(os.path.join(request.filename, files[0]), 'rb') as f:
                    first_bytes = read_n_bytes(f, 140)
                return first_bytes[128:132] == b'DICM'
            else:
                return False
        # Check
        return request.firstbytes[128:132] == b'DICM'
```

For example dicom case with the shown file hierarchy always raises error:
```
data
├── 4PQUVRCL
│   ├── 1CEDXV2R
│   │   ├── I1000000
│   │   ├── ...
│   │   ├── I9900000
│   │   └── VERSION
│   └── VERSION
├── DICOMDIR
├── LOCKFILE
└── VERSION
```

**Comment by almarklein** [comment]
Well found, thanks for reporting! Yeah, there should be an extra test to ignore directories.
