### ISSUE TITLE
Support for frozen apps

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#32]
We would like imageio to work well in frozen apps.

For now, frozen apps with imageio should just work, but required binaries are still downloaded at runtime. This requires an internet connection, so it may be good to provide a way to _ship_ the binary dependencies.

For this we need to provide a way for the developer to copy all required binaries to the app directory (so they can be shipped along) and we need to _look_ in that directory too.

**Comment by paulmueller** [comment]
I propose the following workflow:
1. Implement an [entry point](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) named e.g. `imageio_download_binary` for downloading the required binary.
2. Add the option `--package-dir` to the entry point which will download the binary to the `plugins` directory of the installed package. This directory can be determined with [`pkg_resources.recource_filename`](http://setuptools.readthedocs.io/en/latest/pkg_resources.html#resource-extraction) (which also works with eggs), e.g. `pkg_resources.resource_filename("imageio.plugins", imageio.plugins.ffmpeg.FNAME_PER_PLATFORM[imageio.plugins.ffmpeg.get_platform()])`.
3. Give the binary file in the plugins directory highest priority when calling the `get_exe` method.
4. For Pyinstaller, only a simple hooks script is required:
   ```python
   # hook-imageio.py
   from PyInstaller.utils.hooks import collect_data_files
   datas = collect_data_files('imageio')
   ```
   (needs pull request for PyInstaller)

This workflow as these advantages:
1. It does not break the current behaviour
2. Not many changes to the sources of imageio are required
2. It allows to download binaries with a command line script
3. On CIs such as appveyor or travisCI, it allows to easily build PyInstaller distributables with only the required binaries

**Comment by almarklein** [comment]
Sounds like a plan. How do we deal with the fact that there are multiple binaries? Would you do e.g.
`imageio_download_binary ffmpeg` ?

**Comment by paulmueller** [comment]
Yes, that would be the usage of the entry point script. Did I oversee anything? I could start with a PR.

**Comment by almarklein** [comment]
As far as I can see, this should work. Looking forward to a PR!

**Comment by paulmueller** [comment]
I have a question regarding the `_set_platform_resources` method in `setup.py` (used in `build_with_fi`). What is the use-case of this method? Also, there are two lines dealing with ffmpeg commented out in `_set_platform_resources`?

**Comment by almarklein** [comment]
The purpose was to make it possible to build dists with the libraries packaged in. It's not used anymore though (at least not by me). The FFMPEG lines were added at some point, but then commented because it would make the dist package very large.

**Comment by paulmueller** [comment]
This one can be closed now.
