### ISSUE TITLE
ImportError: Imageio Pillow requires Pillow, not PIL! 

### ISSUE THREAD

**Issue by Swiffers** [imageio/imageio#322]
hi, 

I'm falling into this error, 

```
Traceback (most recent call last):
  File "./script.py", line 255, in add_watermark
    watermark = (ImageClip("./watermark.png")
  File "/usr/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 968, in __init__
    img = imread(img)
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 185, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/usr/lib/python2.7/site-packages/imageio/core/functions.py", line 105, in get_reader
    format = formats.search_read_format(request)
  File "/usr/lib/python2.7/site-packages/imageio/core/format.py", line 660, in search_read_format
    if format.can_read(request):
  File "/usr/lib/python2.7/site-packages/imageio/core/format.py", line 189, in can_read
    return self._can_read(request)
  File "/usr/lib/python2.7/site-packages/imageio/plugins/pillow.py", line 57, in _can_read
    Image = self._init_pillow()
  File "/usr/lib/python2.7/site-packages/imageio/plugins/pillow.py", line 43, in _init_pillow
    raise ImportError('Imageio Pillow requires Pillow, not PIL!')
ImportError: Imageio Pillow requires Pillow, not PIL!
```

**Comment by almarklein** [comment]
Hi! It looks like you've installed PIL instead of Pillow. If this is not the case, please let me know.

**Comment by Swiffers** [comment]
```
> sudo pip install Pillow
Requirement already satisfied: Pillow in /usr/lib64/python2.7/site-packages
```

**Comment by almarklein** [comment]
What does this give you?
```py
>> import PIL
>> PIL
>> PIL.VERSION
>> PIL.PILLOW_VERSION
```

**Comment by Swiffers** [comment]
Somehow pillow was installed in /usr/**lib64**/python2.7/site-packages/
But python was looking for it in /usr/**lib**/python2.7/site-packages/

I solved the issue by running:
`pip install --target=/usr/lib/python2.7/site-packages/ --upgrade pillow`

**Comment by chrischma** [comment]
still getting the same error in 2022. any other ideas how to solve it? thank you!

**Comment by FirefoxMetzger** [comment]
@chrischma Hard to say without you providing more information about your situation. In general, this error comes up if your environment is ill-configured and there isn't much we can bake into the library to prevent that from happening.

A few angles to start debugging:

- Check from which location you are importing pil: `python -c "import PIL; print(PIL.__file__)"` and verify that it comes from the `site-packages` where you can install packages to and that nothing unexpected happens.
- try uninstalling pillow (`pip uninstall pillow`) and see if anything aliases the package, i.e., after you've uninstalled pillow a `import PIL` should raise an `ImportError`, if not, you have packages aliasing each other.
- Try upgrading pillow via `pip install -U pillow`

If none of this provides useful insight, you will have to describe your problem in more detail.

**Comment by surak** [comment]
> What does this give you?
> 
> ```python
> >> import PIL
> >> PIL
> >> PIL.VERSION
> >> PIL.PILLOW_VERSION
> ```

```
python                                                                                                                                                                                                             ✔  ytmaker Py  00:21:08 
Python 3.11.8 (main, Feb  6 2024, 21:21:21) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>  import PIL
  File "<stdin>", line 1
    import PIL
IndentationError: unexpected indent
>>> import PIL
>>> PIL
<module 'PIL' from '/Users/surak/Devel/ytmaker/.venv/lib/python3.11/site-packages/PIL/__init__.py'>
>>> PIL.VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'VERSION'
>>> PIL.PILLOW_VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'PILLOW_VERSION'
>>> PIL.__version__
'11.0.0'
```
