### ISSUE TITLE
mimwrite - option to turn interpolation off

### ISSUE THREAD

**Issue by catubc** [imageio/imageio#326]
Great tool. Whenever I convert a 3D movie (time by x_pixels by y_pixels) the movie comes out with a default interpolation (I think it is a bilinear interpolation). Is it possible to turn interpolation off? I couldn't see the option in your functions.py. Also possible to change color map and vmin/vmax?

I do see these parameters in a main fucntion in ...plugins/_tifffile.py:
```
def main():
...
opt('--interpol', dest='interpol', metavar='INTERPOL', default='bilinear',
        help="image interpolation method")
```

Here's my code for saving:

imageio.mimwrite('movie.mp4', data_matrix, fps = 15)

Thanks,
catubc

**Comment by almarklein** [comment]
You can refer to the ffmpeg documentation for setting the output encoding. But note that the point of ffmpeg is to compress the frames (spatially and temporally), and the interpolation is likely part of the decoding step by the video viewer. If you want less lossy video, try e.g. GIF or SWF. Or TIFF/NPZ/BSDF if you have no need to view the video as a video (i.e. only storage of the frames).

I'd recommend applying vmin and vmax yourself using some math on the numpy arrays that represent the frames.

**Comment by catubc** [comment]
Thanks for the answer. But it's unclear how I can set the ffmpeg output options from within mimwrite? 

Are you suggesting that I use the command line version of imageio for that purpose?

Thanks,

**Comment by almarklein** [comment]
See the output_parems parameter in http://imageio.readthedocs.io/en/stable/format_ffmpeg.html#ffmpeg

**Comment by catubc** [comment]
Great, thank you!
