### ISSUE TITLE
Keep imageio light while scaling the number of plugins

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#33]
I think we should provide much of the IO implementation in one module (e.g. `_swf.py`), while the format itself is defined in another (e.g. `swf.py`). The former should *not* be imported by default, but only as the format is being used.

**Comment by blink1073** [comment]
How about deferring the actual import to within the `_open` methods where possible?  This will work for `tifffile` and `swf`.

**Comment by blink1073** [comment]
See #97 for implementation.

**Comment by almarklein** [comment]
Yes, that makes sense. Setup.py won't need changing, but people who freeze an app that makes use of imageio should include these `_tiffile.py` and the likes. Maybe we can provide some functionality to help such users.

**Comment by blink1073** [comment]
I have no experience with freezing, and I'm on OSX.

**Comment by blink1073** [comment]
Would you like a PR that defers loading of `_swf.py`?

**Comment by blink1073** [comment]
I got `cx_freeze` working and verified that `mimread` and `mimsave` work with a mult-page tif file.

**Comment by almarklein** [comment]
But I suppose that you had to add `_tiffile.py` or `tiffile.py` (the 5k one) to the includes?

**Comment by blink1073** [comment]
The only change I made to `imageiotest_freeze.py` was to remove this [line](https://github.com/imageio/imageio/blob/master/tests/freezing/imageiotest_freeze.py#L63), because that function does not exist in [freeze.py](https://github.com/imageio/imageio/blob/master/imageio/freeze.py).

**Comment by blink1073** [comment]
I assume that function *should* have been needed, in which case it looks like the frozen folder is not truly isolated.

**Comment by blink1073** [comment]
I also noticed that when the app is frozen it cannot pull files from github due to an https error with `urlparse`.  I think freezing is an antipattern for many reasons.

**Comment by almarklein** [comment]
>  I think freezing is an antipattern for many reasons.

haha, very True. Ah well, we'll see what happens. 

> Would you like a PR that defers loading of _swf.py?

Forgot to answer that: Sure, since its already split, it should be easy. To do the same for e.g. DICOM would need some refactoring; we can safe that for later.

**Comment by blink1073** [comment]
Sure, I'll take a stab at both PRs. Are you going to the SciPy conference by chance?



—

**Comment by almarklein** [comment]
Nope, I'm going to Euroscipy in August.

**Comment by blink1073** [comment]
Ah well, perhaps Google Hangout sometime to discuss strategy?



—

**Comment by almarklein** [comment]
Yes, would be good!

**Comment by almarklein** [comment]
Closing this, since we've made good progress here, and #110 is on the way to help more.
