### ISSUE TITLE
Understanding gif processing

### ISSUE THREAD

**Issue by carlosdubus** [imageio/imageio#331]
Hi, this is more a question than an issue.

I thought if I did the following, I would get the same pixel data back. Instead I get single int values:

```
import imageio
import numpy as np

# write
gif = imageio.get_writer("test.gif")
pixel = np.array([0,0,0,255], dtype=np.uint8)
print(pixel)
gif.append_data(np.array([[pixel]]))
pixel = np.array([140,212,245,255], dtype=np.uint8)
print(pixel)
gif.append_data(np.array([[pixel]]))
gif.close()

# read
gif = imageio.get_reader("test.gif")
data = gif.get_next_data()
print(data[0][0])
data = gif.get_next_data()
print(data[0][0])
```

Output:
```
[  0   0   0 255]
[140 212 245 255]
0
194
```

Why I don't get the same pixels back?

Thanks for your help.

**Comment by almarklein** [comment]
I suspect that the color gets lost somehow during the color-coding stage. It might be related to the image having just one pixels. Could you try with in `nxnx4` image, where `n >= 10`?

**Comment by almarklein** [comment]
Note that you probably won't get your original colors back anyway. GIF can use just 8 bit per pixel, and tries to produce a colormap that most efficiently packs the most relevant colors.

**Comment by carlosdubus** [comment]
@almarklein thanks for your help. The following answers the question so I'm no longer needing this. Thanks!

> Note that you probably won't get your original colors back anyway. GIF can use just 8 bit per pixel, and tries to produce a colormap that most efficiently packs the most relevant colors.

**Comment by almarklein** [comment]
Thanks for the clarification!
