### ISSUE TITLE
how to open an image file as rgb

### ISSUE THREAD

**Issue by wenouyang** [imageio/imageio#332]
Hi,
I have an existing code segment reading image using `scipy.misc`
`imref = misc.imread(self.file_image, False, "RGB")`

If I would like to replace it with imageio, how to do that, can I just use

`imref = imageio.imread(self.file_image, False). `
I am not clear where to setup the `"RGB"` parameter while using `imageio.imread.`

Thanks

**Comment by almarklein** [comment]
http://imageio.readthedocs.io/en/stable/scipy.html

**Comment by almarklein** [comment]
In other words. you can use ``imref = imageio.imread(self.file_image, as_gray=False, pilmode='RGB').
