### ISSUE TITLE
Is webm file supported?

### ISSUE THREAD

**Issue by pipehappy1** [imageio/imageio#340]
`reader = imageio.get_reader('/path/to/movie.webm')`

gets

`Unknown standard image '/path/to/movie.webm'.`

Could someone shed some light on this? Thanks!

**Comment by almarklein** [comment]
Hi,

I see that the original post was slightly different. The `'imageio:xxx'` prefix is used for standard images. You omit it when you target your own data, as you now wrote above :)

**Comment by pipehappy1** [comment]
Thanks! Although the problem is still there, I guess that conversion to mp4 first may be a durable workaround.
