### ISSUE TITLE
Spurious warnings from tiffile

### ISSUE THREAD

**Issue by kohr-h** [imageio/imageio#350]
When reading a TIFF file, I get the following warning:
```
[...]/_tifffile.py:7285: UserWarning: module 'imageio.plugins._tifffile' has no attribute 'reverse_bitorder'
  Functionality might be degraded or be slow.

  warnings.warn("%s%s" % (e, warn))
```
This happens on Linux and Windows, with version 2.3.0 from conda as well as with current Git master, commit 1335217992aca7558a3600bd11cd05a22e698e22.

**Comment by kohr-h** [comment]
The same happens for `'decode_packbits'`, `'decode_lzw'` and `'unpack_ints'`.

**Comment by almarklein** [comment]
cc @scivision

**Comment by scivision** [comment]
With the following setup and some example TIF, I don't get any warnings. Can you upload a sample image?

```bash
$ python
```

> Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58) 
> [GCC 7.2.0] on linux

```python
 import tifffile; tifffile.__version__
'0.14.0'

import imageio; imageio.__version__
'2.3.0'
```

**Comment by kohr-h** [comment]
Well, that explains. I don't have `tifffile` installed. So the real issue is that the warning doesn't point to the problem. Also I can't find it mentioned in the documentation that fast handling of TIFF requires the `tifffile` package, mentioning that would be good as well.

Shall I make a PR?

**Comment by almarklein** [comment]
@kohr-h  Actually, imageio uses its own baked-in version of tifffile if its not installed.

**Comment by kohr-h** [comment]
@almarklein Is that baked-in version slower, i.e. is the warning justified? In that case, maybe the warning could say "To improve performance, you can install the tifffile package." or so.

**Comment by almarklein** [comment]
No, it's simply a snapshot of a release of tifffile.py

**Comment by kohr-h** [comment]
In that case, the warning doesn't make sense to me.

**Comment by nineclicks** [comment]
Totally agree here, the warnings shouldn't be there if it doesn't affect anything. And if it does, they should mention the very simple solution of installing tifffile.

**Comment by almarklein** [comment]
> And if it does, they should mention the very simple solution of installing tifffile.

Imageio does not create the warning, so its not trivial to add such a mention :)  We should probably just update our version of tifffile ...

Actually, I could use some help managing the tifffile plugin, I hardly ever use it myself so I don't see quirks like these (and don't care enough to do something about it right away). It's not a lot of work: helping out with questions like this and upgrading the builtin version from time to time. Perhaps someone on this thread is interested?

**Comment by almarklein** [comment]
In my view, we should replace/remove the decorator so that no warning is shown, because it leads to confusion. The fact that it is slower should be documented clearly in the docs of our TIFFFILE plugin. What do you think?

**Comment by almarklein** [comment]
@scivision do you perhaps have time to make a PR to do this?

**Comment by hmaarrfk** [comment]
Maybe if wheels are provided by tifffile, tifffile can just be made a dependency?

https://github.com/imageio/imageio/issues/350

**Comment by almarklein** [comment]
@hmaarrfk That definitely worth considering ....

**Comment by scivision** [comment]
I would really be behind making `tifffile` a simple dependency e.g. `setup.cfg` or `requirements.txt` instead of copying it inline. Unless there was some specific reason for keeping a local copy.  Many people are *not* using TIFF.

**Comment by almarklein** [comment]
@scivision the propblem AFAIU is that tifffile is not pure Python anymore, so installing is nontrivial, unless binary wheels are provided.

**Comment by hmaarrfk** [comment]
The author of the package was not enthousiastic about providing wheels. maybe somebody knows how to automate that?

**Comment by almarklein** [comment]
Knowing him a bit, I think he'd be enthusiastic, but he's swamped :)

**Comment by hmaarrfk** [comment]
Yeah, he mentionned he was too busy to setup the infrastructure. See the issue I linked to above asking him the question.

**Comment by hmaarrfk** [comment]
Well, I had started with making some wheels https://github.com/hmaarrfk/tifffle-wheels

Except that I ran into this warning https://github.com/matthew-brett/multibuild/issues/202#issuecomment-425670715

**Comment by almarklein** [comment]
> I wish there was just an option to quiet these warnings down, I don't need them repeated to the user each time it runs.

I completely agree ...
