### ISSUE TITLE
Clarify version of ffmpeg needed for video capabilities in anaconda distribution

### ISSUE THREAD

**Issue by mszegedy** [imageio/imageio#353]
It would be helpful if the documentation explicitly recommended which ffmpeg package to install from Anaconda Cloud so that the primary video capabilities of imageio would work, in the case that one is installing imageio from there. For example, I had `anacoda/ffmpeg` lying around as my ffmpeg package, and found out that it's missing the libx264 codec for encoding H.264 video, which made imageio's video writers fail when having frames appended to them. It took me a while to realize that the problem was with my ffmpeg distribution, and that I should install `conda-forge/ffmpeg` instead.
The [current documentation](http://imageio.readthedocs.io/en/stable/installation.html) on installing imageio promises that imageio will "help ... download" additional libraries needed for various operations, but it wasn't very helpful here; the only helpful error I ever got was ffmpeg saying `Unknown encoder 'libx264'`. An explicit list of optional dependencies and recommended sources for them on that page in particular would be helpful.

**Comment by almarklein** [comment]
Thanks for the feedback! I was not aware that the standard anaconda distribution of ffmpeg lacked such a common codec. I will update the docs.

**Comment by mszegedy** [comment]
I guess it should have tipped me off when `conda-forge/ffmpeg` had 27 times as many downloads as `anaconda/ffmpeg`. I think it has to do with the fact that `libx264` is GPL, as opposed to LGPL, as discussed in [this issue.](https://github.com/conda-forge/ffmpeg-feedstock/issues/44)

**Comment by mszegedy** [comment]
Now that I've looked at the docs more closely, [they do](http://imageio.readthedocs.io/en/latest/format_ffmpeg.html#ffmpeg) actually recommend the `conda-forge` version of ffmpeg, but it's somewhat buried, being in the format-specific docs.

**Comment by almarklein** [comment]
Thanks. I have very little time right now. If you're interested to make a pull request to update the docs that would be awesome. Otherwise I'll do it later, which might be after the summer holidays.

**Comment by almarklein** [comment]
On second thought, with #115 things will change, so I'm holding this off until then.

**Comment by dmexs** [comment]
A year later I ran into this issue. Furthermore, the output from ffmpeg: `Unknown encoder 'libx264'`, doesn't make it back to the Jupyter notebook.

I think OP's suggestion about including a hint towards conda-forge/ffmpeg would be helpful.

**Comment by MaratZakirov** [comment]
Any chages?

**Comment by FirefoxMetzger** [comment]
@MaratZakirov Yes and no. You are still responsible for choosing the FFMPEG version that you would like to use for read/write. We can't make that choice for you, because we want to remain unopinionated.

Regarding the docs, there is a doc PR I am currently working on (you can view the *preview* here: https://imageio--648.org.readthedocs.build/en/648/index.html). We can add a note to the FFMPEG plugin that anaconda/ffmpeg does not support H.264 and suggest using conda-forge/ffmpeg as an alternative. I guess this would resolve the issue?
