### ISSUE TITLE
how to uninstall imageio?

### ISSUE THREAD

**Issue by agangzz** [imageio/imageio#354]
how to uninstall imageio?
thanks

**Comment by almarklein** [comment]
Depends on how you installed it:

* With pip: `pip uninstall imageio`
* With conda: `conda remove imageio`

**Comment by yashwardhanchauhan** [comment]
ERROR: Cannot uninstall 'imageio'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by almarklein** [comment]
@yashwardhanchauhan I think this can happen when you've installed from source using `python setup.py install`. In this case you best go to your `site_packages` directory, and remove the imageio directory there.

You can find the location of imageio using `>> import imageio; print(imageio.__file__)`.
