### ISSUE TITLE
Value changed when loading logical tiff image

### ISSUE THREAD

**Issue by xycyx** [imageio/imageio#355]
After loading a logical uncompressed tiff image with imread, the values of loaded image were inverted.
For example, the image I have was like below,
![capture](https://user-images.githubusercontent.com/16574534/41753335-ad1fb2f4-7581-11e8-8b98-3b5b4e595b48.PNG)
After using imageio.imread('image.tiff'), the logical values changed.
![capture2](https://user-images.githubusercontent.com/16574534/41753384-f0313b80-7581-11e8-9dd5-fe6d60e8760e.PNG)
I examined the values of the numpy array, the pixels which should be 'False' were changed to 'True'.
![capture3](https://user-images.githubusercontent.com/16574534/41753421-3faafe26-7582-11e8-99bf-6e551062b62f.PNG)

Not test on other platforms. 

Platform: Windows 10
Version: imageio (2.2.0)
Python 3.5

Test image:
[Target.zip](https://github.com/imageio/imageio/files/2125832/Target.zip)

**Comment by almarklein** [comment]
I can reproduce this. It appears to be a bug in the `tifffile` plugin. Possibly in the 3d party `tiffffile.py`.

You can workaround this by using the Pillow plugin: `im= imageio.imread('/path/to/Target.tiff', 'tiff-pil')`.

I verified that the bug is indeed in the `tifffile` module:
```
import imageio
import tifffile
import visvis as vv

filename = r'C:\stack\data\Target.tiff'
im1 = imageio.imread(filename, 'tiff-pil')  # workaround
im2 = tifffile.imread(filename)

vv.figure(1); vv.clf()
vv.subplot(211); vv.imshow(im1)  # good
vv.subplot(212); vv.imshow(im2)  # bad
```

```
>>> tifffile.__version__
'0.13.5'
```

If you want, you could open an issue at the tifffile repo: https://github.com/blink1073/tifffile

**Comment by cgohlke** [comment]
Tifffile correctly reads and returns the image data stored in the file as a numpy array of dtype `bool`. Other libraries further process/normalize the image data for display according to the `PhotometricInterpretation` and other tags and return the processed image data. In the case of Target.tiff, PIL etc flip the bits according to `PhotometricInterpretation=MINISWHITE` and return a 'uint8' array where `True` is mapped to 0 and `False` to 1. Not exactly what one wants in a scientific application. Same for other `PhotometricInterpretation` values, `Orientation`, `PlanarConfiguration` and other tags.

**Comment by almarklein** [comment]
Thanks for chiming in @cgohlke! So if I understand correctly, the data in the image in reality has more truthy than falsy pixels (as in the second image of the first post)?

**Comment by cgohlke** [comment]
> So if I understand correctly, the data in the image in reality has more truthy than falsy pixels (as in the second image of the first post)?

Yes. But the image should be displayed with False->White and True->Black, e.g. `cmap='gray_r'`.

**Comment by xycyx** [comment]
@cgohlke @almarklein Thank you. But the first image I shown there was created and displayed by matlab, which actually had more `False` pixels than the `True` pixels. The problem  was that when I loaded it to numpy array with default setting `tifffile` , its already been flipped as shown in third picture. While the PIL didn't flip it.

```python
import imageio
import matplotlib.pyplot as plt

filename = r'F:\test\Target.tiff'
im1 = imageio.imread(filename, 'tiff-pil')  # workaround
im2 = imageio.imread(filename)

fig = plt.figure()
ax1 = fig.add_subplot(121)
ax1.imshow(im1, cmap=plt.get_cmap('gray'))
ax1.set_title('tiff-pil')
ax2 = fig.add_subplot(122)
ax2.imshow(im2, cmap=plt.get_cmap('gray'))
ax2.set_title('default `tiff')`
```
![capture4](https://user-images.githubusercontent.com/16574534/41804601-6877c498-764e-11e8-87d9-188bf21212c0.PNG)
![capture5](https://user-images.githubusercontent.com/16574534/41804602-6ac903b0-764e-11e8-8623-6241d34c9ff4.PNG)

**Comment by cgohlke** [comment]
OK, lets look at the first 8 values of the image data in the file without any library:
```Python
>>> with open('Target.tiff', 'rb') as fh:
...     fh.seek(8)  # seek to first StripOffset
...     bin(ord(fh.read(1)))  # read one byte and convert to binary string
...
8
'0b11111111'
```
The first 8 bits are all `1`, `True`. Tifffile does not flip the values.

**Comment by almarklein** [comment]
Closing, as this appears to be not a problem of imageio (nor tifffile), but a somewhat confusing image :) and perhaps a bug in Matlab. Please reopen if you disagree.

**Comment by cgohlke** [comment]
Related issue https://github.com/scikit-image/scikit-image/issues/1940
