### ISSUE TITLE
Add proxy support to ```fetching.py``` 

### ISSUE THREAD

**Issue by eli-s-goldberg** [imageio/imageio#357]
Installing ffmpeg automatically causes some problems behind a firewall using the ```imageio.plugins.ffmpeg.download()``` method. 

Proxy support can be enhanced by adding/changing the following within [```_fetch_file```](https://github.com/imageio/imageio/blob/368c724957cc67652f9c24b32628e4fdc19ecd3c/imageio/core/fetching.py#L159). 
``` python 
authinfo = urllib.request.HTTPBasicAuthHandler()
proxy_support = urllib.request.ProxyHandler({'https': 'http://yourproxy.corporate.zombie.net:2011'})
opener = urllib.request.build_opener(proxy_support, authinfo,urllib.request.CacheFTPHandler)
urllib.request.install_opener(opener)
remote_file = urllib.request.urlopen(url)
```

Perhaps it would be good to pass a proxy location through ```imageio.plugins.ffmpeg.download()``` to make the process suitable when needing a proxy?

**Comment by almarklein** [comment]
That's a great idea. Since you already know how to do this, would you be interested in making a PR? :)

**Comment by SimonAltmannshofer** [comment]
I have the same problem with `imageio.plugins.ffmpeg.download()` behind a proxy. The solution from eli-s-goldberg worked perfectly (had to add `import urllib` at the beginning of `fetching.py`).

**Comment by eli-s-goldberg** [comment]
Hi Simon, glad to hear it. I have time this weekend to make a pull request:)

**Comment by almarklein** [comment]
Closing this, since `imageio-ffmpeg` solves the problem of distributing the ffmpeg executables.

**Comment by eli-s-goldberg** [comment]
Oh man. Spaced out in corporate zombie land.

Sorry about that.

Nice work!
