### ISSUE TITLE
How to get the accurate frame number?

### ISSUE THREAD

**Issue by yelantingfeng** [imageio/imageio#363]
Well, I notice that the number of frames is estimated by the frame rate, which is not always equal to the actual number. My current solution is to test from the meta_data['nframes']-1 until it do return an available frame, but this is still not good. Is there any good suggestions? Thank you for your generous help in advance.

**Comment by almarklein** [comment]
This is a known problem, see e.g. #341, #264. Hopefully things well be better once we move to pyav (#115).

**Comment by yelantingfeng** [comment]
Ok, there seems to be no good solution in imageio of current version.  Anyway, thank you all the same and look forward to the new plugin based on pyav.
