### ISSUE TITLE
Animation PNG (.apng) to GIF it's real?

### ISSUE THREAD

**Issue by JakeBV** [imageio/imageio#364]
How to do it?

**Comment by almarklein** [comment]
There is no support for apng yet, see #172

**Comment by FirefoxMetzger** [comment]
For future readers: You can now read and write APNG. There is a bug when iterating over frames, but that will be fixed by https://github.com/imageio/imageio/pull/750. Once merged, 

To convert an APNG file into GIF, you'd use something along the lines of:

```python
import imageio.v3 as iio

frames = iio.imread("path/to/my.apng", index=None) 
iio.imwrite("path/to/my.gif", frames)

```
