### ISSUE TITLE
When should the Pillow plugin apply gamma correction?

### ISSUE THREAD

**Issue by habi** [imageio/imageio#366]
*original title: Reading PNG files differently than scipy.misc*

I've been using `scipy.misc.imread`for reading (tomographic) images for processing.
After a recent upgrade of my system I'm told this is deprecated in favor of  `imageio.imread`.

Unfortunately my images are read differently depending on which I use, namely with a different gray-scale range, as can be seen below.

```
import scipy.misc
import imageio
import matplotlib.pyplot as plt
%matplotlib inline
import numpy
r = 'test.png'  # attached tho this issue
img_scipy = scipy.misc.imread(r)
img_imageio = imageio.imread(r)
plt.subplot(121)
plt.title('scipy min: %s, max: %s' %(numpy.min(img_scipy), numpy.max(img_scipy)))
plt.imshow(img_scipy)
plt.subplot(122)
plt.imshow(img_imageio)
plt.title('imageio min: %s, max: %s' %(numpy.min(img_imageio), numpy.max(img_imageio)))
plt.show()
```
![output](https://user-images.githubusercontent.com/1651235/43787395-2bf373c8-9a6b-11e8-98d4-1c04190ce38c.png)

[ImageJ](http://fiji.sc/) reports a maximum gray value of 162 for the image, which is what I would have expected...

imageio.__version__ =  '2.3.0'
scipy.__version__ = '1.1.0'

![test.png](https://user-images.githubusercontent.com/1651235/43787150-a6cf810a-9a6a-11e8-9a3d-71f06eb6e2db.png)

How can I get my correct gray value range back?

**Comment by almarklein** [comment]
I can reproduce this. Before diving in, there's a difference in shape:
```
>>> img_scipy.shape
(2452, 2452, 3)
>>> img_imageio.shape
(2452, 2452)
```

I traced the steps that the image takes inside imagio, and it has the same values as the other image ... until gamma correction is applied. This should do the trick:
```py
img_imageio = imageio.imread(r, ignoregamma=True)
```

Now, imageio applies the gamma by default when gamma info is available. But this case makes me doubt whether this is the right thing to do. Because when I save both images to png again, and view them with my OS (and also paint.NET), the original image looks like the scipy one. In other words, my OS nor plaint.net do not apply the gamma correction. Do you perhaps have any idea about the best approach here?

**Comment by habi** [comment]
I tried to minizmize the example as much as possible, usually I load the images with `scipy.misc.imread(filename, flatten=True), to convert any possibly RGB images to gray values.
And I've also seen that when I open and overwrite the file with ImageJ that `imageio.imread` reads them correctly.
I'll ignore the gamma for the moment, thanks for the pointer!

**Comment by habi** [comment]
> Do you perhaps have any idea about the best approach here?

In everything I've done up to now I relied on ImageJ giving me the 
'real' data of the images, I treat this as kind of baseline.
And since scipy.misc.imread gives the same result as ImageJ I would also 
expect imageio.imread to give me the same result, e.g. discard the gamma 
by default.

**Comment by almarklein** [comment]
I agree. I am pretty sure that when I wrote that code, I also tested it against some baseline. It could have been for jpg images though... will look into this (so please leave the issue open).

**Comment by almarklein** [comment]
More reading materials on the background of gamma correction in PNG:
* https://hsivonen.fi/png-gamma/
* https://jonathannicol.com/blog/2006/12/01/fixing-png-gamma/

**Comment by almarklein** [comment]
Gamma correction is now not applied anymore by default. And a test has been added to make sure it does not regress. Thanks for reporting @habi !

**Comment by habi** [comment]
Thanks for fixing it!
