### ISSUE TITLE
Is imageio safe with multiprocessing?

### ISSUE THREAD

**Issue by yelantingfeng** [imageio/imageio#367]
I am using imageio to decode some video files with multiprocessing. Somehow my system always crashes. I wonder is imageio safe when using it this way.

**Comment by almarklein** [comment]
In principal is should be. As long as you don't try to write to the same file from multiple processes ...  Any more information about the kind of errors?

**Comment by yelantingfeng** [comment]
Sorry,  I finally found out the source of the crashes is the compatibility of my baseboard with some other hardware. Thank you for you help.
