### ISSUE TITLE
AVBIN won't release memory when using .close()

### ISSUE THREAD

**Issue by RaphP** [imageio/imageio#370]
Every time I use get_reader() with avbin, a bit of ram is used. This bit of ram is not freed until the python process is closed. It does the same on linux64 and OSX. I tried to understand the avbin implementation, but ctypes etc goes beyond my scope. 
To reproduce 
```
import imageio
for i in range(100):
    video = imageio.get_reader('imageio:cockatoo.mp4', format='avbin')
    video._close()
```

It will use around 400Mb on my ram. 

avbin goes effectively faster that ffmpeg and I liked that a lot, I saw in another issue that avbin hasn't been updated since a long time, but can this problem be fixed ?

Thanks a lot for this library anyway,
Best,
R.

**Comment by almarklein** [comment]
Not sure if @rreilink still has an interest in this? :)

Note that #115 should be coming in a few months, which should make for a more robust and faster video reading/writing experience...

**Comment by almarklein** [comment]
I'll leave this open, but note that it likely wont be fixed, because avbin's development has stalled many years and we're deprecating this plugin.
