### ISSUE TITLE
Don't use the root logger when emitting messages

### ISSUE THREAD

**Issue by mjpieters** [imageio/imageio#376]
In three places, the `imageio` library uses `logging.warning()` to emit warning messages, using the root logger:

* The core library uses `imagio.core.util._precision_warn()` to warn about lossy conversions https://github.com/imageio/imageio/blob/5c8c440a55eb22e0ec8526e47bf405eb84b9a164/imageio/core/util.py#L56-L61
* The `ffmpeg` plugin warns about input image resizing: https://github.com/imageio/imageio/blob/5c8c440a55eb22e0ec8526e47bf405eb84b9a164/imageio/plugins/ffmpeg.py#L829-L841
* The `freeimg` plugin emits a warning when the downloading the dependency fails with an unknown error: https://github.com/imageio/imageio/blob/5c8c440a55eb22e0ec8526e47bf405eb84b9a164/imageio/plugins/_freeimage.py#L97-L98

This makes it extremely hard to disable such messages if the developer using the library deems the warning ignorable; often the root logger is used to only hold logging handlers to collect and direct logging output (to the console, to files, to syslog, etc.), and disabling warnings at this level would affect a lot of other logging output too.

Please use a named logger instead. At the very least, use one named for your library:

```python
# top-level code in the module
import logging

logger = logging.getLogger('imageio')

# anywhere you want to log a warning
logger.warning(...)
```

That way code using the library can opt to configure *just that logging object* to perhaps silence the warning.

Ideally, a logger per module is used, that's trivially achieved with

```python
logger = logging.getLogger(__name__)
```

The `__name__` value is the name of the current module, so `imageio.core.utils` for the module that the precision warning function lives in, linked above. Names with dots in them are treated as a hierarchical namespace by the logging module, giving the option to configure logging at different levels.

This then gives code the option to alter how all of `imageio` logs are handled (by configuring the `imagio` logger) or by altering specific sub-sections (such as `imageio.core` or `imageio.plugins.ffmpeg`).

Currently, users [would have to patch `imagio` code](https://stackoverflow.com/questions/52165705/how-to-ignore-root-warnings) to selectively silence a warning.

A viable alternative would be to use the [`warnings` infrastructure](https://docs.python.org/3/library/warnings.html) instead. This would allow developers to configure for warnings, specifically, such as silencing them (with a lot of control as to when to do so), or even turning such warnings into exceptions (if they would deem triggering the conditions a bug on their side).

**Comment by episodeyang** [comment]
Just want to bump this up a bit.

**Comment by almarklein** [comment]
> in a week or two

... or 5 months

**Comment by episodeyang** [comment]
@almarklein awesome!! is this published? 

Also warnings seems to offer better configuration for the developer.

> A viable alternative would be to use the warnings infrastructure instead. This would allow developers to configure for warnings, specifically, such as silencing them (with a lot of control as to when to do so), or even turning such warnings into exceptions (if they would deem triggering the conditions a bug on their side).

**Comment by almarklein** [comment]
Yes, it was done in https://github.com/imageio/imageio/pull/428/commits/1f1cbb4916c61fe382c1090e536230b71d30e0ca, the latest release has it.
