### ISSUE TITLE
get_writer does not make proper mp4s for low fps

### ISSUE THREAD

**Issue by gokul-uf** [imageio/imageio#389]
Hi,
i am using imageio 2.3.0 on Python 3.6, Ubuntu 18.04. 

I am trying to create a `mp4` from a series of `png` images and I am using `get_writer` for the same.
For `fps < 5`, I observe the following in the generated mp4 while playing on VLC

1. The video is blacked out for the first few seconds.
2. After that, the video stay on the first `png` and does not proceed.

I have not tried for higher fps, but seems the issue gets resolved when `fps>10`.

Someone has also raised this issue on [stackoverflow](https://stackoverflow.com/questions/51067576/video-is-black-when-framerate-is-too-low-using-imageio-and-python)  but has not yet received any comment / answer.
Am I doing something wrong or does this seem like a bug with `imageio`?

Thanks!

**Comment by almarklein** [comment]
It's likely more a problem with the low fps and ffmpeg settings ... perhaps a setting is needed to increase the number of keyframes?

**Comment by gokul-uf** [comment]
I'm not sure how I can change the `ffmpeg` settings or what to change. Would be great if you had any suggestions.

Thanks!

**Comment by almarklein** [comment]
I know how to change the ffmpeg settings, see the `input_params` and `output_params` in [the docs](https://imageio.readthedocs.io/en/latest/format_ffmpeg.html#ffmpeg). But I don't know what settings to use :) you'd need to look at the ffmpeg docs for this, or perhaps someone already asked something similar on Stackoverflow.

**Comment by almarklein** [comment]
I am closing this, since this looks like an issue specific to ffmpeg in combination with low fps.
