### ISSUE TITLE
Feature request: use np.asarray in imwrite

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#393]
Would you consider using `np.asarray` in `imwrite` to coerce things into a numpy array?

https://github.com/imageio/imageio/blob/1e08c70ce38b8607fbc528d91f1b604bec4c7a88/imageio/core/functions.py#L247

Writing dask arrays or xarrays would become more convenient among other things.

**Comment by almarklein** [comment]
Yes, I think this makes sense. Though we should probably catch any exceptions in this step and reraise with a more meaningful error message. A PR would be great 🙏

**Comment by hmaarrfk** [comment]
I'm not even sure what can't be coerced into a numpy array
