### ISSUE TITLE
[security issue] You have to check file fingerprints after you download them

### ISSUE THREAD

**Issue by yurivict** [imageio/imageio#416]
The function ```get_remote_file``` (here https://github.com/imageio/imageio/blob/master/imageio/core/fetching.py#L35) downloads files from the Internet without checking their fingerprints. For example, it downloads the ```ffmpeg``` executable.

Please note that just having ```https``` in the URL isn't a guarantee that the file is downloaded from the intended location. https certificate verification can be subverted, and can't be relied on. One example is that governments can subvert it systematically: https://news.ycombinator.com/item?id=10663843 But there could also be compromised certification authorities, and hacked connections.

You need to store and check cryptographic fingerprints of all downloaded files, or, better just depend on pre-installed executables. For example, ```ffmpeg``` packages exist on virtually all systems.

**Comment by almarklein** [comment]
Thanks for the heads up. I agree. The ffmpeg plugin is `up for discussion](https://github.com/imageio/imageio/issues/406) right now, and this issue should be part of any new solution.

**Comment by almarklein** [comment]
With #425 the binaries are distributed via the new `imageio-ffmpeg` library via pip.

**Comment by almarklein** [comment]
Though the issue still stands for the avbin and freeimage downloads. I plan on using a similar approach for freeimage if this works out well. The avbin plugin will be deprecated.
