### ISSUE TITLE
Latest release does not contain commits

### ISSUE THREAD

**Issue by addisonElliott** [imageio/imageio#420]
Correct me if I'm wrong, but I authored a PR back in October of last year (#388) and a release has been published since then but does not contain my commit.

Maybe I'm going crazy, but it all seems very confusing. Let me walk you through what I mean...

First, if you look at the master branch, it shows my commit fine. Line 574 of the pillow.py plugin, you can see the "rawmode_saved" code I added to fix a special case. [https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py#L574](https://github.com/imageio/imageio/blob/master/imageio/plugins/pillow.py#L574)

My PR was merged October 1, 2018. Version 2.4.1 was released on November 15th, 2018. Thus, my changes should be in v2.4.1.

Downloading the source directly from PyPi for v2.4.1, I look at the same file and my changes are not there.
![Screenshot](https://i.imgur.com/1GugSU7.png)

# Solution
Probably just release another version? Luckily I don't **need** these changes now but just wanted to bring to your attention.

**Comment by almarklein** [comment]
You nearly had me going crazy too there :)

The 2.4.1 release was actually from 6 September. See e.g. [pypi](https://pypi.org/project/imageio/#history). This is also the date that this release was tagged. But apparently at some point in November I turned the tag to a "release" on Github, and Girhub will display the day that this was done (with no option to change it). I can see how this caused confusion! :)
