### ISSUE TITLE
Exposure value written incorrectly for HDR-FI format

### ISSUE THREAD

**Issue by NoRoKr** [imageio/imageio#421]
Exposure value is a scalar multiplier. By default, writing to HDR images seems to result in files with exposure = 0

**Comment by almarklein** [comment]
Thanks for reporting this. I'll have a look at it when I have the time. If you want, you could have a look at [this file](https://github.com/imageio/imageio/blob/master/imageio/plugins/_freeimage.py) and maybe spot where a change is needed. That should certainly speed up the fix :)

**Comment by almarklein** [comment]
Even better! Thanks for looking into this :)
