### ISSUE TITLE
Error while fetching file: HTTP Error 404: Not Found. 

### ISSUE THREAD

**Issue by rec99** [imageio/imageio#423]
Hi!

In python scrip starts with:
```
import imageio

imageio.plugins.ffmpeg.download()
```
on Ubuntu and Win machines the script stops with exception:
```
Imageio: 'ffmpeg.win32.exe' was not found on your computer; downloading it now.
Error while fetching file: HTTP Error 404: Not Found.
Error while fetching file: HTTP Error 404: Not Found.
Error while fetching file: HTTP Error 404: Not Found.
Error while fetching file: HTTP Error 404: Not Found.
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    imageio.plugins.ffmpeg.download()
  File "C:\Users\ilya\Desktop\ins\.venv\lib\site-packages\imageio\plugins\ffmpeg.py", line 55, in download
    get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])
  File "C:\Users\ilya\Desktop\telegram-insta-bot\.venv\lib\site-packages\imageio\core\fetching.py", line 121, in get_remote_file
    _fetch_file(url, filename)
  File "C:\Users\ilya\Desktop\ins\.venv\lib\site-packages\imageio\core\fetching.py", line 177, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg.win32.exe'. Perhaps there is a no internet connection? If there is, please report this problem.
```
I was try to manually change the _url_root in get_remote_file to` 'https://github.com/imageio/imageio-binaries/'` instead of `'https://github.com/imageio/imageio-binaries/raw/master/'` but it is didn't help.

**Comment by almarklein** [comment]
What version of imageio are you using? I've recently cleaned up some of the online binaries, and it looks like it is trying to download one that corresponds to a rather old version of imageio.

**Comment by almarklein** [comment]
I just checked, and imageio started using versioned ffmpeg downloads from v2.2.0 (25 May 2017). Since I only removed unversioned files, downloading ffmpeg should work for any version equal or higher than that.

**Comment by rec99** [comment]
Oh, yeah.
One of my dependency modules has the imageio-2.1.2. After change on version 2.4.1 download starts ok.
Thank you so much, @almarklein

**Comment by almarklein** [comment]
Got another similar [report](https://github.com/imageio/imageio-binaries/commit/3104b271c62ae59c1744fee1aec203fb807f7ed3#commitcomment-32161296). To be safe, I restored the files.
