### ISSUE TITLE
Failure to write when using a file for plugins using get_local_filename

### ISSUE THREAD

**Issue by MakarovDi** [imageio/imageio#424]
Hi, 

It's said in the [docs](https://imageio.readthedocs.io/en/stable/userapi.html#imageio.imwrite) that I can use file objects for imread/imwrite functions
but actually it's only true for PIL, so this code 
```python
import imageio
import numpy as np

image = np.random.randint(0, 65535, size=[512, 512], dtype=np.uint16)

with open('test.png', 'wb') as f:
    imageio.imwrite(f, image, format='PNG-FI')
```
creates an empty file without any exception or warning.

It would be great to have the binary streams support like file/BytesIO for FI.

```
imageio: v2.4.1
```

**Comment by almarklein** [comment]
> but actually it's only true for PIL, so this code

It should work for any format. If not it's a bug.  And I can indeed confirm that your example fails.
