### ISSUE TITLE
Spin out freeimage wrapper?

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#432]
We recently spun out our ffmpeg wrapper. For one because it makes it easier for user to install the binaries by pip-installing `imageio-ffmpeg`. If this turns out to work well, we might do the same with freeimage. Then we can get rid of the whole binary-download mechanism too.

**Comment by xkortex** [comment]
+1. Much nicer pattern to deal with in docker builds.

**Comment by FirefoxMetzger** [comment]
@almarklein Old issue, but maybe we can address it soon™. Do you remember what you were thinking when you said that we can depreciate the binary download mechanism? How would installation of the wrapper library work?

**Comment by almarklein** [comment]
The idea is to make a new library (and corrsponding GH repo), something like "imageio-freeimage". This would provide the wrapper code (what now is `plugins/_freeimage.py`. It would put binary wheels on pypi that have the matching freeimage DLL's in them.

Then, for a user to enable freeimage support, she would just `pip install `imageio-freeimage`.

**Comment by FirefoxMetzger** [comment]
Closed in favor of https://github.com/imageio/imageio/issues/809.
