### ISSUE TITLE
Function to return list of readable formats?

### ISSUE THREAD

**Issue by 0x00b1** [imageio/imageio#434]
Is there a function to return a list of readable image or volume formats? Ideally I'd like something that returned something similar to the content on https://imageio.readthedocs.io/en/latest/formats.html. It would also be nice to have a function that tested whether a provided format is readable, e.g. `is_readable(".png")`.

**Comment by 0x00b1** [comment]
Oops! I found `list(imageio.formats)`. Thanks!

**Comment by 0x00b1** [comment]
If a future visitor from Google is looking for the recipe:

```Python
sum([format.extensions for format in imageio.formats], ())
```

**Comment by almarklein** [comment]
Even better, this uses the extension but (in some cases) also inspects the first few bytes of a file.
```py
def is_readable_by_imageio(filename):
   request = imageio.core.Request(filename, "ri")
   for f in imageio.formats:
        if f.can_read(request):
            return True
   else:
        return False
```

And this can be reduced to:
```py
request = imageio.core.Request(filename, "ri")
imageio.formats.search_read_format(request)
```
