### ISSUE TITLE
can not open second camera when two camera have same name

### ISSUE THREAD

**Issue by One-sixth** [imageio/imageio#441]
My system is windows 10.  
I have two camera. It have same name 'USB Camera'.  
I will get an error when I execute the following command.  
```
cam1 = imageio.get_reader('<video0>')
cam2 = imageio.get_reader('<video1>')
```
I found the problem because the first names of the two cameras are the same, and using alternative name to open camera will avoid this problem.  
I think imageio\plugins\ffmpeg.py‘s parse_device_names function needs to be modified to use alternative name.

**Comment by One-sixth** [comment]
My currently solution.  
In file Anaconda3\Lib\site-packages\imageio\plugins\ffmpeg.py  
in line 671, replace  
```
            if in_video_devices and line.startswith('"'):
                device_names.append(line[1:-1])
```
to  
```
            if in_video_devices and line.startswith('Alternative name'):
                device_names.append(line[17:])
```
In file Anaconda3\Lib\site-packages\imageio_ffmpeg\_io.py  
Add line 122，
```
    cmd = [_get_exe()]
    cmd += input_params + ["-i", path]
    cmd += pre_output_params + output_params + ["-"]
```
to  
```
    cmd = [_get_exe()]
    cmd += input_params + ["-i", path]
    cmd += pre_output_params + output_params + ["-"]
    cmd = ' '.join(cmd)
```

**Comment by almarklein** [comment]
> `cmd = ' '.join(cmd)`

I'd rather not do this, but instead escape the arguments as needed. See #466
