### ISSUE TITLE
PPM-FI not creating ASCII output

### ISSUE THREAD

**Issue by ttobsen** [imageio/imageio#445]
When ssing the PPM-FI format string, no ASCII output is created.

```python
imageio.imwrite(path, image_data, "PPM-FI")
```

Produces for example

```
P6
200 100
65535
<binary data>
```

This is the expected behavior when using PPMRAW-FI. The expected ASCII output would be something like 

```
P3
200 100
65535
1 2 3 4 5 6 ...
```

**Comment by almarklein** [comment]
I don't have experience with this file format specifically. Could it be an upstream bug in FreeImage?

**Comment by ttobsen** [comment]
Yes this is possible, but I can't tell where exactly the problem is.

I'm not the best Python developer, so I couldn't get through the imageio code, to see if it really calls FreeImage with the correct mode.

Can you have a look in it and give some feedback? If it seems that the bug is in FreeImage, I would start to look there. FreeImage is written in C, this is much easier for me to understand. :-)

**Comment by ttobsen** [comment]
Ok, I've just made a small test within FreeImage and I can reproduce the problem there. This snippet

```c++
#include <iostream>
#include "FreeImage.h"

#define WIDTH 800
#define HEIGHT 600
#define BPP 24

int main() {

	std::cout << "Let's see if FreeImage is working" << std::endl << std::endl;
	
	FreeImage_Initialise();

	std::cout << "FreeImage: " << FreeImage_GetVersion() << std::endl;
	std::cout << FreeImage_GetCopyrightMessage() << std::endl << std::endl;
	
	std::cout << "Let's do something useful" << std::endl << std::endl;
	
	FIBITMAP* bitmap = FreeImage_Allocate(WIDTH, HEIGHT, BPP);
	RGBQUAD color;
	
	for (int i=0; i<WIDTH; i++) {
		for (int j=0; j<HEIGHT; j++) {
			color.rgbRed = 0;
			color.rgbGreen = (double)i / WIDTH * 255.0;
			color.rgbBlue = (double)j / HEIGHT * 255.0;
			FreeImage_SetPixelColor(bitmap, i, j, &color);
		}
	}

	if (FreeImage_Save(FIF_PPMRAW, bitmap, "raw.ppm", 0))
		std::cout << "Image successfully saved!" << std::endl;
	
	if (FreeImage_Save(FIF_PPM, bitmap, "ascii.ppm", 0))
		std::cout << "Image successfully saved!" << std::endl;
	
	FreeImage_DeInitialise();
	
	return 0;
	
}
```
produces the same RAW image with FIF_PPMRAW and FIF_PPM.

I will forward this problem to the FreeImage people. Thanks a lot for guess @almarklein, now I'm on the right road to get a fix. :+1:

**Comment by ttobsen** [comment]
After some more research, I found out that the format specifier is not enough. Also a flag needs to be set

```c++
	if (FreeImage_Save(FIF_PPMRAW, bitmap, "raw.ppm", PNM_SAVE_RAW))
		std::cout << "Image successfully saved!" << std::endl;
	
	if (FreeImage_Save(FIF_PPM, bitmap, "ascii.ppm", PNM_SAVE_ASCII))
		std::cout << "Image successfully saved!" << std::endl;
```
is it possible to pass the `PNM_SAVE_ASCII` flag (which is equal to 1) with the `imwrite` method?

**Comment by almarklein** [comment]
Thanks for diving into this!

So is this properly documented in the FreeImage documentation?

**Comment by ttobsen** [comment]
As far as I could see, it's not documented like it should (at least in my opinion). The flags are specified, but not that they are mandatory.

So the FreeImage lib should either drop the support of this flag or the support of the two different PPM format specifiers. To me it makes no sense that FIF_PPM is only working with PNM_SAVE_ASCII. Maybe its an historically artefact due PPM files aren't used very often. :wink: 

See https://sourceforge.net/p/freeimage/bugs/293/ for reference.

**Comment by almarklein** [comment]
We could document this behavior in imageio so that it is visible here: https://imageio.readthedocs.io/en/stable/format_pgmraw-fi.html

Though given the relatively few users, perhaps this issue is enough (and hopefully it will get fixed in FreeImage).

**Comment by ttobsen** [comment]
Yes, this would be great! If you guide me to the file which needs to be updated, I can open a merge request with the updated docs. Before, I would make a few tests to ensure that the doc update is valid.

On the other hand, to put it in the words of a famous German politician: Es ist besser nicht zu dokumentieren, als falsch zu dokumentieren. :wink:

**Comment by almarklein** [comment]
Have a look at `imageio/plugins/freeimage.py` and see how we create subclasses for e.g. png. You can make a very small subclass for PPM and or PPM-raw so that it gets a custom docstring instead of the general Freeimage docstring. Then add an entry in `SPECIAL_CLASSES`. That should be it :)

**Comment by ttobsen** [comment]
Thanks for your help. I've opened a new PR. :-)
