### ISSUE TITLE
Output is speed up

### ISSUE THREAD

**Issue by cyanidee** [imageio/imageio#446]
My code:
```py
from datetime import datetime

import time
import numpy as np
import imageio

start = datetime.now()
end = start.replace(second=start.second + 15)
writer = imageio.get_writer('output.mp4', mode='I', fps=60)
data = np.random.uniform(0, 255, (1280, 720, 3))

while datetime.now() < end:
    time.sleep(1.0 / 60.0)
    writer.append_data(data)

writer.close()
```

I expect this to be 15 seconds long at 60 frames per second. Instead we get 2 second long file at 60 frames per second. Tried with data that is constantly changing - the output is just speed up.

**Comment by almarklein** [comment]
I'm not surprised that you don't get *exactly* 15 seconds, but 2s is a bit small. What about doing
```py
for i in range(60*16):
    ...
```

**Comment by almarklein** [comment]
On second thought, I suspect that since all frames are the same, ffmpeg is using a single keyframe or something, which may be affecting the duration of the movie. Ffmpeg can be weird like that.

**Comment by almarklein** [comment]
Closing, as this can probably be attributed to having the same data written for each frame.
