### ISSUE TITLE
TypeError: unexpected keyword argument: pilmode for tif files

### ISSUE THREAD

**Issue by magnusja** [imageio/imageio#448]
```
(pid=18670) Traceback (most recent call last):
(pid=18670)   File "/home/magnus/.cache/pypoetry/virtualenvs/training-py3.6/lib/python3.6/site-packages/imageio/core/functions.py", line 143, in get_reader
(pid=18670)     return format.get_reader(request)
(pid=18670) TypeError: unexpected keyword argument: pilmode
```

**Comment by almarklein** [comment]
What version of imageio are you using, and how did you call imageio?

**Comment by magnusja** [comment]
```py
>>> imageio.__version__
'2.5.0'

```

```py
def read(self, path: str) -> np.ndarray:
        """Reads the datapoint as an image from an absolute path."""
        return imageio.imread(path, pilmode="RGB")
```

**Comment by almarklein** [comment]
`pilmode` only works with the pillow plugin. The title suggests that you're reading a tiff file, which is probably handled by the tifffile plugin.

**Comment by magnusja** [comment]
Yes that is the problem. But I feel like the API should be consistent regardless of the backend which is used to actually read the file. Otherwise I need to distinguish between tif and other image files which is a little annoying. 
I also do not understand why you are not using Pillow for tif files as well?

**Comment by almarklein** [comment]
> I feel like the API should be consistent regardless of the backend

The thing is that each plugin exposes different options, which is impossible (or at the least very impractical) to generalize over.

> I also do not understand why you are not using Pillow for tif files as well?

Because Tifffile is more powerful. Tiff is a weird format with a lot of use-cases. Pillow only handles the simpler cases correctly.

**Comment by magnusja** [comment]
> > I feel like the API should be consistent regardless of the backend
> 
> The thing is that each plugin exposes different options, which is impossible (or at the least very impractical) to generalize over.
> 

Well this is in some sense true, but then I can also just use the plugins directly and there is no real need for you library right?

> > I also do not understand why you are not using Pillow for tif files as well?
> 
> Because Tifffile is more powerful. Tiff is a weird format with a lot of use-cases. Pillow only handles the simpler cases correctly.

I see. So how can I get the `pilmode="RGB"` for tif files?

**Comment by almarklein** [comment]
> > > I feel like the API should be consistent regardless of the backend
> > 
> > The thing is that each plugin exposes different options, which is impossible (or at the least very impractical) to generalize over.
> 
> Well this is in some sense true, but then I can also just use the plugins directly and there is no real need for you library right?

To some extend this is true, though imageio still provides a unified API to all those plugins. It's only that the arguments are specific to each plugin. These are documented mostly [here](https://imageio.readthedocs.io/en/stable/formats.html).

> So what is the equivalent pilmode="RGB" for tif files?

https://imageio.readthedocs.io/en/stable/format_tiff.html#metadata-for-writing
https://www.lfd.uci.edu/~gohlke/code/tifffile.py.html

**Comment by almarklein** [comment]
BTW, these meta args should be given per-image:
```py
with imageio.get_writer('myfile.tiff') as w:
    w.append_data(im, {'photometric ':'rgb'})
```

**Comment by mathieuboudreau** [comment]
I'm encountering this error, and this discussion did not resolve my issue. 

In ImageIO's documentation here (https://imageio.readthedocs.io/en/stable/format_tiff-pil.html), it clearly suggests that `pilmode` should be a useable option for tif files; what gives?

**Comment by almarklein** [comment]
@mathieuboudreau The default plugin for Tiff is [this one](https://imageio.readthedocs.io/en/stable/format_tiff.html). To use the Pillow functionality, use `format='tiff-pil'`.

**Comment by mathieuboudreau** [comment]
Great - that resolves it, thanks!

**Comment by coddiw0mple** [comment]
For any future readers, I was getting an error as : 

TypeError: _open() got an unexpected keyword argument 'pilmode'

Upon adding format='tiff-pil', I then had: 

SyntaxError: not a TIFF file (header b'\xff\xd8\xff\xe0\x00\x10JF' not valid)

Simply removing the pilmode argument resolved it for me

**Comment by FirefoxMetzger** [comment]
If I read this correctly, this question has been answered. I'm closing the issue, but if there is more need for clarification feel free to comment.

The resolution here is: `pilmode` is only available when using the pillow backend, however TIFF is read using tifffile by default (because tifffile is more competent when it comes to TIFF). `pilmode` is a pillow-specific keyword argument and not supported by tifffile. To use pillow to read tiff use

```python
iio.imread("fancy.tif", format="TIFF-PIL")
```
