### ISSUE TITLE
Read TIF 3D from ImageJ

### ISSUE THREAD

**Issue by paulojamorim** [imageio/imageio#449]
Hi all,

I tried read a 3D TIF generated by ImageJ software but it open only first slice. The skimage io open all slices.

I created a black image with 20 slices (400x400) in ImageJ to test: https://mega.nz/#!RDwi1Y7L!5kvIf7KukB6G2bfupznzbdMuVvENgx96o-AZ_UPB_iU

```
img = imageio.imread('./imagej_file_sample.tif')
print(img.shape)
(400, 400)
```

Using skimage.io
```
from skimage import io
img = io.imread('./imagej_file_sample.tif')
print(img.shape)
(20, 400, 400)
```

Thanks in advance,
Paulo Amorim

**Comment by almarklein** [comment]
That's because you asked for a single image :) use `imageio.mimread()` instead.

**Comment by almarklein** [comment]
Or `imageio.volread()`, depending on semantics.
