### ISSUE TITLE
replace cameraman image due to an uncertain rights?

### ISSUE THREAD

**Issue by sciunto** [imageio/imageio#452]
See [scikit-image/scikit-image#3927](https://github.com/scikit-image/scikit-image/issues/3927) and https://github.com/PyWavelets/pywt/issues/500

**Comment by almarklein** [comment]
Thanks for the heads-up! Let's see what image the scikit-image team comes up with to replace it with :)

**Comment by almarklein** [comment]
There is now a confirmation in that the cameraman is not compatible with the way we distribute it, and it must therefore be removed.

**Comment by almarklein** [comment]
Fixed, replaced with the same image as scikit-image.

**Comment by sciunto** [comment]
awesome!
