### ISSUE TITLE
how to use IO flags like JPEG_ACCURATE

### ISSUE THREAD

**Issue by Erhie** [imageio/imageio#457]
Hello,
 please tell me,
where are the IO flags defined.

What should I import to use them?

And finally, how to use them with imread or imwrite?

Thank you for your advice
Erhy

**Comment by almarklein** [comment]
Assuming that you're talking about the Pillow plugin (the default for jpg), that format supports the parameters listed [here](https://imageio.readthedocs.io/en/stable/format_jpeg-pil.html#jpeg-pil)

**Comment by Erhie** [comment]
thank you so much!
Erhy
