### ISSUE TITLE
How to use metadata ?

### ISSUE THREAD

**Issue by romain7594** [imageio/imageio#463]
I want to use metadata to write a tiff file such as described here : https://imageio.readthedocs.io/en/stable/format_tiff.html#metadata-for-writing.

I tried this : `imageio.mimwrite("test", imagelist, format=".tiff", compress=9)` but it said that compress is an unexpected argument.

Any ideas ?

**Comment by almarklein** [comment]
These are arguments for the meta data, and need to be set using the write object. Something like this:
```py
import imageio

im = imageio.imread('imageio:chelsea.png')
imagelist = [im, im]

with imageio.get_writer("test", format=".tiff") as writer:
    writer.set_meta_data({"compress": 9})
    for im in imagelist:
        writer.append_data(im)
```

We are aware that the handling of meta data is sub optimal, and we are thinking of ways to improve that ....
