### ISSUE TITLE
slow import

### ISSUE THREAD

**Issue by benjimin** [imageio/imageio#464]
Why is `imageio` slow to import?
```python
import time
t = time.perf_counter()
import imageio
print(time.perf_counter() - t)
```
I'm finding that `imageio` (tested 2.5.0 on python 3.6) takes around one full second to import, which is several times longer than `rasterio` or `numpy` and hundreds of times slower than `PIL` (Pillow). Has anyone recently profiled `import imageio`? Just briefly:

```python
import time, builtins
orig = builtins.__import__
def profiler(name, glob=None, loc=None, fromlist=None, level=0):
    t = time.perf_counter() 
    r = orig(name, glob, loc, fromlist, level)
    print(time.perf_counter() - t, name)
    return r
builtins.__import__ = profiler
import imageio
```

```bash
$ python quick.py | sort -g | tail
0.10757197719067335 numpy
0.8292381973005831 pkg_resources
0.9597033429890871 util
0.9634586442261934 core
0.9866004879586399 imageio
```
Surprisingly, the plugins seem not to be the cause. The cause is that `imageio` is using `pkg_resources`, despite that this has been deprecated (in favour of `importlib.resources` and its backport `importlib_resources`) due to widely-documented performance shortcomings.

**Comment by almarklein** [comment]
This has been fixed in https://github.com/imageio/imageio/pull/462

Thanks for reporting though!
