### ISSUE TITLE
spe plugin fails on spe3 files with dtype uint32

### ISSUE THREAD

**Issue by dscran** [imageio/imageio#474]
imageio.__version__
    '2.5.0'

SPE3 has introduced uint32 as a new choice for data type. It is denoted by the value "8" at the respective datatype byte position in the file header. Currently, loading such SPE3 files fails with an

    IndexError: list index out of range

as it tries to access index 8 in the 5-entry list of dtypes in Spec.dtypes:

    dtypes = [
        np.dtype("<f"),
        np.dtype("<i"),
        np.dtype("<h"),
        np.dtype("<H"),
        np.dtype("<I"),
        ]

changing Spec.dtypes into a dictionary, including an entry for uint32 solves this:

    dtypes = {
            0: np.dtype(np.float32),
            1: np.dtype(np.int32),
            2: np.dtype(np.int16),
            3: np.dtype(np.uint16),
            8: np.dtype(np.uint32),
            }

I attached the output of

    patch -u <spe_orig.py> <spe_patched.py>

Cheers,

Michael

[spe_patch.txt](https://github.com/imageio/imageio/files/3573924/spe_patch.txt)

**Comment by almarklein** [comment]
Thanks for looking into this and providing a solution! Would you mind providing that patch in the form of a PR please?
