### ISSUE TITLE
warning when reading png palette image with transparency

### ISSUE THREAD

**Issue by anntzer** [imageio/imageio#475]
The following image was generated by dvipng (actually, invoked via matplotlib's usetex mode):
![palettetransparency](https://user-images.githubusercontent.com/1322974/64266126-5dc5bd80-cf34-11e9-9869-1840ed9636e0.png)
It's a png image with palette and transparency (see also http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.2).  Loading it with imageio yields a warning:
```
/usr/lib/python3.7/site-packages/PIL/Image.py:993: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
```
My guess is that, as the warning says, such images should be converted to RGBA rather than L?

**Comment by almarklein** [comment]
The function that checks whether a palette looks like grayscale does not take available alpha info into account. Fixed in #478
