### ISSUE TITLE
error reading pathlib Path object when axis 2 is greater than 3, an axis gets dropped on read

### ISSUE THREAD

**Issue by rbavery** [imageio/imageio#476]
I'm moving this issue over here from scikit-image: https://github.com/scikit-image/scikit-image/issues/4138

See this example, axis 0 or 1 gets dropped when reading with imageio

```python
import imageio as io 
import numpy as np 
import skimage.io as skio 
from pathlib import Path 
arr = np.ones((512, 512, 30)) 

skio.imsave("test.tif", arr) 

io.imread(Path("test.tif")).shape    
```

If we read using a string instead of a Path object, then the array is read correctly

**Comment by almarklein** [comment]
This is not because of the `Path` object - I get the same result when using a plain `str`. The thing is that to read a 30-layer image, you must use `imageio.volread()`. When using `imread()`, imageio assumes that you want a single image (NxM grayscale, MxMx3 RGB or NxMx4 RGBA).

**Comment by rbavery** [comment]
Got it thanks, I've noted this in the original issue at scikit-image.
