### ISSUE TITLE
Possibility/plans to write GIFs with an alpha layer ?

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#48]
I have seen in the docs that it is not possible right now, and I played a little bit with it but it is still unclear to me if it is a limitation of freeimage, or just not implemented yet.

**Comment by almarklein** [comment]
We should try again with Pillows gif writer.

**Comment by almarklein** [comment]
I tried with Pillow, but it keeps producing RGB palettes instead of RGBA. I spend more time on than this ancient format is worth :)  So from my end this is a wontfix. (Though I am open for PR's that address this issue.)

**Comment by almarklein** [comment]
Maybe via  #220

**Comment by FirefoxMetzger** [comment]
Closed in favor of #360 .

The original question for free-image, which doesn't support alpha/transparency in GIF, this issue has been identified as a won't fix. If there is a particular need to support transparent GIF via free-image, please create a new issue that can be titled and tagged appropriately.
