### ISSUE TITLE
ImageIO 2.6.0 is breaking with Python 2.7.

### ISSUE THREAD

**Issue by KelSolaar** [imageio/imageio#485]
Hi,

So my unit tests just started to break tonight with Python 2.7, culprit being using the `exist_ok` argument with `os.makedirs` which does not exist on Python 2.7: https://github.com/colour-science/colour/commit/c5fae5deebe87f894bf1d45fdf3d6783bed03512/checks#step:6:129

I think it would be fine if the 2.6.0 version had been tagged Python 3.x only but this is not the case and it is picked up by Pip (and Poetry):

```
(test) Kali:~ kelsolaar$ pip install imageio
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting imageio
  Downloading https://files.pythonhosted.org/packages/d3/cc/e7a58cab7dff2efbfaa6216e372ae9f56a066d80908d848949427aa0f168/imageio-2.6.0.tar.gz (3.4MB)
[...]
```

I guess that if the intent is to drop Python 2.7 support now, it would be good to have the latest available build for it in a working state.

Cheers,

Thomas

**Comment by almarklein** [comment]
Thanks for reporting. imageio 2.6.0 is intended to be the last release to support Python 2.7, so this is indeed a bug. I guess we'll also have a v2.6.1 then :)

**Comment by KelSolaar** [comment]
Thanks @almarklein! That would be appreciated :]

**Comment by almarklein** [comment]
Fixed and re-released.

**Comment by KelSolaar** [comment]
Awesome thanks, I kicked a build it worked!

**Comment by almarklein** [comment]
Thanks again for the catch :)
