### ISSUE TITLE
imageio.imread DICOM file meta not having few parameters

### ISSUE THREAD

**Issue by bhavesh0009** [imageio/imageio#486]
Loading pydicom images from following Kaggle competition:
https://www.kaggle.com/c/rsna-intracranial-hemorrhage-detection

While reading from pydicom it is showing Window Center and Window Width
```
import pydicom
pdim = pydicom.read_file(train_dir + 'ID_63eb1e259.dcm')

pdim
```
(0008, 0018) SOP Instance UID                    UI: ID_63eb1e259
(0008, 0060) Modality                            CS: 'CT'
(0010, 0020) Patient ID                          LO: 'ID_a449357f'
(0020, 000d) Study Instance UID                  UI: ID_62d125e5b2
(0020, 000e) Series Instance UID                 UI: ID_0be5c0d1b3
(0020, 0010) Study ID                            SH: ''
(0020, 0032) Image Position (Patient)            DS: ['-125', '-8', '180.199951']
(0020, 0037) Image Orientation (Patient)         DS: ['1', '0', '0', '0', '1', '0']
(0028, 0002) Samples per Pixel                   US: 1
(0028, 0004) Photometric Interpretation          CS: 'MONOCHROME2'
(0028, 0010) Rows                                US: 512
(0028, 0011) Columns                             US: 512
(0028, 0030) Pixel Spacing                       DS: ['0.48828125', '0.48828125']
(0028, 0100) Bits Allocated                      US: 16
(0028, 0101) Bits Stored                         US: 12
(0028, 0102) High Bit                            US: 11
(0028, 0103) Pixel Representation                US: 0
(0028, 1050) Window Center                       DS: ['00036', '00036']
(0028, 1051) Window Width                        DS: ['00080', '00080']
(0028, 1052) Rescale Intercept                   DS: "-1024"
(0028, 1053) Rescale Slope                       DS: "1"
(7fe0, 0010) Pixel Data                          OW: Array of 524288 elements

However while reading same file from imageio, it is not showing these parameters.
```
train_dir = '../input/rsna-intracranial-hemorrhage-detection/stage_1_train_images/'
im = imageio.imread(train_dir + 'ID_63eb1e259.dcm')
im.meta
```

Dict([('TransferSyntaxUID', '1.2.840.10008.1.2'),
      ('SOPInstanceUID', 'ID_63eb1e259'),
      ('Modality', 'CT'),
      ('PatientID', 'ID_a449357f'),
      ('StudyInstanceUID', 'ID_62d125e5b2'),
      ('SeriesInstanceUID', 'ID_0be5c0d1b3'),
      ('ImagePositionPatient', (-125.0, -8.0, 180.199951)),
      ('ImageOrientationPatient', (1.0, 0.0, 0.0, 0.0, 1.0, 0.0)),
      ('SamplesPerPixel', 1),
      ('Rows', 512),
      ('Columns', 512),
      ('PixelSpacing', (0.48828125, 0.48828125)),
      ('BitsAllocated', 16),
      ('BitsStored', 12),
      ('HighBit', 11),
      ('PixelRepresentation', 0),
      ('RescaleIntercept', -1024.0),
      ('RescaleSlope', 1.0),
      ('PixelData',
       b'Data converted to numpy array, raw data removed to preserve memory'),
      ('shape', (512, 512)),
      ('sampling', (0.48828125, 0.48828125))])

**Comment by almarklein** [comment]
This is because imageio's Dicom support is quite "lightweight". It defines a dictionary of keys that it supports: https://github.com/imageio/imageio/blob/master/imageio/plugins/_dicom.py#L29

**Comment by almarklein** [comment]
I'd welcome a PR that adds some more parameters. But for full support you'd have to use pydicom.
