### ISSUE TITLE
Imwrite limits

### ISSUE THREAD

**Issue by kunguz** [imageio/imageio#487]
I am wondering if there is any means to set maximum and minimum for an imwrite operation. 

Say I have a Numpy array with values ranging from minus something to plus something, can I save it to the disk as a PNG using `imageio` in a way where max or min are different than the range given in a Numpy array. 

To be more specific, say I have values 0-10, but I want to force it save in a way as if I have an array with values ranging from 0-50. Therefore, 10 will lead to 51 in the PNG rather than 255 in a 8-bit PNG.

**Comment by almarklein** [comment]
Yes, if you want full control, provide the image as a `uint8` array, and imageio will use the values as is. The full decision tree regarding conversion of image values depending on the data type is here: https://github.com/imageio/imageio/blob/master/imageio/core/util.py#L45
