### ISSUE TITLE
Get_reader hangs randomly

### ISSUE THREAD

**Issue by eXpensia** [imageio/imageio#489]
Hello,
I am using ubuntu and installed imageio and ffpeg imageio from pip
I'm trying to compute the median of an mp4 movie, i read some images long the movie to then take the median.
for example:
```
n=50
vid = get_reader("path/to/video.mp4")
size = (n, 500, 500)
buf = np.empty(size, dtype=np.uint8)
for i, k in enumerate(
    (np.arange(1, self.number, self.number // (n - 1)))
):
    buf[k, :, :] = vid.get_data(k)[:, :, 1])
    print(k)

background = np.median(buf, axis=0)
```

I then get the output :

```
1
3197
6393
9589
...
118253
121449
```
It then hangs at k = 121449.

if i rerun another time it stops at differents k, i tried on two different computers and got the same issue.

The funny thing is that when i tried to launch the program in battery saving mode it took more time per image but it worked...

**Comment by almarklein** [comment]
This looks similar to https://github.com/imageio/imageio-ffmpeg/issues/17. I don't have time to dive into it now, but when I do I'll also take your case into account. Thanks!

**Comment by eXpensia** [comment]
I'd like to add that this the get_next_data method it never hangs !

**Comment by almarklein** [comment]
This is probably fixed with the new version of imageio-ffmpeg. Closing. Please re-open if the problem persist.
