### ISSUE TITLE
UnsupportedOperation seek while reading GIF from HTTP uri

### ISSUE THREAD

**Issue by timothybrooks** [imageio/imageio#505]
Related to:
https://github.com/imageio/imageio/issues/202
https://github.com/imageio/imageio/issues/238
https://github.com/imageio/imageio/issues/335

Reading GIF images from a HTTP fails with `"UnsupportedOperation: seek"`

For example, try running:
```im = imageio.mimread('http://media.giphy.com/media/3oD3YveOJWdwIAfZ5e/giphy.gif')```

Python 3.7.6
Imageio 2.6.1
Pillow 7.0.0

**Comment by almarklein** [comment]
This is a recurring issue. I'm tempted to say that since pillow needs seek for gif, we can't support http for it. But maybe we should bite the bullet and provide a buffer object that caches read data and does provide seek.

**Comment by almarklein** [comment]
Done!
