### ISSUE TITLE
Unable to save image as uint16

### ISSUE THREAD

**Issue by Sentient07** [imageio/imageio#507]
Hi,

I am trying to save an array of `uint16` as a 16-bit grayscale PNG. However, `imageio` converts to `uint8` before saving it.

Code : 

```
imageio.imsave("test.png", np.ones((480, 640)).astype(np.uint16))
img = imageio.imread("test.png")
print(img.dtype)
```

Expected Output: `uint16`
Current Output : `uint8` 
imageio version : `2.6.1`

For others facing this issue : following this  [comment](https://github.com/python-pillow/Pillow/issues/2970#issuecomment-395477584), I get the desired output

**Comment by Sentient07** [comment]
An additional note,

I think `imageio` reads the value of the content of the array rather than its `dtype` before saving. I am not sure if this is the desired behaviour or a bug. 

```

In [8]: imageio.imsave("test.png", (np.ones((480, 640))*1000).astype(np.uint16))                                                                  

In [9]: img = imageio.imread("test.png")                                                                                                          

In [10]: img.dtype                                                                                                                                
Out[10]: dtype('uint16')

In [11]: imageio.imsave("test.png", (np.ones((480, 640))*100).astype(np.uint16))                                                                  

In [12]: img = imageio.imread("test.png")                                                                                                         

In [13]: img.dtype                                                                                                                                
Out[13]: dtype('uint8')
```

**Comment by almarklein** [comment]
See the `prefer_uint8` parameter in https://imageio.readthedocs.io/en/stable/format_png-pil.html. So yeah, it's a "feature" for backwards compatibility.
