### ISSUE TITLE
Tests related to "Avbin" are failing on aarch64.

### ISSUE THREAD

**Issue by Ross1503** [imageio/imageio#508]
While testing "imageio" on aarch64 platform, tests related to "Avbin" are failing as "Avbin" binary is not available for aarch64. I've Built "Avbin" locally on aarch64 platform, but now i'm getting  following error:
`ZeroDivisionError: float division by zero`
below is the source code code, where i'm getting above error:
`self._meta["fps"] = float(info.u.video.frame_rate_num) / float(info.u.video.frame_rate_den)`
as we are getting **info.u.video.frame_rate_den** = 0.
Not sure whether the issue is with locally built "Avbin" binary or something related to Imageio code.

**Comment by almarklein** [comment]
Avbin has been sort of deprecated. I'm now completely removing support in #511.
