### ISSUE TITLE
Support specific extension for temporary file

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#509]
Related issue: https://github.com/imageio/imageio-ffmpeg/issues/28; this would make it possible to "write video to memory" using ffmpeg. Change to be made about [here](https://github.com/imageio/imageio/blob/master/imageio/core/request.py#L349)

**Comment by almarklein** [comment]
The original question in https://github.com/imageio/imageio-ffmpeg/issues/28 was to stream video to a file like object. This won't allow that, because first the whole file must be written. Therefore I've marked this as wontfix until there's a better use-case.

**Comment by FirefoxMetzger** [comment]
Since this issue won't be fixed, I will close it. If there is a more specific use-case about this in the future, I'll be happy to discuss it in a new issue.
