### ISSUE TITLE
Pip is unable to resolve to correct version of imageio for Python2

### ISSUE THREAD

**Issue by zhanwu** [imageio/imageio#515]
Trying to install imageio via pip for Python2 and failed with following error message:

```
(p2) ~$ python2 -m pip install imageio
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting imageio
  Using cached imageio-2.8.0.tar.gz (3.3 MB)
ERROR: Package 'imageio' requires a different Python: 2.7.17 not in '>=3.5'
(p2) ~$ 
```

Pip mistakenly consider `imageio-2.8.0.tar.gz` as a installation candidate for Python2 because there is no `data-requires-python` attributes defined for its URL in pypi:
![Screenshot from 2020-02-19 10-54-33](https://user-images.githubusercontent.com/488359/74880902-22238200-5321-11ea-905d-6362a17a4f02.png)

Pinning the version would resolve the issue so it's not very critical

**Comment by Adam-Braincorp** [comment]
Just ran into this myself, my build worked fine yesterday, broken today

**Comment by almarklein** [comment]
I'd think the `python_requires=">=3.5",` would prevent this sort of thing ... I google'd `data-requires-python` a bit, but as far as I can tell it's a flag that the Pypi server should mirror from `python_requires`, right? Or is there something I can do?

**Comment by almarklein** [comment]
But anyway, pinning to `2.6.x` for Python 2 projects is probably the best way regardless, as it's the last release to support Python 2.

**Comment by zhanwu** [comment]
> I'd think the `python_requires=">=3.5",` would prevent this sort of thing ... I google'd `data-requires-python` a bit, but as far as I can tell it's a flag that the Pypi server should mirror from `python_requires`, right? Or is there something I can do?

I also assume that `python_requires=">=3.5"` should be sufficient. And I tried to upload (using twine) `imageio` to our private artifactory, which has `data-requires-python` correctly populated.

It could be a behavior controlled by pypi.org on the server-side, which I don't really have experience with. But I do see some other packages (e.g. numpy) with the `data-requires-python` in pypi.org.
