### ISSUE TITLE
Tests are failing on aarch64

### ISSUE THREAD

**Issue by odidev** [imageio/imageio#516]
Hi,
I am trying to add arm64 jobs for Travis-CI. I have two queries here:
1. Tests related to ffmpeg are getting failed on arm64 platform, actually it is not able to find "ffmpeg" binary in imageio_ffmpeg module. But in case of amd64 it is working as expected, though it is working on arm64 as well when i install it using "apt-get install ffmpeg". 1 test case is failing as we are installing "ffmpeg" separately using apt, where it is unable to get ffmpeg path. May I know why we need to install ffmpeg seperately for arm64 platform.
2. The dependencies which we are installing in case of “TEST_FULL=1” are optional and does not make any difference after installation as well, same number of test cases are running if we don’t install them.
May I know the importance of setting  “Test_full=1” and install those optional dependencies.

**Comment by almarklein** [comment]
1: imageio-ffmpeg provides binary wheels for Linux X86_64. So for Linuxes that do not match manylinux2010, are 32bit, or are ARM, one needs to install ffmpeg separately.

2: The same number of tests are running, but some tests are skipped if `simpleitk`  or `astropy` are not available.

**Comment by odidev** [comment]
Hi @almarklein ,
Thanks for the quick response.
1. Even after downloading "ffmpeg" separatly using apt-get, two test cases are getting failed in Travis-CI. Though locally it is working fine and all the tests are passing.
 here are the details of error::
`=================================== FAILURES ===================================
____________________________ test_get_exe_installed ____________________________
    def test_get_exe_installed():
        import imageio_ffmpeg
        # backup any user-defined path
        if "IMAGEIO_FFMPEG_EXE" in os.environ:
            oldpath = os.environ["IMAGEIO_FFMPEG_EXE"]
        else:
            oldpath = ""
        # Test if download works
        os.environ["IMAGEIO_FFMPEG_EXE"] = ""
        path = imageio_ffmpeg.get_ffmpeg_exe()
        #path = "/usr/bin/ffmpeg"
        # cleanup
        os.environ.pop("IMAGEIO_FFMPEG_EXE")
        if oldpath:
            os.environ["IMAGEIO_FFMPEG_EXE"] = oldpath
        print(path)
>       assert os.path.isfile(path)
E       AssertionError: assert False
E        +  where False = <function isfile at 0xffff7fc59e60>('ffmpeg')
E        +    where <function isfile at 0xffff7fc59e60> = <module 'posixpath' from '/home/travis/virtualenv/python3.7.5/lib/python3.7/posixpath.py'>.isfile
E        +      where <module 'posixpath' from '/home/travis/virtualenv/python3.7.5/lib/python3.7/posixpath.py'> = os.path
tests/test_ffmpeg.py:59: AssertionError
----------------------------- Captured stdout call -----------------------------
ffmpeg
______________________________ test_overload_fps _______________________________
    def test_overload_fps():
    
        need_internet()
    
        # Native
        r = imageio.get_reader("imageio:cockatoo.mp4")
        print(r)
        assert r.count_frames() == 280  # native
        assert int(r._meta["fps"] * r._meta["duration"] + 0.5) == 280
        ims = [im for im in r]
>       assert len(ims) == 280
E       assert 281 == 280
E         -281
E         +280
tests/test_ffmpeg_info.py:64: AssertionError
----------------------------- Captured stdout call -----------------------------
<imageio.plugins.ffmpeg.FfmpegFormat.Reader object at 0xffff7ae40f50>`

Thnaks

**Comment by almarklein** [comment]
`test_get_exe_installed` assumes that imageio-ffmpeg comes with a working binary. So we should find a way to skip that test on systems like yours. Like detecting ARM?

IN the second fail, there is a discrepancy of 1 frame, which is not uncommon between different Python versions. We should allow for a tiny range there, I guess.

PR's welcome for both issues; I would love to see the tests working in other settings :)

**Comment by Ross1503** [comment]
Hi @almarklein,
Thanks for explaining it properly.
In second case, what do you think will be a good value for providing the range? I've tested it with multiple python versions and i am getting 281 frames at max. shall i put just 280 to 281 or something else?

**Comment by odidev** [comment]
Hi @almarklein,
Thanks for explaining it properly.
In second case, what do you think will be a good value for providing the range? I've tested it with multiple python versions and i am getting 281 frames at max. shall i put just 280 to 281 or something else?

**Comment by almarklein** [comment]
I principal think we can consider the test as passed if its 280 +/- 2 or so. But if you see only values of 280 and 281, let's just `assert len(ims) in (280, 281)` :)

**Comment by odidev** [comment]
Hi @almarklein, 
Thanks for your suggestion. I've tested it with the changes suggested by you and now it is working on ARM64 architecture for python version 3.5 & 3.6. but getting cmake build issue for python 3.7 because simpleITK package is using it. If we are building Cmake separately through source, it is taking a lot of time (around 40 min) and also needs administrative permission. so can we skip one test case related to simpleITK for ARM64 platform?
Please let me know your thoughts on same.

**Comment by almarklein** [comment]
> . so can we skip one test case related to simpleITK for ARM64 platform?

Sure. If you're coming with a PR that ads such a skip, please add a note similar to your comment :)

**Comment by almarklein** [comment]
This was closed by #518, right?

**Comment by odidev** [comment]
> This was closed by #518, right?
Yes.
