### ISSUE TITLE
saving gif via libfreeimage dylib causes segfault on os x 10.10

### ISSUE THREAD

**Issue by levskaya** [imageio/imageio#52]
When attempting to save a gif with the automatically downloaded libfreeimage I get a segfault on os x 10.10 with python 2.7.9.

``` python
import imageio
import numpy
im=numpy.zeros((400,400,3))
imageio.imsave('fail.gif',im)
```

lldb trace:

```
* thread #1: tid = 0xa6f3cd, 0x0000000105105eab libfreeimage-3.16.0-osx10.6.dylib`FreeImage_HasPixels + 11, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2a4730)
    frame #0: 0x0000000105105eab libfreeimage-3.16.0-osx10.6.dylib`FreeImage_HasPixels + 11
libfreeimage-3.16.0-osx10.6.dylib`FreeImage_HasPixels + 11:
```

the internal FreeImage_HasPixels function is being passed an incorrect pointer (via first arg in %rdi) to the freeimage bitmap data, since it's often the first function called in freeimage routines, I suspect somehow the bitmap pointer is being mangled somewhere, perhaps by ctypes?

(the same segfault and stack trace occurs if I manually edit the library-searching code to use a locally compiled copy of libfreeimage 3.16.0 from homebrew.)

**Comment by chengxxxxwang** [comment]
hi,my Python crashed when I used it saving an 5M large gif,and give me this msg of crash.
I use pip to install it,and my os is OS X EI Captain 10.11.4 version
