### ISSUE TITLE
how can i get object of each frame if I use imageio_ffmpeg.read_frames？

### ISSUE THREAD

**Issue by CarolinGao** [imageio/imageio#521]
When I use `driving_video = imageio.mimread(opt.driving_video, memtest=False)` , it always throws the exception `imageio.core.format.CannotReadFrameError: Could not read frame 0:
Frame is 0 bytes, but expected 230400.` Instead I use `driving_video = read_frames(opt.driving_video)` , but  I also want to iterate frames and resize each of them, but each frame is type of bytes, how can I get object like the first method that return?
Thank u!

**Comment by almarklein** [comment]
A reader object is an iterable of numpy arrays. See this example:
```py
import imageio

reader = imageio.read("imageio:cockatoo.mp4")
for im in reader:
    print(im.shape)
```

Though the first error might suggest that the video file is corrupt (or not really a video file). What is the extension of filename? You might want to add `format='ffmpeg'` to make sure that the ffmpeg plugin is used.
