### ISSUE TITLE
_tiffile.py SyntaxWarning 

### ISSUE THREAD

**Issue by marxenegls** [imageio/imageio#522]
Setting up python3-imageio (2.4.1-2) ...
/usr/lib/python3/dist-packages/imageio/plugins/_tifffile.py:2813: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is 0:

```py
def __getitem__(self, key):
        """Return specified page(s) from cache or file."""
        pages = self.pages
        if not pages:
            raise IndexError('list index out of range')
        if key is 0:                                                                              * 2813                                         
            return pages[key]

        if isinstance(key, slice):
            start, stop, _ = key.indices(2**31)
            if not self.complete and max(stop, start) > len(pages):
                self._seek(-1)
            return [self[i] for i in range(*key.indices(len(pages)))]

        if self.complete and key >= len(pages):
```

I also noticed two diff tifffile.py and _tifffile.py in the same plugins folder

[_tifffile.txt](https://github.com/imageio/imageio/files/4440141/_tifffile.txt)
[tifffile.txt](https://github.com/imageio/imageio/files/4440143/tifffile.txt)

**Comment by almarklein** [comment]
The `_tifffle.py` is a 3d party module that is included in imageio. The `tifffile.py` is imageio's wrapper for it. So the error is actually in the 3d party code. Fortunately it is also no longer there :)
