### ISSUE TITLE
Slow performance with ffmpeg mkv parsing

### ISSUE THREAD

**Issue by ekcheng** [imageio/imageio#524]
Hello,

Hoping you can help me understand a performance slowdown I am experiencing.

I am using `imageio` to parse frames from a live video stream that I receive as a sequence of ~1-second `mkv` video fragments. Every time a new fragment is read from the stream, its bytes are passed to `imageio` like so:

```
# Create reader out of the bytes of a 1-sec mkv video fragment
reader = imageio.get_reader(io.BytesIO(fragment), 'ffmpeg')
```

Then we process the frames until we run out, create a new reader out of the next fragment in the stream, and repeat.

```
# grab frame from current fragment
im = reader.get_next_data()

# do something 
process(im)

# ... repeat until you run out of frames in the current fragment
```

When I use `imageio` to read the `mkv` stream in this way, it is causing my `process` function to run 4x slower than when I simply pass in an offline `mp4` file to `imageio`.

Is this performance discrepancy (between running on an `mkv` stream rather than an `mp4` file) expected? How might you explain it? Is the cost of creating a new reader for every fragment (and initiating a new subprocess call to `ffmpeg`) causing some sort of context switching or other overhead that would slow down my downstream `process` call so much when compared to just reading from a file? 

Is there a more efficient way to parse a sequence of `mkv` fragments that does not require creating a new reader every fragment?

Much appreciate any insight or advice you could provide on whether I am using the library as efficiently as possible.

Thank you.

**Comment by almarklein** [comment]
The problem is that because of the way that imageio-ffmpeg works, the video needs to be on the file system. (ffmpeg is called in a subprocess and all we can do is pass a filename). So when you give imageio a chunk of data to read video frames from, that data will first be written to disk, where ffmpeg will read it from, and send the frames to Python.

Perhaps this can be sped up using memory mapped files or something similar. But I am not sure if it will work/help and it might depend on your OS whether it does :)

**Comment by ekcheng** [comment]
Hi @almarklein, much appreciate the tip. For what it's worth, it looks as though writing the mkv bytes to disk and parsing them using OpenCV's `VideoCapture` is significantly faster than passing the bytes into `imageio`. Wondering if this is because OpenCV somehow uses ffmpeg under the hood in a more native fashion, without the need to spawn a separate subprocess.

Will let you know if we have any success with memory mapped files. Closing the issue for now. Thanks.

**Comment by almarklein** [comment]
> Wondering if this is because OpenCV somehow uses ffmpeg under the hood in a more native fashion

Yes, it's likely that OpenCV uses ffmpeg as a library. We could have gone with that approach too, but it would make imageio-ffmpeg more complex, harder to maintain, and harder to distribute. You're now running into on of its downsides ...
