### ISSUE TITLE
Colorbar displayed incorrectly when creating Gif

### ISSUE THREAD

**Issue by MHBalsmeier** [imageio/imageio#528]
Hi I want to create a gif test.gif out of 2 pngs 0.png and 1.png with the following code:

import imageio;
gif = [];
gif.append(imageio.imread("0.png"));
gif.append(imageio.imread("1.png"));
imageio.mimsave("test.gif", gif, "GIF", duration = 1);
![0](https://user-images.githubusercontent.com/56491557/82709205-59872f00-9c80-11ea-8271-86d4cfba6836.png)
![1](https://user-images.githubusercontent.com/56491557/82709208-5b50f280-9c80-11ea-9b72-37971be05f00.png)
![test](https://user-images.githubusercontent.com/56491557/82709215-5d1ab600-9c80-11ea-83d7-e4693db1a786.gif)

However the colorbar is displayed incorrectly.
Any suggestions?

**Comment by almarklein** [comment]
This is because the limited amounts of colors available in gif images. It may be worth trying mp4 instead.

**Comment by MHBalsmeier** [comment]
Thanks, that solved  the problem. It is not possible to make an MP4 loop like a gif, right?

**Comment by almarklein** [comment]
> It is not possible to make an MP4 loop like a gif, right?

No, but if you display it on a web-page, you can turn on looping there: https://www.w3schools.com/tags/av_prop_loop.asp

**Comment by MHBalsmeier** [comment]
Ok, thanks.
