### ISSUE TITLE
Imageio  python Heroku read only access error

### ISSUE THREAD

**Issue by hunaidkhan2000** [imageio/imageio#536]
Hi i am deplying a scanner using tesseract and pytesseract. While scanning the file imageio is creating a temp BMP file in the system but due to Heroku's policy of only allowing read only access to the libraries ,I am not able to run my code. I am getting following error. 
 **File "/app/.heroku/python/lib/python3.8/site-packages/imageio/core/request.py", line 328, in get_file
2020-06-29T05:08:44.787037+00:00 app[web.1]:     self._file = open(self.filename, "wb")
2020-06-29T05:08:44.787037+00:00 app[web.1]: OSError: [Errno 30] Read-only file system: '/tmptess_105rvap2.bmp'**

Can you please help me out how can I resolve it or how can I save the image in my personal Temp folder in heroku.  uploading screenshot as well. 

![image](https://user-images.githubusercontent.com/34857371/85980234-a1c40a80-b9ff-11ea-8900-f37efb4cc348.png)

**Comment by almarklein** [comment]
To be honest, this question is a Heroko question. If you don't have access to read the image, there's nothing imageio can do to help. You should make sure to place the image in a folder that you have read-access to. But I am not very familiar with Heroku so I don't know where that would be.
