### ISSUE TITLE
Get GIF from numpy 4d array

### ISSUE THREAD

**Issue by MichelangeloConserva** [imageio/imageio#538]
I d like to produce a GIF from a 4d array. How can I do it using this library?

This is a reproducible example of what I would like to do:
```
import numpy as np
frames = (np.random.rand(100,11,11,3).round() * 220).astype(np.uint8)
```

One way possible that I have found is to locally save the image using matplotlib.
However this is extremely slow.

Another way is the following:
```
frames = (np.random.rand(100,11,11,3).round() * 220).astype(np.uint8)
with imageio.get_writer(os.path.join('images', 'round_{}.gif'.format(0)), mode='I', fps=5) as writer:
    
    dd = imageio.core.util.Dict()
    dd["dpi"] = (72,72)
    
    for t,frame in enumerate(frames):
        img = imageio.core.util.Image(frame.astype(np.uint8), meta = dd)
        writer.append_data(img)
```
This is fast enough however the images in the gif are extremely small and not clearly visible.

**Comment by almarklein** [comment]
This should be the way to go, though you could use just a `dict` instead of imageio's internal `Dict`, and you can use `append_data(frame, dd)` instead of using imageio's internal `Image`.

> This is fast enough however the images in the gif are extremely small and not clearly visible.

Well, the data creates 100 images that are 11x11, which is already quite small indeed :)  note that the GIF format has just 8 bits for colours, which may contribute to the images looking odd, if many different colors are present.

**Comment by MichelangeloConserva** [comment]
I have found a faster and easier way.
I will share it here so that others can benefit as well.

```
import numpy as np
import imageio

frames = (np.random.rand(100,11,11,3).round() * 220).astype(np.uint8)
frames = [frames[i] for i in range(len(frames))]

imageio.mimwrite('output_filename.gif', frames , fps = 60.)
```
The key is that frames should be a list of numpy arrays.

**Comment by almarklein** [comment]
Thanks! Yes, that's nice and short 👍

For completeness, I should mention that the former way that uses `append_data()` is streaming, so it will be more efficient in terms of memory. This could matter if the number of images becomes large.
