### ISSUE TITLE
can read from webcam using python3 idle, cant when running script

### ISSUE THREAD

**Issue by hwilson10** [imageio/imageio#542]
When I open python3 on my raspberry pi 4 command line I can type the following and get an image from my webcam
```
import imageio
cam = imageio.get_reader('<video0>')
image = cam.get_next_data()
imageio.imwrite("newimage.jpg", image)
cam = 0
```

however when I write the exact same thing into a python script (snap.py) and run with python3 ($ python3 snap.py) i get a black image. 

Does anyone have any idea as to what could be the issue here?  Im on a fresh install of the no desktop version of raspbian from the NOOBS packaged with the raspberry pi.

**Comment by almarklein** [comment]
That's odd ... Not sure why this would be. My suggestion would be to apply a for-loop taking e.g. 10 screenshots, and a `time.sleep(1)` between each one.
