### ISSUE TITLE
np.ndarray.tostring() is deprecated, should use tobytes()

### ISSUE THREAD

**Issue by alkasm** [imageio/imageio#545]
As of numpy 1.19.0, the usage of `a.tostring()` raises a `DeprecationWarning` as discussed in the [release notes](https://numpy.org/devdocs/release/1.19.0-notes.html) and the [docs](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tostring.html).

This method is deprecated since the name implies it returns a string, although it returns bytes. The name is simply an alias for `tobytes()`, which is not deprecated. `tobytes()` has been around since numpy 1.9.0, which was released on PyPI in September 2014: https://pypi.org/project/numpy/1.9.0/#history, before `imageio` hit 1.0.

This method is called just a few times in some plugins: https://github.com/imageio/imageio/search?q=tostring%28%29&unscoped_q=tostring%28%29

**Comment by almarklein** [comment]
Fixed. A few references leftin the vendored tifffile plugin. Should update that to the latest version, but it seems its API has changed, because it causes tests to fail ... so leaving that for another day/person ...
