### ISSUE TITLE
[Question] get_reader kwargs docs/example

### ISSUE THREAD

**Issue by JuanFMontesinos** [imageio/imageio#546]
Hi,
I really like this library and I think it's powerful and efficient but it's not very well documented. 
Most of the functions accept kwargs nor formats which aren't really described. So the library ends up becoming a simple reader 

In case of `get_reader` is there any example of what can be done through kwargs¿?

**Comment by almarklein** [comment]
Imageio has a wide range of plugins, which each offer different functionality, specific to the image format and the plugin itself.

The `kwargs` are passed to the formats. See [this page](https://imageio.readthedocs.io/en/stable/formats.html) for all the formats. Each format has docs for the `kwargs` that are accepted.

Perhaps a link to this page could be added to the docs of `get_reader()`, or to the `userapi.html` page. A PR is very welcome :)
