### ISSUE TITLE
 Unable to download 'freeimage-3.15.1-win64.dll'.

### ISSUE THREAD

**Issue by DoubleQ0726** [imageio/imageio#547]
https://github.com/imageio/imageio/blob/master/imageio/core/fetching.py，
in this file line62: _url_root = "https://github.com/imageio/imageio-binaries/raw/master/" is invalidation. 
web page has 404 NOTFOUND error.

**Comment by almarklein** [comment]
The root (https://github.com/imageio/imageio-binaries/raw/master/) is a 404, but the freeimage lib is not:
https://github.com/imageio/imageio-binaries/raw/master/freeimage/FreeImage-3.15.1-win64.dll
