### ISSUE TITLE
Large color change when saving image to video

### ISSUE THREAD

**Issue by isht7** [imageio/imageio#552]
Minimum working example of issue - 
```
import imageio
import numpy as np

root = '/home/idwivedi/Desktop/example/'
img = imageio.imread('https://i.imgur.com/ldWy8Wf.png')
writer = imageio.get_writer(root  + '/video.mp4', fps = 12)
for i in range(24):
    frame = np.concatenate((img,img), axis = 0)
    writer.append_data(frame)
writer.close()
imageio.imwrite(root  + '/image.png',frame)
print ('min, max value of frame', np.max(frame), np.max(frame))
print ('shape, dtype of frame', frame.shape, frame.dtype)
```
The output printed is, 
```
min, max value of frame 229 229
shape, dtype of frame (2160, 1920, 3) uint8
```

The image.png saved looks like this
![image](https://user-images.githubusercontent.com/21278652/93475733-d41e2f00-f8ad-11ea-8f8f-37c12a55bb4e.png)

The video is just this image being repeated several times over. But the video looks like this,
![image](https://user-images.githubusercontent.com/21278652/93475931-0d569f00-f8ae-11ea-86b4-00e049348c40.png)

Why do the above 2 images look so different? Shouldn't they look very similar?

I am running Ubuntu 16.04 with anaconda. This is the [anaconda environment where I ran this file](https://gist.github.com/isht7/e3942ad6092d239a08a3cf985d7d450a).

**Comment by almarklein** [comment]
> Shouldn't they look very similar?

Relatively similar, yes, but you cannot expect the images to be the same :)

PNG is stored as RGB (or RGBA) and video (usually) as HSV or Y'CbCr. So colors will change. It might be possible to tell ffmpeg to use a custom color space (sRGB perhaps?) using an ffmpeg-specific output-param.

**Comment by isht7** [comment]
@almarklein thanks for the reply. My main concern was that if I replace `frame = np.concatenate((img,img), axis = 0)` with `frame = img`, then both the images look very similar. Could you tell why adding this line is causing this change?

**Comment by isht7** [comment]
I see, okay. Do you still think that it is not a bug?

**Comment by almarklein** [comment]
If it were a bug, it would be one in ffmpeg itself. But I don't think it should be considered a bug. Video decoding is weird sometimes, especially for single frames.

**Comment by isht7** [comment]
@almarklein thanks for the reply. Actually, in this scenario, this happened with me when I was using different frames as well. But I replaced the different frames with a single frame to show a minimal reproducible example. 
When I used opencv to write the video, it worked as expected. Is that because opencv does not use ffmpeg?

**Comment by almarklein** [comment]
> opencv does not use ffmpeg?

I don't know. At the least I presume it will use a different encoding ...
