### ISSUE TITLE
volread not reading multi page tifs

### ISSUE THREAD

**Issue by chaplinta** [imageio/imageio#558]
Hi, I'm having an issue with volread where it only reads the first page of tiffs. Please see this example file:

https://www.dropbox.com/s/vob9iwwqzwrsz7s/20201012_17_11_48_344486.1_XYT_ch_1.tif?dl=0

I installed imagio just today and have the latest version, on Ubuntu 18.04. These tif files were created with SciScan on Windows 7 and on that OS imagio seemed to have no problem reading all the pages properly.

I can load the file with another program like ImageJ, re-save the tif and then imagio is fine.

I'm guessing there might be something unusual about the tif files I have? Not sure why it appears to platform dependent.

In the meantime, I can work around it with a mimread and a loop, but if there is a problem I thought you should know.

**Comment by almarklein** [comment]
Thanks for reporting this issue!

Tiff has a notion of series, and apparently `imageio.volread()` will only select data from the first series, becasue `Tifffile.asarray` does this by default. Your data has two series. One containging a single page (i.e. image), and one containing 4649 images. I think that when opening/saving, then theire stores as a single series. 

Any idea why the data might be split up in multiple series?

**Comment by chaplinta** [comment]
Thanks for looking into it.

Not sure about the extra series, maybe it's something to do with the microscopy software. One guess is that it sets the first frame aside in another series because it may not acquire a full image on the first frame - it's acquired with a scanning method (2-photon) the beam may start in some arbitrary position. I will take a closer look to see if I can figure it out.

It seems that mimread() will just read all of the frames across these series, is that right?

**Comment by almarklein** [comment]
> It seems that mimread() will just read all of the frames across these series, is that right?

Yes. And #559 makes `volread()` be more like reading all frames and stacking them together.
