### ISSUE TITLE
Why does imageio produce blurry gif images?

### ISSUE THREAD

**Issue by nbro** [imageio/imageio#566]
I'm trying to produce a gif animation with `imageio` by concatenating NumPy arrays of shape `(4, 4, 3)` that are stored in a list. Here's an example of such an array.

```
[[[ 51 153 255]
  [224 224 224]
  [224 224 224]
  [224 224 224]]

 [[224 224 224]
  [224 224 224]
  [224 224 224]
  [224 224 224]]

 [[224 224 224]
  [224 224 224]
  [224 224 224]
  [224 224 224]]

 [[224 224 224]
  [224 224 224]
  [224 224 224]
  [ 51 255  51]]]
```

The type of these arrays is `uint8`. Typically, I have from 6 to 10 of these arrays, but this is not a big problem. Now, here's an example of such an array plotted with matplotlib's `imshow` (note that the white lines are added with matplotlib, but this is not strictly necessary to do, though it would be nice to have those lines, but I guess that cannot be done with `imageio`).

![myplot](https://user-images.githubusercontent.com/9349000/99320189-58b80a00-286b-11eb-97c7-31090eef3c2c.png)

When I try to produce a `gif` with `imageio` by passing a list of these arrays to `imageio.mimsave("file_name.gif", my_list_of_arrays_like_above, fps=1)`, I don't see a sequence of images like the one above, but a blurred version, like this

<img width="494" alt="Screenshot 2020-11-17 at 00 27 55" src="https://user-images.githubusercontent.com/9349000/99320391-d11ecb00-286b-11eb-9e37-7675ea4d4d21.png">

I want a gif that is just a sequence of images, where each image is like the first image above. How can I achieve that with `imageio`. Note that you can just use my array above to give me an example.

**Comment by almarklein** [comment]
I think that what is hapening is that imshow uses linear interpolation to display the image. You can probably turn that off with a parameter.

**Comment by nbro** [comment]
@almarklein Maybe you did not understand, I want to create a gif (with `imageio`, or something else that does the job) like the image displayed by `imshow`, from one or more arrays like the ones I am sharing with you above. These arrays mostly have numbers `224` (the grey colors) or the numbers corresponding to the green or blue.

**Comment by almarklein** [comment]
Ah, I misread that part, sorry. Nevertheless, whatever application you're using to view the GIF is applying linear interpolation rather than the nearest-neighbour interpolation that you want.

My recommendation would be to upscale the image, e.g. to represent each pixel with 10x10 pixels. You can then even add white lines :)   This requires some numpy tricks, but should not be too hard. You can also perhaps use a function from scikit-image to upscale youre image.

**Comment by nbro** [comment]
@almarklein Can you be more specific about the function I am supposed to use to upscale the image? I was trying to use [rescale](https://scikit-image.org/docs/dev/auto_examples/transform/plot_rescale.html), but it produces a black image. Check this code

```
import matplotlib.pyplot as plt
import numpy as np
from skimage.transform import rescale

image = np.array(
    [[[51, 153, 255],
      [224, 224, 224],
      [224, 224, 224],
      [224, 224, 224]],

     [[224, 224, 224],
      [224, 224, 224],
      [224, 224, 224],
      [224, 224, 224]],

     [[224, 224, 224],
      [224, 224, 224],
      [224, 224, 224],
      [224, 224, 224]],

     [[224, 224, 224],
      [224, 224, 224],
      [224, 224, 224],
      [51, 255, 51]]]
)

image2 = rescale(image, 40.0, anti_aliasing=True, multichannel=True).astype(np.int)
# image2 = rescale(image, 40.0, anti_aliasing=True, multichannel=True)

plt.imshow(image)
plt.imshow(image2)

plt.show()

```

Maybe you're already familiar with the library and know how to do it, so I wouldn't lose a lot of time trying to figure out what's wrong and why it doesn't do what I would it to.
