### ISSUE TITLE
Saving high-quality JPEG ignores quality factor

### ISSUE THREAD

**Issue by btlorch** [imageio/imageio#571]
After storing an image in JPEG format with imageio's imwrite method and quality 100, I was surprised to see that the quantization table of the saved image did not match my expectations, i.e., I would have expected a quantization table with all 1s. This is also the quantization table that Pillow produces for quality 100. The quantization tables also differ for quality factors 96 through 99.
Could someone please check whether I am using the imwrite method in the intended way? Otherwise, I think this might be a bug in imageio.

Here is the code to reproduce this issue:
```python
import imageio
import numpy as np
from PIL import Image
print(imageio.__version__)


# Create random pixels
img = np.random.randint(0, 256, size=(512, 512), dtype=np.uint8)
quality = 100

# Use imageio to save the image in JPEG format
imageio_filename = "/tmp/imageio.jpg"
imageio.imwrite(imageio_filename, img, quality=quality)

# Read quantization table from saved JPEG file
im = Image.open(imageio_filename)
quantization_table = np.array(im.quantization[0]).reshape(8, 8)
print("[imageio] Quantization table\n", quantization_table)

# Use Pillow to save the image
pil_filename = "/tmp/pil.jpg"
im = Image.fromarray(img)
im.save(pil_filename, quality=quality)

# Read quantization table from saved JPEG file
im = Image.open(pil_filename)
quantization_table = np.array(im.quantization[0]).reshape(8, 8)
print("[Pillow] Quantization table\n", quantization_table)
```

Output:
```
2.9.0
[imageio] Quantization table
 [[ 2  1  1  1  1  1  2  1]
 [ 1  1  2  2  2  2  2  4]
 [ 3  2  2  2  2  5  4  4]
 [ 3  4  6  5  6  6  6  5]
 [ 6  6  6  7  9  8  6  7]
 [ 9  7  6  6  8 11  8  9]
 [10 10 10 10 10  6  8 11]
 [12 11 10 12  9 10 10 10]]
[Pillow] Quantization table
 [[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
```

**Comment by almarklein** [comment]
There is these lines:

https://github.com/imageio/imageio/blob/6d8a0b7b848dbf810910d11199294aed1ba3f255/imageio/plugins/pillow.py#L484-L488

These suggest that suggest that the max quality should be 95. Git blame tells me that I wrote that code, but I have no idea why the quality is limited like that, TBH. Maybe at the time Pillow behaved odd for those numbers?  I think we should just remove it. Care for a PR?
