### ISSUE TITLE
Imageio mimsave only writes gif when using the Debugger mode in Visual Studio Code

### ISSUE THREAD

**Issue by ChinCity** [imageio/imageio#578]
When I run the code (below) using the green play button (run python file in terminal) in Visual Studio Code the script runs through fine with no problems, however it will not save the gif. If I run it in the debugger (Run and Debug) it outputs just fine. 

What is happening here? Is very unusual. Also I am new to using Python in Visual Studio Code, I was using Spyder before.

Code: 

    import glob
    import os

    import imageio
    from pygifsicle import optimize

    if __name__ == '__main__':
        # Switches
        folder = os.path.join('D:\\', 'Documents, 'Gif')
        gif_path = os.path.join(folder, 'test.gif')

        # Get a list of filepaths for the images
        image_filepaths = glob.glob(os.path.join(folder, 'img*.jpg'))

        print(image_filepaths)
        print(folder)
   
        # Sort, read and store images in sequence
        images = []
        seconds = []

        for path in image_filepaths:
            images.append(imageio.imread(path))
            seconds.append(1)

        print(images)

        imageio.mimsave(gif_path, images, duration=seconds)

**Comment by almarklein** [comment]
This does not look  like a problem with imageio. But what I suspect is going on is that when you hit the play button, it will run the code, but not "as a script", so that the value of `__name__` is not "__main__", and the code in that `if` is not executed.

**Comment by ChinCity** [comment]
Thanks @almarklein, you are right. I executed the script from the command line and it worked. Do you know how I would execute fully from within visual studio code? Seems like an issue with the play button if it doesn't actually execute "main".

**Comment by almarklein** [comment]
I'm not that familiar with VS Code, but I suspect that it's intentional. It basically copies the code and runs it in an existing interpreter, which has its own value for `__name__`.
