### ISSUE TITLE
Inaccurate frames per second on metadata

### ISSUE THREAD

**Issue by iverona** [imageio/imageio#579]
imageio reports a FPS (frames per second) of 23.98 via `reader.get_meta_data()['fps']` when it actually is 23.976024 according to e.g. VLC. 

Is there any way to get the full precision? Or any other recommended way to do frames to offset calculations with full precision? 

Complete `reader.get_meta_data()` output:

```{'plugin': 'ffmpeg', 'nframes': inf, 'ffmpeg_version': '4.2.2 built with Apple clang version 11.0.0 (clang-1100.0.33.8)', 'codec': 'h264', 'pix_fmt': 'yuv420p', 'fps': 23.98, 'source_size': (1280, 544), 'size': (1280, 544), 'duration': 82.59}```

**Comment by almarklein** [comment]
That FPS value is indeed inaccurate. There is a way to get the accurate number of frames. Please have a look at this: https://imageio.readthedocs.io/en/stable/format_ffmpeg.html#ffmpeg

Other than that, imageio (nor imagio_ffmpeg) do not provide a more accurate way to provide the FPS at the moment.
