### ISSUE TITLE
Going from scipy to imageio

### ISSUE THREAD

**Issue by quintendewilde** [imageio/imageio#582]
Hi I'm running a slightly expensive aws... And trying to solve old scipy.imread to the new imagio.read standard. 

In this file 
https://github.com/ml5js/training-styletransfer/blob/master/src/utils.py

There is imresize how do I translate this into the new standard. 

(there are several more errors showing up like mode should be pilmode?) 

Secundary question is there an easy way to convert these files? 

Error code 👍 

```
WARNING:tensorflow:From /home/ubuntu/mlquinten/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
ml5.js Style Transfer Training!
Note: This traning will take a couple of hours.
Training is starting!...
Train set has been trimmed slightly..
(1, 708, 500, 3)
UID: 97
Traceback (most recent call last):
  File "style.py", line 179, in <module>
    main()
  File "style.py", line 156, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 107, in optimize
    X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
  File "src/utils.py", line 22, in get_img
    img = scipy.misc.imresize(img, img_size)
AttributeError: module 'scipy.misc' has no attribute 'imresize'
```

**Comment by almarklein** [comment]
Imageio does not have support for image resizing, as it focuses on the IO only. The way to go would be to use skimage for that. Alternatively, if you know that all your images can be read by Pillow, you could chose to use that, because it does have some support for image manipulations like resizing.

**Comment by almarklein** [comment]
> is there an easy way to convert these files?

I'm not sure what you mean here, to be honest :)

**Comment by FirefoxMetzger** [comment]
@quintendewilde This issue has gone a bit stale. Has your problem been resolved?

If there is no further activity in the next couple of days I'll close this issue.
