### ISSUE TITLE
When saving a 16bit png with all 0 values, it saves an 8bit image.

### ISSUE THREAD

**Issue by One-sixth** [imageio/imageio#585]
This should not be expected.
```
imageio.imsave('1.png', np.zeros([2048, 2048], np.uint16))
a=imageio.imread('1.png')
print(a.dtype)
# will print uint8
```
imageio.__version__ == '2.9.0'
windows10

**Comment by kmilos** [comment]
The default PNG format ('PNG-PIL') assumes 8-bit without any configuration. You can create a new writer and set the 'bits' keyword:

https://imageio.readthedocs.io/en/stable/format_png-pil.html#png-pil

Alternatively use the 'PNG-FI' format once you have the freeimage library installed:

https://imageio.readthedocs.io/en/stable/format_png-fi.html#png-fi

```python
imageio.imsave('1-FI.png', np.zeros([2048, 2048], np.uint16), 'PNG-FI')
```

**Comment by One-sixth** [comment]
@kmilos Thank you. I know i need to set prefer_uint8=False now.
