### ISSUE TITLE
imread does not detect .tga format

### ISSUE THREAD

**Issue by djhoese** [imageio/imageio#586]
Example file: https://github.com/vispy/demo-data/raw/master/jfa/shape1.tga

Script:

```
import imageio
imageio.imread('/home/davidh/.vispy/data/jfa/shape1.tga')
```

Error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-5a23ad325705> in <module>
----> 1 imageio.imread('/home/davidh/.vispy/data/jfa/shape1.tga')

~/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/imageio/core/functions.py in imread(uri, format, **kwargs)
    263
    264     # Get reader and read first
--> 265     reader = read(uri, format, "i", **kwargs)
    266     with reader:
    267         return reader.get_data(0)

~/miniconda3/envs/vispy_pyqt5_py37/lib/python3.7/site-packages/imageio/core/functions.py in get_reader(uri, format, mode, **kwargs)
    180         modename = MODENAMES.get(mode, mode)
    181         raise ValueError(
--> 182             "Could not find a format to read the specified file in %s mode" % modename
    183         )
    184

ValueError: Could not find a format to read the specified file in single-image mode
```

If I specify `format='tga'` then it works fine.

**Comment by almarklein** [comment]
I can reproduce this, and traced it down to here:
https://github.com/imageio/imageio/blob/2ce79b91c5415dd3069be1050d979a5bfd4245e1/imageio/plugins/pillow.py#L100-L107

The `Image.OPEN[self.plugin_id]` returns a factory, but not an `accept` function (a function that can be given the first bytes to validate that it in fact a file that can be read). This is the case for 6 formats (on my current install of Pillow).

At the moment, the `can_read()` method must return either True or False. But in this case it's more of a "maybe" or "likely". If we'd return True here, there is a chance that the Pillow plugin will fail reading it afterall, and we have not given other plugins a chance. The downside is that for these formats, users need to specify the plugin explicitly.

That said, I think it may be reasonable to change this behavior, especially for the Pillow plugin which is the best option we have in many cases. The safest way to do this would be an allowlist for (at least) tga. What do you think?

**Comment by djhoese** [comment]
I'm obviously not familiar with a lot (any) of this code, but shouldn't the extension on the file be a pretty hard rule? The extension is ".tga" so this must be a tga file. If that doesn't work are there really that many other plugins/readers that should be able to read the file?

**Comment by almarklein** [comment]
The thing is that there could be other plugins that are capable of reading certain formats. By returning True, and assuming that it will be fine, we're denying such other plugins a chance. But yeah, in this specific case, we can probably define that Pillow should be the preferred plugin for tga ...

**Comment by djhoese** [comment]
Understood. So this `can_read()` can be true or false right now, right? If this returns `True` for a reader and it fails to read it, is the file then passed on to another format? If you add a "maybe" third option, how would that differ from `True` with error handling?

**Comment by almarklein** [comment]
> If this returns True for a reader and it fails to read it, is the file then passed on to another format?

No, the format selection takes place first, after which the selected format is used to do the io. This is more deterministic. If we'd try one and move to another if that fails, we are wasting time for every operation, and the user would not be aware. Worst case we'd be hiding errors.

> If you add a "maybe" third option, how would that differ from True with error handling?

I think the formats that return maybe would move to the end of the list, so they'd be tried if there is no other format that is more "certain" (returned True).

**Comment by djhoese** [comment]
Hm ok, so like an order or "confidence" in the operation. That makes sense I guess.
