### ISSUE TITLE
Implement sizes kwarg for Ico format

### ISSUE THREAD

**Issue by HansHirse** [imageio/imageio#587]
According to the [ICO-PIL format documentation](https://imageio.readthedocs.io/en/stable/format_ico-pil.html#ico-pil), it should be possible to provide a list of `sizes` as an additional kwarg while saving. That doesn't seem to work.

Saving ICO files in general works:

```python
import imageio

# Read image
img = imageio.imread('image.png')

# Write ICO image
imageio.imwrite('image.ico', img)
```

The resulting `image.ico` has seven images (pages) with the mentioned sizes.

Trying to use the `sizes` kwarg fails:

```python
import imageio

# Read image
img = imageio.imread('image.png')

# Write ICO image with ICO specific kwargs
imageio.imwrite('image.ico', img, sizes=[(24, 24), (64, 64)])
```

The following error message occurs:

```lang-none
Traceback (most recent call last):
  File "...", 
    imageio.imwrite('image.ico', img, sizes=[(24, 24), (64, 64)])
  File "..\lib\site-packages\imageio\core\functions.py", line 303, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "..\lib\site-packages\imageio\core\functions.py", line 231, in get_writer
    return format.get_writer(request)
  File "..\lib\site-packages\imageio\core\format.py", line 185, in get_writer
    return self.Writer(self, request)
  File "..\lib\site-packages\imageio\core\format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
TypeError: _open() got an unexpected keyword argument 'sizes'
```

The `sizes` kwarg works in plain Pillow code:

```python
from PIL import Image

# Read image
img = Image.open('image.png')

# Write ICO image
img.save('image.ico', sizes=[(24, 24), (64, 64)])
```

The resulting `image.ico` has only two images (pages) of the desired sizes.

And, additional kwargs in general work, e.g. here setting some transparency when saving a PNG file:

```python
import imageio

# Read image
img = imageio.imread('image.png')

# Write PNG image with PNG specific kwargs
imageio.imwrite('image.png', img, transparency=(0, 0, 0))
```

The former black pixels are now transparent.

So, I think there's a bug in or a missing implementation of the `sizes` support when saving ICO files through `imageio`.

```lang-none
----------------------------------------
System information
----------------------------------------
Platform:      Windows-10-10.0.16299-SP0
Python:        3.8.5
imageio:       2.9.0
Pillow:        8.1.0
----------------------------------------
```

**Comment by almarklein** [comment]
These docs are copied from Pillow. In most cases this works out, but in this case the `sizes` attribute is indeed not yet implemented. We support most Pillow-supported formats via a single format class. To support special/common formats better, we have implemented specialized classes, e.g. for animated gif, png, and jpg. We should also add one for Ico.

**Comment by FirefoxMetzger** [comment]
@HansHirse Could you verify if this problem still exists, or do you have the "image.png" you mentioned and can make it available so I can test this? 

I think this may have been fixed in the process of me writing the v3 plugin for pillow. I tried the following:

```python
import imageio as iio

img = iio.v3.imread("imageio:chelsea.png")
iio.v3.imwrite('image.ico', img[...,0], plugin="pillow", sizes=[(24, 24), (64, 64)])
```

It correctly forwards the `sizes` argument to pillow, and it does produce an ICO file. I do seem to lack introspection tools for ICO though (not a format I actively work with), so I can't confirm how many pages the result has, or if it has corrupted the file in any way.

**Comment by HansHirse** [comment]
@FirefoxMetzger Indeed, this works very well! Nevertheless, I had to use plain `img` instead of `img[..., 0]` in the `imwrite` call. But, the resulting `image.ico` only holds two pages with the desired sizes. Thanks for the update on that!

I use IrfanView for fast and simple ICO introspection.
