### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by kshru9** [imageio/imageio#597]
I was trying to make a gif using some images by the help following code: [](https://github.com/akcgjc007/k-means-clustering/blob/master/draw.py)

I have installed pil library in my windows desktop, still it was throwing following error. 

File "gifmaker.py", line 13, in <module>
    imageio.mimsave(cur_dir+'/gifs/'+'sc.gif', images, duration=0.5)
    writer = get_writer(uri, format, "I", **kwargs)
  File "D:\python\lib\site-packages\imageio\core\functions.py", line 231, in get_writer
    return format.get_writer(request)
  File "D:\python\lib\site-packages\imageio\core\format.py", line 185, in get_writer
    return self.Writer(self, request)
  File "D:\python\lib\site-packages\imageio\core\format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "D:\python\lib\site-packages\imageio\plugins\pillowmulti.py", line 101, in _open
    self._writer = GifWriter(
  File "D:\python\lib\site-packages\imageio\plugins\pillowmulti.py", line 149, in __init__
    from PIL.GifImagePlugin import getdata
ModuleNotFoundError: No module named 'PIL'

I have worked with PIL library before where I have imported it using small letters pil. Is it the same library here as well ?

Can someone help me around with this.
Thanks.

**Comment by almarklein** [comment]
Odd. Anyway, the general way to install it is `pip install pillow`, please give that a try.

**Comment by ShrutiKatpara** [comment]
> Odd. Anyway, the general way to install it is `pip install pillow`, please give that a try.

![image](https://user-images.githubusercontent.com/45987734/108334714-3af69a00-71f8-11eb-97d8-ca27d4cee282.png)

![image](https://user-images.githubusercontent.com/45987734/108334775-4cd83d00-71f8-11eb-9590-563b27d1e0c5.png)

I have used following code: https://github.com/akcgjc007/k-means-clustering/blob/master/draw.py

**Comment by almarklein** [comment]
mmm ... perhaps the `pil` command is for another Python interpreter? What happens if you run `python -m pip install pillow`?

**Comment by FirefoxMetzger** [comment]
what @almarklein said.

Also what would be helpful in debugging this is the output of the following commands:
```
pip --version
python --version
pip freeze | findstr P[iI][lL]
python -m pip freeze | findstr P[iI][lL]
```
(assuming you re using powershell)

**Comment by FirefoxMetzger** [comment]
@kshru9 Did you manage to solve your problem?

This issue has been stale for a while; I will close it in the next few days if it remains this way. If it is still an issue, please let me know and I am happy to reopen.
