### ISSUE TITLE
Plugin Re-Organization

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#599]
We brought the reorganization up in #595 and I decided to make this a dedicated issue to allow discussing it in a central place. The aim of this issue is to converge on how to go about doing this.

@almarklein suggested outsourcing some of the plugins that `imageio` currently offers into separate repositories. The motivation behind this is - as far as I understand - (1) remaining/becoming a pure python library, and (2) easing maintainability by only having the core in this repository. (Please @almarklein add to this summary, if you think I missed something.)

Personally, I am not so happy about scattering the repo, because it means tracking issues and bugs across several repositories. I like the "single point of contact" style that we have currently. A spontaneous thought on this is that we could disable the issue page in the satellite repos and point to this repo for creating issues; I don't know how smooth it would be to handle PRs though.

Another point about this, which I really like, is the ability to structure user-side installation into different plugin groups/tiers. I.e.,

- `pip install imageio` Leightweight, installs commonly used formats only (.png, .jpg, .gif, others?)
- `pip install imageio[biomed]` Installs the basic formats + biomedical formats
- `pip install imageio[video]` Installs the basic formats + video formats
- `pip install imageio[full]` installs all available formats
- `...` other groups are possible

Ideas are appreciated.

**Comment by almarklein** [comment]
I agree that dividing the code over too many repositories will be counterproductive. The decision to move a plugin (or a set of plugins) to its own project should be based on a few factors:

* Does it help keep imageio itself easier to maintain (i.e. pure Python)? This was e.g. the case for imageio-ffmpeg, which comes with a platform-dependent binary. The imageio-ffmpeg project has special CI and code for distribution for the different platforms. I would want to do the same with the freeimage plugin (which would then ship the freeimage lib).
* Licensing. E.g. The implications of the license for freeimage have been a bit unclear.
* Keeping imageio itself lightweight. The risk of keeping adding to imagio is that `import imagio` will become slow. We should avoid this. That said, this can be done without spinning projects out.
* Dividing developer responsibilities. Sometimes people contribute a plugin, which is great, but sometimes it would be nice to more formally move the responsibility for maintaining that plugin to someone who knows more about it. This is especially true for very specific formats, or plugins that are relatively large/complex (Both imageio-ffmpeg and freeimage are examples that require specific skill / familiarity with the things they wrap).

Another way to go about this is to look at the topic. E.g. have imageio-biomed for formats specific to biomedical imaging, imageio-microscopy for microscopy formats, etc. Although I'm not sure if the boundaries between topics are that clear.

**Comment by FirefoxMetzger** [comment]
> Does it help keep imageio itself easier to maintain (i.e. pure Python)?

Afaik, for `imageio-ffmpeg` we are essentially maintaining the repo and I would assume the same will be true for any other plugin that we outsource. I totally agree that platform-dependent libraries can be a pain to deal with. I don't know, looking at it I don't see how we save any work by outsourcing. Could you elaborate?

> The imageio-ffmpeg project has special CI and code for distribution for the different platforms.

We have multi-platform CI in the main repo now as well :) On the same token, I think it would be a cool thing to get CD going using GH Actions. This is probably something we want to look into after cleaning the current backlog a bit though.

> Dividing developer responsibilities.

We could also think about using GitHub teams. Then again, we can currently count the number of maintainers on one hand, so maybe we don't need this categorization (yet).

**Comment by almarklein** [comment]
imageio-ffmpeg requires a different release procedure. Because it's a different library, it can have a separate release cycle, and this makes things a lot easier. Things are just a lot simpler when it's pure Python. Also the ffmpeg plugin comes with its own kind of problems, that are just easier to manage this way.

>  we are essentially maintaining the repo and I would assume the same will be true for any other plugin that we outsource.

Maybe, but maybe not so much for new plugins that others contribute in the first place.

**Comment by FirefoxMetzger** [comment]
Linking my comment here for future reference. It proposes a high level structure for the library.

https://github.com/imageio/imageio/pull/574#issuecomment-808789326

Happy to take feedback on this here :)

**Comment by FirefoxMetzger** [comment]
Closing this in favor of https://github.com/imageio/imageio/issues/633 .

I've also added the linked high-level structure in #648 .
