### ISSUE TITLE
Add RTD builds for PRs

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#602]
Read the docs offers to build documentation for each PR: https://docs.readthedocs.io/en/stable/pull-requests.html

It would be nice if we could have that, to check the styling of the docs before merging them. Currently, docs are tested via the GH Actions CI (build test, no styling). This will likely have to be modified and we may be able to remove this test from GH Actions in favor of using RTD.

**Comment by FirefoxMetzger** [comment]
@almarklein How can I get access to the administration side of RTD? I'd like to enable doc builds after every pull request.

**Comment by almarklein** [comment]
Done! I used the same username as your GH handle.

**Comment by FirefoxMetzger** [comment]
@almarklein Perfect, thanks. I'll have a go at it the next time I get some free time to work on `imageio`.
