### ISSUE TITLE
Wrap python av 

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#610]
[av](https://pyav.org/docs/develop/#) is a python library that wraps ffmpeg and aims to provide pythonic access to it. It apprears quite similar to our `imageio-ffmpeg`, so it could be useful to create a wrapper for it instead of maintaining our own wrapper.

Of course, both could exist in parallel instead of being a replacement.

**Comment by almarklein** [comment]
> Due to the complexity of the dependencies, PyAV is not always the easiest Python package to install from source. Since release 8.0.0 binary wheels are provided on PyPI for Linux, Mac and Windows linked against a modern FFmpeg. 

One of the main reasons for building imagio-ffmpeg instead of using pyav was that pyav was not trivial to install. It looks like this has changed.
