### ISSUE TITLE
Frame is 0 bytes, but expected 691200.

### ISSUE THREAD

**Issue by notsuraj** [imageio/imageio#612]
`
import torch

import cv2
from data import BaseTransform, VOC_CLASSES as labelmap
from ssd import build_ssd
import imageio

def detect(frame, net, transform):
    height, width = frame.shape[:2]
    frame_t = transform(frame)[0]
    x = torch.from_numpy(frame_t).permute(2, 0, 1)
    # PyTorch 1.5.1
    # x = Variable(x.unsqueeze(0))
    # y = net(x)
    x = x.unsqueeze(0)
    with torch.no_grad():
        y = net(x)
    detections = y.data
    scale = torch.Tensor([width, height, width, height])
    # detections = [batch, number of classes, number of occurence, (score, x0, Y0, x1, y1)]
    for i in range(detections.size(1)):
        j = 0
        while detections[0, i, j, 0] >= 0.3:
            pt = (detections[0, i, j, 1:] * scale).numpy()
            cv2.rectangle(frame, (int(pt[0]), int(pt[1])), (int(pt[2]), int(pt[3])), (255, 0, 0), 2)
            cv2.putText(frame, labelmap[i - 1], (int(pt[0]), int(pt[1])), cv2.FONT_HERSHEY_SIMPLEX, 2, (255, 255, 255), 2, cv2.LINE_AA)
            j += 1
    return frame

# Creating the SSD neural network
net = build_ssd('test')
net.load_state_dict(torch.load('ssd300_mAP_77.43_v2.pth', map_location = lambda storage, loc: storage))

# Creating the transformation
transform = BaseTransform(net.size, (104/256.0, 117/256.0, 123/256.0))

# Doing some Object Detection on a video
reader = imageio.get_reader('New Maserati Quattroporte Official Promo Comercial.-w4KifcavGQs.mp4')

fps = reader.get_meta_data()['fps']
writer = imageio.get_writer('output.mp4', fps = fps)

for i, frame in enumerate(reader):

          frame = detect(frame, net.eval(), transform)
          writer.append_data(frame)
          print(i)    

writer.close()

`

Error occurred:
RuntimeError: Frame is 0 bytes, but expected 691200.

What changes I have to make in the code

**Comment by FirefoxMetzger** [comment]
The runtime error states that the frame you are trying to write `frame` contains 0 bytes, whereas it should contain 691200 bytes (a full image). This means that - at some point in your pipeline - you are dropping the frame. Where exactly that is, I can not say from the error, as you didn't include a stacktrace.

**Comment by FirefoxMetzger** [comment]
@notsuraj Did you manage to solve your problem? 

Since this issue has been stale for a while I will close it in a few days if it remains this way. If the issue still exists, feel free to comment and I will reopen it.
