### ISSUE TITLE
Iteration/Volume support for paths

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#619]
The current API offers `mimread/mvolread` and the new API will offer `iter` as ways to read multiple images from containers that store more than a single image.

I was wondering if it would make sense to expand this functionality to paths and treat them as a container, i.e., `mimread("some/path")` will return a list of all the images inside the given path. Whether or not this should be recursive we can discuss.

On the same token, `mimread("some/file.zip")`  can allow reading multiple files from a zip-compressed file which could significantly decrease loading time if we operate on multiple images. I could simply zip my dataset and trivially enjoy the benefits of compressed IO while having imageIO inflate the file(s) on-demand.

**Comment by almarklein** [comment]
> `mimread("some/path")`

I feel this should not be in the scope of imageio. This is easily solved with `from fname in os.listdir(path): imagio.imread(fname)`. There are also potentially different plugins involved, which can all fail in their own way.


> `mimread("some/file.zip")`

I can see the advantage, but still think it's out of scope. It's still a rather specific use-case which can become complex quickly. Let's avoid feature creep. I'd much rather add an example to our docs that demonstrates how to implement this:

```py
import os
import zipfile
import imageio

def read_images_from_zipfile(filename):
    zf = zipfile.ZipFile(filename)
    images = []    
    for item in zf.filelist:
        ext = os.path.splitext(item.filename)[1]
        f = zf.open(item.filename)
        im = imageio.imread(f, format=ext)
        images.append(im)
    return images
```

**Comment by FirefoxMetzger** [comment]
Fair enough. This would sound like a nice first issue; I'll update the tags.

This could make a great "good-first-issue". How come we don't have this label?

**Comment by almarklein** [comment]
I jusr created that label and assigned it to this issue.
