### ISSUE TITLE
Pure Python ico/png

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#62]
I have code in ~zoof~ Flexx that can read/write ICO, BMP, PNG in pure Python. Limited to RGB(A) though. But might be interesting to not need freeimage for png. And also for  #21

**Comment by almarklein** [comment]
Need increases, because the current freeimage-based ico implementation segfaults on Travis on 3.5.

**Comment by almarklein** [comment]
The cases for which this makes sense is either people who have somehow managed to install imageio without pillow, or people who need good ico support, in which case its probably related to some sort of app, which can include other code (e.g. https://github.com/zoofIO/flexx/blob/master/flexx/util/icon.py). Either way, adding such functionality at this point does not seem to benefit much, and costs extra weight to imageio, plus extra maintenance. 

Therefore, wont do this unless the need for it increases for some reason.

BTW: Pillow can export icons but reading only gives largest image.

**Comment by FirefoxMetzger** [comment]
@almarklein This is an old issue flagged as wontfix. Revisiting this after 5 years, do you think anything has changed regarding your decision? I.e., do we still think that not adding this is the best solution?

If so, I suggest we close this issue to stay organized :)

**Comment by almarklein** [comment]
If Pillow stays a hard dependency the need for this is indeed quite low. Let's close.
