### ISSUE TITLE
(generated) API docs

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#621]
One thing that I didn't find for the current API is documentation of the actual functions in the library. Are we generating it? If not, I think we should, since we already have some pretty reasonable docstrings for our functions.

**Comment by almarklein** [comment]
We use Sphinx autodoc: https://github.com/imageio/imageio/blob/master/docs/userapi.rst

**Comment by FirefoxMetzger** [comment]
I am blind 🤣  I noticed the sphinx builder but didn't see the actual function documentation being shown anywhere.

Do you think it makes sense to rename the "User API" section to "API Reference"? (since this is what I've been searching for)

**Comment by almarklein** [comment]
> Do you think it makes sense to rename the "User API" section to "API Reference"?

Sure. The reasoning was to distinguish between user-reference and developer docs (for e.g. plugin developers). But I have no objection to renaming things.
