### ISSUE TITLE
Performance issues when loading some .tif files

### ISSUE THREAD

**Issue by DavidStirling** [imageio/imageio#623]
I have some 2k x 2k .tif files which I believe are compressed. I noticed that loading these with imageio was very slow.

On further investigation, specifying `format="TIFF-PIL"` with `imread` makes the file load almost instantly, so I believe this may be an issue with tifffile. In keeping with this, installing the latest version of tifffile via `pip` fixes the issue, though the plugin then also asks that `imagecodecs` be installed to load the file:

`ValueError: TiffPage 0: <COMPRESSION.LZW: 5> requires the 'imagecodecs' package`

Oddly enough pillow doesn't seem to need any other package to load the file quickly. Perhaps this is just a matter of updating the packed-in copy of tifffile, but if pillow can do just as a good a job I don't know if you have some way of selecting it when imagecodecs is absent?

Sample image attached. Just calling imread on it should replicate the issue.
[test_image.zip](https://github.com/imageio/imageio/files/6267409/test_image.zip)

Thanks

**Comment by cgohlke** [comment]
The vendored version of tifffile in imageio uses a pure Python implementation of the LZW decompressor. The solution is to install tifffile and imagecodecs.

https://github.com/imageio/imageio/blob/23cdcf5e62aceb1a32ee37e529eb731612b98298/imageio/plugins/_tifffile.py#L8308-L8390

**Comment by DavidStirling** [comment]
That makes sense, thanks for explaining. So is there no way to have imageio switch over to the PIL plugin if the incoming file is compressed and a user doesn't have the extra packages installed?

**Comment by almarklein** [comment]
> is there no way to have imageio switch over to the PIL plugin if the incoming file is compressed and a user doesn't have the extra packages installed?

Imagio uses a plugin system, where a suitable plugin is automatically selected. Including rules like these would make that process much more complex. Tifffile has priority over Pillow for Tiff, because Pillow can only deal with a subset of Tiff. It could be that the vendored version of Tiffile will be removed in future versions, so users will automatically use the latest/faster version.

**Comment by FirefoxMetzger** [comment]
> Or perhaps have some kind of warning about this, so that users know why loading performance isn't optimal.

The concern that I have with a warning here is that it may not be true for every user. I'm not a tifffile user, so I don't know for certain, but my guess is that there is a reason for imageio having a pure-python implementation in a place where tifffile has a dependency. Usually, this is to support as many platforms as possible (and sometimes to support pypy).

If this is the case, a user may end up seeing a warning that something isn't optimal, although they can't install a faster codec on their system, which would be very confusing.

>  So is there no way to have imageio switch over to the PIL plugin if the incoming file is compressed and a user doesn't have the extra packages installed?

The problem that I am not sure how to solve is that the decision to use a plugin is made without considering other plugins. Internally, a plugin implements a `can_read(...)` function which, if it returns true, indicates that the plugin is capable of reading this format and no further searching is necessary. 

This check is done without providing a plugin with information about other plugins, which means that the tifffile plugin would have to manually check for the availability of pillow and say that it can't read TIFF if it is SWF encoded and pillow is present (but only if it uses imageio's native tiffile backend, not if it uses the external one). What about third plugins a user may have installed that can handle tiff, too? Is ANY alternative better than the native tiffile backend for SWF? I'm worried about running down a rabbit hole here. If you have an elegant solution in mind, I'm happy to hear it and discuss :)

---

While I was writing this, @almarklein answered, too. You can read more about our ideas to stop vendoring backends here:

https://github.com/imageio/imageio/issues/599
https://github.com/imageio/imageio/pull/574#issuecomment-808789326

Please keep in mind that this may still change once we get around to actually implementing it and/or depending on the feedback we get on these ideas.

**Comment by DavidStirling** [comment]
Thanks very much for the information. In my own experience tifffile can read pretty much anything you'd commonly throw at it, and if it's only the vendored version that struggles to efficiently load some formats then preferring the packaged version seems like the obvious solution.

> If this is the case, a user may end up seeing a warning that something isn't optimal, although they can't install a faster codec on their system, which would be very confusing.

Agreed here, if the vendored version stays within imageio then perhaps it's just worth making a note somewhere in the docs (if it hasn't been already). I only discovered that the tifffile package version could be switched to upon inspecting the source code. On the subject of docs, the page on scipy [here](https://imageio.readthedocs.io/en/stable/scipy.html) also appears to suggest that pillow would be the preferred reader, rather than tifffile.

>  What about third plugins a user may have installed that can handle tiff, too? Is ANY alternative better than the native tiffile backend for SWF? I'm worried about running down a rabbit hole here. If you have an elegant solution in mind, I'm happy to hear it and discuss :)

While tifffile does strike me as the best available reader for tifs in general, as it's a container format there might be some risk in assuming that it'll _always_ be the optimal solution for any particular file. Perhaps that's something that can be resolved within `can_read()`, though I'm not sure if there'd be an efficient way to test compatibility.

In terms of plugins, it's not clear to me how priority is currently handled if the user provides a third party reader? I could imagine that in the future some very kind person might develop a plugin for python-bioformats, which can handle a massive assortment of formats but can be relatively slow due to the need to run over javabridge. In that situation I figure you'd want to declare the plugin as being low priority, rather than the best option for any compatible format.

I guess one solution you might have considered would be to make `can_read()` return some kind of measure of competency for the file in question, rather than a boolean. Doing so might require plugins to inspect the file a bit more when evaluating a format though, so perhaps that'd need to be assisted by some sort of caching of the results from each plugin if the user is going to call numerous files in sequence.

**Comment by FirefoxMetzger** [comment]
>  perhaps it's just worth making a note somewhere in the docs

That would indeed be a nice and welcome addition. Would you like to submit a PR for this? @DavidStirling 

> In terms of plugins, it's not clear to me how priority is currently handled if the user provides a third-party reader?

That is a good question. Plugins are selected based on an ordered list that specifies the preference. After adding your own plugin I think it is added with the highest priority (not 100% sure), and then you can set your preferred order using `format.sort()` See: 

https://github.com/imageio/imageio/blob/dc2d06b2358b6451164961b42a6d2f566fa5169e/imageio/core/format.py#L601-L619


> Doing so might require plugins to inspect the file a bit more when evaluating a format though

We do have functionality that caches the file's header and allows plugins to make decisions based on this without having to re-read the file each time. I am not intimately familiar with the layout of the tiff format, so I can't say if this is enough to make an informed decision or if the compression type is stored somewhere deeper in the file. However, not many plugins make use of this functionality at the moment.

**Comment by FirefoxMetzger** [comment]
Closed via #625 .

@DavidStirling If you think we could/should add additional items to properly address this issue, feel free to leave a comment, and I'll happily reopen the issue.
