### ISSUE TITLE
Depreciate or Upgrade Website

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#631]
On top of this GH and a RTD page, we have a website ([located here](https://imageio.github.io/)) which seems to not have aged too gracefully. I wonder if it is worth keeping around since it doesn't seem to provide any information on top of the GH's main `Readme.md`. If it is worth keeping around, I think we should update it and highlight what it adds to the GH and the RTD pages.

From my current understanding, my approach would be to depreciate it, and move any information that is useful to the main page in RTD. Then again, I may not have the full picture, so other input is appreciated :)

**Comment by almarklein** [comment]
> [...] which seems to not have aged too gracefully

No, it's just not pretty because I am not a designer :P 

Yeah, let's deprecate it and target RTD to be the main page.

**Comment by FirefoxMetzger** [comment]
> No, it's just not pretty because I am not a designer :P

Accounting for the fact that the initial style was created ~ 5-7 years ago, I think it was a quite good and functional design at that time. It's just that web design has massive turnover so it takes some dedication to always look "modern" and I don't think we currently have the capacity for that.

> Yeah, let's deprecate it and target RTD to be the main page.

Done. The website looks like an (almost) 1:1 copy of our `Readme.md`; are you (@almarklein ) aware of anything that should be migrated to RTD?

**Comment by almarklein** [comment]
The website is even generated from the readme on GH, so we should be fine :)

**Comment by almarklein** [comment]
I'll make the website redirect to RTD
