### ISSUE TITLE
depreciate avbin label

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#632]
I've noticed that the `avbin` plugin isn't a part of the current plugin folder, but there is a label for it (assigned to this issue). The library doesn't seem to have been updated in quite a while (last commit 2 years ago). In addition, none of the formats in our docs mention that they use the avbin backend.

Is it okay to remove the label, or is there anything that still needs us to have it around?

**Comment by almarklein** [comment]
Label removed.
