### ISSUE TITLE
How to best pass file ownership from imopen to a plugin?

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#643]
The basic idea behind the file-management of the new API is simple:

```python
with iio.imopen(...) as img_file:
    img = img_file.read(...)
    ...
```

The file is opened by `imopen`, held by `img_file` during the context, and closed once the context manager exits. This works nicely.

A problem occurs when we use `imopen` outside a context manager:

```python
instance = iio.imopen(...)
# ... program crashes or returns here
instance.read(...)
```

In this case, the open file may not be cleaned up properly or could cause a dangling reference. How can we smooth this out?

One option would be to have `imopen` close the file after it is done selecting a plugin and have the plugin reopen it. This might work, but is undesirable because it slows down the default case of using `imopen` inside a context manager (as intended)

Another option would be to use a promise-style setup where `imopen` returns a `PluginPromise` which gets turned into the correct plugin by its `__enter__` method. This would ensure that all file access is properly guarded. Promise-based interfaces are more common in JS than they are in python though, so I don't know if this idea is easily maintainable. 

A third option could be to make the destructor of `imopen` close the file. However, this may limit applications, because they cant use the file outside `imopen`'s scope.

All the options have pros and cons. The question here is which option is the best.

**Comment by almarklein** [comment]
> #also, is the file closed here or left open?

This would typically close the file right there, because the object is never even stored in this scope.

You're right that this behavior is an implementation detail of the Python interpreter. But maybe this is ok? The same aplies to Python file objects; you have to use them with care.

I think we have three options:
1. Do open+close when instantiating and then again when reading. This feels like a waste.
2. Follow same approach as Python file objects. Yes, the users need to use it with care, but this *is* our somewhat lower-level API, and it helps that it's the same as Python's `open()`.
3. Provide keywords args to specify the behavior. This complicates the API, and the default behavior would still be (1).

I'm leaning towards (2) because I don't like the other options. I think we can get away with shifting responsibility to the user here, since we have the higher level API that does not have this issue, and is what 90% of users will use.

**Comment by FirefoxMetzger** [comment]
@almarklein Okay then let's opt for a behavior that is similar to `open` in CPython and see if any pypy user runs into issues. I will add a warning to the `iio.imopen` docs to inform pypy users about this behavior.

**Comment by almarklein** [comment]
> Edit: This will essentially make each plugin responsible for closing the file once it is done with it.

What do you mean? Isn't the file only closed by `.close()`  and `__exit__()`?

**Comment by almarklein** [comment]
Oh, I think I see what you mean. New style plugins don't inherit from anything, so they need to implement close, context-manager and __del__ ... mmm

**Comment by FirefoxMetzger** [comment]
@almarklein Yes, because we made the deliberate decision to not have a base plugin class to inherit from. I remember adding it initially, but based on review suggestions I removed it later on.

**Comment by almarklein** [comment]
> but based on review suggestions I removed it later on.

Hehe. Maybe this'd change my opinion ... Adding this boilerplate code to all plugins seems like a shame.

**Comment by almarklein** [comment]
What do you think?

**Comment by FirefoxMetzger** [comment]
@almarklein I think a `Plugin` class could be nice, indeed. That way, we can avoid boilerplate, but also get some typing support, because `imopen` can now define `Plugin` as a return type.

**Comment by almarklein** [comment]
IIRC my main hesitance with a base `Plugin` class was this: I think it would be good if 3d party libraries *can* create plugins without subclassing something (i.e. define a plugin without having to actually import imageio). By not using subclassing ourselves, we guarantee that this works, but we can just as well guarantee this with a test. So yeah, let's do this :)

**Comment by FirefoxMetzger** [comment]
> I think it would be good if 3d party libraries can create plugins without subclassing something

An alternative maverick solution would be to simply copy-paste the base class (can I sell this as vendoring?) and subclass it or change it into the desired plugin. At the end of the day python is dynamically typed so it doesn't care if the object it returns actually is a subclass of `Plugin` or not. It will just hint that this to the IDE to provide auto-completion.

On a tangent: I would actually prefer to keep all plugins in our codebase and encourage 3d parties to contribute theirs. This way we can write tests against it and our CI/CD can break if any changes end up breaking compatibility with a backend. This seems like a much saner/easier way to ensure compatibility.

**Comment by almarklein** [comment]
> An alternative maverick solution would be to simply copy-paste the base class

But then `isinstance` would not work. I guess my point is that we should not use `isinstance` on plugin objects, but rely on ducktyping instead.

**Comment by FirefoxMetzger** [comment]
> But then isinstance would not work. 

True. Do we actually use it anywhere? Maybe I am missing something. What I had in mind was to use it for a type annotation ala

```python
def imopen(...) -> Plugin:
```

so no actual enforcing that the plugin is indeed a subclass.

**Comment by almarklein** [comment]
> Do we actually use it anywhere? 

No, but maybe we should make sure that we don't with a test, so that it stays that way
