### ISSUE TITLE
DOI for v2.9.0 lists version as v0.9.0

### ISSUE THREAD

**Issue by J-Wall** [imageio/imageio#649]
I am about to cite imageio in a paper, and (unless I am missing something) I noticed that the version number listed on zenodo for imageio v2.9.0 (<https://doi.org/10.5281/zenodo.3931847>) lists the version as v0.9.0.

I think this can be fixed for this version by manually editing the metadata on zenodo, but I am not sure what the underlying cause of it is.

**Comment by FirefoxMetzger** [comment]
I think the reason is the lack of automation that will publish the most recent version to zenodo.

That said, I don't have permissions to modify our page there, so we will have to wait for @almarklein to update it :)

**Comment by FirefoxMetzger** [comment]
@J-Wall zenodo is updated. You can find it here: https://zenodo.org/record/4972048#.YMsQTGgzaHs

Thanks for reporting, and thanks for citing us :)
