### ISSUE TITLE
Segmentation fault when writing a GIF in a non-existing folder

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#65]
If I run `imageio.get_writer("myfolder/test.gif")` without creating `myfolder` first, I get a Segmentation fault. You should wrap this in a `if os.path.exists`, with a `os.mkdir`, or simply raise an error when the path doesn't exist (maybe the simplest solution).

**Comment by almarklein** [comment]
Reproduced. Thanks!

**Comment by almarklein** [comment]
This should be fixed per #67
