### ISSUE TITLE
Consistent type annotations across the library

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#651]
Some of the functions in our library have the correct annotation already, whereas some (more legacy) functions don't feature annotations yet. At the same time, there is a (pretty useful) trend to outsource annotations into a separate [`.pyi` file](https://www.python.org/dev/peps/pep-0484/#id44) (think C++ headers, but actually just annotations not declarations). It makes sense to follow this trend here because it keeps the code clean while giving us nice typing support.

What is needed here is the following:

- [ ] introduce a .pyi file for each file in the library that contains code (we can ignore the `_plugin.py` files, as they are subject to depreciation/outsourcing in the future)
- [ ] introduce a new `ImageResource` type containing all valid inputs for a Request
- [ ] migrate the existing annotations from our functions into the pyi files
- [ ] add annotations for each function that currently lacks annotations

This is an easy addition and a great way to get an overview of the code-base. If there is a section of the library that you use particularly often, and you would like it to support annotations, partial contributions are also welcome.  If you do, please do leave a comment below, so we can coordinate the work and avoid people racing each other on the same section of the library.

**Comment by almarklein** [comment]
How would the information in the .pyi file be used? Would you include new tools to validate stuff in CI for instance? Or can people using imageio benefit from them?

**Comment by FirefoxMetzger** [comment]
It is primarily for consumers of ImageIO. With proper type annotations, you get a lot of help from a modern IDE; for example, it can more easily deduce the type of a variable and - for example in the case of classes - hint available methods. For example, I can do `instance: PillowPlugin = imopen(..., plugin="pillow")` and then my IDE will provide auto-completion for all the methods that PillowPlugin offers (+ the docstrings of said functions if desired) whenever I type `instance.re...`. Similar to what you are used to from IntelliSense in C++ or Java. Very handy.

The other option is that it allows you to run static/"compile-time" code analysis to verify that data types are handled consistently. This can warn you C-style if your variables change type through a function's execution, or if you pass unexpected types into a function, or your function doesn't return what it claims in some cases. Sometimes this is intentional, but most of the time it is a bug and you probably wish to fix it. For that to work, however, the module needs some indication of what the expected/allowed type is. Hence, type hinting.
