### ISSUE TITLE
Feature request: Support mypy type checking?

### ISSUE THREAD

**Issue by rggjan** [imageio/imageio#652]
Would be great if imageio could be statically type checked with:
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library

**Comment by FirefoxMetzger** [comment]
Sounds very closely related to #651 . I absolutely agree that type annotations would be a great addition. Being able to statically check them would be even better. 

The main reason this hasn't happened yet is lack of manpower. If you would like to contribute this @rggjan , I'm happy to help you navigate the library and to review the PR :)

**Comment by rggjan** [comment]
Thanks! Yes, I didn't find the other PR, they would probably nicely complement each other...
