### ISSUE TITLE
Trivial docfix

### ISSUE THREAD

**Issue by bsdphk** [imageio/imageio#657]
This is too trivial for me to bother going through the pull-request dance:
    
    >>> help(imageio.imwrite)
    Help on function imwrite in module imageio.core.functions:
 
    imwrite(uri, im, format=None, **kwargs)
        imwrite(uri, im, format=None, **kwargs)
 
        Write an image to the specified file.
 
        Parameters
        ----------
        uri : {str, pathlib.Path, file}
            The resource to write the image to, e.g. a filename, pathlib.Path
            or file object, see the docs for more info.
        im : numpy.ndarray
            The image data. Must be NxM, NxMx3 or NxMx4.
        format : str
            The format to use to read the file. By default imageio selects
            the appropriate for you based on the filename and its contents.
 
Note: It says "format used to *read* the file"

PS: Thanks for FOSS'ing!

**Comment by FirefoxMetzger** [comment]
Thanks for reporting

@almarklein I think we can fix this separately or add it into #648 .

PS: @bsdphk Thanks for using imageio :)

**Comment by almarklein** [comment]
Yes, probably easiest to just add to #648.

@bsdphk for the record, I've found that trivial fixes like these can be done relatively easily via the the Github UI (no need to make a local clone and use the command-line).

**Comment by FirefoxMetzger** [comment]
Will be fixed in #648 .
