### ISSUE TITLE
The FFMPEG reader fetches frames with the wrong time

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#66]
If I want the 300th frame and I call `myreader.get_data(300)` I will not get the 300th frame, but the frame from one second before. This is because [this line in ffmpeg.py](https://github.com/imageio/imageio/blob/3db112824c336f9b3336149fcc44359e58642a88/imageio/plugins/ffmpeg.py#L292) reads

    iargs = ['-ss', "%.03f" % (starttime-offset)]

Where the offset is 1. Actually, after reaching starttime-offset, it should advance of 'offset' seconds to be exactly on 'starttime', like this:

    i_arg = ['-ss', "%.06f" % (starttime - offset),
          '-i', self.filename,
          '-ss', "%.06f" % offset]

See [here](https://trac.ffmpeg.org/wiki/Seeking#Combinedseeking) for details and explanations.

**Comment by almarklein** [comment]
Care for a PR?
