### ISSUE TITLE
imageiov2.10.1. The imwrite will raise ValueError when filename include "#".

### ISSUE THREAD

**Issue by One-sixth** [imageio/imageio#674]
Imageio V2.10.1
```
import imageio
import numpy as np

imageio.imwrite('#1.jpg', np.zeros([512, 512, 3], dtype=np.uint8))
```
It will raise ValueError: Could not find a format to read the specified file in ImageMode.single_image mode.

But it will good. No raise.
```
imageio.imwrite('#1.jpg', np.zeros([512, 512, 3], dtype=np.uint8), '.jpg')
```

**Comment by FirefoxMetzger** [comment]
That's an interesting find @One-sixth . I tried to run your snippet on the master branch but did not encounter the exception:

```python
>>> import numpy as np
>>> import imageio as iio
>>> iio.imwrite('#1.jpg', np.zeros([512, 512, 3], dtype=np.uint8))     
>>> img = iio.imread("#1.jpg") 
>>> np.allclose(img, 0)
True
```

How did you install imageio, and which plugins/backends are you using?

**Comment by One-sixth** [comment]
System is win10 and ubuntu 20.
Python 3.9

I also tried to use the main branch, but the problem still exists.

This is my installation command.
```
pip install -U imageio imageio-ffmpeg
```

This is the complete error stack on win10.
```
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import imageio
   ...: import numpy as np
   ...:
   ...: imageio.imwrite('#1.jpg', np.zeros([512, 512, 3], dtype=np.uint8))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a29697784073> in <module>
      2 import numpy as np
      3
----> 4 imageio.imwrite('#1.jpg', np.zeros([512, 512, 3], dtype=np.uint8))

d:\python\python39\lib\site-packages\imageio\core\functions.py in imwrite(uri, im, format, **kwargs)
    192         raise ValueError("Image must be 2D (grayscale, RGB, or RGBA).")
    193
--> 194     with imopen()(uri, "wi", format=format) as file:
    195         return file.write(im, **kwargs)
    196

d:\python\python39\lib\site-packages\imageio\core\imopen.py in __call__(self, uri, io_mode, plugin, search_legacy_only, **kwargs)
    118                         # type of error raised to IOError
    119                         request.finish()
--> 120                         raise e
    121
    122         if plugin_instance is None:

d:\python\python39\lib\site-packages\imageio\core\imopen.py in __call__(self, uri, io_mode, plugin, search_legacy_only, **kwargs)
    111
    112                 try:
--> 113                     plugin_instance = LegacyPlugin(request, **kwargs)
    114                 except (ValueError, IndexError, KeyError) as e:
    115                     plugin_instance = None

d:\python\python39\lib\site-packages\imageio\core\imopen.py in __init__(self, request, plugin_manager, uri, io_mode, format)
    214         if plugin is None:
    215             modename = MODENAMES(self._request.mode[1])
--> 216             raise ValueError(
    217                 "Could not find a format to read the specified file"
    218                 " in %s mode" % modename

ValueError: Could not find a format to read the specified file in ImageMode.single_image mode
```

**Comment by almarklein** [comment]
I can reproduce the error. The cause this line, where we use `urlparse` on something that is not a url:

https://github.com/imageio/imageio/blob/51a8cd57cd2ea2722523206e61b617556c725f25/imageio/core/request.py#L245-L249


> Could not find a format to **read** the specified file

@FirefoxMetzger Also we should update this message to say "write" in this case :)

**Comment by FirefoxMetzger** [comment]
> I can reproduce the error.

Strange. Why does it work for me? I'll need to investigate ...

> The cause this line, where we use urlparse on something that is not a URL

This is what I was expecting when I first saw the issue. The call to `urlparse` itself is fine (I think), because it actually parses generic URI and we interpret the input as a URI (as far as I understand). The problem is that `#1.jpg`, when interpreted as a URI, is a fragment and not a path.

```python
>>> from urllib.parse import urlparse
>>> urlparse("#1.jpg")
ParseResult(scheme='', netloc='', path='', params='', query='', fragment='1.jpg')
```

I can see two ways to fix this: (1) Join the fragment and the path when the schema is `file:` (default schema). In this case, we will have to add an exception for zip files later on, since they will actually make use of fragments), or (2) make `#` a reserved character since its first occurrence marks the beginning of the fragment part of the URI.

**Comment by almarklein** [comment]
> we interpret the input as a URI

Well, we do call it a uri in some places, but if its a filename, then it's not a url. I suspect tat using urlparse may also break when the filename contains e.g. question marks. Characters like `?` and `#` in filenames are rare, but it seems silly if imageio would not support them.

In short, I think `urlparse` should only be used when we know its a url.

**Comment by FirefoxMetzger** [comment]
Okay. How about something like this @almarklein ?

```python
# Note: uri is the name of Request's input variable
parts = urlparse(uri)
if parts.scheme not in SUPPORTED_SCHEMES:
    parts._replace(path=uri)

```

I'm a bit hesitant about completely tossing out `urlparse`, because the alternative (parsing URIs manually) seems much more error prone and less maintainable.

**Comment by almarklein** [comment]
Yes, something like that should work! I agree that we should still use urlparse for urls.

Don't we know whether its a url in this part of the code? 
```py
if is_url:
     path= urlparse(self._filename).path
else:
    path = self._filename
ext = Path(path).suffix.lower() 
```

Otherwise, lets avoid using private methods. Maybe:
```py
url_parts = urlparse(self._filename)
if parts.scheme in SUPPORTED_SCHEMES:
    path = url_parts.path
else:
    path = self._filename
ext = Path(path).suffix.lower() 
```

**Comment by FirefoxMetzger** [comment]
@almarklein I agree. 

Looks like we found a solution for this and it doesn't seem too complicated to implement: Replace

https://github.com/imageio/imageio/blob/51a8cd57cd2ea2722523206e61b617556c725f25/imageio/core/request.py#L247

with the snippet @almarklein suggested:

```python
url_parts = urlparse(self._filename)
if parts.scheme in SUPPORTED_SCHEMES:
    path = url_parts.path
else:
    path = self._filename
ext = Path(path).suffix.lower() 
```

and to define `SUPPORTED_SCHEMES` and write a regression test.

This is a good first issue and I'll flag it as such. @One-sixth Are you interested in adding this to ImageIO? If not, if anyone else is interested, feel free to open a PR.

**Comment by One-sixth** [comment]
@FirefoxMetzger How about this method? It seems that there is no need to maintain a new constant.  
Replace
```
            parts = urlparse(self._filename)
            ext = Path(parts.path).suffix.lower()
```
To
```
            if self._uri_type in (URI_FILENAME,):
                path = self._filename
            else:
                path = urlparse(self._filename).path
            ext = Path(path).suffix.lower()
```

**Comment by FirefoxMetzger** [comment]
@One-sixth That works, too, although we would have to use `(URI_FILENAME, URI_ZIPPED)` to catch zip files as well.

**Comment by FirefoxMetzger** [comment]
Actually, @One-sixth I like your suggestion the most. Would you like to implement it?

**Comment by One-sixth** [comment]
@FirefoxMetzger Yes, I am interested. I will open a PR later.
