### ISSUE TITLE
Webcams with ID over 10 are not supported by ffmpeg plugin

### ISSUE THREAD

**Issue by hashb** [imageio/imageio#676]
https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py#L190 prevents ffmpeg to support reading webcams with id over 10

https://github.com/imageio/imageio/pull/675 uses regex to solve this

**Comment by FirefoxMetzger** [comment]
Thanks for spotting and fixing this @hashb . I reviewed your PR and triggered the CI. We only miss a regression test, so I would expect to get this merged during this week :)
