### ISSUE TITLE
volread on tifffile produces the wrong shape

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#681]
This is a regression from 2.9.0 first shared by @mkcor in https://github.com/scikit-image/scikit-image/pull/5262.

Reproducing example:

```python
img = iio.volread('http://cmci.embl.de/sampleimages/NPCsingleNucleus.tif')
img.shape  
# in v2.10.3 (30, 180, 183)
# in v2.9.0 (15, 2, 180, 183)
```

It traces back to something that, at least to me, is unexpected behavior in v2.9.0. Calling `imageio.imread` on the above tiff (in either version of ImageIO) returns a single page of the file, not a single image. I.e.,

```python
import imageio as iio
img = iio.imread('http://cmci.embl.de/sampleimages/NPCsingleNucleus.tif')
img.shape  # (180, 183) not the expected (2, 180, 183)
```

Consequentially, iterating over single images and stacking them, doesn't yield a stack of channel-first images, but a stack of pages:

```python
reader = iio.get_reader('http://cmci.embl.de/sampleimages/NPCsingleNucleus.tif', mode="i") 
img = np.stack([reader.get_data(index=x) for x in range(reader.get_length())])
img.shape # (30, 180, 183)
```

Reading a volume, on the other hand, does the expected thing and produces a stack of channel-first images (in v2.9.0)

```python
img = iio.volread('http://cmci.embl.de/sampleimages/NPCsingleNucleus.tif')
img.shape  # (15, 2, 180, 183)
```

however, does the page-stacking thing in v2.10.3:

```python
img = iio.volread('http://cmci.embl.de/sampleimages/NPCsingleNucleus.tif')
img.shape  # (30, 180, 183)
```

@cgohlke @almarklein @mkcor (and others who use TIFF more than me) What is expected behavior here? Would you expect `imread` to return a single *image* (shape: (2, 180, 183)) or a single *page* (shape: (180, 183))? I am leaning towards a single image, but I am open for comments here.

Depending on this answer, I would either look into a bugfix fir `get_data(index=...)` (any version) or `volread(...)` (v2.10.3).

**Comment by FirefoxMetzger** [comment]
> I wonder if you'd like to introduce an optional channel_axis parameter like we do in scikit-image @grlee77 😉 (where the default usually corresponds to channel-last images: channel_axis=-1)...

@mkcor Hm, what would you expect the `channel_axis` to do when reading? Would it be the channel axis of the returned ndarray (swapped if needed), or a hint to the reader which axis represents the color space?

**Comment by mkcor** [comment]
In this case, I was thinking of a hint to the reader, because apparently `imread` didn't pick that the second axis was part of the image... But I don't know the `imread` internals so maybe this is irrelevant; plus, the reader doesn't take care of any color space conversion or anything like this, so maybe it could/should be oblivious to which axis corresponds to channels in an image?

**Comment by FirefoxMetzger** [comment]
@mkcor As far as I am aware most formats store channel-last. This includes TIFF, where a single page handles one binary, gray, palette, or (channel-last) RGB image. Because of this, a `channel_axis` hint wouldn't help with this case; unfortunately.

I think what is happening is that the TIFF here uses tiles (or some other metadata flag that I am not aware of) to inform the reader to rearrange the pages into the shape of `(15, 2, ...)` and that each page by itself is actually a gray-scale image. We then simply choose to interpret `img.shape[2]` as the color channel, because that axis happens to correspond to different stains which we wish to represent in different colors (which then happens to do the right thing). For TIFF itself, however, each page is simply a gray-scale image (I think).

I will have to take a dive into tifffile and our plugin for it to see if that is indeed what is happening and then see how a fix could look like. This should happen during the week, but I don't think I can promise a specific day for it.

**Comment by mkcor** [comment]
Sure, it's an interpretation, that's why I don't even speak of *color* channels. Looking up this TIFF file's metadata:
```bash
$ exiv2 -pv NPCsingleNucleus.tif 
0x00fe Image        NewSubfileType              Long        1  0
0x0100 Image        ImageWidth                  Long        1  183
0x0101 Image        ImageLength                 Long        1  180
0x0102 Image        BitsPerSample               Short       1  8
0x0106 Image        PhotometricInterpretation   Short       1  3
0x010e Image        ImageDescription            Ascii     128  ImageJ=1.47n
images=30
channels=2
frames=15
hyperstack=true
mode=composite
unit=um
spacing=1.0E-13
loop=false
min=1.0
max=90.0
[...]
```
They provide the information for the number of channels, but they call 'frames' (resp. 'images') what we call 'images' (resp. 'pages'): Are these fields used by imageio's readers?

**Comment by FirefoxMetzger** [comment]
Oh, sorry @mkcor, I didn't mean that in a nit-picking or philosophical way. Rather in a "I think we kind of hack the TIFF spec to achieve this particular channel format" way. I'm not deeply familiar with TIFF, so I checked [Adobe's TIFF Spec](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf), and for colorspaces, they only mention binary, gray, palette, and RGB in the so-called _baseline_ TIFF spec. 

The only way I can see TIFF storing images from staining (with 2 color channels) is by pretending that these are actually two gray-scale images (to comply with the format). We would then have to rely on some other mechanism (likely the metadata you just shared) to reconstruct the original image from the two gray-scale images later on. Chances are high that the current `imread` is simply not aware of that mechanism or is otherwise ignoring it and, as a result, happily serves us a single gray-scale image instead.

**Comment by mkcor** [comment]
Oh, me neither, sorry @FirefoxMetzger! Re-reading my reply, I realize that it could come off as defensive. :pray: 

I'm not *that* familiar with TIFF files either, so I'm happy to try and clarify any possible aspect! More generally, I'm interested in the topic of (standardizing) image metadata; I'm also interested in *multichannel* images *in general*: for example, in our [data registry](https://gitlab.com/scikit-image/data/),

* `cells3d.tif` has 2 channels,
* `kidney-tissue-fluorescence.tif` has 3 channels,
* `lily-of-the-valley-fluorescence.tif` has 4 channels,

and these channels are not always in the last axis.

> pretending that these are actually two gray-scale images

Hmm, I'm not sure what you mean by 'pretending' since 'grayscale == single-channel' so... whenever you select a single channel in an image, it *is* a grayscale image. This is true of RGB images (the R channel is a grayscale image, etc.) and it is no different with any other kind of multichannel images (it's just that RGB is standard, commonplace, and corresponds to actual colors in the visible spectrum).

> I checked Adobe's TIFF Spec, and for colorspaces, they only mention binary, gray, palette, and RGB in the so-called *baseline* TIFF spec.

Out of curiosity, I tried this [online TIFF metadata viewer](https://products.groupdocs.app/metadata/tiff) on the file in question, and it says `PhotometricInterpretation: RGB Palette`... I believe that it means *multichannel* basically! :sweat_smile: 

> We would then have to rely on some other mechanism (likely the metadata you just shared) to reconstruct the original image from the two gray-scale images later on.

How do you deal with RGB images, where you also need to 'reconstruct the original image' from three grayscale images? Conceptually and computationally, it shouldn't be any different... :thinking: 

Again, I'm aware that RGB is standard and commonplace, but it's not robust nor satisfying to rely on a guess as in, say, :see_no_evil: 
https://github.com/scikit-image/scikit-image/blob/293fb937f675b62638dfbc31db1785b0fa026ba9/skimage/color/adapt_rgb.py#L12-L19
so the challenge is the same, right?

**Comment by kmilos** [comment]
IMHO the TIFF spec pretty clear and flexible on this: you can have almost any number of samples (channels) per pixel you want, everything is handled through interplay and parsing of SamplesPerPixel (w/ BitsPerSample, which could all be different btw), ExtraSamples, and PhotometricInterpretation fields. For a 2-channel image you could possibly have

SamplesPerPixel = 2
BitsPerSample = 8 8, if that is the case
PhotometricInterpretation = BlackIsZero (grayscale), if that is the case for the 1st sample
ExtraSamples = 0 (2nd sample is unspecified data)

It's just that the baseline defined PhotometricInterpretation values assume a presence of minimal prescribed SamplesPerPixel, and baseline only readers could ignore any superfluous ones.

Furthermore, nothing prevents you from defining/registering your own "vendor" [PhotometricInterpretation](https://www.awaresystems.be/imaging/tiff/tifftags/photometricinterpretation.html) unique value that you will then use to interpret the data correctly for that use case (and could do away w/ ExtraSamples then). For example, the DNG file format added CFA, LinearRaw, and Depth.

Volumetric data could/should be organized in ["TIFF trees" (linked list of IFDs and SubIFDs)](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFPM6.pdf), not channels...

**Comment by FirefoxMetzger** [comment]
> everything is handled through interplay and parsing of SamplesPerPixel (w/ BitsPerSample, which could all be different btw), ExtraSamples, and PhotometricInterpretation fields

Thanks, @kmilos that's interesting. When I read the spec it only mentioned four different channel layouts and I understood that as those being the only supported ones for a strip. There are a few more mentioned in the TIFF Extensions section, but I didn't read up too much on those. 

Do I understand it correctly though that changing `SamplesPerPixel` away from the default would make the TIFF application-specific and I should not expect other TIFF readers to know how to handle this correctly?

> Volumetric data could/should be organized in "TIFF trees" (linked list of IFDs and SubIFDs), , i.e. "pages", not channels...

Yes from what I understood, this is how the image discussed here is saved. Although I don't know about SubIDFs. Is it possible to organize IFDs hierarchically? If so, how is that stored in the file? It could be the piece of info that I am missing to figure where exactly the bug is.

From what I've gathered so far, the current TIFF has 30 pages (IFDs, iiuc) each storing one channel of one slice of the full volume. What I don't know is where to look for the info on how to stack those pages back together into a `(15, 2, ...)` array instead of a `(30, ...)` array. 

There is metadata that @mkcor shared (and that ImageIO can read) that specifies `frames=15` and `channels=2` inside the `description` tag and inside a custom `is_imagej` tag. I don't know if this is the correct place to check this info though...

> Hmm, I'm not sure what you mean by 'pretending' since 'grayscale == single-channel'

@mkcor Did @kmilos comment help? We need to choose a value for `PhotometricInterpretation` among the list of existing ones when creating a TIFF. This value gives us a sense of how the image data inside a single page should look like. We can extend this using tags like `SamplesPerPixel`, but - from what I understand - if we do that, we are a bit on our own.

Alternatively, we can put each channel onto a different page inside the file and stack the pages when we load the file. I think this is what is happening here. This may not be the originally intended way of doing things, because each page should represent a unique image, but it seems to work for ImageJ.

> it says PhotometricInterpretation: RGB Palette... I believe that it means multichannel basically! 😅

Sort of. Palette images are (in principle) single channel, but come with a separate 256 element lookup table which is used to reconstruct the RGB values; a bit like doing `plt.imshow(gray_image, cmap=...)` in matplotlib.

It is interesting though, because if there is indeed a pallet attached to each image then we should probably look it up while we read the image. However, that would make the image `(30, 180. 183, 3)` or `(15, 2, 180. 183, 3)` respectively, which seems off. I'll have to think about this x)

> How do you deal with RGB images, where you also need to 'reconstruct the original image' from three grayscale images? Conceptually and computationally, it shouldn't be any different... 🤔

As per the above. We could set the page's `PhotometricInterpretation` to `2`, which implies RGB. Then, we can directly store the image on a single page instead of 3 pages.

**Comment by kmilos** [comment]
> Do I understand it correctly though that changing SamplesPerPixel away from the default would make the TIFF application-specific and I should not expect other TIFF readers to know how to handle this correctly?

Correct. But this is also (end even more so) true with the completely arbitrary metadata scheme mentioned by @mkcor, which is even less "standard" and therefore impossible to support generally (you can whack whatever free from text you want in ImageDescription; no app would know what to look for and where, and shouldn't really rely on hacky schemes like this). TIFF extensions are at least implementable in a general way, it's just that applications must only guarantee the baseline spec and most stop there.

> Although I don't know about SubIDFs.
> 
> Is it possible to organize IFDs hierarchically? If so, how is that stored in the file? It could be the piece of info that I am missing to figure where exactly the bug is.

Yes, this is what SubIFDs are for - see the previously linked TIFFPM6.pdf document describing "TIFF Trees" for all the details.

So to get the shape of e.g. (15, 2, 180, 183), you could have a TIFF w/ 15 main IFDs, each main IFD having also a single additional SubIFD, and each of these 30 IFDs/SubIFDs would hold a 180x183 image w/ e.g. baseline  PhotometricInterpretation = BlackIsZero (and implied SamplesPerPixel = 1).

**Comment by FirefoxMetzger** [comment]
> Yes, this is what SubIFDs are for - see the previously linked TIFFPM6.pdf document describing "TIFF Trees" for all the details.

Huh, my bad. I somehow thought its the actual TIFF spec rather than a tech note on subIFDs. That's a pretty cool feature actually that I should start using. The more you know 💯 

On that note, @almarklein I think it is time to deprecate ImageIO's vendored `tifffile` library. It doesn't support subIFDs, but the actual library has since added support for it. We prefer a pip install over our vendored one, but I think we would make our life easier if we simply install the latest tifffile from pypi instead, e.g., via something like `pip install imageio[tifffile]`.

> the completely arbitrary metadata scheme mentioned by @mkcor, which is even less "standard" and therefore impossible to support generally

I agree, there is definitely a better way to do this, assuming it actually does rely on metadata. It is the way ImageJ does it though, which makes it standard in medical image analysis ... by virtue of popularity >.< ... and important enough for us to support since medical imaging is one of the areas relying on ImageIO.

---

On a more general note:

I removed my installation of `tifffile` and switched to our vendored version (no SubIFD support). I then tested the reading again and `iio.volread` still produces the desired shape of `(15, 2, 180, 183)`. From this, I conclude that the image, unfortunately, isn't using SubIFDs to organize the data. More evidence towards it relying on the custom metadata string to format the data...

@kmilos Do you have any other ideas on where the file might store relevant information for stacking, or happen to know how ImageJ solves this? (please don't say "well, they use the metadata string you already found" xD)

**Comment by kmilos** [comment]
Nope, sorry :( It looks like that really is it for ImageJ files, see these tifffile comments:

https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L319-L323
https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L1134-L1143
https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L1431-L1440
https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L15399-L15431

I especially liked "The ImageJ file format is undocumented."

Note also the TODO for ImageJ palette images: https://github.com/cgohlke/tifffile/blob/0eadc15ca044429f8af70a59ae9cc5a3d54b18e2/tifffile/tifffile.py#L3711

In any case, it looks like you want to delegate this to tifffile indeed.

**Comment by FirefoxMetzger** [comment]
Okay, I've implemented a fix that addresses the `volread` regression that @mkcor reported. If/once @mkcor gets permission to use the above image under CC0, I will uncomment the regression test and add the image to our test suite. Then we should be able to merge the fix.

---

I still have to look into the (v2) imread bug, but I will address that in a separate PR. I will have to think a bit more about this, because - having read into the TIFF spec - it is no longer obvious to me how this should best look like in ImageIO v3. Plugins can decide what behavior of the `index` kwarg makes the most sense for `iio.v3.imread(index=N)`, but what is the most sensible thing to do for TIFFfile? My hunch is that `index` should index the different series inside a TIFF and we should delegate to tifffile to decide what a series is, but I am more than happy to hear opinions here.

**Comment by mkcor** [comment]
Hi @FirefoxMetzger,

> @mkcor Did @kmilos comment help? We need to choose a value for `PhotometricInterpretation` among the list of existing ones when creating a TIFF. This value gives us a sense of how the image data inside a single page should look like.

Yes, absolutely! Thank you, @kmilos. This sentence I had to read a couple times:

> It's just that the baseline defined PhotometricInterpretation values assume a presence of minimal prescribed SamplesPerPixel, and baseline only readers could ignore any superfluous ones.

Visible hyphenation helps understanding as you read (rather than afterwards):

> It's just that the baseline-defined PhotometricInterpretation values assume a presence of minimal prescribed SamplesPerPixel, and baseline-only readers could ignore any superfluous ones.

:pray: 

> > How do you deal with RGB images, where you also need to 'reconstruct the original image' from three grayscale images? Conceptually and computationally, it shouldn't be any different... thinking
> 
> As per the above. We could set the page's `PhotometricInterpretation` to `2`, which implies RGB. Then, we can directly store the image on a single page instead of 3 pages.

Didn't you mean "on *2 pages* instead of 3 pages?" We want to access either channel when manipulating the image. Ok, I guess you meant `(30, 180, 183)` or `(15, 2, 180, 183)` as opposed to `(30, 180, 183, 3)` or `(15, 2, 180, 183, 3)`.

**Comment by FirefoxMetzger** [comment]
> Didn't you mean "on 2 pages instead of 3 pages?" We want to access either channel when manipulating the image. Ok, I guess you meant (30, 180, 183) or (15, 2, 180, 183) as opposed to (30, 180, 183, 3) or (15, 2, 180, 183, 3).

@mkcor No I actually meant `(15, 2, 180, 183, 3)`. To reconstruct a RGB palette image, you take the bitmap of channel indices (a `(180, 183)` array) and for each pixel in it, you look up the corresponding RGB value in a 256 color colormap (a `(256, 3)` array). In numpy fancy-index notation, this is something like `colormap[bitmap]` which gives you a `(180, 183, 3)` array. You have a total of 30 such pallets in the file, which would stack up into a `(30, 180, 183, 3)` volume.

However, the solution here is that ImageJ hyperstacks simply ignore the actual PhotometricInterpretation and do their own thing based on a string stored in the metadata. So they don't do any lookup of RGB values, but instead use the metadata string to figure out the number of channels and frames to then stack the 30 pages appropriately into a `(15, 2, 180, 183)` array. This is (a bit) non-standard, and perhaps undesirable, but that's what we got 💯 .

**Comment by mkcor** [comment]
> > Didn't you mean "on 2 pages instead of 3 pages?" We want to access either channel when manipulating the image. Ok, I guess you meant (30, 180, 183) or (15, 2, 180, 183) as opposed to (30, 180, 183, 3) or (15, 2, 180, 183, 3).
> 
> @mkcor No I actually meant `(15, 2, 180, 183, 3)`.

But your concluding sentence was "we can directly store the image on a *single* page *instead of* 3 pages." :confused: 

> However, the solution here is that ImageJ hyperstacks simply ignore the actual PhotometricInterpretation and do their own thing based on a string stored in the metadata. So they don't do any lookup of RGB values, but instead use the metadata string to figure out the number of channels and frames to then stack the 30 pages appropriately into a `(15, 2, 180, 183)` array. This is (a bit) non-standard, and perhaps undesirable, but that's what we got :100: .

As you reminded us earlier, ImageJ is a *de facto* standard in biomedical image analysis. :wink:

**Comment by FirefoxMetzger** [comment]
Ah, @mkcor, I think we have different things in mind when we head the word *page*.  On the hard-drive / inside the TIFF file, a page is essentially a block of data + some metadata (in the form of a Image File Directory (IFD)). The IFD tells the reader how to make sense of of the data block, e.g., number of pixels per row/column, where in the file the data block starts, the colorspace to use (`PhotometricInterpretation`). Traditionally, one IFD represents one (full) image and if you have more than one IFD in a file, then you also have multiple images in that file.

In *baseline* TIFF (i.e., the universally recognized minimal standard of what a TIFF is), there is a limited set of presets on what metadata values are allowed in the IFD. In particular, the previously discussed `PhotometricInterpretation`, that intends to communicate the color space, can have one of 4 different values (`0` = binary or gray image where white is zero, `1` = binary or gray image where black is zero, `2` = palette RGB image, `3` = channel-last RGB image). In addition, are `SamplesPerPixel` and `BitsPerSample`, which describe the layout of the channel axis, if channels are stored channel-last. For those, we are again limited to a few presets if we want to stick to *baseline* TIFF. In this case, however, the value depends on what we have chosen for `PhotometricInterpretation`, e.g., choosing `PhotometricInterpretation=3` (RGB) means that `SamplesPerPixel` must be 3 (3 values for each pixel), and `BitsPerSample` must be `888` (each value is an 8-bit unsigned integer (uint8)). There is no other choices. Similarly, for grayscale we can choose `PhotometricInterpretation=1`, but are then forced to set `SamplesPerPixel=1` and `BitsPerSample=8`.

Because of these constraints, we can't actually represent a staining picture (shape `(2, 180, 183)`, or `(180, 183, 2)`) in *baseline* TIFF. There is no way to choose `PhotometricInterpretation`, `SamplesPerPixel`, and `BitsPerSample` appropriately. Some trickery or non-standard approach is needed. One way to do this was suggested by @kmilos and that is to go beyond baseline TIFF and simply choose the `SamplesPerPixel` and `BitsPerSample` values that we actually need to store the staining image in one page. This is likely the least surprising because the format itself suggests you do so, but also gives the disclaimer of "if you do this, the result is still a TIFF, but most readers won't be able to read it, because it is non-standard". Another way is to go down the ImageJ route. Here we ignore the value of `PhotometricInterpretation`, store only a part of the image (one channel of one slice) in one page, and use many pages. Then, we add a custom metadata string to the image where we store the actual number of channels and number of slices in the z-stack. Again, no other reader will be able to reconstruct the image (how would they know what our homebrew metadata string means, or even where to look for it?), and - considering the format's official suggestion - this is a much less expected way of doing things.

> But your concluding sentence was "we can directly store the image on a single page instead of 3 pages." 😕

Assuming the above makes sense (if not please do let me know), this should now be less confusing. For RGB there exists something akin to a "metadata preset" that is universally recognized and allows you to put the full RGB image into one page, hence you only need one page for the image. The same applies to palette RGB. 

For an N-channel stain, however, there is no "metadata preset". Here, the least surprising solution would be to treat each channel as a grayscale image (for which a metadata preset exists) and to store the image as N grayscale pages. This would allow many readers to reconstruct the staining picture later on because they can read out one stain at a time in the order that we saved our channels; exactly what we wanted.

So as a recap, a RGB image fits into 1 page (*baseline* preset exists), but a staining image typically doesn't fit into a single page (*baseline* preset does not exist) unless we do something non-standard.

> As you reminded us earlier, ImageJ is a de facto standard in biomedical image analysis. 😉

Yes, and I still agree that we should (and do) support it, because of that. However, just because it is common practice doesn't mean that it is a good idea ... slavery was common practice once, but that doesn't mean we shouldn't be critical toward it 😛 .

**Comment by kmilos** [comment]
One thing to note: with the "TIFF trees" I guess one is limited to adding 2 extra axis only, while the ImageJ way, although "hacky" and standard-breaking, is indeed more flexible/powerful (they should've really just called it the ImageJ format, not TIFF).

**Comment by GenevieveBuckley** [comment]
I just ran into this as well, thanks for fixing it

**Comment by FirefoxMetzger** [comment]
@GenevieveBuckley The fix should roll out to PyPI tonight.
