### ISSUE TITLE
make ffmpeg's can_read more sophisticated

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#686]
Details in https://github.com/imageio/imageio/pull/680#issuecomment-970142963

Currently, there is a discrepancy between what our FFmpeg plugin can actually read and what it claims it can read. It claims to be able to read less than it actually does. The cause of this is that `_can_read` makes a decision based on the file's extension alone instead of querying the file's metadata/header (e.g., via ffprobe). This is problematic because it will reject reading from `bytes`/`BytesIO` or reading any format that we have not manually registered.

**Comment by Kulikovpavel** [comment]
Temporary fix
```
from imageio.plugins.ffmpeg import FfmpegFormat 
FfmpegFormat.can_read = lambda x, y: True
```

**Comment by JacksonMaxfield** [comment]
Bumping this after your comment @FirefoxMetzger!

This also affects us over at `aicsimageio`. Until one of our own users requires a change it is a lower priority for us but will update this issue if something comes up.

**Comment by FirefoxMetzger** [comment]
For future readers, you can use the new (v2.15.0) `format_hint=` kwarg in v3 to help the FFmpeg backend and read the bytes/BytesIO:

```python
import imageio as iio

frame = iio.v3.imread(video_bytes, format_hint=".mkv")
frame = iio.v3.imread(video_bytesio, format_hint=".mp4")
```

On older versions of ImageIO, a workaround is to set the extension for the stream manually. Note, however, that this is more of a hack, because there is no guarantee that the (private) `_extension` will be around forever:

```python
import imageio as iio

req = iio.core.Request(video_bytes, "r")
req._extension = ".mkv"  # your format extension here
frame = iio.imread(req)
```
