### ISSUE TITLE
Add rawpy backend

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#691]
I found an I/O library that I wasn't aware of today; perhaps it is worth adding a plugin for it. It is called rawpy and provides access to various RAW formats via [libraw](https://www.libraw.org/).

GH Link: https://github.com/letmaik/rawpy
Docs: https://letmaik.github.io/rawpy/api/
Tutorials: https://github.com/letmaik/rawpy-notebooks/blob/master/README.md

If you would like to see this backend added, please react to this post or leave a comment below. The more feedback I get on a backend, the more likely I am to prioritize implementing it over solving other issues :)

**Comment by Scarlet-2** [comment]
hello i am just starting on programming and would like to make my first contribution can i help with this issue?

**Comment by FirefoxMetzger** [comment]
Hej @Scarlet-2 , super cool that you decided to start learning how to code. Sure, you can absolutely take a shot at implementing this. 

If you don't mind me asking: How familiar are you already with the concepts in Open Source and (for this PR specifically) image formats? Depending on this I can suggest a way to get you started.

**Comment by Scarlet-2** [comment]
well it is my first time trying to help or you could say participating in open source and i am not very familiar with image formats

**Comment by FirefoxMetzger** [comment]
Right. Do you know your way around Git and your IDE of choice? 

In that case, we have some instructions on getting started with plugin writing here: https://imageio.readthedocs.io/en/stable/development/index.html#implementing-a-new-plugin 
 I'd suggest that you start setting up a dev environment for ImageIO (up until the point "Installation") and let me know if you run into trouble along the way.

**Comment by Scarlet-2** [comment]
Ok if i can start getting to it i will tell you because right now i am solving some problems in my college

**Comment by tahseenadit** [comment]
Hi, I would like to pick it up and work on it.

**Comment by FirefoxMetzger** [comment]
Closed by: https://github.com/imageio/imageio/pull/1063
