### ISSUE TITLE
Allow ffmpeg to make use of system executable

### ISSUE THREAD

**Issue by almarklein** [imageio/imageio#70]
Original discussion in #63. cc @ghisvail

**Comment by almarklein** [comment]
Both the system `ffmpeg` and `avconv` executables do not work.

**Comment by almarklein** [comment]
This is actually implemented via IMAGEIO_FFMPEG_EXE

**Comment by almarklein** [comment]
(and now documented too #86)

**Comment by cancan101** [comment]
Is it acceptable to set `IMAGEIO_FFMPEG_EXE=avconv` (i.e. is the `avconv` executable a good enough drop in replacement for `ffmpeg`)?

**Comment by almarklein** [comment]
@cancan101 I am not sure. My suggestion is to just try and see if it works.
