### ISSUE TITLE
Automatically use locally available version libfreeimage

### ISSUE THREAD

**Issue by anjos** [imageio/imageio#706]
What would it take to make this package try to **automatically** use the pre-installed version of that library instead of downloading its own copy?  (N.B. I realise that `$IMAGEIO_FREEIMAGE_LIB` may be set on the user environment to point to a common installation of the file, however, I'm looking for an automated solution.)

For example, in conda-forge, freeimage is currently available for installation (https://anaconda.org/conda-forge/freeimage, v3.18), in a variety of platforms.  One of the issues I'm trying to improve is the support for different OS/architecture types.  Specifically, I'd like to have support of OSX/arm64 (new M1 macs).  This would be possible by setting `$IMAGEIO_FREEIMAGE_LIB`, however, this would be a little bit uglier from a packaging perspective.    Moreover, not all packaging systems support this kind of strategy.

Furthermore, as of now, everytime a new combination of os/hardware is introduced, you must ensure that the binary is available remotely, on the freeimage repository, and then patch imageio to make it work for that new OS/arch combination.  An auto-detection would allow one to benefit from the existing library if available w/o an extra effort.

Another side effect of this behaviour is that you need to have some sort of external directory in which we are caching the downloaded freeimage library.  If no environment variable is set, multiple users (benefiting from a global imageio installation) will end up downloading multiple copies of this file.  An auto-detect strategy would make this package a bit more "unmutable" after installation.

**Comment by FirefoxMetzger** [comment]
Hm, @anjos do you know how other python packages auto-detect existing C-libraries? 

I have some knowledge on how this is done in C/C++ projects (in particular through CMake), but that mostly revolves around searching default installation paths for various OSes or relying on hints from the user; both get messy fast.

If there is a pre-existing python package that we can check the existence of that makes things a lot easier. In this case, we could make it take precedence over our vendored version if it exists in the local environment ... that shouldn't be too complicated (famous last words 😅 ).

> An auto-detection would allow one to benefit from the existing library if available w/o an extra effort.

If the auto-detection can rely on some pre-existing toolchain to discover that the library exists :) This is, from my side, the biggest unknown. Once we know which binary to use (and assuming the version is compatible), the rest should be a matter of setting up the plumbing. Rolling our own auto-detection code that checks different locations depending on the OS is possible, but painful; especially if we have to make sure that the versions are compatible.

---

Finally, the same point as with `imageio-ffmpeg` applies here. We would like to move the binary and its wrapper into a dedicated repo (`imageio-freeimage`). We could even think of making freeimage an optional dependency. This way, we can pre-build wheels with the correct binary installed. This doesn't directly affect your suggestion (in that that repo would then have the auto-detection to use a pre-existing freeimage binary), but it is related, so I mention it here in case it becomes relevant further down the line.

**Comment by anjos** [comment]
There are solutions for libraries that standardise packaging, e.g., via pkg-config.  The python library pkgconfig (https://github.com/matze/pkgconfig) can help with that.  Here is an example for ffmpeg's libavutil:

```python
>>> import pkgconfig
>>> pkgconfig.modversion('libavutil')
'56.70.100'
>>> pkgconfig.libs('libavutil')
'-L/Users/andre/mamba/envs/imageio/lib -lavutil'
```

Then all you need to do is parse this output.  Now, freeimage does not provide any of that, so no luck on that side, you'll have to load the library by hand and check the version yourself.  Doesn't the C-API of that package offer any version numbering?

**Comment by anjos** [comment]
I took a look at the FreeImage API (https://freeimage.sourceforge.io/documentation.html), and apparently, they do provide a method inside the C-API that outputs the version: `DLL_API const char *DLL_CALLCONV FreeImage_GetVersion(void);`

So, here is the strategy for this library:

1. Use `ctypes` to find the library to load, with the correct name (https://docs.python.org/3/library/ctypes.html#finding-shared-libraries): `import ctypes.util; ctypes.util.find_library('freeimage')`
2. Load the library
3. Call `FreeImage_GetVersion()` to see if the loaded version is compatible with current code

**Comment by anjos** [comment]
You may apply the same strategy for the ffmpeg library or its components.

**Comment by kmilos** [comment]
> For example, in conda-forge, freeimage is currently available for installation (https://anaconda.org/conda-forge/freeimage, v3.18), in a variety of platforms. One of the issues I'm trying to improve is the support for different OS/architecture types.

With conda (at least I tested on Windows), imageio will "automatically" use the installed freeimage library ([it searches the known locations and shared library names](https://github.com/imageio/imageio/blob/9df61d23f398904c96c334c67dbf67c655e15c52/imageio/core/findlib.py#L32)). Not as elegant as you suggest, but seems to work for most known environments so far...

For example, with MSYS2 packages, the shared system library can also be detected (known location and filename), so freeimage is added as an optional dependency in the package manager and we removed the binary download scripts to avoid any problems.

**Comment by anjos** [comment]
Let me verify this and get back to you.

**Comment by anjos** [comment]
I verified this to be true for all platforms I tested this library with.  This then looks like a non-issue.  I propose we close it.

**Comment by FirefoxMetzger** [comment]
Closed as per @anjos comment.

**Comment by anjos** [comment]
Thank you.  This does not preclude re-thinking the purpose of this mechanism existing in imageio.  I'm not sure it is the job of imageio to install its own dependencies.  That can probably be better managing to the underlying packaging managers.  However, this is a question for another issue.

**Comment by FirefoxMetzger** [comment]
@anjos Yep, see also https://github.com/imageio/imageio/issues/628#issuecomment-838470536 (and similar comments across issues). The idea is to eventually move the FreeImage backend into its own repo and make it a dependency that can be installed via `pip install imageio[freeimage]`.
