### ISSUE TITLE
Deprecate Python3.6 support

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#723]
Python 3.6 reached EOL at the end of 2021. @almarklein Do we want to follow suit and depreciate support for it? If so, should this affect the version number? Since it doesn't affect the API I'd assume no, but I can also see why we would want to bump something.

**Comment by almarklein** [comment]
Sure, that also shaves off some CI cycles. Since this would only change some meta-stuff (I assume you're not going to change code that makes imageio incompatible with py3.6 right now :)  ), I don't think a bump is needed.

**Comment by FirefoxMetzger** [comment]
@almarklein Yes, this change itself would simply mean changing our docs to say that it requires python 3.7+ instead of python 3.6+ as well as changes in the setup.py and the CI.

In the future, I would like to add `@dataclass` to some of our config files, which got added in  python 3.7. At this point, we would then lose 3.6 compatibilities.
