### ISSUE TITLE
TIFF reader: ResolutionUnit, XResolution, YResolution not accessible

### ISSUE THREAD

**Issue by lfriedri** [imageio/imageio#731]
Documentation states that TIFF resolution (pixel scaling) can be read:
https://imageio.readthedocs.io/en/stable/reference/_backends/imageio.plugins.tifffile.html#module-imageio.plugins.tifffile

However, resolution_unit is not available in meta data after reading.
Example:

```
import numpy as np
import imageio

filename = 'test.tif'
data = np.zeros((200, 100), dtype=N.uint8)
dpi = (100, 200)

writer = imageio.get_writer(filename)
writer.append_data(data, dict(resolution=dpi))
writer.close()

read = imageio.imread(filename)
print(read.meta)
```

It seems that tifffile provides only certain tags as attributes:
https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#:~:text=def%20TAG_ATTRIBUTES()%3A,%7D

imageio on the other hand only provides those tags, that are attributes:
https://github.com/imageio/imageio/blob/master/imageio/plugins/tifffile.py#:~:text=def%20_get_meta_data(self,pass

Additionally, in the list of the reading tags in imageio, "resolution_unit" appears without comma, is that intended?
https://github.com/imageio/imageio/blob/master/imageio/plugins/tifffile.py#:~:text=READ_METADATA_KEYS%20%3D%20(,)

**Comment by lfriedri** [comment]
Note that the resolution of the generated 'test.tif' can be successfully read with ImageJ.

**Comment by FirefoxMetzger** [comment]
@lfriedri This should get fixed in next monday's release. You should then be able to access the resolution under the metadata key "resolution".

**Comment by lfriedri** [comment]
thank you, that was fast. I will try to test the release in this regard.
