### ISSUE TITLE
Valid WebP image does not work in ImageIO

### ISSUE THREAD

**Issue by neave** [imageio/imageio#735]
This WebP image:

https://bug-235316-attachments.webkit.org/attachment.cgi?id=449378

of a simple transparent image with a horizontal line does not display when using ImageIO. The image loads and displays correctly in Chrome and Firefox, but fails to display in Safari (Mac or iOS) as Safari uses ImageIO.

Bug also reported in WebKit: https://bugs.webkit.org/show_bug.cgi?id=235316

**Comment by neave** [comment]
Ah, you may be correct. I'll leave a comment on the WebKit bug report to clarify which ImageIO this is.

**Comment by FirefoxMetzger** [comment]
@neave I just gave the image a shot, and it loads fine on my end:

```python
>>> import imageio as iio
>>> im = iio.v3.imread("bug.webp")
>>> import matplotlib.pyplot as plt
>>> # show image (all white, because background is white in mpl)
>>> plt.imshow(im)
<matplotlib.image.AxesImage object at 0x000001A7544D68B0>
>>> plt.show()
>>> # show mask channel only (gray image)
>>> plt.imshow(im[...,-1], cmap="gray") 
<matplotlib.image.AxesImage object at 0x000001A74FEE4820>
>>> plt.show()
```

**Comment by neave** [comment]
OK thank you - that's great. I'll close this issue.
