### ISSUE TITLE
"Subrectangles" optimization when writing GIFs

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#74]
Hi there ! So apparently the subrectangles optimization to reduce the size of gifs is broken, but I'm not completely sure what is wrong. Is this something that we must wait for FreeImage to fix, or is there something that could be done at the level of ImageIO ?

Cheers !

**Comment by almarklein** [comment]
Optimization for subrectangles is not implemented in FreeImage. Therefore imageio does the subrectangle processing itself (see plugins/freeimagemulti.py).

**Comment by Zulko** [comment]
Sure, but my question was about the meaning of [these lines](https://github.com/imageio/imageio/blob/master/imageio/plugins/freeimagemulti.py#L169-L174).

**Comment by almarklein** [comment]
Aah. Completely forgot about that. I don't think there is much we can do while FreeImage is broken, unfortunately :(

**Comment by darkdragon-001** [comment]
For me, it seems to work. At least setting this option to true results in significantly smaller files...

**Comment by almarklein** [comment]
@darkdragon-001, IIRC that is expected, but the visual result can be wrong due to FreeImage not writing the disposal method correctly, i.e. the frames are composed in the wrong way. Could be that its fixed by now though.

All this said, we're about to have a gif writer based on Pillow that supersedes the FreeImage version.

**Comment by almarklein** [comment]
Closing this, since the gif writer of the Pillow plugin supersedes the one provided by the FreeImage plugin, and theres not much that we can do about it anyway.
