### ISSUE TITLE
ValueError when reading TIFF file with volread on 2.11.1

### ISSUE THREAD

**Issue by BptGrm** [imageio/imageio#748]
When opening a TIFF stack with `imageio.volread()` using version `2.11.1`, I get the following message : 
`<tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
I previously opened the same files with version `2.9.0` without any issue. Considering the message itself, I wonder if it's because of the update or if it's numpy dependent ?

**Comment by FirefoxMetzger** [comment]
It's hard to say what is happening exactly from the error message alone. A few points:

- Since you are not using the latest version of ImageIO, have you tried upgrading your version? (and does that fix the problem?)
- Would you be able to share the image so that I can try to reproduce the issue locally and see what is going on?
- If you can't share the image, could you share the full stack trace of the error so that I can at least see where things fail?

**Comment by FirefoxMetzger** [comment]
> Turns out it's size-dependent : a stack of 1022 frames does not trigger that message, but a stack of 1023 does. [...] I can share the file if you want, but it's still about ~175Mb.

That sounds quite odd indeed. If you are able to share it that would help quite a lot. I don't mind the file size.

> I'm not quite sure how to get the full trace, as it's apparently not recognized as raising an error. I tried in both CLI and VS Code, it's just printed out in the terminal.

Copy-pasting the message you get in the console works for me. Alternatively, you can create a log file and share that. Assuming that there are no external factors influencing the behavior, you could use

```bash
python3 -c "import imageio; imageio.volread('/path/to/your/file.tiff')" 2> /path/to/your/crash.log
```

(this assumes that your python executable is available on the command line and called `python3`. On some OSes (eg., Windows) it may be called `python` instead.)

For example, `python3 -c "import imageio; imageio.volread('imageio:chelsea.png')" 2> crash.log` produces a file with the following content:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\sebastian\documents\coding-projects\imageio\imageio\core\functions.py", line 310, in volread
    return file.read(index=0, **kwargs)
  File "c:\users\sebastian\documents\coding-projects\imageio\imageio\core\legacy_plugin_wrapper.py", line 133, in read
    reader = self.legacy_get_reader(**kwargs)
  File "c:\users\sebastian\documents\coding-projects\imageio\imageio\core\legacy_plugin_wrapper.py", line 103, in legacy_get_reader
    return self._format.get_reader(self._request)
  File "c:\users\sebastian\documents\coding-projects\imageio\imageio\core\format.py", line 187, in get_reader
    raise RuntimeError(
RuntimeError: Format PNG-FI cannot read in v mode
```

**Comment by BptGrm** [comment]
I'll upload the file, but in the meanwhile, here's the log, using the command you provided :
```
python : <tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
At line:1 char:1
+ python -c "import imageio; imageio.volread(r'D:\ZF\Substack (1-1023). ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (<tifffile.TiffP...ny() or a.all():String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
<tifffile.TiffPage 0 @8> imagej_metadata failed with ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by FirefoxMetzger** [comment]
Interesting. This seems to trace back to the tifffile backend itself. Are you using our vendored one, or do you have tifffile installed as a separate package?

**Comment by BptGrm** [comment]
Everything was installed with `imageio` through `pip`

**Comment by FirefoxMetzger** [comment]
> Everything was installed with imageio through pip

In this case, you could try to install imageio with the latest tiffile backend `pip install -U imageio[tifffile]` and see if that resolves the problem. Otherwise, I'd have to get my hands on a problematic file to reproduce the problem and investigate locally.

**Comment by BptGrm** [comment]
I uninstalled `imageio` then reinstalled it with the command you provided, no changes.
Here's the file : https://filesender.renater.fr/?s=download&token=508ecc94-f690-4646-b104-224ce8e53afa&lang=en

**Comment by cgohlke** [comment]
https://github.com/cgohlke/tifffile/issues/111

**Comment by BptGrm** [comment]
> [cgohlke/tifffile#111](https://github.com/cgohlke/tifffile/issues/111)
Thanks ! So the solution, for now, is either build from source with that tweak or wait for a new release

**Comment by cgohlke** [comment]
Imageio users can ignore the warning.

**Comment by FirefoxMetzger** [comment]
Thanks @cgohlke for chiming in and pointing us to the cause of the problem :)

**Comment by FirefoxMetzger** [comment]
I had to put this issue down due to other obligations, but now I found some time. I tried the file you uploaded using the following snippet:

```python
>>> import imageio as iio
>>> foo = iio.volread("Substack (1-1023).tif")
```

I can reproduce the problem on tifffile v2022.11.2 (though it produces a warning instead of an error). I also tried using our vendored tiffile as well as tifffile v2022.2.2 (released today ❤️ ). For both of these, I didn't see this warning and everything seems to be in order.

@BptGrm Could you upgrade your version of tifffile (`pip install -U tifffile`) and let me know if that solves the problem?

**Comment by BptGrm** [comment]
`pip install -U tifffile` apparently still fetches v2021.11.2 as of now, at least for me.
If I `run pip index versions tifffile` I get :                                                                                 
```
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.                                                              
tifffile (2021.11.2)
Available versions: (listed versions)
INSTALLED: 2021.11.2
LATEST:    2021.11.2  
```

**Comment by FirefoxMetzger** [comment]
Hm, maybe it takes a while for pypi's CDN to distribute the new version around. [This here](https://pypi.org/project/tifffile/) is the tifffile on pypi. If it doesn't show 2022.2.2 today, I'd expect it will do so tomorrow.
