### ISSUE TITLE
Default value for ImageProperties

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#754]
In https://github.com/imageio/imageio/pull/739 we've added `improps`, which serves standardized metadata. One of the values I kept thinking about is `spacing`, which currently defaults to a tuple of `(1,1,1...)` for each dimension of the image. Then in https://github.com/imageio/imageio/pull/753#issuecomment-1040747876 I've made a point that replacing broken/unreadable metadata values with a default can cause hard to spot problems (ironically this was for the TIFF tag resolution, which - unless I am mistaken - is spacing). Because of that, I've been thinking if our default choice for `spacing` was a good decision, and by extension how we should handle other metadata fields (`fps` seems like a good candidate, and I've been getting requests for that).

My current idea would be to change the default value for each field to `None`, which would represent "not set by the ImageResource". Users could then go with their own default value, which I think will be less opinionated. Users could then do something like (though we could come up with better syntax for this):

```python
props = iio.improps(...)
props.spacing = props.spacing or (1,) * len(props.shape)
```

I'm not 100% certain about this approach yet though, so if anybody wants to add some feedback that would be appreciated.

**Comment by almarklein** [comment]
I think this makes sense. That way you also signal that the image data does not specify a spacing, which might be valuable information by itself, which would be lost if imageio applies the default.
