### ISSUE TITLE
Imagoio installation should fail when Numpy version being installed is < 1.20

### ISSUE THREAD

**Issue by AshwinJay101** [imageio/imageio#758]
We were recently installing this on the Conda environment with Pip and our Numpy version was 1.19.x

There was no issue with Pip and the package version 2.16.0 was installed with our Numpy version. During the code execution, this started to fail

We should fail this when we are installing this with Pip which checks the requirements

**Comment by FirefoxMetzger** [comment]
Interesting find. ImageIO v2.16.0 declares numpy >= 1.20 as dependency:

https://github.com/imageio/imageio/blob/f80f068329123fc3c164c522391969ac8eeb0dd4/setup.py#L174

Could it be that you are installing a different package later on that downgrades numpy (tensorflow is among one of the usual suspects here)? 

If not, could you share some more detail on how you are installing imageio so I can work out a way to reproduce this? My naive attempt upgrades numpy along the way:

```
sonny@sonny:~$ pip install numpy==1.19.0
Collecting numpy==1.19.0
  Using cached numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.2
    Uninstalling numpy-1.22.2:
      Successfully uninstalled numpy-1.22.2
Successfully installed numpy-1.19.0
sonny@sonny:~$ pip install imageio
Collecting imageio
  Using cached imageio-2.16.0-py3-none-any.whl (3.3 MB)
Collecting numpy>=1.20.0
  Using cached numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Requirement already satisfied: pillow>=8.3.2 in ./.local/lib/python3.8/site-packages (from imageio) (8.4.0)
Installing collected packages: numpy, imageio
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.0
    Uninstalling numpy-1.19.0:
      Successfully uninstalled numpy-1.19.0
Successfully installed imageio-2.16.0 numpy-1.22.2

```

**Comment by AshwinJay101** [comment]
Yes I was installing Tensorflow 2.5.0 

I also installed scikit-learn 0.24.1

**Comment by FirefoxMetzger** [comment]
> I have a requirements.txt file with these versions and I install it from that file. I specifically install Numpy 1.19.5 but do not mention imageio in the file. That automatically installed the latest version

Ah, pip's dependency hell at its finest :cupid: Which version of pip are you using? (I will guess and say that it is ` pip<21.0`.)

**Comment by FirefoxMetzger** [comment]
Yep. pip 21.0 switches the dependency resolver to one that will use backtracking to resolve dependencies (not 100% if this includes transitive dependencies though). Before that you will get greedy dependency resolution by default, which will lead to the behavior you describe.

Does that solve your problem? If so, we should close the issue to keep things tidy. If not, let me know what's missing.

Sidenote: tensorflow works fine alongside numpy 1.22 on my machine, but if you are forced to use numpy 1.19.5, you can also pin ImageIO to `imageio<2.16.0` which won't need features from numpy 1.20.

**Comment by AshwinJay101** [comment]
Got it

Thanks, yes we can close this issue. Thanks for the quick turnaround
