### ISSUE TITLE
Feature Request: Support TS/MTS format

### ISSUE THREAD

**Issue by Gilthans** [imageio/imageio#762]
Hey,
Would be wonderful if [MPEG Transport Stream](https://en.wikipedia.org/wiki/MPEG_transport_stream) format was supported.
This is already supported with FFMPEG - using the command line, ffmpeg reads it just fine. However, TS and MTS extension is not in the plugin extension list. AFAICT, adding them to the list would add support.

I can try and submit a PR myself, if someone who knows the code base better can get around to it more quickly I'd be thankful!

**Comment by FirefoxMetzger** [comment]
Hmm, would this be a file or an actual stream that comes in via a socket? 

If it is a file, it will likely be supported by https://github.com/imageio/imageio/pull/745 . Additionally, I'd be happy to review a PR adding this extension if you are willing to submit it.

**Comment by FirefoxMetzger** [comment]
Both MTS and TS are now supported when using the [pyav plugin](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pyav.html#module-imageio.plugins.pyav).

```python
>>> import imageio.v3 as iio                                          
>>> frames = iio.imread("imageio:cockatoo.mp4")
>>> iio.imwrite("foo.ts", frames, plugin="pyav", codec="h264")               
>>> iio.imwrite("foo.mts", frames, plugin="pyav", codec="h264")
```

Closing this as fixed, but if you want/need support in imageio-ffmpeg, I'm happy to discuss.
