### ISSUE TITLE
Move type hints into separate module

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#763]
I'm wondering if it is worthwhile to move all of our type hints into a separate module. The reason for this is that we depend on `numpy>=1.20` because we use `numpy.typing.ArrayLike`. This doesn't affect core functionality and it may, hence, be useful to relax this constraint.

**Comment by almarklein** [comment]
Having a dependency on a specific minimum version of numpy just for the type hint is indeed not great.

What would it look like to have the typing in a separate module?

**Comment by FirefoxMetzger** [comment]
I'm not 100% sure actually, so I will have to look into that. I know that it is possible to have annotations separate (mainly intended for packages where maintainers don't add them directly, but you still want them), but I never dug into this. I will have a look once I have dealt with more urgent work :)

**Comment by almarklein** [comment]
As someone who is not a particular fan of type hints, them not "polluting" the code, while still having their benefits sounds appealing :D
