### ISSUE TITLE
Delete py2 branch?

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#765]
@almarklein We have a (very) old and stale branch on this repo called "py2". What is it's use ... and - if we don't need it - can we remove it?

**Comment by almarklein** [comment]
I'm not 100% sure, but I think it's the version of imageio that still works on Python 2. I think we can remove it.

**Comment by FirefoxMetzger** [comment]
Okay, then I will remove it. The suggested way to get python 2 support would be to install the respective version from PyPI.
