### ISSUE TITLE
How to set the gif do not loop

### ISSUE THREAD

**Issue by AaronWaxson** [imageio/imageio#767]
I use a function to create a gif like follow now:
``` python
def create_gif(image_list, gif_name, duration=0.35):
    frames = []
    for image_name in image_list:
        frames.append(imageio.imread(image_name))
    imageio.mimsave(gif_name, frames, 'GIF', duration=duration)
    return
````
The gif shows again and again, but I only want the gif show once and stop. How can I do that?

**Comment by AaronWaxson** [comment]
![dijkstra](https://user-images.githubusercontent.com/37990023/158522294-bc22e7b6-2a98-441c-9ce8-833d37f8e1c7.gif)

It's my gif, and I want it show only once and stop at the end.

**Comment by FirefoxMetzger** [comment]
You specify the number of times the gif should loop using the `loop` kwarg. `loop=0` means loop indefinitely and any number greater than 0 will indicate the number of loops. In the v3 API you can do this via `imwrite` directly:

```python
>>> import imageio.v3 as iio
>>> frames = iio.imread("grid-search.gif", index=None)
>>> iio.imwrite("grid-search-once.gif", frames, duration=0.35, loop=1)
```

![grid-search-once](https://user-images.githubusercontent.com/4402489/158542122-884280f1-b1d8-47da-b123-b40992cf0bd6.gif)

or you stick to v2 and use `mimread` as you are doing now:

```python
>>> import imageio.v2 as iio
>>> iio.mimwrite("grid-search-once.gif", frames, duration=0.35, loop=1)
```

![grid-search-once](https://user-images.githubusercontent.com/4402489/158542706-70e08284-ade0-4d79-b3d8-907195ce4393.gif)

Does that solve your issue?

---

Nice graph btw. Reminds me of [RoboticsPython's GridSearch](https://pythonrobotics.readthedocs.io/en/latest/modules/path_planning/path_planning.html#breadth-first-search)

**Comment by almarklein** [comment]
> Interestingly, the GIF loops twice on GitHub, but only once if I view it in the Windows file explorer

Yeah, the loop variable is interpreted differently - loop 1 could mean *play once*, or *play once and then loop one time*.

This graph reminds me of the [Minumum Cost Path (MCP) method](https://scikit-image.org/docs/stable/api/skimage.graph.html#skimage.graph.MCP) :)

**Comment by AaronWaxson** [comment]
> 
That's very nice, thanks a lot. 
But I have one more question. Is there a mimsave function to control the loops?

--------------------------------------------------------------------------------------------------------------------------------------------

And yes, it's my graduated project based on [RoboticsPython's GridSearch](https://pythonrobotics.readthedocs.io/en/latest/modules/path_planning/path_planning.html#breadth-first-search) 🤣

**Comment by FirefoxMetzger** [comment]
> But I have one more question. Is there a mimsave function to control the loops?

`mimsave` is just an alias for `mimwrite`. Since they are the same function you can use `loop=1` there, too.

https://github.com/imageio/imageio/blob/6c475242282823a73573164fd180dd78871588a4/imageio/__init__.py#L45-L51

As that solves the problem, I will close this issue to keep this repo organized, but feel free to continue commenting if there is anything else.

**Comment by AaronWaxson** [comment]
> 
Thanks！
