### ISSUE TITLE
Remove test_freeimage_suite.py

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#778]
I just ran into the `test_freeimage_suite` file in our testsuite. It doesn't contain any tests for pytest, and I read through it and it seems to run through files in various different formats and checks if freeimage can read them or not.

@almarklein Do you remember what this file is for? If not, any objections to removing it?

**Comment by almarklein** [comment]
Meh, that hasn't been run in years. Sure lets remove.
