### ISSUE TITLE
ffmpeg leaves processes behind

### ISSUE THREAD

**Issue by black-puppydog** [imageio/imageio#79]
Not sure if this is just me doping something stupid, but here goes:

    for f in files:
             try:
                 vol = imageio.mimread(f)
             except Exception as e:
                 print f

This leaves me with this kind of process list:

![leftover_processes](https://cloud.githubusercontent.com/assets/189241/6616346/62e15442-c8ad-11e4-8d16-3c44bb75bfc5.png)

As you can see, this is just a stupid loop to check I can actually load every file in my dataset, HMDB51 btw. Once this loop finishes (with the first error) the process list turns into this:

![zombies](https://cloud.githubusercontent.com/assets/189241/6616469/8b1ea698-c8ae-11e4-87b7-619aa2102cf7.png)

Now the error:

    dataset/files/hmdb51_org/videos/scaled_256/stand/RETURN_OF_THE_KING_stand_u_cm_np1_fr_med_12.avi [Errno 24] Too many open files

looking at the ffmpeg plugin there *is* a `_terminate` function.
It sends a SIGTERM to the process and then waits for one second for it to terminate.
If I add a SIGKILL after the busy waiting the method looks like this:

    def _terminate(self, timeout=1.0):
        """ Terminate the sub process.
        """
        # Check
        if self._proc is None:  # pragma: no cover
            return  # no process
        if self._proc.poll() is not None:
            return  # process already dead
        # Terminate process
        self._proc.terminate()
        # Wait for it to close (but do not get stuck)
        etime = time.time() + timeout
        while time.time() < etime:
            time.sleep(0.01)
            if self._proc.poll() is not None:
                break
        if self._proc.poll() is None:
            print('killing process')
            self._proc.kill()

And the kill seems to be called every time.
Any idea what's happening?
I am on Fedora 21 btw.

    ~/.imageio/ffmpeg/ffmpeg.linux64 -version
    ffmpeg version 2.4.2-   http://johnvansickle.com/ffmpeg/    Copyright (c) 2000-2014 the FFmpeg developers
    built on Oct  9 2014 07:24:56 with gcc 4.8 (Debian 4.8.3-11)
    configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --disable-ffserver --enable-libass --enable-gnutls --cc=gcc-4.8
    libavutil      54.  7.100 / 54.  7.100
    libavcodec     56.  1.100 / 56.  1.100
    libavformat    56.  4.101 / 56.  4.101
    libavdevice    56.  0.100 / 56.  0.100
    libavfilter     5.  1.100 /  5.  1.100
    libswscale      3.  0.100 /  3.  0.100
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  0.100 / 53.  0.100

**Comment by almarklein** [comment]
Ai, I can reproduce this. Strange, I'm pretty sure it worked when I wrote that `_terminate()` function.

Anyway, if your kill tweak works, we can include that. Care for a PR with the fix?

**Comment by black-puppydog** [comment]
Seems more like a hack than a fix to me :P

**Comment by almarklein** [comment]
Well yeah, I'd prefer it if the process would just terminate by itself, but if it doesn't, I suppose we have to kill it. Unless we can find out the reason why ffmpeg won't listen to our request to terminate ...
