### ISSUE TITLE
Is it possible to pass arbitrary arguments to ffmpeg with get_writer()

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#80]
I would like to pass arguments like: bitrate, file for soundtrack, etc... and could not find an easy way, from the code I wonder if it's even possible. Thanks in advance !

**Comment by almarklein** [comment]
See http://imageio.readthedocs.org/en/latest/format_ffmpeg.html#parameters-for-saving

You can set the fps, codec and bitrate, but no other parameters are "exposed" at the moment. I'd be happy to add more parameters though. PR's welcome :)

**Comment by almarklein** [comment]
Maybe we just need one `ffmpeg_params` argument to specify *any* ffmpeg argument. The user would have to know about ffmpeg, but it would be very flexible.

**Comment by Zulko** [comment]
Yes, that's what is done in MoviePy at the moment. If you want I can make a PR.

**Comment by almarklein** [comment]
That would be great!

**Comment by almarklein** [comment]
Done in #83
