### ISSUE TITLE
Reading raw/encoded video?

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#803]
<div type='discussions-op-text'>

<sup>Originally posted by **daveisfera** April 28, 2022</sup>
Is it possible to read the raw/encoded video from a file? Basically, the standard way of using `imageio` decodes each frame of the video into an image, but is there a way to read the raw frames that are still encoded?

On a similar note, is there a way to read the encoded frames when "writing" a video? (i.e. access them in the memory of the application instead of them being written to a file)</div>

@daveisfera I'm converting your discussion into an issue, and I will answer in a dedicated comment below.

So far we haven't been using discussions, and I don't think there is so much velocity in the issues that we loose track of questions like this :) I will also close down discussions to avoid confusion in the future (@almarklein please let me know if you have any objections to this.)

**Comment by FirefoxMetzger** [comment]
> Is it possible to read the raw/encoded video from a file? Basically, the standard way of using imageio decodes each frame of the video into an image, but is there a way to read the raw frames that are still encoded?

You can always read the raw byte string using `open`, or `pathlib` (which I prefer). This applies to any file on your filesystem.

```python
from pathlib import Path

raw_content = Path("my_video.mp4").read_bytes()
```

If you are asking if it is possible to read the individual packets of a video without decoding them, then also, yes that is possible by - for example - using `pyav` directly. That said, it may not be as useful as you think it is because there is no correspondence between packets and frames, i.e., the information needed to decode one frame may be spread over one or multiple packets, and one packet may contain information relevant for one or multiple frames. It all depends on the used codec, profile and specifics of the video, so unless you have a specialist use-case for messing with this it is often easier not to.

> On a similar note, is there a way to read the encoded frames when "writing" a video? (i.e. access them in the memory of the application instead of them being written to a file)

Of course, you can write them into either a `io.BytesIO` object or have ImageIO return them as `bytes` directly. In the case of the former, you can do incremental writes and introspect the buffer in between. In the case of the latter, you can only write once and will immediately get the result back (because `bytes` are immutable so we can't append frames). Neither of these options will touch your filesystem, so everything will stay in RAM.

```python
import imageio.v3 as iio
import io

frames = iio.imread("imageio:cockatoo.mp4")

encoded_bytes = iio.imwrite("<bytes>", frames)

buffer = io.BytesIO()
iio.imwrite(buffer, frames)
buffer.seek(0)
```

Keep in mind though, that video backends typically buffer frames internally as you append them to allow for better compression. This means that (by default) there is no guarantee as to when a frame will be written to a file/BytesIO until you finish writing (at which point all internally buffered frames will be flushed).

**Comment by FirefoxMetzger** [comment]
@daveisfera Does this answer your question, or did I misunderstand what you were asking about?

**Comment by daveisfera** [comment]
That makes total sense. My use case is with Kinesis Video Streams and it [needs an encoded input](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html). It sounds like `pyav` will be the best potential route, so I'll take a look at that.

**Comment by FirefoxMetzger** [comment]
@daveisfera Yes `pyav` or a more custom-built solution seem like the way to go here. Handling streams in ImageIO is something that isn't implemented yet; however, it is on the roadmap.

Reading through the docs you've shared, I've noticed that the Kinesis Video Stream format seems to be chunking Matroska (mkv) specifically at the boundaries of its binary chunks (mkv calls them segments). This is quite specific to mkv and not something that fits into the high-level FFmpeg API, which is the one that `pyav` exposes. Do you happen to know if this streaming method is a standard format with an explicit name? If so, you might be able to find direct support for it in FFmpeg, which could save you a lot of time and headache.

**Comment by daveisfera** [comment]
It's basically a fragment for HLS streaming. KVS has each of the fragments be a standalone series of frames with each key frame and the rest of the frames packaged in a Matroska container. They have a [Producer SDK](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk.html) to take care of all of that packaging and network requests, but to get the contents of an H.264 or H.265 file into KVS, I need to read the raw/encoded data and pass it to the Producer SDK.

**Comment by FirefoxMetzger** [comment]
@daveisfera Did you make any headway on this problem and/or is this still an issue for you? 

Since ImageIO doesn't support streams at the moment I'm tempted to close the issue; however, there might be an opportunity for an enhancement here. What do you think?
