### ISSUE TITLE
Apparent bug in `imageio.v3.imwrite`

### ISSUE THREAD

**Issue by bwohlberg** [imageio/imageio#810]
There appears to be a bug in the v3 API related to saving TIFF files. The following simple test script
```python
import numpy as np
import imageio.v3 as iio

v = np.zeros((32, 32), dtype=np.uint16)
iio.imwrite("v.tif", v)
```
fails with error `ValueError: Image must be 3D, or 4D if each voxel is a tuple.` The same example functions correctly when using `import imageio.v2 as iio`. This test was run with the `tifffile` package installed and `imageio` 2.19.1.

**Comment by FirefoxMetzger** [comment]
Thanks for the report; I can reproduce this on master. 

Looks like I missed a case inside a `if/elif/else` block of the legacy plugin wrapper. It should be an easy fix, so I will submit a PR that fixes this soon.
