### ISSUE TITLE
Images to video - Won't play back. Freezes after 725 images.

### ISSUE THREAD

**Issue by tehUsual** [imageio/imageio#84]
I've asked about the issue on stackoverflow, the link is here: http://stackoverflow.com/questions/30583873/ffmpeg-image-to-video-images-from-ram-python

INFO: Running Python 2.7.9/10 on Windows 7. Imageio downloaded from pip.
These are the two main problems
1) After creating an .mp4 file from several images(.png), it wont play back. The file does not have a thumbnail either. I've tried with both windows player, and vlc player.
2) My program looks for a path in a custom maze (explained in link), and makes an image for every step it makes. It creates 4840 images, and on the first prototype, I saved every image with PIL in a folder, and then ran FFMPEG commands from the command-line. This did the job, but when I try to add images on the go (from RAM) with "writer.append_data(image)", it just stops at 725 images. I confirmed this by adding "print loopCount" to my program. Nothing happens, no crash, just full stop.

**Comment by almarklein** [comment]
Does this happen also when you try to write 4840 images of random noise (e.g. with `np.random.uniform(0, 255, (N, M, 3))`)?

**Comment by almarklein** [comment]
Also note #83 which might solve the issue nr 1.

**Comment by tehUsual** [comment]
Something wierd i going on. I just tried to run my full program again, and this time it stopped at 701. A new test 2 minutes later, it stopped at 840ish.
Then I tried your np.random.uniform line, and I got to 1627. The second test landed at 1568.
I'm currently testing this on my laptop with a 2.5GHz CPU. The odd thing is tat my fans start to speed up at the exact moment the process stops.

**Comment by kuchi** [comment]
For 1), what player are you trying to play the videos with?  Try playing them with ffplay as a double check.

For 2) sounds like you might have some memory leak / accumulation of jumpy arrays and you are running out of memory. Make a new simple script that is only a loop that makes a video of random noise. Post the simple script if it still fails.

**Comment by tehUsual** [comment]
1) I'll try that later, in the mean time.. nr2)
2) This is the code I ran yesterday with random noise: http://pastebin.com/4QqQWdJv Just tried it again, stopped at 1503.

**Comment by kuchi** [comment]
For 2) I tried the pastebin code, works fine for me and runs very fast. I'm running OS X though. I'll have to try it on windows tomorrow at work.

Try installing this forked branch with the ffmpeg defaults fixed to work better in most players. After installing, that should fix your problem of the videos not playing on windows.  To install, run in your terminal:

    pip install --upgrade git+https://github.com/kuchi/imageio.git@ffmpeg-enhance#egg=imageio

To go back to the stable imageio, just run

    pip install --upgrade --force imageio

**Comment by tehUsual** [comment]
Video do playback when I succesfully executes the program (i.e. 200 loops), but not when canceled by user after freeze, even though I'm manually adding `writer.close()`.

**After updating your fork branch:**
Video playback when I succesfully executes the program (i.e 200 loops), and now there's a thumbnail showing too. The same freezing problem is there too.

As additional information, I did a clean install of windows 2 days ago, and it was the same problem before clean install.

**Comment by kuchi** [comment]
I updated the ffmpeg-enhance branch, install the updated fork:
    pip install --upgrade --force git+https://github.com/kuchi/imageio.git@ffmpeg-enhance#egg=imageio

Then run the following, you should get more output that may help debug what is going on:


```python
import numpy as np
import imageio
writer = imageio.get_writer('some_file.mp4', fps=30,
                            ffmpeg_args=['-v', 'verbose'], verbose=True)
for index in xrange(4096):
    ar = np.random.uniform(0, 255, (100, 100, 3))
    writer.append_data(ar)
    print index
writer.close()
```

**Comment by kuchi** [comment]
I've had this same issue on windows with a ffmpeg python wrapper I wrote a while back. That's one reason I was moving to imageio to have one good ffmpeg wrapper rather than roll my own.  I think your problem may be due to the stderr buffer filling up and somehow behaving differently on windows than nix based systems. Try the above code I posted to use the verbose option with the updated branch. That stops the stderr redirection and may fix the issue. Let me know if that works. Then I think imageio has a StreamCatcher that can be used for the stderr stream to maybe fix this?

**Comment by tehUsual** [comment]
The code above ran withouth any freezes. However, my pathfinder to video is broken. I get this error: `Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`. A few lines up, it outputs `[libx264 @ 0037d780] width not divisible by 2 (101x101)`. Do the picture have to be divisible by 2?

If it helps;
Here's a consol output of the error: http://pastebin.com/Av2Kn2U2
Here's the code that converts my list to a np.array: http://pastebin.com/BERQEM73

**Comment by kuchi** [comment]
For certain codecs like h264, the videos must have an even number of pixels. So you'll have to use 100x100 or something like that.

Can you run the following and let me know if it works, this will isolate if it's a stderr issue on windows:

```python 
import numpy as np
import imageio
writer = imageio.get_writer('some_file.mp4', fps=30, verbose=True)
for index in xrange(4096):
    ar = np.random.uniform(0, 255, (100, 100, 3))
    writer.append_data(ar)
    print index
writer.close()
```

**Comment by kuchi** [comment]
If you need to have odd frame sizes, try a different codec, this 'mpeg4' works for odd sizes:

    writer = imageio.get_writer('some_file.mp4', fps=30, codec='mpeg4')

**Comment by tehUsual** [comment]
`writer = imageio.get_writer('some_file.mp4', fps=30, codec='mpeg4')` made my video, though I have to work a bit with it to upscale it to a more comfortable size, as 101x101 is to small.

`ffprobe` gave me this: http://pastebin.com/YPmtXMFt

**Comment by kuchi** [comment]
I updated the ffmpeg-enhance branch, let's see if your issue is now fixed so you don't have to use the verbose option, run:

    pip install --upgrade --force git+https://github.com/kuchi/imageio.git@ffmpeg-enhance#egg=imageio

Then, see if this works:

```python
import numpy as np
import imageio
writer = imageio.get_writer('some_file.mp4', fps=30)
for index in xrange(4096):
    ar = np.random.uniform(0, 255, (100, 100, 3))
    writer.append_data(ar)
    print index
writer.close()
```

**Comment by tehUsual** [comment]
Everything works perfectly now! I'll have to rewrite some code to make adapt to the np.array apporach. As a thank you, here's a video of it in action: https://www.dropbox.com/s/qvbsse578spcrnt/Maze%202.1%20Video.mp4?dl=0

But how about the future? Do I just ignore the verbose option?

**Comment by kuchi** [comment]
Awesome to see the video of how your code solve the problem. Nice work.

Sounds like we have the issue solved, the verbose option was just to help figure out the problem. So you don't need to use it anymore. But if you run into other issues you can turn it on to help debug. The main issue was the stdout stream getting full on windows due to how it handles streams.  Hopefully this pull request can get merged into the master branch but until then you'll need to keep using the other branch.

**Comment by tehUsual** [comment]
Thanks for everything! If I find any other problems, i'll contact you.

**Comment by almarklein** [comment]
Wow, thanks to both of you; it's nice to see how the two of you worked out the problem!

**Comment by tehUsual** [comment]
Also, it would be nice if someone would post a solution to the problem at stackoverflow: http://stackoverflow.com/questions/30583873/ffmpeg-image-to-video-images-from-ram-python this way other people with the same problem will have a working solution until the problem is permanently fixed.
