### ISSUE TITLE
pyav testing (wrongly) requires ffmpeg plugin to be installed

### ISSUE THREAD

**Issue by anjos** [imageio/imageio#856]
This seems like a bug introduced on a couple of releases back.  The test function `test_sequential_reading()` from ` tests/test_pyav.py` is failing on conda-forge builds (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=544225&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d).   The reason, I think, could be as simple as a missing `plugin="pyav",` on calls to `iio.imread()`?

**Comment by FirefoxMetzger** [comment]
Interesting find @anjos . In theory ImageIO should, if no plugin is explicitly given, step over missing plugins and try the next. As such, if imageio-ffmpeg is missing, it should default to pyav.

You are correct that `plugin="pyav"` will likely fix this; however, this might be a symptom of a different underlying cause. I will have a look during the week :)

**Comment by anjos** [comment]
OK, so we have package, I'll patch this like so for the time being on conda-forge.
