### ISSUE TITLE
imread can't read dicom in v3, but v2 can

### ISSUE THREAD

**Issue by promedius-dkyun** [imageio/imageio#862]
python: 3.8
imageio: 2.21.1
python-gdcm: 3.0.15

it seems related request.mode.
in v3, mode is set to "r?".
in v2, mode is set to "ri".

**Comment by FirefoxMetzger** [comment]
Indeed, I can produce an error using the following snippet:

```python
import imageio.v3 as iio

iio.imread("https://github.com/imageio/test_images/raw/main/dicom_file01.dcm")
```

I must admit that I am not very familiar with DICOM as a format yet, so I can't say exactly how complicated an issue this is. In general, we are moving away from using an image mode (`v`, `i`, `?`, ...) and instead rely on the file's metadata to tell us how the image should be read. This is possible for most formats and I suspect it works with DICOM as well, so I would prefer a solution that doesn't involve setting the image mode.
