### ISSUE TITLE
PNG-FI format error

### ISSUE THREAD

**Issue by biphasic** [imageio/imageio#867]
Hello,
I'm trying to read a file according to some instructions.

```
imageio.imread('filename.png', format='PNG-FI')
```
Versions I've tried with are 2.14.1 and 2.21.1

Both times I receive the following stacktrace: 

```
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/core/imopen.py", line 163, in imopen
    return loader(request, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/core/imopen.py", line 152, in loader
    return config.plugin_class(request, **kwargs)
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/core/legacy_plugin_wrapper.py", line 68, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `PNG-FI` can not read `/home/user/filename.png`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/core/functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "/home/user/anaconda3/lib/python3.8/site-packages/imageio/core/imopen.py", line 181, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `PNG-FI` can not handle the given uri.
```

My colleague runs the same line on the same file with the same imageio version and it works. I tried installing imageio into a new conda environment but I always get this error. I didn't find anything about this PNG-FI format, do you have an idea why I receive this error? Thank you very much

**Comment by biphasic** [comment]
This is an example file that I'm trying to read. It works when I don't specify the format, but then I don't get the results I need.

![000164](https://user-images.githubusercontent.com/11279568/186648237-64c3655e-476d-4f70-a802-e238e9cadf49.png)

**Comment by FirefoxMetzger** [comment]
`PNG-FI` refers to our v2 [FreeImage plugin](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.freeimage.html#module-imageio.plugins.freeimage). The same is true for all other plugins that end with `-FI`. 

Unfortunately, I can't replicate the issue because the image loads fine for me, too:

```python
>>> import imageio.v3 as iio
>>> img = iio.imread("https://user-images.githubusercontent.com/11279568/186648237-64c3655e-476d-4f70-a802-e238e9cadf49.png", plugin="PNG-FI")
>>> img.shape
(480, 640, 3)
>>> import imageio.v2 as iio2
>>> img = iio2.imread("https://user-images.githubusercontent.com/11279568/186648237-64c3655e-476d-4f70-a802-e238e9cadf49.png", format="PNG-FI")
>>> img.shape
(480, 640, 3)
```

Did you make sure to install the FreeImage library before trying to make the call? (`imageio.plugins.freeimage.download()`)

> It works when I don't specify the format, but then I don't get the results I need.

If you don't specify a plugin explicitly, ImageIO will attempt to identify the file format and choose an appropriate backend for you. For PNG we default to using pillow, because compared to freeimage it is more performant (faster) and still actively maintained. You mentioned that this "doesn't get the results you need". What results were you expecting?

**Comment by biphasic** [comment]
that solved it, thank you so much! It would be great if a search for 'PNG-FI' would somewhere relate to the freeimage library or some description at least.

**Comment by FirefoxMetzger** [comment]
Yes, that the search functionality provided by read the docs, unfortunately, rarely finds what I am looking for. This isn't just ImageIO related but also true for all other projects that I've tried the search engine on. I'm no expert in this domain though, so not sure if this can be improved somehow...

Regarding which names are chosen for which plugin, we have a [list of all plugins](https://imageio.readthedocs.io/en/stable/reference/index.html#plugins-backend-libraries) we are aware of as well as a [list of supported formats](https://imageio.readthedocs.io/en/stable/formats/index.html). The later lists all the plugins that a format supports using the name they are registered with and a xref to the respective plugin's docs. You can read about how to use this list [here](https://imageio.readthedocs.io/en/stable/formats/index.html#all-formats). For PNG it says:

![image](https://user-images.githubusercontent.com/4402489/186692135-dbbe7504-01e5-4a0a-a986-df5fe8573473.png)

which are all the names that the [`plugin=` kwarg](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.imread.html#imageio.v3.imread) recognizes and clicking on any name will direct you to the plugin behind it.

**Comment by biphasic** [comment]
you're right, it is there! I guess I had a strong prior to some docstring that would explain parameter args and hence overlooked the result. Thanks for the library :)

**Comment by FirefoxMetzger** [comment]
We could add a reference to the supported formats list to the docstring, which might make it more obvious where to look for this information. I'll see if I can add that once I have some spare time.
