### ISSUE TITLE
 ValueError("Not an SGI image file") ValueError: Not an SGI image file

### ISSUE THREAD

**Issue by jinfagang** [imageio/imageio#874]
same image can not read by: 

```
a = imageio.imread('results/21_1/tmp_images/000001.png', format='RGB')
```

but without format can read. why?

opencv can read normally.

**Comment by FirefoxMetzger** [comment]
Given the syntax you used, I am assuming that you are importing imageio via `import imageio`. In this case, you are using [v2.imread](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v2.imread.html#imageio.v2.imread) and `format=` is a keyword argument that specifies the plugin/backend to use when reading. `RGB` is not a registered format, so the reading will fail. In v3 (where the kwarg is called `plugin=` to free the name `format`) you will get a clear error message that the plugin `RGB` does not exist; however, in v2 the error message is a bit less clean (though both cases fail).

Assuming that all you want is to read a PNG image as RGB, you could use this syntax:

```python
import imageio.v3 as iio

img = iio.imread("results/21_1/tmp_images/000001.png", mode="RGB")
```

**Comment by jinfagang** [comment]
I turned into opencv.... you guys are makeing a simple thing so much more complicated.

**Comment by almarklein** [comment]
The only problem was that you expected the argument to be `format` while it should have been `mode`. Please don't confuse that with "making a simple thing complicated" 🤷 . (The `format` arg is something else (which is incidentally being in flux because we're moving to a new API))

**Comment by jinfagang** [comment]
Because we only need `imageio.imread` but not `imageio.v2.imread` `imageio.v3.imread`......
