### ISSUE TITLE
OSError: Could not load meta information

### ISSUE THREAD

**Issue by lp20010415** [imageio/imageio#876]
![2](https://user-images.githubusercontent.com/56969920/189467368-87bd9b4a-30ee-4556-b863-6311271dfc8e.png)

At first, I used version 2.9, and then this problem occurred. But I still have the latest version

**Comment by FirefoxMetzger** [comment]
Hard to say what is happening without knowing some more context. Could you share some example code that produces this exception?

**Comment by FirefoxMetzger** [comment]
Hm, chances are that the metadata of the MP4 file you try to read is corrupted. That's about as specific as I can be without access to the file. 

Here is the same snippet with one of our standard images, which runs fine on my machine:

```python
>>> import imageio.v2 as iio 
>>> frames = iio.mimread("imageio:cockatoo.mp4", memtest=False)
```

You could try to read the image using the v3 API:

```python
import imageio.v3 as iio

video_path = r'E:\python-workspace\studyPython\深度学习\视频画质修复，上色\data\圣哥传OAD2_30s.mp4'
print(video_path)
frames = iio.imrea(video_path)
```

If that doesn't work, try installing pyav (`pip install pyav`) and use it as backend:

```python
import imageio.v3 as iio

video_path = r'E:\python-workspace\studyPython\深度学习\视频画质修复，上色\data\圣哥传OAD2_30s.mp4'
print(video_path)
frames = iio.imrea(video_path, plugin="pyav")
```

Our pyav plugin separates reading metadata and decoding pixel data. As a consequence, it might be able to cope with the corruption in the metadata by simply skipping over it and only reading pixel data.

**Comment by lp20010415** [comment]
Thank you. No.3 it works.

**Comment by FirefoxMetzger** [comment]
Great! Then I will close this issue as solved. Feel free to comment if there is more and we can reopen as needed.
