### ISSUE TITLE
Saving TIFF files with v3 API and using the compression keyword results in unexpected argument

### ISSUE THREAD

**Issue by lagru** [imageio/imageio#893]
### Description:

I am struggling to make compression work when saving a TIFF with imageio's v3 API (see the reproducing code below). From the [plugin documenation](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.tifffile.html#metadata-for-writing) I get the impression that some form of compression is supported (previous version of tifffile used `compress`, now it's called `compression`). I've also tried specifying `plugin='TIFF'` and `plugin='TIFF-PIL'` explicitly with a similar outcome. Same behavior if I uninstall tifffile. Is imageio perhaps not detecting the externally installed tifffile package?

I would be grateful for guidance on how to save compressed TIFF-files with the v3 API.

### Code to reproduce:

```python
import tifffile  # version 2022.10.10
import numpy as np
import imageio.v3 as iio  # version 2.22.2
import imageio.v2 as iio2

image = np.ones((3, 4))

tifffile.imwrite("/tmp/foo.tiff", data=image, compression="zlib")  # works fine
with iio2.get_writer("/tmp/baz.tiff", mode="i") as writer:
    writer.append_data(image, {"compression": "zlib"})  # works fine

iio.imwrite(uri="/tmp/bar.tiff", image=np.ones((3, 3)), compression="zlib")  # raises
# TypeError: TiffFormat.Writer._open() got an unexpected keyword argument 'compression'
with iio.imopen("/tmp/bar.tiff", "w") as file:
    file.write(image, compression="zlib")  # raises 
# TypeError: TiffFormat.Writer._open() got an unexpected keyword argument 'compression'
```

<details>
<summary>imageio.plugins.formats.show()</summary>

`imageio.plugins.formats.show()` prints:
```
TIFF - TIFF format [.tif .tiff .stk .lsm]
BMP-PIL - Windows Bitmap via Pillow [.bmp]
BUFR-PIL - BUFR via Pillow [.bufr]
CUR-PIL - Windows Cursor via Pillow [.cur]
DCX-PIL - Intel DCX via Pillow [.dcx]
DDS-PIL - DirectDraw Surface via Pillow [.dds]
DIB-PIL - Windows Bitmap via Pillow []
EPS-PIL - Encapsulated Postscript via Pillow [.ps .eps]
FITS-PIL - FITS via Pillow [.fit .fits]
FLI-PIL - Autodesk FLI/FLC Animation via Pillow [.fli .flc]
FPX-PIL - FlashPix via Pillow [.fpx]
FTEX-PIL - Texture File Format (IW2:EOC) via Pillow [.ftc .ftu]
GBR-PIL - GIMP brush file via Pillow [.gbr]
GIF-PIL - Compuserve GIF via Pillow [.gif]
GRIB-PIL - GRIB via Pillow [.grib]
HDF5-PIL - HDF5 via Pillow [.h5 .hdf]
ICNS-PIL - Mac OS icns resource via Pillow [.icns]
ICO-PIL - Windows Icon via Pillow [.ico]
IM-PIL - IFUNC Image Memory via Pillow [.im]
IMT-PIL - IM Tools via Pillow []
IPTC-PIL - IPTC/NAA via Pillow [.iim]
JPEG-PIL - JPEG (ISO 10918) via Pillow [.jfif .jpe .jpg .jpeg]
JPEG2000-PIL - JPEG 2000 (ISO 15444) via Pillow [.jp2 .j2k .jpc .jpf .jpx .j2c]
MCIDAS-PIL - McIdas area file via Pillow []
MIC-PIL - Microsoft Image Composer via Pillow [.mic]
MPO-PIL - MPO (CIPA DC-007) via Pillow [.mpo]
MSP-PIL - Windows Paint via Pillow [.msp]
PCD-PIL - Kodak PhotoCD via Pillow [.pcd]
PCX-PIL - Paintbrush via Pillow [.pcx]
PIXAR-PIL - PIXAR raster image via Pillow [.pxr]
PNG-PIL - Portable network graphics via Pillow [.png]
PPM-PIL - Pbmplus image via Pillow [.pbm .pgm .ppm]
PSD-PIL - Adobe Photoshop via Pillow [.psd]
SGI-PIL - SGI Image File Format via Pillow [.bw .rgb .rgba .sgi]
SPIDER-PIL - Spider 2D image via Pillow []
SUN-PIL - Sun Raster File via Pillow [.ras]
TGA-PIL - Targa via Pillow [.tga]
TIFF-PIL - Adobe TIFF via Pillow [.tif .tiff]
WMF-PIL - Windows Metafile via Pillow [.wmf .emf]
XBM-PIL - X11 Bitmap via Pillow [.xbm]
XPM-PIL - X11 Pixel Map via Pillow [.xpm]
XVTHUMB-PIL - XV thumbnail image via Pillow []
BSDF - Format based on the Binary Structured Data Format [.bsdf]
DICOM - Digital Imaging and Communications in Medicine [.dcm .ct .mri]
FEI - FEI-SEM TIFF format [['.tif', '.tiff']]
FITS - Flexible Image Transport System (FITS) format [.fits .fit .fts .fz]
GDAL - Geospatial Data Abstraction Library [.tiff  .tif .img .ecw .jpg .jpeg]
ITK - Insight Segmentation and Registration Toolkit (ITK) format [.gipl .ipl .mha .mhd .nhdr .nia .hdr .nrrd .nii .nii.gz .img .img.gz .vtk .hdf5 .lsm .mnc .mnc2 .mgh .mnc .pic .bmp .jpeg .jpg .png .tiff .tif .dicom .dcm .gdcm]
NPZ - Numpy's compressed array format [.npz]
SPE - SPE file format [.spe]
SWF - Shockwave flash [.swf]
SCREENGRAB - Grab screenshots (Windows and OS X only) [[]]
CLIPBOARDGRAB - Grab from clipboard (Windows only) [[]]
LYTRO-LFR - Lytro Illum lfr image file [.lfr]
LYTRO-ILLUM-RAW - Lytro Illum raw image file [.raw]
LYTRO-LFP - Lytro F01 lfp image file [.lfp]
LYTRO-F01-RAW - Lytro F01 raw image file [.raw]
BMP-FI - Windows or OS/2 Bitmap [.bmp]
CUT-FI - Dr. Halo [.cut]
DDS-FI - DirectX Surface [.dds]
EXR-FI - ILM OpenEXR [.exr]
G3-FI - Raw fax format CCITT G.3 [.g3]
GIF-FI - Static and animated gif (FreeImage) [.gif]
HDR-FI - High Dynamic Range Image [.hdr]
ICO-FI - Windows Icon [.ico]
IFF-FI - IFF Interleaved Bitmap [.iff .lbm]
J2K-FI - JPEG-2000 codestream [.j2k .j2c]
JNG-FI - JPEG Network Graphics [.jng]
JP2-FI - JPEG-2000 File Format [.jp2]
JPEG-FI - JPEG - JFIF Compliant [.jpg .jif .jpeg .jpe]
JPEG-XR-FI - JPEG XR image format [.jxr .wdp .hdp]
KOALA-FI - C64 Koala Graphics [.koa]
PBM-FI - Portable Bitmap (ASCII) [.pbm]
PBMRAW-FI - Portable Bitmap (RAW) [.pbm]
PCD-FI - Kodak PhotoCD [.pcd]
PCX-FI - Zsoft Paintbrush [.pcx]
PFM-FI - Portable floatmap [.pfm]
PGM-FI - Portable Greymap (ASCII) [.pgm]
PGMRAW-FI - Portable Greymap (RAW) [.pgm]
PICT-FI - Macintosh PICT [.pct .pict .pic]
PNG-FI - Portable Network Graphics [.png]
PPM-FI - Portable Pixelmap (ASCII) [.ppm]
PPMRAW-FI - Portable Pixelmap (RAW) [.ppm]
PSD-FI - Adobe Photoshop [.psd]
RAS-FI - Sun Raster Image [.ras]
RAW-FI - RAW camera image [.3fr .arw .bay .bmq .cap .cine .cr2 .crw .cs1 .dc2 .dcr .drf .dsc .dng .erf .fff .ia .iiq .k25 .kc2 .kdc .mdc .mef .mos .mrw .nef .nrw .orf .pef .ptx .pxn .qtk .raf .raw .rdc .rw2 .rwl .rwz .sr2 .srf .srw .sti]
SGI-FI - SGI Image Format [.sgi .rgb .rgba .bw]
TARGA-FI - Truevision Targa [.tga .targa]
TIFF-FI - Tagged Image File Format [.tif .tiff]
WBMP-FI - Wireless Bitmap [.wap .wbmp .wbm]
WEBP-FI - Google WebP image format [.webp]
XBM-FI - X11 Bitmap Format [.xbm]
XPM-FI - X11 Pixmap Format [.xpm]
```

</details>

I'm happy to provide more information if required.

**Comment by xkszltl** [comment]
Hit similar issue too, but with an important difference:
Have you ever checked where the "works fine" part actually works?
Is the TIFF really compressed?

At least on my side it's not.
There's a `_sanitize_meta()` call, which silently drops all args it's not familiar with.
And somehow the whitelist only has "compress", not "compression".
So if you say `writer.append_data(img, {"compress": "zlib"})`, that'll actually be passed to tifffile and return a unknown arg error; if you say "compression", nothing would happen.

- https://github.com/imageio/imageio/blob/93e2919c8dbe921bb5742ed41f81dc510b25e1e8/imageio/plugins/tifffile.py#L193
- https://github.com/imageio/imageio/blob/93e2919c8dbe921bb5742ed41f81dc510b25e1e8/imageio/plugins/tifffile.py#L523-L534

I don't know if this is a historical issue or just a typo, but I do have a workaround:
- `imageio.plugins.tifffile.TiffFormat.Writer._sanitize_meta = lambda cls, meta: meta`

**Comment by xkszltl** [comment]
And AFAIK v3 code path to TIFF, via LegacyPlugin, simply won't pass down any flag, so don't bother to struggle with that:
- https://github.com/imageio/imageio/blob/93e2919c8dbe921bb5742ed41f81dc510b25e1e8/imageio/core/legacy_plugin_wrapper.py#L251

Correct me if I'm wrong.

**Comment by FirefoxMetzger** [comment]
There are multiple parts to this; however, the bottom line is that `compression` is not supported by the current tifffile plugin and thus creates problems. 

The reason for this is two-fold: The first is that our tifffile plugin still uses our old plugin API which explicitly validates kwargs and drops unrecognized ones (as pointed out by @xkszltl ). This causes problems with `compression` (new kwarg, not recognized by us) and `compress` (old kwarg, no longer recognized by tifffile). The other is that, for plugins that still use the old API, `**kwargs` passed to `imwrite` or `file.write` are internally passed to `format.get_writer`, i.e., you can use the [Parameters for saving](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.tifffile.html#parameters-for-saving), but not the ["Metadata for Writing"](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.tifffile.html#metadata-for-writing) in the v3 API, which would have to be passed to `writer.append_data`.

I see two possible ways forward: (1) We introduce a `metadata` kwarg for v3's LegacyPluginWrapper that passes a dict of `metadata` to `writer.append_data`. On top, we add `compression` and `compressionargs` to the list of supported metadata keys in the tifffile plugin, potentially adding a deprecation notice for `compression`. (2) We write a v3 plugin for tifffile, which can directly forward the available kwargs to tifffile without having to jump through validation hoops. The former would be patching this particular problem (we have to revisit this as tifffile improves), the latter would be the long-term maintainable solution.

My preferred approach would be to add a v3 plugin for tifffile that can supersede the current plugin, but right now there is nobody working on this. It would be a fairly straight-forward contribution though, so if anybody is interested let me know :)

**Comment by xkszltl** [comment]
I agree v3 plugin would be much better, but the short term workaround can be a normal way to suppress unnecessary validation or to forward `compress` to `compression` based on tiffile's version.
IMO any "validation" like this is not forward compatibility, because you're simply asserting the current API, so at least a suppression flag should be provided for user to override the behavior.

**Comment by lagru** [comment]
@FirefoxMetzger, thank you for for the quick fix. :+1:
