### ISSUE TITLE
Webcam frames are all the same

### ISSUE THREAD

**Issue by yukw777** [imageio/imageio#898]
I just followed the example code to capture frames from my webcam, but the frames I get are all the same (the initial image). Here's a minimal reproducible example:

Running on MacBook Air (M2, 2022) macOS Monterey 12.6, python3.9, imageio 2.22.3

```python
import imageio.v3 as iio
import numpy as np

prev_frame = None
for idx, frame in enumerate(iio.imiter("<video0>")):
    if prev_frame is None:
        prev_frame = frame
        continue
    print(np.array_equal(frame, prev_frame))
    prev_frame = frame
```

You'll notice that it only outputs True despite you moving in front of the camera.

**Comment by almarklein** [comment]
I can indeed reproduce this.  A somewhat lower level example, using imageio_ffmpeg directly:
```py
import time
import numpy as np
import imageio_ffmpeg

iargs = ['-framerate', '30.0', '-f', 'avfoundation']
oargs = []
read_gen = imageio_ffmpeg.read_frames(
    "0", "rgb24", 3, input_params=iargs, output_params=oargs
)
read_gen.__next__()  # meta
for i in range(20):
    frame = read_gen.__next__()
    time.sleep(0.1)
    a = np.frombuffer(frame, dtype=np.uint8).copy()
    print(i, a.mean())
```

**Comment by almarklein** [comment]
I found that by specifying a framerate the issue can be resolved. In my example this would be adding `["-r", 30]` to the input args. In the top example that would mean using `iio.imiter("<video0>", fps=30)`.

The number to use does not matter for it to work. It does not have to match the actual camera's framerate. From some small experiments it seems to be clipped at 30 (the native framerate) but it can be set lower.

The quick solution would be to just specify an fps when reading from video. But to prevent this surprising behavior it would be good to specify the fps if it is not given. I will prepare a PR.

**Comment by yukw777** [comment]
@almarklein Thank you so much for your quick help!
