### ISSUE TITLE
Use Wheels on PyPI

### ISSUE THREAD

**Issue by blink1073** [imageio/imageio#91]
Right now, `pip install imageio` downloads the Linux tarball and associated `freeimage` library.  Wheels are preferred downloads for pip.

**Comment by blink1073** [comment]
This does the trick:

```bash
$ export IMAGEIO_PLAT=linux64; python setup.py bdist_wheel
```

```python
if 'bdist_wheel' in sys.argv:
    # 'linux64', 'linux32', 'win64', 'win32', 'osx64']:
    import imageio
    import os
    resource_dir = imageio.core.resource_dirs()[0]
    _set_crossplatform_resources(resource_dir)
    _set_platform_resources(resource_dir, os.environ['IMAGEIO_PLAT'])
```

**Comment by blink1073** [comment]
The resulting file would have to be renamed for the appropriate platform.

**Comment by blink1073** [comment]
Hmm, it appears a less hacky way is to use `from wheel.bdist_wheel import Command`

https://bitbucket.org/pypa/wheel/src/f746a01eab7a673cb628a52f99c129d0d5741bcf/wheel/bdist_wheel.py?at=default

**Comment by almarklein** [comment]
So we can build the wheels for all platforms from a single box?

**Comment by blink1073** [comment]
Yessir

**Comment by almarklein** [comment]
Oh wait, if I read your first earlier more closely, a wheel is really just a .tar.gz that has platform specific resources and is renamed to.whl?

**Comment by blink1073** [comment]
That's it. 



—

**Comment by blink1073** [comment]
It creates a `imageio-1.3.dist-info` folder in the tar file.

**Comment by blink1073** [comment]
Want me to take a stab at it?

**Comment by almarklein** [comment]
Yes, please, if you have some free cycles :)

**Comment by blink1073** [comment]
What are conferences for :smile:

**Comment by blink1073** [comment]
I'm calling this a dead end, see #108.
