### ISSUE TITLE
Add Support for Mult-Page Images

### ISSUE THREAD

**Issue by blink1073** [imageio/imageio#92]
Some image types (such as TIFF and GIF), and return multiple images.

**Comment by blink1073** [comment]
Right now, `imageio` only returns one image.

**Comment by almarklein** [comment]
`imageio.mimread()`?

**Comment by almarklein** [comment]
http://imageio.readthedocs.org/en/latest/userapi.html#imageio.mimread
:)

**Comment by blink1073** [comment]
Ah, that's fair :smile:

**Comment by almarklein** [comment]
But API wise, how does skimage handle this? Does it have a separate function, or does "imread" return a list?

**Comment by blink1073** [comment]
Right now, the only plugin supporting this is the `pil` [plugin](https://github.com/scikit-image/scikit-image/blob/master/skimage/io/_plugins/pil_plugin.py#L11).  If `img_num` is not specified, it will return all images in the file as a multidimensional array.
