### ISSUE TITLE
OSError: Could not find a backend to open `<video0>`` with iomode `r`.

### ISSUE THREAD

**Issue by svaidyans** [imageio/imageio#925]
Please look into this issue.  I am on Windows 11, with Python==3.9 and imageio.v3==2.23.0.  Steps to reproduce:

import imageio.v3 as iio
cam = iio.imopen( '\<video0\>', 'r' )

OR

import imageio.v3 as iio
cam = iio.imread(  '\<video0\>' )

Thanks.

**Comment by FirefoxMetzger** [comment]
Did you install the imageio-ffmpeg backend? (`pip install imageio-ffmpeg`)

**Comment by svaidyans** [comment]
Thanks for the quick response!  Yes, had forgotten the ffmpeg install.  It solved the problem.
