### ISSUE TITLE
PyAV Plugin: Allow ffmpeg to reformat the color if it wants to?

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#926]
I was comparing the performance of different video encoding paths and ultimately, I found that:

https://github.com/imageio/imageio/blob/4658049bc37b6e89796233306df393d8a51b68bd/imageio/plugins/pyav.py#L864

is a source of potential slowdowns. The slowdown was most apparently when using it with nvidia's encoders, but it was still "measurable" with libopenh264

I think it is ultimately due to some multi threading or GPU optimizations that can be done. Or something...

Would it be possible to avoid that call? Was there a reason to add it?

<details> <summary> potentially useful benchmark </summary>

```python
import numpy as np
from imageio import imopen
import av
from pathlib import Path


images = np.random.randint(0, 256, (512, 256, 256, 3), dtype='uint8')
encoder = 'libopenh264'

# %%
def doit_imageio():
    total_frames = images.shape[0]

    with imopen("output_pyav.mp4", "w", plugin="pyav") as file:
        file.init_video_stream(encoder, fps=30, pixel_format='yuv420p')
        file.set_video_filter(None, None)
    
        for i in range(total_frames):
            file.write_frame(
                images[i], pixel_format="rgb24"
            )

# %%
def doit_pyav():
    total_frames = images.shape[0]
    height, width = images.shape[1:3]
    
    container = av.open("pyav.mp4", mode="w")
    stream = container.add_stream(encoder, rate=30)
    stream.width = width
    stream.height = height
    stream.pix_fmt = "yuv420p"
    stream.codec_context.gop_size = 60
    stream.codec_context.thread_count = 4
    # sc_threshold to 0? to avoid scene cut detection
    # keyint_min?
    
    
    for frame_i in range(total_frames):
        image = images[frame_i]
        frame = av.VideoFrame.from_ndarray(image, format="rgb24")
    
        for packet in stream.encode(frame):
            container.mux(packet)
    
    # Flush stream, cannot use the stream after a flush command
    for packet in stream.encode():
        print("packet")
        container.mux(packet)
    
    # Close the file
    container.close()

# %%
doit_pyav()
# doit_imageio()
```
</details>

**Comment by FirefoxMetzger** [comment]
Interesting. I will have a closer look once I have access to my dev machine again (we are traveling back home tomorrow).

We have to call `reformat` because we have to convert the VideoFrame into the output's format (I think) before we can encode it. I might be mistaken about this requirement though in which case it _should_ be safe to remove this line. I would have to check the details though.

**Comment by hmaarrfk** [comment]
I don't think it is entirely true. For example, nvidia assumes that images are in nv12 format but will output yuv encoded streams. I think it can also take RGB. But i may be wrong.

I should probably look at the videos i generated extensively.

**Comment by FirefoxMetzger** [comment]
@hmaarrfk You keep mentioning the nvidia encoder. Are you using hardware encoding together with pyav? If so, do you happen to have documentation on that you could share? I always wanted to play with it, but never got the chance to sit down and work out how to set it up.

**Comment by hmaarrfk** [comment]
It has been a really long road toward using the nvidia encoders....

1. Use conda-forge packaged pyav (I've compjled ffmpeg there to allow nvidia encoding. Llvm makes it easy. There really is no reason you can't follow the same strategy to enable it in the imageio bundle).
2. Specify the codec the same way you would for the command line https://github.com/imageio/imageio-ffmpeg/blob/7bfe71d4a23fa881c792d23e0cf67ef4fc446dd8/imageio_ffmpeg/_io.py#L19
3. Profit.
