### ISSUE TITLE
Why are you overwriting the timebase for pyav

### ISSUE THREAD

**Issue by hmaarrfk** [imageio/imageio#929]
https://github.com/imageio/imageio/blob/c591a1c4ea20269382877110ce486c5bf84bd99d/imageio/plugins/pyav.py#L785

It seems strange that this is happening. In my experience you do not need to do this, and can provide fractional timebases to pyav for more precise playback speeds (3.5 fps)

Is there a technical reason for this line or can we remove it?

Best,

Mark

**Comment by hmaarrfk** [comment]
> That said, I don't know what the implications of this are nor do I know the limits of this.

Yeah, there are some liminations that I learned of during my testing. One of them is that certain codecs, mpeg, only support 16 bit denominator (65k max).


> by various media players

That i haven't tested so intricately.

I think that av might require some commonality between codec context time base, and the stream's

https://github.com/PyAV-Org/PyAV/blob/main/av/container/output.pyx#L103

I'm not sure how that reconciles with it.

It might be that you can remove this. People that want compatibility with "media players", may cast to an int.

This is the code that i use my (new) av wrapper:
```
        stream = container.add_stream(
            codec,
            rate=Fraction(frame_rate).limit_denominator(65_535)
        )
```

**Comment by FirefoxMetzger** [comment]
That works. We should be mindful though that the limit imposed on the denominator means that the framerate will "only" be accurate up to the first 4 significant digits.

> This is the code that i use my (new) av wrapper:

I think this would be useful for ImageIO as well. Could you contribute it together with a note in `init_video_stream` that mentions the limitation of a 16bit denominator (and the resulting 4 digits of precision)?
