### ISSUE TITLE
PyAVPlugin.metadata raise TypeError when video does not contains duration

### ISSUE THREAD

**Issue by kchaiyo** [imageio/imageio#935]
I tried to use imageio.v3.immeta to read video's metadata. The video binary is part of live stream, so there is no EBML field named /Segment/Info/Duration in the binary.

To reproduce, pass a video without duration into immeta as follow

`metadata = imageio.v3.immeta(data, index=..., plugin='pyav')`

According to the stack trace and some debugging, the error is raised from line 709 in plugin/pyav.py

`duration = float(self._video_stream.duration * self._video_stream.time_base)`

A fix could be made by not populate duration field into output metadata dict when self._video_stream.duration is not present.

imageio version is 2.24.0
av (pyav) version is 9.2.0

**Comment by FirefoxMetzger** [comment]
Interesting. For streams, there is indeed no duration (or infinity?). So far, we only have limited support for streams, but I am very happy to extend it.

@kchaiyo I like your suggestion. Do you know if/how we could generate a test input for this? If so, we can create a suitable regression test for it and incorporate the update :)

**Comment by kchaiyo** [comment]
Originally I found the error from data received from AWS's Kinesis Video Stream. The stream was produced by this gstreamer command.
`gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! videorate ! video/x-raw,format=I420,width=640,height=480,framerate=15/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! kvssink stream-name=<stream-name> storage-size=128`
The significant 

I was trying to reduce the steps necessary to reproduce this issue by trying to save the stream before passing to Kinesis Video Stream with this command.
`gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=15/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! matroskamux ! filesink location=capture.mkv`
However, for this case duration field was exist with value of 0, so the issue cannot be reproduced.

**Comment by kchaiyo** [comment]
I was trying to reduce the steps necessary to reproduce this issue. This command would record a video stream from camera and save into an mkv file locally. The video stream is no needed to be long, as all we need is the metadata in header, so we can interrupt the command just after few seconds of recording.

`gst-launch-1.0 -v v4l2src device=/dev/video0 ! videoconvert ! video/x-raw,format=I420,width=640,height=480,framerate=30/1 ! x264enc  bframes=0 key-int-max=45 bitrate=500 tune=zerolatency ! video/x-h264,stream-format=avc,alignment=au ! matroskamux ! filesink location=capture.mkv`

By looking into hexdump of the output file I found that since this file is a record from streaming video, The EBML fields /Segment and /Segment/Cluster have duration set to -1 (UNKNOWN). Also /Segment/Info/Duration field has value of 0.

**Comment by kchaiyo** [comment]
After video was recorded, this python commands should be able to reproduce the issue.

`Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> import imageio
>>> f = open('capture.mkv', mode='rb')
>>> b = io.BytesIO(f.read())
>>> imageio.v3.immeta(b, index=..., plugin='pyav')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<username>/.cache/pypoetry/virtualenvs/kvs-consumer-RNI5UpRF-py3.10/lib/python3.10/site-packages/imageio/v3.py", line 250, in immeta
    metadata = img_file.metadata(**call_kwargs)
  File "/home/<username>/.cache/pypoetry/virtualenvs/kvs-consumer-RNI5UpRF-py3.10/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 709, in metadata
    duration = float(self._video_stream.duration * self._video_stream.time_base)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'Fraction'
>>> 
`
