### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by apiszcz** [imageio/imageio#942]
https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pyav.html

Current
This plugin wraps pyAV, a pythonic binding for the FFMPEG library. It is similar to our FFMPEG plugin but offers a more performant and robut interface and aims to superseed the FFMPEG plugin in the future.

Possible
This plugin wraps pyAV, a pythonic binding for the FFMPEG library. It is similar to our FFMPEG plugin **with improved performance, a **robust** interface and aims to **supersede**** the FFMPEG plugin in the future.

**Comment by FirefoxMetzger** [comment]
Good catch. Would you like to submit a PR to fix the typo, or shall I update it?

**Comment by apiszcz** [comment]
please update
________________________________
