### ISSUE TITLE
Utility to convert numpy.ndarray to ndimage?

### ISSUE THREAD

**Issue by apiszcz** [imageio/imageio#943]
Is there a utility to convert a numpy.ndarray to a ndimage?

(Pdb) type(img)
<class 'numpy.ndarray'>
(Pdb) imgbytes=imageio.plugins.pyav.PyAVPlugin.write(img,codec='libx264',is_batch=True,fps=25)
*** TypeError: PyAVPlugin.write() missing 1 required positional argument: 'ndimage'

**Comment by FirefoxMetzger** [comment]
A `ndimage` is a simple `numpy.ndarray`, so there is no conversion needed.


As a sidenote, it is probably cleaner if you use ImageIO's user-facing API instead of calling plugins directly:

```python
import imageio.v3 as iio

iio.imwrite("video.mp4", img, plugin="pyav", codec="libx264", is_batch=True, fps=25)
```

**Comment by apiszcz** [comment]
I am looking forward to using the filter graph with the pyav plugin. The  filter_graphs appear to require the pyav plugin write? https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pyav.html.

**Comment by apiszcz** [comment]
So what is missing, from this call:

(Pdb) imgbytes=imageio.plugins.pyav.PyAVPlugin.write(img,codec='libx264',is_batch=True,fps=25)
*** TypeError: PyAVPlugin.write() missing 1 required positional argument: 'ndimage'

**Comment by FirefoxMetzger** [comment]
> The filter_graphs appear to require the pyav plugin write?

All functions in ImageIO's user-facing API accept `**kwargs` (additional keyword arguments) which will be forwarded to the selected plugin's `read`/`write`/`iter`/etc. methods. So if you want to use `filter_graphs` while writing with pyav, simply specify it:

```python
import imageio.v3 as iio

img = iio.imread("imageio:cockatoo.mp4")

iio.imwrite(
    "resampled.mp4", 
    img,
    plugin="pyav",  # force using pyav (skips automatic plugin selection)
    codec="libx264",
    filter_graph=(
        {
            "step": ("framestep", "5"),
            "scale": ("scale", {"size": "vga", "flags": "lanczos"}),
        },
        [
            ("video_in", "step", 0, 0),
            ("step", "scale", 0, 0),
            ("scale", "video_out", 0, 0),
        ],
    ),
)

```

> So what is missing from this call?

`write` is a class method and expects two positional arguments: the instance of the class itself, and the frames to write. You are only passing the frames to write to the method declared on the class not the method declared on an object/instance of the class. Hence, the function is complaining that it doesn't have an instance (`self`) it can use to do the work.

You would have to first instantiate `PyAVPlugin`, which involves creating a `Request` (internal object of ImageIO) that the plugin can use to configure itself. While this is possible in theory, it is much easier to use the [public-facing API](https://imageio.readthedocs.io/en/stable/reference/core_v3.html) if you plan to use ImageIO downstream.

**Comment by apiszcz** [comment]
Thank you, your sample works fine. Now on to testing the filter_graph example, from https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.pyav.html

Produces a 0 byte output file test.ts

This message is repeated (probably for each frame)
`Changing video frame properties on the fly is not supported by all filters.`


```

img = iio.imread("imageio:cockatoo.mp4")
img = iio.imwrite("test.ts",
    img,
    plugin="pyav",
    codec="libx264",
    filter_graph=(
        {
            "split": ("split", ""),
            "scale_overlay":("scale", "512:-1"),
            "overlay":("overlay", "x=25:y=25:enable='between(t,1,8)'"),
        },
        [
            ("video_in", "split", 0, 0),
            ("split", "overlay", 0, 0),
            ("split", "scale_overlay", 1, 0),
            ("scale_overlay", "overlay", 0, 1),
            ("overlay", "video_out", 0, 0),
        ]
    )
)
```

**Comment by apiszcz** [comment]
Ignore prior, conversion happens on read, all set, Thank you.

This works fine.

```
img = iio.imread(
    "imageio:cockatoo.mp4",
    plugin="pyav",
    filter_graph=(
        {
            "split": ("split", ""),
            "scale_overlay":("scale", "512:-1"),
            "overlay":("overlay", "x=25:y=25:enable='between(t,1,8)'"),
        },
        [
            ("video_in", "split", 0, 0),
            ("split", "overlay", 0, 0),
            ("split", "scale_overlay", 1, 0),
            ("scale_overlay", "overlay", 0, 1),
            ("overlay", "video_out", 0, 0),
        ]
    )
)
iio.imwrite('test.ts',img,codec='libx264')
```
