### ISSUE TITLE
How to control anomation speed while creating GIF image?

### ISSUE THREAD

**Issue by wxguy** [imageio/imageio#947]
I have used the following code for a long time that never let me down from creating GIF image:

```
import imageio

image_dir = '/path/to/png/dir'

image_files_list = sorted(os.listdir(image_dir))

images = []

for image in image_files_list:
    image_path = os.path.join(image_dir, image)
    if image_path.endswith('.png'):
        images.append(imageio.imread(image_path))

imageio.mimsave('movie.gif', images, duration=0.25)
```

After upgrading my Python and `imageio` versions to the latest one, I found that the earlier API was no longer supported. However, I would like to use this excellent library for one of my personal projects. How do I control the speed of the animation which was earlier done using `duration=` keyword?

**Comment by FirefoxMetzger** [comment]
In v3 `mimsave` simply becomes `imwrite`. You can also continue to use `duration`. It just matches pillow's kwarg and is now in ms, not sec (assuming you continue with the pillow backend):

```python
import imageio.v3 as iio

image_dir = '/path/to/png/dir'

image_files_list = sorted(os.listdir(image_dir))

images = []

for image in image_files_list:
    image_path = os.path.join(image_dir, image)
    if image_path.endswith('.png'):
        images.append(iio.imread(image_path))

iio.imwrite('movie.gif', images, duration=250)  # 4 FPS i.e. .25s between two frames
```

**Comment by wxguy** [comment]
Thank you for your help. I think you should have included this as part of the package documentation as the internet is filled with a code similar to the one I posted here.

Closing the issue.
