### ISSUE TITLE
Convert colorspace OSError: Cannot understand given URI:

### ISSUE THREAD

**Issue by apiszcz** [imageio/imageio#948]
from imageio.plugins.opencv import OpenCVPlugin

My guess is I'm calling OCV.read incorrectly.

```
img = imageio.read()...
img2=imageio.read(img,index=..., plugin='opencv',colorspace='RGB')
*** OSError: Cannot understand given URI: array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0....
```

**Comment by FirefoxMetzger** [comment]
Sorry for taking so long to respond @apiszcz , somehow this issue slipped past my radar.

When you call the first line (`img = imageio.read()...`) you already get a numpy array back. There is no need (or ability) to decode it again by calling `img2 = iio.imread(img)`. Perhaps you meant to pass the same path as in `img`? I.e., something along the lines of `img2 = iio.imread("path/to/img.png", plugin="opencv", ...)`?

**Comment by apiszcz** [comment]
all set, my error, thanks. hope u r ok!
