### ISSUE TITLE
failing avbin tests due to frame_rate_den=0 frame_rate_num=0

### ISSUE THREAD

**Issue by kuchi** [imageio/imageio#95]
On my system (OS X 10.10.3) the following tests are failing 

```
tests/test_avbin.py::test_read FAILED
tests/test_avbin.py::test_reader_more FAILED
tests/test_avbin.py::test_read_format FAILED
```

due to the test file having

ZeroDivisionError on avbin.py at:

```
self._meta['fps'] = (float(info.u.video.frame_rate_num) /
                                     float(info.u.video.frame_rate_den))
```

I'm not sure what is causing this, I tried to debug it but I couldn't figure out why. Any thoughts?

Here is a full print of the following variables before the failure line:

```
self._meta = {'title': u'', 'author': u'', 'source_size': (1280L, 720L), 
    'plugin': 'avbin', 'duration': 14.069063, 'avbin_version': '11', 'size': (1280L, 720L)}

info.u.video:
frame_rate_den 0
frame_rate_num 0
height 720
sample_aspect_den 1
sample_aspect_num 0
width 1280
```

I wasn't sure how to get more debug info for avbin.

**Comment by almarklein** [comment]
cc @rreilink who wrote this plugin. I could also have a look later when I find some free time to spin up my osx VM.
