### ISSUE TITLE
`trim` filter results in `End of file` error

### ISSUE THREAD

**Issue by accelyte** [imageio/imageio#951]
When trying to run the following, I get an `End of file error`:
```
iio.imread("imageio:cockatoo.mp4",
               plugin="pyav",
               filter_sequence=[("trim", {"start": "00:00:01", "end":"00:00:02"})])
```

av: 9.2.0
imageio: 2.25.1

**Comment by FirefoxMetzger** [comment]
Thanks for sharing; I can reproduce this on master. 

Looks like I didn't account for filters that can terminate the stream before all frames were read from the file. I'll see how complicated a fix is and then we take it from there :)

**Comment by FirefoxMetzger** [comment]
Turns out that the fix was easy 🚀 As we are currently down to 1 maintainer, I will do the same as I did with other PRs: I will keep it open for about a week and if nobody has any complaints/comments, I will merge it in. It will roll out the first Monday after the merge.
