### ISSUE TITLE
 Image use same version imageio in different python version get different result.

### ISSUE THREAD

**Issue by AmberCheng** [imageio/imageio#967]
Hi, thanks for the tools. I always use imageio to do lots of CV work. However, recently I found that I use the imageio-python3.7 and imageio-python3.8 both are 2.20.0 to read the same image, I got different rgb values. I want to know how to deal with it for the different value cause the different result with my model.

**Comment by FirefoxMetzger** [comment]
Hard to say without additional information. What format is the image stored in? A likely option is that the backend uses different binaries for python 3.7 and 3.8 respectively. It could also be a bug, but that is hard to say without more context.

**Comment by FirefoxMetzger** [comment]
@AmberCheng It has been a while since there was activity on this issue. Is it still relevant for you or did you manage to resolve the problem?

(If I don't hear anything for a while, I will assume this is resolved and will close the issue.)
