### ISSUE TITLE
error: `FFMPEG` can not read `<bytes>` in google colab

### ISSUE THREAD

**Issue by qsxdr111** [imageio/imageio#968]
the error occurs when loading a video file (mp4) previously the code worked with this video. to run https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb you need to put !pip install -U scikit-image==0.18.0 in the first cell. video can download this https://youtu.be/smQvWpqX13I (144p).
![image](https://user-images.githubusercontent.com/110227428/230709299-7d173cf4-7c18-4d7c-a893-9a8364262e47.png)
error:
InitializationError         Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/imageio/core/imopen.py 
in imopen(uri, io_mode, plugin, extension, format_hint, 
legacy_mode, **kwargs)
    141         try:
--> 142             return loader(request, **kwargs)
    143         except InitializationError as class_specific:
    
20 frames
    
InitializationError: `FFMPEG` can not read `<bytes>`.

The above exception was the direct cause of the following 
exception:

RuntimeError           Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/imageio/core/imopen.py 
in imopen(uri, io_mode, plugin, extension, format_hint, 
legacy_mode, **kwargs)
    158 
    159         request.finish()
--> 160         raise err_type(err_msg) from err_from
    161 
    162     # fast-path based on format_hint

RuntimeError: `FFMPEG` can not handle the given uri.

**Comment by qsxdr111** [comment]
i tried to upload their output video there

**Comment by FirefoxMetzger** [comment]
It looks like you are using an outdated version of ImageIO. The issue looks similar to https://github.com/imageio/imageio/issues/686 and https://github.com/imageio/imageio/issues/777 . 

A quick look at the code also reveals that you are using aquite dated version of ImageIO as well as the old v2 API. I would suggest you update your code, which will likely solve the problem in the process. Try the following:

1. Update ImageIO and pick up the latest pyav plugin along the way: `pip install -U imageio av`
2. Import the new V3 API: `import imageio` -> `import imageio.v3 as iio`
3. Change the places where you call ImageIO to the current best practice. (Also try to not mix tabs and spaces when indenting ... your app seems to use tabs, which is disadvantageous for many reasons.)

```python
# old
def thumbnail(file):
    return imageio.get_reader(file, mode='I', format='FFMPEG').get_next_data()

# new:
def thumbnail(file):
    return iio.imread(file, index=0, plugin="pyav")
```

```python
# in generate(button):
# old
reader = imageio.get_reader(selected_video, mode='I', format='FFMPEG')
	fps = reader.get_meta_data()['fps']
	driving_video = []
	for frame in reader:
		driving_video.append(frame)

# new
fps = iio.immeta(selected_video, plugin="pyav")["fps"]
driving_video = iio.imread(selected_video, plugin="pyav")
```

```python
# in generate(button):
# old:
imageio.mimsave('output.mp4', [img_as_ubyte(frame) for frame in predictions], fps=fps)

# new:
iio.imwrite("output.mp4", [img_as_ubyte(frame) for frame in predictions], plugin="pyav", codec="libx264", fps=fps)
```

Apart from this, I also noticed that you are using pretty much _every_ IO capable library in the python ecosystem. While you can, ofc, do this, it will probably make your life much more complicated than it has to be, so if you have some spare time in the future I'd recommend refactoring into a single library. (May I suggest ImageIO? 😅 )

**Comment by qsxdr111** [comment]
I cannot express in words how grateful I am to you, I have been trying to fix this for a month now. Thank you very much.
now i can fix it.

**Comment by mylawacad** [comment]
@FirefoxMetzger  Thank you very much for great help! 
Not sure if any additional value, in my case had to use `iio.imiter()` instead:
```
# in generate(button):
# old
reader = imageio.get_reader(selected_video, mode='I', format='FFMPEG')
	fps = reader.get_meta_data()['fps']
	driving_video = []
	for frame in reader:
		driving_video.append(frame)

# new
fps = iio.immeta(selected_video, plugin="pyav")["fps"]
	driving_video = []
	for idx, frame in enumerate(iio.imiter(selected_video, plugin="pyav")):
		driving_video.append(frame)
```

**Comment by mylawacad** [comment]
@FirefoxMetzger Thank you very much for great help!
Not sure if any additional value, in my case to make this [colab](https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb) work had to use iio.imiter() instead:
```
# in generate(button):
# old
reader = imageio.get_reader(selected_video, mode='I', format='FFMPEG')
	fps = reader.get_meta_data()['fps']
	driving_video = []
	for frame in reader:
		driving_video.append(frame)

# new
fps = iio.immeta(selected_video, plugin="pyav")["fps"]
	driving_video = []
	for idx, frame in enumerate(iio.imiter(selected_video, plugin="pyav")):
		driving_video.append(frame)
```
and omit the `codec="libx264"` parameter: 

```
# in generate(button):
# old:
imageio.mimsave('output.mp4', [img_as_ubyte(frame) for frame in predictions], fps=fps)

# new:
iio.imwrite("output.mp4", [img_as_ubyte(frame) for frame in predictions], plugin="pyav", fps=fps)
```
