### ISSUE TITLE
Duration of individual frames?

### ISSUE THREAD

**Issue by WASasquatch** [imageio/imageio#975]
I want to write a GIF where I can control each frames duration independently. I can't wrap my head around how to do this.

**Comment by FirefoxMetzger** [comment]
You can control the duration for each frame by passing a list (or iterable) of durations to the `duration` kwarg. Here is a small example:

```python
import imageio.v3 as iio
import numpy as np

# create the images
red = np.zeros((100, 100, 3), dtype=np.uint8)
green = np.zeros((100, 100, 3), dtype=np.uint8)
blue = np.zeros((100, 100, 3), dtype=np.uint8)
red[..., 0] = 255
green[..., 1] = 255
blue[..., 2] = 255

# duration is the time (in ms) that a frame is shown. If you pass an int it will
# be the same for each frame, if you pass a list (or iterable) it can be set on
# a per-frame basis.
iio.imwrite("test.gif", [red, green, blue], duration=[1000, 3000, 1000], loop=0)

```

Which produces:

![test](https://user-images.githubusercontent.com/4402489/234392434-b9b34394-f04b-425d-90f1-9f7f82876ac1.gif)

**Comment by WASasquatch** [comment]
That's so strange, I kept trying to do this but it kept giving me a uniform speed result. Maybe my list wasn't matching the frames generated I need to rethink the process I think cause that's clearly working just like I want.

**Comment by FirefoxMetzger** [comment]
No worries @WASasquatch bugs like this can be subtle. 

For the GIF format specifically, there is also the limitation that many players don't support the full set of duration values. For example, In theory, 100Hz GIFs (`duration=10`) are supported by the GIF standard, but in practice, most players (especially browsers) cap out at 50Hz (`duration=20`). This means that GIFs minimum delta is `10` ms in theory and `20` ms in practice. If you try to show a "next frame" with an unsupported duration, your GIF will be written correctly (assuming your durations are standard-conform), but the GIF will play at a constant and slow/default speed for each frame.

At any rate, I assume that this answers your question and I can close this issue as completed?

**Comment by WASasquatch** [comment]
Thanks for the additional information. I did figure out the issues. Biggest issue was my logic for setting the "still frame" duration basically just wasn't firing off in any scenario cause I subtracted from it making it unaligned from everything it was comparing to. 

I'll close this.
