### ISSUE TITLE
Deprecation in pillow causing problems with imageio gif writing

### ISSUE THREAD

**Issue by alisterburt** [imageio/imageio#992]
Hi there, thanks for all the great work on imageio! 🙂 

I had a bug report at napari/napari-animation#174 which boils down to a deprecation in pillow causing a problem with the imageio gif writing, reporting here 

```python
import numpy as np
import imageio

writer = imageio.get_writer(
    'test.gif',
    fps=20,
)
for i in range(5):
    writer.append_data(np.random.random((32, 32)).astype(np.uint8))
```

```txt
  File "/Users/alisterburt/micromamba/envs/napari-animation/lib/python3.9/site-packages/imageio/v2.py", line 215, in append_data
    return self.instance.write(im, **self.write_args)
  File "/Users/alisterburt/micromamba/envs/napari-animation/lib/python3.9/site-packages/imageio/plugins/pillow.py", line 354, in write
    raise TypeError(
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).
```

**Comment by FirefoxMetzger** [comment]
Thanks for the report @alisterburt . Looks like we have been too eager with deprecating a kwarg and that `fps` should raise a warning for now instead of `TypeError`. Would you be interested in contributing this change or shall I pick it up once I get to do my next round of implementations?

**Comment by alisterburt** [comment]
@FirefoxMetzger thanks for taking a look! Happy to contribute knowing that a PR is welcome - I'll try to get it tomorrow morning 🙂

**Comment by alisterburt** [comment]
Quick q: will the change to duration be unified across writers for all different formats or is it specific to the gif writer? At the moment I'm only seeing the deprecation for gif

**Comment by FirefoxMetzger** [comment]
The deprecation is specific to the pillow plugin, so it affects all animated formats that pillow can write. The popular ones are GIF, APNG, and WEBP. If you write GIF with another plugin, you will not see this deprecation.
