### ISSUE TITLE
Cannot open PGM file

### ISSUE THREAD

**Issue by miguelmpn** [imageio/imageio#999]
Cannot open PGM file.

The following code on imageio/core/format.py -> `def __getitem__(self, name):` line 683

`return imopen(name, "r", legacy_mode=True)._format`

Gives me the error **'PillowPlugin' object has no attribute '_format'**

**Comment by Ai-Himmel** [comment]
I cannot reproduce this issue with the example file from the [PGM specification](https://netpbm.sourceforge.net/doc/pgm.html) website in my environment. Maybe you can try to update to the latest version? Or could you share your image file if possible?

**Comment by Ai-Himmel** [comment]
Sorry for my misunderstanding. In recent versions of iio, the `legacy_mode` parameter almost influences nothing in `imopen`. And the FormatManager is deprecated much earlier. Could you tell me your imageio version and provide more detail on how you trigger this exception?

**Comment by miguelmpn** [comment]
I updated it while debugging, to see if it would fix, I'm currently using v2.30.0
Please check line 683 from this file https://github.com/imageio/imageio/blob/master/imageio/core/format.py

To replicate it on your side you may just run that line of code. `image = imopen(FILES / "image.pgm", "r")._format`

**Comment by miguelmpn** [comment]
I'm using Gamma-Desk, which in turn uses that method. 
Can we fix it? Both the plugin and the  https://github.com/imageio/imageio/blob/b0f9f3bfce914f335d06375c76c094a10dcca236/imageio/core/format.py#L683 are from ImageIO. 

This may happen elsewhere, so I decided to post the issue.

**Comment by Ai-Himmel** [comment]
`FormatManager` is deprecated and will be removed in future versions. 

In the `Gamma-Desk` project this FormatManager is used only for logging. And even if we make `imageio.formats` works like before, the result returned is not the real plugin used in the [next line](https://github.com/thocoo/gamma-desk/blob/ab23a780b3c41137efa76e17f58cc85e637b2080/gdesk/panels/imgview/imgview.py#L1366).

I think the proper way is to fix `Gamma-Desk`  itself. Replace `imageio.formats[filepath]` to `iio.imopen(filepath,'r').__class__` may be a better way.

**Comment by miguelmpn** [comment]
Sorry my mistake, I created a ticket on the wrong place and I cannot delete, can you please do it? 
Delete this one -> https://github.com/imageio/imageio/issues/1000

**Comment by FirefoxMetzger** [comment]
@miguelmpn Sure thing. I will go and delete it.

@Ai-Himmel Thanks for being a beacon of wisdom for this issue; you were spot-on with your analysis and comments.
